### ISSUE TITLE
`--lcov` output includes excluded lines

### ISSUE THREAD

**Issue by Syeberman** [gcovr/gcovr#1008]
# Describe the bug

Lines marked with `LCOV_EXCL_LINE` are represented with a `DA:` entry in the `--locv` output. Compare this to `lcov`, where excluded lines do not have a `DA:` entry.

(Additionally, I believe that `lcov` [does not count excluded lines when calculating `LF:`](https://github.com/linux-test-project/lcov/blob/d100e6cdd4c67cbe5322fa26b2ee8aa34ea7ebcf/bin/lcov#L2669), although I wasn't able to reproduce this with a test.) 

# To Reproduce

1. `main.c`
```C
#include <stdio.h>

int main(int argc, char **argv)
{
    printf("First line\n");
    printf("Second line\n"); // LCOV_EXCL_LINE
    printf("Third line\n");
    return 0;
}
```
2. Commands
```
sye.test>gcc --version
gcc (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.

sye.test>gcc -o main.exe -m64 -O0 --coverage main.c

sye.test>main.exe
First line
Second line
Third line

sye.test>gcovr --lcov gcovr.info
(INFO) Reading coverage data...
(INFO) Writing coverage report...

sye.test>perl C:\ProgramData\chocolatey\lib\lcov\tools\bin\lcov --version
lcov: LCOV version 1.15.alpha0w

sye.test>perl C:\ProgramData\chocolatey\lib\lcov\tools\bin\lcov --output-file lcov.info --capture --directory .
Capturing coverage data from .
Found gcov version: 13.2.0
Using intermediate gcov format
Scanning . for .gcda files ...
Found 1 data files in .
Processing main.gcda
Finished .info-file creation
```
3. `lcov.info` (note that `DA:6` is not present)
```
TN:
SF:c:\Projects\nohtyP\sye.test\main.c
FN:3,main
FNDA:1,main
DA:3,1
DA:5,1
DA:7,1
DA:8,1
end_of_record
```
4. `gcov.info` (note that `DA:6` has an execution count of zero)
```
TN:GCOVR report
SF:C:/Projects/nohtyP/sye.test/main.c
VER:cc2968fca58eb68bfef7312ad14144c3
FN:3,main
FNDA:1,main
FNF:1
FNH:1
BRF:0
BRH:0
DA:3,1,8fe7c279e25dbaffcf9846b45dab4e38
DA:5,1,c6911eb4b609ddd150e4f23197ba0621
DA:6,0,d44c08ee0679e70d94d2066bcdcb2a7d
DA:7,1,545d93f834e1de4d6a2b3563f891d512
DA:8,1,02abc18c3b46fbd7cfee6bbcd0986b79
LH:4
LF:5
end_of_record
```

# Expected behavior

`DA:` entries should not be written for excluded lines.

# Desktop (please complete the following information)

- OS: Windows 11
- GCC version: MinGW 13.2.0
- GCOVR version: 8.2
- LCOV version: 1.15.alpha0w

# Additional context

I'm working on uploading my coverage to Codecov, which does not support these types of exclusions, so excluded lines are showing up as not executed (as the `gcovr` appears to reset the execution count of excluded lines to zero).

**Comment by Spacetown** [comment]
Thanks for reporting this. You're right that we shouldn't print excluded lines. 
While doing the fix one question came up: We add the line statistics at the end and the lines won't be counted for the covered lines but what about the instrumented once?
```python
            # LH:<number of lines with a non\-zero execution count>
            fh.write(f"LH:{lines_covered}\n")
            # LF:<number of instrumented lines>
            fh.write(f"LF:{len(covdata[key].lines)}\n")
```

**Comment by Spacetown** [comment]
@Syeberman Can you check the branch from the PR?

**Comment by Syeberman** [comment]
I just checked it out and it's working as expected: the excluded lines have been removed from the `--lcov` output.

Thanks for the quick fix! Sorry I didn't follow-up as quickly as you did.
