### ISSUE TITLE
More coverage metrics from GCovr?

### ISSUE THREAD

**Issue by vsnimantha** [gcovr/gcovr#1011]
I'm using gcovr for one of my research projects. Currently, by default, it provides line, function and branch coverage. Is it possible to use it to generate other coverage metrics such as Statements, Conditions, Paths, etc.?

**Comment by vsnimantha** [comment]
I tried with GCC 14. Even though I could get the condition coverage results via Gcov, I could not figure out how to use GCovr to reflect those. Do you think I should use any specific flags?

**Comment by Spacetown** [comment]
If gcov is new enough to write JSON format 2 then govt always use the conditions if you activated them during compilation.

**Comment by Spacetown** [comment]
Closing this issue because of missing response.
