### ISSUE TITLE
Certain CLI flags not working

### ISSUE THREAD

**Issue by ollieSayer** [gcovr/gcovr#1017]
# Describe the bug

We are using gcovr (7.2) in our CI systems however, it seems some of our passed CLI flags are not used by gcovr i.e. we add certain flags to ignore errors however, gcovr still flags these errors

# To Reproduce

Steps to reproduce the behaviour:

1. gcovr --output=coverage.xml --exclude=.*/test/.* -exclude-unreachable-branches --object-directory=/home/ci/workspace/coverage_pipeline/build --root=/home/ci/workspace/coverage_pipeline/src --gcov-ignore-parse-errors --gcov-ignore-errors=no_working_dir_found -x
2. Observe in the logs "To ignore this error use option --gcov-ignore-errors=no_working_dir_found."

# Expected behaviour

The errors in the logs to be ignore and not logged

# Desktop

- OS: Debian Bookworm
- GCC version 12.2.0
- GCOVR version 7.2

**Comment by Spacetown** [comment]
Can you post the exact error message? This can't be reproduced with the command line.

**Comment by ollieSayer** [comment]
Hi, there is about 500k log lines so have shared the first example of the error below 

``
gcovr --output=coverage.xml --exclude=.*/test/.* --exclude-unreachable-branches --object-directory=/home/ci/workspace/coverage_pipeline/build --root=/home/ci/workspace/coverage_pipeline/src --gcov-ignore-parse-errors --gcov-ignore-errors=no_working_dir_found -x
(INFO) Reading coverage data...
(ERROR) GCOV produced the following errors processing /home/ci/workspace/coverage_pipeline/build/kernel/idc/CMakeFiles/component.dir/__/__/src/misc/kernel/object/constraint.cxx.gcda:
	In directory /home/ci/workspace/coverage_pipeline/build:
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/seqTemplatedecls.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/templatedecls.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/seqTemplatedefns.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/callHandle.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/callDescriptor.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/CORBA_Object.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/CORBA_Exception.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/cdrStream.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/omniInternal.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/stringtypes.h

	In directory /home/ci/workspace/coverage_pipeline/src:
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/seqTemplatedecls.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/templatedecls.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/seqTemplatedefns.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/callHandle.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/callDescriptor.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/CORBA_Object.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/CORBA_Exception.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/cdrStream.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/omniInternal.h
Cannot open source file /var/lib/ci/conan/.conan/data/componentx/4.2.5/conan/testing/package/dw2r2rv2fv2fcf2v2vv2342322323/include/componentx4/stringtypes.h

	(gcovr could not infer a working directory that resolved it.)
To ignore this error use option --gcov-ignore-errors=no_working_dir_found.
(ERROR) GCOV produced the following errors processing /home/ci/workspace/coverage_pipeline/build/kernel/validation/testing/CMakeFiles/common.dir/experimental.cxx.gcda:
	In directory /home/ci/workspace/coverage_pipeline/build:
Cannot open source file /var/lib/ci/conan/.conan/data/componenty/1.85.0/conan/testing/package/10fp1e,1e0c02em2d0vcpwd2d02d02d/include/componenty/optional/optional.hpp
Cannot open source file /var/lib/ci/conan/.conan/data/componenty/1.85.0/conan/testing/package/10fp1e,1e0c02em2d0vcpwd2d02d02d/include/componenty/smart_ptr/intrusive_ptr.hpp
``

**Comment by latk** [comment]
This is working as documented: `--gcov-ignore-errors` prevents gcovr from crashing, and lets it continue with likely-invalid data. It doesn't silence the errors, the problems are still reported.

https://gcovr.com/en/stable/manpage.html#cmdoption-gcovr-gcov-ignore-errors

I suspect that your use of the `--object-directory` option is causing problems. It causes gcovr to use different heuristics that are almost always worse than just specifying a search path and/or changing the working directory from which you run gcovr.

**Comment by ollieSayer** [comment]
Thank you for the speedy replies and the help , I'll explore moving away from '--object-directory' and mark this issue a closed
