### ISSUE TITLE
Report uncompatible gcov version

### ISSUE THREAD

**Issue by mrx23dot** [gcovr/gcovr#102]
Old gcov version in mingw 3 produced weird behaviour:
It didn't accept abs path for gcda.

So for a cmd like:
gcov C:\KBData\Sandbox\Out\sl_f_nibble.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory

there were errors like:
gcov C couldn't be found
gcov KBData couldn't be found
gcov Sandbox couldn't be found
..

Later this has been fixed with gcov version >=4.x (which accepts abs paths to).
A gcov version check would be nice, so others wouldn't have to debug for hours.

eg.
gcc --version
gcc (GCC) 4.8.1

Strange thing that gcov errors were printed out BEFORE the gcovr code got to the calling part, must be some threading (so it took some time to debug).

**Comment by latk** [comment]
I'm not going to add code to detect GCC 3.x. That compiler is over a decade old.

For more up-to-date GCC versions, a failure to parse gcov output would be a bug in gcovr. Trying to determine the GCC version then has little value, except for making it slightly easier to make a good bug report.
