### ISSUE TITLE
Is it possible to use run GCOVR only for changed part of coverage data?

### ISSUE THREAD

**Issue by superhail** [gcovr/gcovr#1025]
For example, if i have a program and a bunch of test, i ran gcovr and i got the coverage report. And then i modified one line of code, is there a way that i can avoid running gcovr over all coverage data generated by gcov? because maybe lots of coverage information is not changed.

**Comment by Spacetown** [comment]
It isn't because if you run your executable again the gcda files are overwritten by your executable. As a result of this gcov needs to be executed again.

**Comment by superhail** [comment]
i dont really know about gcda too much, so its not even possible to do something like ccache?

**Comment by Spacetown** [comment]
The gcno are generated by gcc during compilation and the gcda by running the executable. Gcov processes this files to generate gcov or gcov.gz files which we're using to generate the report
