### ISSUE TITLE
gcovr 6.0 release link broken

### ISSUE THREAD

**Issue by ulisses** [gcovr/gcovr#1031]
Hi guys,

The tar.gz release of gcovr 6.0 link is broken since yesterday. Can you fix this?

https://codeload.github.com/gcovr/gcovr/tar.gz/6.0/tags/6.0

Thanks.

**Comment by Spacetown** [comment]
Hmmh, I don't know how they get broken. Can you download from https://pypi.org/project/gcovr/6.0/#files?

**Comment by latk** [comment]
I can reproduce that the download links from the release page do not work. However, these links are auto-generated by GitHub. We cannot delete or edit them, and did not actively upload these files.

By tinkering around a bit, I noticed that the URL schema for these download links has changed:

* https://codeload.github.com/gcovr/gcovr/tar.gz/6.0/tags/6.0 is broken
* https://codeload.github.com/gcovr/gcovr/tar.gz/refs/tags/6.0 works

This is a bug in the GitHub web interface. People have reported similar problems at <https://github.com/orgs/community/discussions/8149>.

However, all of this is only relevant for *archival* purposes.

If you want to *install* gcovr, either do it via git, or via PyPI. Here's the link to the PyPI page with the installable wheel + sdist for gcovr 6.0: <https://pypi.org/project/gcovr/6.0/#files>.
