### ISSUE TITLE
Gcovr Coverage

### ISSUE THREAD

**Issue by subhasankarisaravanan** [gcovr/gcovr#1036]
I am using CPPUTEST for unittest.In that i am facing the problem that 
for ex

```c
int aa()
{
#ifndef UNITTEST
    some data
#else
    return 0;
}
```

This is my one function and i am calling this function to another file called bb.c

```c
int ss()
{
    if(aa())
    {
        some function
    }
    else
    {
        some function
    }
}
```

now i am writing unittest for ss() function and check coverage by using gcovr .So in my coverage always else condition of ss() covered but if condition of ss() not covered because aa() always returns 0.
In that case we couldnot write test for if() and coverage is low how to avoid it.In gcovr coverage if() of ss() shown uncovered. Hope you understand the problem and kindly help me to resolve it.

**Comment by Spacetown** [comment]
This is not an issue of gcovr. Please read the documentation in gcc about preprocessing.
The compiler, gcov and as a result also gcovr see only the `return 0`.

**Comment by subhasankarisaravanan** [comment]
Dear sir,
    understood.Then is there any chance to eliminate those lines which will
be never covered.I am using gcovr 6.0 version.Kindly reply on this.








Thanks and Regards
SUBHASANKARI S

**Comment by subhasankarisaravanan** [comment]
Dear Sir,
   Thank you for the reply.



Regards
SUBHASANKARI S
