### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by phatakan** [gcovr/gcovr#104]
Hi,

I was trying to run gcovr on .gocv files and I see below problems
1)
        Please report this to the gcovr developers.(WARNING) Unrecognized GCOV output: '$$$$$'
        This is indicitive of a gcov output parse error.
2) It does not report "Branches Executed" always consider "Branches taken atleast once"
3) Function coverage is missing
# gcov -v

gcov (GCC) 4.4.7 20120313 (Red Hat 4.4.7-3)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

**Comment by whart222** [comment]
Please provide a simple example to illustrate these issues.  I haven't seen the output errors in recent gcov releases.

**Comment by latk** [comment]
This issue has not seen any progress in a while, so I am closing it for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.
