### ISSUE TITLE
gcovr by default deletes the gcda files

### ISSUE THREAD

**Issue by baubakg** [gcovr/gcovr#110]
I have been running gcovr (3.2) on an application of mine. Although I am able to generate my reports gcovr deletes all my gcda files after execution.
here is my command:

    gcovr -r /home/prod/svn/trunk -d /home/prod/svn/trunk/XXXXX/ -o myresult.html --html

It is as if the "--delete" were active by default.

Before and after After executing gcovr :
I execute : 

    find / -name *.gcda

After the execution I have none. 

Best regards,

Baubak

**Comment by whart222** [comment]
The "-k" option can be used to keep these files.
