### ISSUE TITLE
How to distinguish branches in the xml report ?

### ISSUE THREAD

**Issue by wichtounet** [gcovr/gcovr#113]
Hello, 

I'm trying to merge several XML files generated by gcovr into one. I don't see any way of merging the branch lines and their conditions. 

If I have two files with a single condition with two branches and both take a different path, is there a way to identity if they have taken the same branch or not ? Each <condition> node only has a number, but this number is always zero. Is there a way to distinguish these branches ? 

Thanks

Baptiste

**Comment by latk** [comment]
The XML files are in the Cobertura format.

I don't think the XML files keep enough info for the branch coverage data to be combined. AFAIK any such merge would have to happen on the .gcov files, before gcovr parses those and generates the report. The `--use-gcov-files` option is necessary for that.

**Comment by wichtounet** [comment]
@latk Ok, thanks for the answer
