### ISSUE TITLE
GCDA and GCNO files are 2 different location

### ISSUE THREAD

**Issue by farooquesayed** [gcovr/gcovr#114]
Hi,

Do you security limitation, my app does not have privilege to write data file in objroot location. I have used GCOV_PREFIX environment variable to setup a different location to write the output file. I realize gcovr does not take that into account when looking for matching gcda and gcno's pair.
When i running the gcovr to generate the coverage report, all the numbers in the report is coming back as 0's.

I debugged this further and figured out, in case where gcda is not in the same spot as gcno, then we have to pass that path to gcda file explicitly when running gcov command. for eg:
gcov -a -b -c -gcda $(pwd)/myapp/Objects-normal/x86_64/SBLSharedPhotoStreamManager.gcda $(pwd)/myapp/objroot/ShareServices.build/ShareServicesCore.build/Objects-normal/x86_64/SBLSharedPhotoStreamManager.gcno

I would highly appreciate if you could tell me how to pass a key/value pair or gcno & gcda file to gcov

Current gcov command works as :
 'gcov $(pwd)/myapp/objroot/Spark.build/Photos.build/Objects-normal/x86_64/IPXTrashRestoreAction.gcno --branch-counts --branch-probabilities --preserve-paths --object-directory $(pwd)/myapp/objroot/Spark.build/Photos.build/Objects-normal/x86_64' in '$(pwd)/myapp/objroot/Spark.build/Photos.build/Objects-normal/x86_64'

Expected:

gcov -a -b -c  *\* -gcda $(pwd)/myapp/Objects-normal/x86_64/SBLSharedPhotoStreamManager.gcda *\* $(pwd)/myapp/objroot/ShareServices.build/ShareServicesCore.build/Objects-normal/x86_64/SBLSharedPhotoStreamManager.gcno

**Comment by latk** [comment]
I am afraid you have a fairly unique scenario with these security restrictions, so I don't think you will be able to use gcovr easily.

This is not the place to get gcov support. Gcovr and gcov are completely separate projects.
