### ISSUE TITLE
Uninitialized options.root in version 3.2

### ISSUE THREAD

**Issue by vajdaz** [gcovr/gcovr#117]
In Version 3.2 the script fails with an error without a -r Option because in this case options.root is not initialized when the report header is printed out. I did not analyse it deeper, but did a workaround by replacing
```python
    OUTPUT.write("Directory: "+options.root+"\n")
```
at line 822 with
```python
    OUTPUT.write("Directory: "+(starting_dir if options.root is None else options.root)+"\n")
```
Maybe you will find a more elegant fix.

**Comment by JonathonReinhart** [comment]
:+1: Also seeing this in `gcovr

**Comment by whart222** [comment]
This issue is fixed in master.  I'll be processing a new release before September.
