### ISSUE TITLE
Verify MS Windows behavior

### ISSUE THREAD

**Issue by whart222** [gcovr/gcovr#12]
When i am using Gcovr through CygWin? With the required file(ie .gcno and .gcda ),i am getting the code coverage results on console as well as in .xml file.But when i am using the same on command prompt(in windows),i dont get the code coverage data.I am just returned with an empty table having coverage data as 0.0.
Configuratio used :
os:Windows XP
gcov version:3.4.5
compiler:Mingw
gcovr version:2.4

**Comment by liudulab** [comment]
I met same issue.i dont get the code coverage data.I am just returned with an empty table having coverage data as 0.0.
Configuratio used :
os:Windows 7
gcov version:4.9.2
compiler: mingw32-gcc.exe
gcovr version:4.1

**Comment by latk** [comment]
@liudulab If you have a problem, please open  a new issue. In that issue, please include the following information:

* the directory structure of your project – where is the source code, where are the object files, from which directory are you running gcovr, are there gcno/gcda files next to the object files, …
* how you are building the project – which build system are you using, are you passing the necessary compiler options for collecting coverage, …
* the output from running gcovr in `--verbose` mode

Often, this is just a problem with filters, e.g. running gcovr from the wrong directory or setting the `--root` to a misleading value. With Windows, there can also be some issues about uppercase vs lowercase paths.
