### ISSUE TITLE
gcovr and xcode 7

### ISSUE THREAD

**Issue by JKuzimski** [gcovr/gcovr#120]
When using gcovr with Xcode 7 code coverage is always 0%.
Same setup is properly working with Xcode 6.

**Comment by wolf99** [comment]
XCode has made it to version 9 now, is this issue still present?

**Comment by latk** [comment]
This issue has not seen any progress in a while, so I am closing it for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.
