### ISSUE TITLE
Supporting "new" LCOV / GCOV markers

### ISSUE THREAD

**Issue by vito-wagl** [gcovr/gcovr#121]
Adding the three "new" LCOV / GCOV markers, which will be excluded code from branch coverage:
- LCOV_EXCL_BR_LINE
- LCOV_EXCL_BR_START
- LCOV_EXCL_BR_STOP

[geninfo(1) man page](http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php)

**Comment by Blabla51** [comment]
You might be able to close this issue @Spacetown :)
