### ISSUE TITLE
option to add css for html

### ISSUE THREAD

**Issue by dewnull** [gcovr/gcovr#125]
This is mostly for Jenkins since its default `Content-Security-Policy` setting doesn't allow for execution of inline style. I end up relaxing this policy by modifying Jenkins configuration file  
`
JENKINS_JAVA_OPTIONS="-Dhudson.model.DirectoryBrowserSupport.CSP=\"sandbox; default-src 'none'; img-src 'self'; style-src 'unsafe-inline' 'self';\""
`

**Comment by Spacetown** [comment]
@latk I think, this can be closed.

**Comment by latk** [comment]
This should be resolved via #348 (removal of inline styles) and  657c294371fe5ed5ebc18ec03cf32a14e9864bbf (--no-html-self-contained).
