### ISSUE TITLE
Add 'Badge'-Output

### ISSUE THREAD

**Issue by cnlpete** [gcovr/gcovr#127]
As the title suggests, i would like an output option `--badge` which would produce a badge like this: ![lines coverage 86%](https://img.shields.io/badge/coverage-86%25-yellow.svg) or ![branches coverage 48%](https://img.shields.io/badge/branches-48%25-red.svg)

The badges would be saved as specified with option `-o`.

Alternatively, provide a 'simple' output, so i could easily combine with https://github.com/dbrgn/coverage-badge

**Comment by whart222** [comment]
This is a great idea!

**Comment by mayeut** [comment]
This might be worth a look also: https://github.com/Tethik/badger

**Comment by latk** [comment]
I think badges are great, but that adding badge generation capability to gcovr itself would be out of scope.

Right now the easiest way to get the coverage is to parse the text report with a regex, or to extract this data from the XML report. This value can then be given to any command-line badge generation program.

I would be open to PRs that make scripting gcovr easier, e.g. with a JSON output format or some machine-readable summary. I would also be interested in a short tutorial to creating badges that can be added to the documentation.
