### ISSUE TITLE
gcovr with html option is not working for nested directory structure

### ISSUE THREAD

**Issue by Mitiricorp** [gcovr/gcovr#13]
Let's say i have 4-level directory structure where 3rd level directory has multi directory structure. In the html report it's considering only a single path, that means if level 4 directories are a,b,c,d then it's only having l1->l2->l3->a

**Comment by latk** [comment]
This issue has not seen any progress in a while, so I am closing it for now. If the problem persists, it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.
