### ISSUE TITLE
TypeError when no coverage files found in Python 2

### ISSUE THREAD

**Issue by rix0rrr** [gcovr/gcovr#131]
```
Traceback (most recent call last):
File "/home/local/ANT/huijbers/Workspaces/Bogart/env/NowYouCMake-1.0/runtime/bin/gcovr", line 1970, in <module>
    print_xml_report(covdata)
File "/home/local/ANT/huijbers/Workspaces/Bogart/env/NowYouCMake-1.0/runtime/bin/gcovr", line 1757, in print_xml_report
    OUTPUT.write(xmlString +'\n')
TypeError: must be unicode, not str
```

When no nodes are added to the minidom document, the output is of type 'str', which cannot be written to a file that has an encoding: it must be unicode.

(When nodes are added, minidom returns a unicode object and everything is fine)

**Comment by whart222** [comment]
So when does this occur?  When a file isn't covered?

I'd like to add a test for this, but I'm not sure what would cause a failure.

**Comment by mayeut** [comment]
This doesn't seem to occur anymore if I understand it correctly.
Using Python 2.7.13:
`./scripts/gcovr -x`
```
<?xml version="1.0" ?>
<!DOCTYPE coverage
  SYSTEM 'http://cobertura.sourceforge.net/xml/coverage-04.dtd'>
<coverage branch-rate="0.0" branches-covered="0" branches-valid="0" complexity="0.0" line-rate="0.0" lines-covered="0" lines-valid="0" timestamp="1516230978" version="gcovr 3.3">
<sources>
<source>.</source>
</sources>
<packages/>
</coverage>
```
No error as well when specifying an output file.

**Comment by latk** [comment]
This issue has not seen any progress in a while, so I am closing it for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.
