### ISSUE TITLE
Enabling verbose generates a crash

### ISSUE THREAD

**Issue by mambu** [gcovr/gcovr#150]
Version 3.3
Running: `gcovr -v -g -k -r . --xml -o file.xml` generates a crash:

> Scanning directory . for gcov files...
Found 49 files (and will process 49)
Finding source file corresponding to a gcov data file
  currdir      /home/mambu/temp/fhcore/debug64/obj/libFhDsMgr.a
  gcov_fname   /home/mambu/temp/fhcore/debug64/obj/libFhDsMgr.a/#opt#rh#devtoolset-2#root#usr#include#c++#4.8.1#bits#stream_iterator.h.gcov
               ['        -', '    0', 'Source', '/opt/rh/devtoolset-2/root/usr/include/c++/4.8.1/bits/stream_iterator.h\n']
Traceback (most recent call last):
  File "/usr/bin/gcovr", line 2310, in <module>
    process_existing_gcov_file(file_, covdata, options)
  File "/usr/bin/gcovr", line 939, in process_existing_gcov_file
    process_gcov_data(filename, covdata, None, options)
  File "/usr/bin/gcovr", line 519, in process_gcov_data
    print('  source_fname '+source_fname)
TypeError: cannot concatenate 'str' and 'NoneType' objects

Either removing "-v" or leaving it and commenting out line 519 in the script `print('  source_fname '+source_fname)` the crash is not seen and gcovr processes all files as expected and produces the expected output.

Marco

**Comment by mambu** [comment]
Forgot to mention that gcov files were correctly generated using this command:
`gcovr -v -s -k -r .`
Note sure if that may help.

**Comment by mayeut** [comment]
@mambu can you confirm that it's the same issue I filed: #143 
If so, I filed a PR for this #144, if you can confirm that it corrects the error you're seeing, please give it a review.

**Comment by mambu** [comment]
Yes, that's the same issue.
