### ISSUE TITLE
Clarify "exclude" options

### ISSUE THREAD

**Issue by daviddoria** [gcovr/gcovr#151]
From my understanding, gcovr turns gcov output (one .gcno file per .cpp file that gets compiled?) into a report. When thinking about which things to exclude from the report, I see what seem to be three relevant options:

  -e EXCLUDE, --exclude=EXCLUDE
                        Exclude data files that match this regular expression
  --gcov-exclude=GCOV_EXCLUDE
                        Exclude gcov data files that match this regular
                        expression
  --exclude-directories=EXCLUDE_DIRS
                        Exclude directories from search path that match this
                        regular expression

1) What is the difference between --exclude and --gcov-exclude?
2) When would an --exclude-directories be needed if I can specify a regular expression to --exclude (i.e. can't you essentially specify a directory using a regular expression?)
3) Can someone give an example of a regular expression and what it implies for gcovr to demonstrate which regular expression syntax gcovr is expecting?

Thanks!

David

**Comment by latk** [comment]
Thank you for this valuable feedback. In #236, the `gcovr --help` output was improved to clarify these options. The filter section now reads:

```
...

  Filter Options:
    Filters decide which files are included in the report. Any filter must
    match, and no exclude filter must match. A filter is a regular
    expression that matches a path. On Windows, the filter must match a
    relative path.

    -f FILTER, --filter=FILTER
                        Keep only source files that match this filter. Can be
                        specified multiple times. If no filters are provided,
                        defaults to --root.
    -e EXCLUDE, --exclude=EXCLUDE
                        Exclude source files that match this filter. Can be
                        specified multiple times.
    --gcov-filter=GCOV_FILTER
                        Keep only gcov data files that match this filter. Can
                        be specified multiple times.
    --gcov-exclude=GCOV_EXCLUDE
                        Exclude gcov data files that match this filter. Can be
                        specified multiple times.
    --exclude-directories=EXCLUDE_DIRS
                        Exclude directories that match this regex while
                        searching raw coverage files. Can be specified
                        multiple times.

  GCOV Options:
    The 'gcov' tool turns raw coverage files (*.gcda and *.gcno) into
    *.gcov files that are then processed by gcovr. The gcno files are
    generated by the compiler. The gcda files are generated when the
    instrumented program is executed.

...
```

Additionally, the User Guide ([Website](http://gcovr.com/guide.html#using-filters), [GitHub](https://github.com/gcovr/gcovr/blob/master/doc/guide.rst#using-filters)) discusses filters:

>  Gcovr tries to only report coverage for files within your project, not for your libraries. This is influenced by the following options:
>
> -   ``-r``, ``--root``
> -   ``-f``, ``--filter``
> -   ``-e``, ``--exclude``
> -   ``--gcov-filter``
> -   ``--gcov-exclude``
> -   ``--exclude-directories``
> -   (the current working directory where gcovr is invoked)
>
> These options take filters. A filter is a regular expression that matches a file path. If the filter looks like an absolute path, it is used as is. Otherwise, the filter is treated as relative to the current directory. Because filters are regexes, you will have to escape “special” characters.
> 
> If no ``--filter`` is provided, the ``--root`` is turned into a default filter. Therefore, files outside of the ``--root`` directory are excluded.
> 
> To be included in a report, the source file must match any ``--filter``, and must not match any ``--exclude`` filter.
>
> The ``--gcov-filter`` and ``--gcov-exclude`` filters apply to the ``.gcov`` files created by ``gcov``. This is useful mostly when running gcov yourself, and then invoking gcovr with ``-g``/``--use-gcov-files``. But these filters also apply when gcov is launched by gcovr.
> 
> **Note:**    The filters will be matched as a regex against an absolute path.    The filter must therefore not include symlinks or relative directories like “..”.
>
> **Warning:**    Currently, only relative filters are supported on Windows.
>
> **Warning:**    The behavior of Windows filters will change in a future release.
>
>    Currently, the filters are matched against normal backslash paths like    ``C:\project\directory\file.cpp``.    To match that, you need to escape the backslashes like    ``directory\\file\.cpp``.
>
> In the future, the paths will use forward slashes,    so that the same filters can be used on Linux and Windows.    You would then have to use filters like    ``directory/file\.cpp``.
>
> To avoid problems when upgrading, do not use path separators in Windows filters.    If absolutely necessary, use a placeholder ``.`` or a charclass ``[/\\]``    in place of path separators.

I am not 100% sure about --exclude-directories, and strongly assume this option is currently broken. In any case, it would mostly be used as an optimization, not as a primary filtering mechanism.

All filters use normal Python regexes, which use a Perl-like regex syntax.
