### ISSUE TITLE
detailed HTML reports broken on windows

### ISSUE THREAD

**Issue by markuseinsle** [gcovr/gcovr#152]
On windows/mingw, gcovr-3.3 throws errors when trying to generate a detailed HTML report, for my project e.g.:

`gcovr -r . --html --html-detail -o coverage.html`

results in:

```
Traceback (most recent call last):
  File "c:/Python27/Scripts/gcovr", line 4, in <module>
    __import__('pkg_resources').run_script('gcovr==3.3', 'gcovr')
  File "c:\Python27\lib\site-packages\pkg_resources\__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "c:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "c:\Python27\lib\site-packages\gcovr-3.3-py2.7.egg\EGG-INFO\scripts\gcovr", line 2323, in <module>

  File "c:\Python27\lib\site-packages\gcovr-3.3-py2.7.egg\EGG-INFO\scripts\gcovr", line 1698, in print_html_report

IOError: [Errno 2] No such file or directory: 'c:\\Daten\\Projekte\\Net16\\PU\\Source\\Watchdog\\Unittest\\coverage.../../Scheduler/IPoll.hpp.html'
```

I was able to track down the problem to line 1572, where longname gets assigned, replacing path separators by underscores. For some reason, parts of cdata._filename use windows conventions ('\' instead of '/').
This can easily be fixed using abspath, an replacing the drive letter's colon by an underscore, too.

My proposal is replacing

`longname = cdata._filename.replace(os.sep, '_')`

by

```
# remove path separators and colon used for drive letters on windows OS
longname = os.path.abspath(cdata._filename)
longname = longname.replace(':' + os.sep, '_')
longname = longname.replace(os.sep, '_')

```

**Comment by itavero** [comment]
If I remember correctly this is similar to #17.

**Comment by markuseinsle** [comment]
Oh... you're right, sorry for the duplicate! But the issue still has't been fixed.

**Comment by aoreskovic** [comment]
#157 Has fixed this but it hasn't been merged, I don't know why.

**Comment by wolf99** [comment]
The code in the version that is currently installed by pip looks somewhat different from that shown in the #157 PR... is the PR out of date? does anyone have an updated fix they could pass along? (unfortunately I don't know Python so have little idea how to solve this myself!)

For ref, the following is what I see in the file installed by Pip in the area of the code changed by #157:

```python
#...
    #
    # Find the source file
    #
    currdir = os.getcwd()
    root_dir = os.path.abspath(options.root)
    if source_fname is None:
        common_dir = os.path.commonprefix([data_fname, currdir])
        if sys.version_info >= (2, 6):
            fname = aliases.unalias_path(os.path.join(common_dir, segments[-1].strip()))
        else:
            fname = aliases.unalias_path(os.path.join(common_dir, segments[-1]).strip())
    else:
        #     1. Try using the path to common prefix with the root_dir as the source directory
        fname = os.path.join(root_dir, segments[-1].strip())
        if not os.path.exists(fname):
            # 2. Try using the path to the gcda file as the source directory
            fname = os.path.join(os.path.dirname(source_fname), os.path.basename(segments[-1].strip()))

    if options.verbose:
        print("Finding source file corresponding to a gcov data file")
        print('  currdir      '+currdir)
#...
```

**Comment by latk** [comment]
@wolf99 I think that error is unrelated to this issue. If so, please create a separate issue. But thank you for finding this, it points to a few real problems!

**Comment by latk** [comment]
PR #157 has been merged, which should fix this problem. Gcovr now consistently uses backslashes `\` when determining the source file name, from which the HTML file name is derived. It does not yet normalize colons `:` in the HTML file names.

Everyone: please try out the new version on Windows. To do so, you must install gcovr from GitHub, not from PyPI. For example:

``` console
> python -m pip install git+https://github.com/gcovr/gcovr.git
```
