### ISSUE TITLE
how to report coverage for files that were not executed

### ISSUE THREAD

**Issue by ffengcs** [gcovr/gcovr#155]
lcov can do like this :
![image](https://cloud.githubusercontent.com/assets/7343471/20175805/987d0f1c-a77f-11e6-934f-8d360d57ff25.png)

what should gcovr do?

**Comment by mambu** [comment]
As far as I know, there is no way to do this at the minute. I need the same feature, therefore a while ago I created a new feature request: #154

**Comment by latk** [comment]
Duplicate of #154.

Thank you for sharing this use case. Gcovr can't do that right now, but I do understand how it might be useful.
