### ISSUE TITLE
Is it possible to hyperlink and nest directories in --html-details output?

### ISSUE THREAD

**Issue by rsmz** [gcovr/gcovr#160]
I have a project with thousands of C++ files organized in a large tree, however, the gcovr html details output presents them all in a single flat table.  Is there an option to nest and hyperlink all the html pages just like the source code tree, as well as links to parent directory pages?  I think lcov did something like that.  If not, I'd be happy to contribute if given some hints on where to start.  Each row for a sub-directory could show totals.  I would also have a link to a flat view like now for each directory.

Also, the html table doesn't maximize to the width of the browser, so my C++ file name links are wrapped while there remains ample unused space in the left/right margins.

**Comment by latk** [comment]
Thank you for your suggestion. This is an often-requested feature, and I too want to see this happen.

However, I'm planning to do larger changes to gcovr's architecture and to the HTML report templating. After those changes have gone through, we can revisit this issue. Implementing nested reports will be much easier after untangling the current HTML generation code.

**Comment by macetw** [comment]
@latk Lukas, I'm working on this feature: my project needs this. I'm pretty satisfied but not fully complete on this feature.

I'm curious if the desired behavior is to always show the nested tree or also show a nested tree. That is, do we allow the option of both a flat-list and a hierarchical list?

I'm not yet clear on whether I can contribute my changes back to the source, but I sure hope I can. It wasn't terribly difficult, and I'd be happy to be a part.

**Comment by Spacetown** [comment]
Thank you for working on this. Please share your work as draft PR than we can discuss about it.

**Comment by chreniuc** [comment]
Any news on this? I've noticed that this was requested 6 years ago.

**Comment by Spacetown** [comment]
I'm also waiz8for a response of @macetw .

**Comment by zchrissirhcz** [comment]
@Spacetown @macetw I suggest hte official gcovr team / organization do the request feature instead of the infinite long waiting, since there is no public branch or commit in @macetw 's fork demonstrate that there is a (draft) PR.
