### ISSUE TITLE
Add option to filter branches automatically created for exceptions in C++

### ISSUE THREAD

**Issue by mambu** [gcovr/gcovr#161]
Hi,

The branch coverage reported for our code is not usable because it contains a lot of wrong/unwanted results from automatic branches added to handler exceptions in C++. However we cannot use gcc with -fno-exceptions in our code and tests, since we sometimes use exceptions (so with that command line options our code does not compile).
See [http://stackoverflow.com/questions/29368482/gcov-reports-branches-for-plain-function-calls](url)

It would be beneficial if we had a gcovr option to skip processing those branches.
It seems they always have the same pattern:

1. a call line
2. a branch taken 100% (fallthrough)
3. a branch taken 0% (throw)

so it should be possible to identify those cases and optionally skip them.

This is the output of `gcov -ab`

> function _ZN19CFhUsBook_ConflatorC2Emm called 27 returned 100% blocks executed 58%
       27:    6:CFhUsBook_Conflator::CFhUsBook_Conflator(std::size_t period, std::size_t mapSize) :
       27:    6-block  0
        -:    7:    period_(period),
        -:    8:    lastUpdateTsDiff_(0,0,0,0,static_cast<int>(period)),
       27:    9:    fimDataMap_(mapSize)
       27:    9-block  0
call    0 returned 100%
call    1 returned 100%
call    2 returned 100%
call    3 returned 100%
branch  4 taken 100% (fallthrough)
branch  5 taken 0% (throw)
       27:    9-block  1
call    6 returned 100%
    %%%%%:    9-block  2
    %%%%%:    9-block  3
    %%%%%:    9-block  4
call    7 never executed
    %%%%%:    9-block  5
call    8 never executed
        -:   10:{
       27:   11:}
        -:   12:

And this is the source code for the constructor above at line 6:

    CFhUsBook_Conflator::CFhUsBook_Conflator(std::size_t period, std::size_t mapSize) :
        period_(period),
        lastUpdateTsDiff_(0,0,0,0,static_cast<int>(period)),
        fimDataMap_(mapSize)
    {
    }

Thanks

**Comment by estan** [comment]
I found this because I suffered from the same problem and was googling around. I'm not using `gcovr` though but CDash (which also does parsing of `.gcov` files). I just thought I should mention that for me, within blocks that are not even executed, these "spurious" branches introduced due to exception handling looks like e.g. this:

```text
        7:  110:    if (!isSimple) {
branch  0 taken 0% (fallthrough)
branch  1 taken 100%
    #####:  111:        m_error = OpenError;
    #####:  112:        m_errorString = QString("%1 in %2 has non-simple dataspace").arg(dataSetName).arg(m_fileName);
call    0 never executed
call    1 never executed
call    2 never executed
call    3 never executed
call    4 never executed
branch  5 never executed
branch  6 never executed
call    7 never executed
branch  8 never executed
branch  9 never executed
call   10 never executed
branch 11 never executed
branch 12 never executed
call   13 never executed
call   14 never executed
call   15 never executed
call   16 never executed
call   17 never executed
call   18 never executed
    #####:  113:        closeDataSet();
call    0 never executed
branch  1 never executed
branch  2 never executed
    #####:  114:        return false;
        -:  115:    }
```

E.g. look at the 6 branches for line 112, probably it's two branches for each call on that line (`QString(..)`, `arg(..)` and `arg(..)`). Just thought I should mention this, since I don't think it will always be easy to detect these branches reliably for exclusion.

I wish there was a way to tell gcov itself to ignore branches in exception handling code generated by gcc.

**Comment by latk** [comment]
I do not think it is possible to exclude these branches on a gcovr level:

 1. Those branches are real. While they are not taken during ordinary control flow, they can still be taken. So excluding these branches would falsify the real coverage.

 2. We are at the compiler's mercy regarding whether or not a branch is emitted. So any branch exclusion logic should be maintained much further upstream, closer to GCC – possibly as part of the instrumentation code that emits the coverage data at runtime.

 3. No heuristic will be perfect. But a branch exclusion heuristic with false positives would be unacceptable. In particular, I'm not convinced that it is possible to detect “a call line” so reliably that this would not remove branches unrelated to a call.

If someone finds a way to pull this off reliably, I'd be glad to see a pull request. But until then, I'm closing this issue as wont-fix.
