### ISSUE TITLE
Add option to exclude coverage reported for destruction of global variables

### ISSUE THREAD

**Issue by mambu** [gcovr/gcovr#162]
Hi,

I basically have the same issue reported here for LCOV: http://stackoverflow.com/questions/20866420/lcov-branches-at-the-end-of-a-function
I see multiple branches reported for the last line of the last function in every source file. This is being added to the total branch report for the file/class and therefore is causing a wrong total value.
The coverage report of such a function is usually meaningless and therefore it would be good if we could exclude it from the gcovr report.

```
function _ZN24CFhUsBook_InstrumentData5ClearEv called 0 returned 0% blocks executed 0%
    #####:   37:void CFhUsBook_InstrumentData::Clear()
    $$$$$:   37-block  0
        -:   38:{
        -:   39:    // This will clear the TopRows filters too
    #####:   40:    summaryBook_.Clear();
    $$$$$:   40-block  0
call    0 never executed
        -:   41:    // Clear time
    #####:   42:    lastUpdateTs_.Initialise();
call    0 never executed
function _GLOBAL__sub_I_FhUsBookInstrumentData.cc called 1 returned 100% blocks executed 100%
function _Z41__static_initialization_and_destruction_0ii called 1 returned 100% blocks executed 100%
        4:   43:}
        1:   43-block  0
        1:   43-block  1
call    0 returned 100%
        1:   43-block  2
        1:   43-block  3
branch  1 taken 100% (fallthrough)
branch  2 taken 0%
        1:   43-block  4
branch  3 taken 100% (fallthrough)
branch  4 taken 0%
```

Thanks,
Marco

**Comment by latk** [comment]
The `--exclude-unreachable-branches` option to gcovr tries to exclude branches from the last line, if the last line doesn't seem to contain any code. This should get rid of the static initialization branches.

If that doesn't fix your problem, please add more details so that this issue can be re-opened.
