### ISSUE TITLE
Configuration files

### ISSUE THREAD

**Issue by psukys** [gcovr/gcovr#167]
Hello,
I am new both to gcov/lcov and gcovr and wonder whether gcovr uses any kind of configuration file (as I failed to quick-search through documentation). If yes, where can I find more information? Else, is there some kind of approach for using configuration files? In particular, I am looking to exclude specific directories via conf file

**Comment by meahow** [comment]
No it doesn't.
All options are given through command line.

MP

sent from my OnePlus One

**Comment by latk** [comment]
Config files have now been implemented: a gcovr.cfg file in the --root directory can be used to set filters etc.
