### ISSUE TITLE
Using gcovr html details on windows

### ISSUE THREAD

**Issue by mretsh91** [gcovr/gcovr#17]
When using the command  (gcovr --html --html-details) on cmd windows it don't work.
I think because of the paths that are interpreted in a way that windows doesn't understand it. The error is:
IOError: [Errno 2] No such file or directory: 'E:user\PGA_Source_Code\PGA_prg.c'

I think the "//" is not interpreted correctly in windows.

Please I need help with this urgently

**Comment by mrx23dot** [comment]
Please use the following for all inputs:

from os.path import normpath
abs_filename = os.path.abspath(normpath(filename))

This will unify all paths for given OS.

**Comment by itavero** [comment]
Has anyone submitted a PR for this?

**Comment by latk** [comment]
This may have been fixed by pull request #157.

If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.
