### ISSUE TITLE
Normalise 'fname' in 'process_gcov_data'

### ISSUE THREAD

**Issue by sawatts** [gcovr/gcovr#170]
Filename (header files) extracted from 'gcov' datafiles may consist of relative paths to the including source file.  These are not currently (HEAD) normalised, resulting in filenames in the coverage XML output of the form "foo/bar/../wibble.h" and "foo/../foo/wibble.h" etc.

This can bypass filtering and could cause duplicate entries (?) for the same (absolute path) file.

Recommend inserting a 'normpath' once 'fname' is determined in 'process_gcov_data' but before filtering is applied.

**Comment by Spacetown** [comment]
Can you create a small example? I can't reproduce this with the current version.
