### ISSUE TITLE
Source file location.

### ISSUE THREAD

**Issue by sawatts** [gcovr/gcovr#171]
The assumption that objects are generated in a subdirectory below the sources is somewhat optimisitic for larger/complex projects. Consider read-only source trees and multi-architecture outputs etc.

Given the object directory and a source root directory, I would cache all subdirectories of the root (inclusive), and test for the existance of the filename extracted from the gcov datafile against each subdirectory (normalising the resultant paths).

This allows separate trees for output and source, and for sources to be spread between different subdirectories.  It would also allow multiple roots to be specified if required.

Ambiguities - multiple matches - are probably a project management issue, but could be amortized by choosing minimum "distance" between proposed source and object (sum of depths, minus twice common path depth).  Not ideal - but better than what we're seeing at the moment.

**Comment by latk** [comment]
Gcovr does support out of source builds, i.e. where you have a `src` directory and a separate `build` directory. For example, look at the [cmake_oos test case](https://github.com/gcovr/gcovr/tree/master/gcovr/tests/cmake_oos). If the coverage data files are not beneath the source root directory, you must provide the path to the source root to gcovr with the `-r` option.

Did you run into any issue using gcovr for a concrete project with an out-of-source build?

**Comment by sawatts** [comment]
I could not get it to work with the `-r` option.  Source files where just assumed to be in the object directory (AFAIR).

For my use case: Source files are being locationed if they are specified by a path which is relative to a directory between the working directory (where `gcovr` is run from) and the object directory.  The actual source files can then be outside this tree if the relative path makes them so.

`gcovr` resolves source file locations by taking the filename from the `gcov` data - which may be relative to the compilation directory - and walking down the path between current and object directories, trying each in turn, by simple concatonation.

This has the side effect of bypassing source path filtering in `gcovr`; it is missing a path resolution between finding the source file and applying the path prefix filter.

**Comment by nickbroon** [comment]
I think this shows that out of source build support in gcovr is broken:
https://github.com/gcovr/gcovr/pull/159

**Comment by inorton** [comment]
Hi, I've been trying to get out-of-source working with gcovr (you guessed it, I'm using cmake). But, what might be helpful is https://android.googlesource.com/platform/test/vts/+/master/utils/python/coverage/

Having fired this up in a debugger It correctly reads my source file absolute paths from the gcno files regardless of where they are in relation to the gcno and gcda files themselves.

**Comment by latk** [comment]
@inorton Thank you for that link, but it's not obvious to me what they do differently. They do seem to assume a very specific project layout. I'll keep that tool in mind for future reference.

**Comment by inorton** [comment]
@latk the most useful files there seem to be gcda_parser.py and gcno_parser.py  I've ignored the rest of the project for now.  Those two are able to output themselves the basic function/block level code coverage
