### ISSUE TITLE
UPdate documentation about how data are filtered

### ISSUE THREAD

**Issue by 1ce8erg0H** [gcovr/gcovr#178]
By default if sources file are not under the root directory they will be ignored.
This is not an obvious design choice and so it should be documented better.

Thank you

**Comment by latk** [comment]
Thank you for pointing out this problem. As of PR #210, the user guide now contains a section on Using Filters. It says:

> If no --filter is provided, the --root is turned into a default filter. Therefore, files outside of the --root directory are excluded.

I will push this version of the user guide to the website tomorrow.
