### ISSUE TITLE
No indication of gcov version compatibility

### ISSUE THREAD

**Issue by Anketell** [gcovr/gcovr#179]
We are currently using a recent version of gcc and experiencing issues with gcovr ver 3.3

It would be useful if you would provide compatibility and/or tested against version numbers of gcc/gcov in your release history.

**Comment by latk** [comment]
The test suite on Travis CI currently only covers GCC 5. I agree that more compiler versions (incl. Clang) should be covered.

I just ran the test suite with a GCC 7 toolchain and there are indeed a few test failures, though they seem minor: if an expression spans multiple lines, different lines are reported as uncovered. But that is a limitation of the tests, and the results are still correct.

Could you please clarify:

 - Which exact versions of gcc/g++/gcov are you using?
 - What issues are you experiencing? Ideally, could you please provide a short test program that can reproduce the problem?

**Comment by Anketell** [comment]
6.2 currently. 

I'm seeing source files and lines of code showing no coverage that are being hit. I'll look at distilling an example.

Comprehensive testing is a big job. As suggested, it would be helpful each release indicated it's compatibility or versions that it has been tested against as a first step.

**Comment by latk** [comment]
As of 1980aaf058907bb185d783b6ca2568cddea61018 the guide mentions the tested versions. Thank you for bringing that to my attention again!

Testing more compilers in addition to GCC 5 will be coordinated in #206.

As these two problems are now covered, I am closing this issue. If you manage reproduce any specific problems, please open a new issue for that problem.

**Comment by Anketell** [comment]
Much appreciated.

**Comment by Anketell** [comment]
@latk I was unable to isolate the circumstances where executed code is being reported as uncovered. However, we have recently upgraded to gcovr 3.4 and not longer experience this problem.

well done and thank you for your efforts.
