### ISSUE TITLE
can't install in archlinux 

### ISSUE THREAD

**Issue by jyapujuju** [gcovr/gcovr#181]
python2-setuptools can't be retrieved...

**Comment by latk** [comment]
How are you installing gcovr?

 - If you are installing via pacman, that sounds like a packaging problem. The gcovr software does not control how it is packaged on Arch. You may want to ask for help in an Arch-specific community.

 - If you are installing via pip or by cloning the Git repository, no such error message should occur. In that case, please show exactly what commands you are running and what messages they output.

**Comment by jyapujuju** [comment]
i entered `yaourt -S gcovr'
