### ISSUE TITLE
gcovr does not work when cpp file is more than 10000 lines

### ISSUE THREAD

**Issue by warguss** [gcovr/gcovr#183]
I have more than 10000 lines of cpp files.
When outputting to an xml report, there is a problem that the file is excluded and output.

Is there a solution?

**Comment by wolf99** [comment]
Can you give some more information on how the file "is excluded and output"? Is there an error? Can you show what is output on the command line?

Also a link to a repo with the project containing the 10,000 line file would likely be handy for testing if it is possible.

**Comment by warguss** [comment]
Sorry
The issue was that the file was excluded due to an incorrect use of the exclude option after gcovr <-> gcov communication.

After correcting the relevant part, we confirmed the operation.

**Comment by latk** [comment]
Thank you for the follow-up. Yes, the exclude options can sometimes get confusing. I'm glad you managed to sort this out :-)
