### ISSUE TITLE
Vote: add "@latk" as admin?

### ISSUE THREAD

**Issue by latk** [gcovr/gcovr#184]
Hi, I am Lukas Atkinson (@latk) and would like to serve as an admin for gcovr.

I think I can fill that role well because:

 - I am kind and thoughtful,
 - I am interested in gcovr, and
 - I have enough time.

In real life, I am a computer science student from Frankfurt, Germany.

**What can an admin do?**

I already have push access to the gcovr repos and can manage issues/discussions. If I become admin, I can also:

 - change repository settings, such as adding protections for the "master" branch.
 - manage the gcovr organization, such as adding new members.

**Is an admin also a project lead?**

No, admin access only gives extra administrative permissions. But it is a position of trust.

However, I am one of the more interested people in this project. Admin access will help me move this project forward.

**Why do we need another admin?**

The current admins are @whart222 and @jsiirola, both of which no longer seem to be very interested in day to day operations. By adding a more involved admin, admin-level requests can be handled more quickly (in #176 it took multiple months for new members to be added). In any case, this reduces the “bus factor” of the project.

**How does this vote work?**

As per the discussion in #176, all **members** of the gcovr organization may cast their vote. There are currently 8 members in total. Jsiirola will add an admin when two-thirds of the votes are in favour. Please cast a **vote by adding a comment** and not via emoji reactions, so that membership status is easy to see. The comment should clearly convey your intent (in favour, oppose, abstain). In order to give everyone enough time, this vote will run for four weeks **until Jan 26th**, 16:00 UTC.

**Comment by denniswjackson** [comment]
I'm in favor of making @latk an admin but I don't who the list of members
are.

**Comment by lu-zero** [comment]
You should tag all the members though.

**Comment by latk** [comment]
All gcovr members are invited to vote on this proposal: @carlos-jenkins @dholm @ja11sop @jsiirola @latk @lu-zero @sinelaw @whart222 

I was initially hesitant to tag members that had set their visibility to private, but not everyone is watching the gcovr repo. Thank you @lu-zero for reminding me.

**Comment by sinelaw** [comment]
fine with me

**Comment by jsiirola** [comment]
+1

...and that makes 6, meeting the 2/3 threshold.  For the record, @whart222 and I are still very interested in gcovr - the problem has been spare time to properly support it.
