### ISSUE TITLE
Which versions of gcov are supported?

### ISSUE THREAD

**Issue by inorton** [gcovr/gcovr#231]
Hi, At the moment I'm having to build with quite an old GCC (4.9.2) and occasionally also 3.0.4!

What versions of gcov does gcovr currently support  as a minimum?

Thanks

**Comment by latk** [comment]
Gcovr is currently only being tested with GCC 5, but is know to work with a variety of GCC and Clang versions. It should also work with earlier GCC versions. I think gcovr was originally developed for GCC 3.4.

There is no clear minimum version. I don't have any personal motivation to support anything pre GCC 4.7, but will gladly accept patches should there be any problems.

Looking at old GCC documentation, it seems that gcov 4.x supports all the required options, but gcov 3.x does not. So I do not think you will be able to use gcovr together with GCC 3.0.4.
