### ISSUE TITLE
Another Cmake out-of-source test case

### ISSUE THREAD

**Issue by inorton** [gcovr/gcovr#232]
Hi, As mentioned in another issue I've been trying to use cmake and gcovr without much luck.

I have created a basic cmake repo with a handful of small c libraries and a single test program that re-creates the sort of structure I'm using (which is common in cmake) and where gcovr doesnt find any data.

https://github.com/inorton/cmake-gcovr-oos

There is a simple "build.sh" that builds, runs a test and then runs gcovr.

I've been running this using gcc 4.9 on 64bit linux

Many thanks

**Comment by inorton** [comment]
Oh! I think I might have an idea I think gcovr is picking up the wrong gcov on my system

**Comment by inorton** [comment]
Aha yes, If I add `--gcov-executable=/usr/bin/gcov` it all works

**Comment by latk** [comment]
OK, so to clarify, this test case does not reproduce a gcovr problem in connection with CMake and OOS builds? When invoked with a suitable gcov executable, then gcovr does successfully create the reports with all the expected data?

Still, thank you very much for trying to hunt down these problems. It is also good to get solid verification that gcovr does work in this scenario.

**Comment by inorton** [comment]
Yes, it all appears to work when the correct gcov is used
