### ISSUE TITLE
Provide css/template overrides for the html output.

### ISSUE THREAD

**Issue by lu-zero** [gcovr/gcovr#25]
Beside what lcov does, would be nice having proper templating so a twitter bootstrap structure can be leveraged.

**Comment by tytouf** [comment]
@lu-zero What is the status on this work? this looks really nice but it appears it has not been integrated yet.

**Comment by lu-zero** [comment]
It lives in my branch and I think somebody volunteered to integrate it by
reimplementing at least part of it so waited to not step on his feet.

On Wed, Jan 7, 2015 at 11:53 AM, Christophe Augier <notifications@github.com

**Comment by pranavpsawant** [comment]
Did we get a chance to integrate it ... because it looks super awesome....

**Comment by davidvanwyk** [comment]
I'd also love for this to be implemented - something akin to [doxygen-bootstrapped](https://github.com/Velron/doxygen-bootstrapped) would be fantastic.

**Comment by lu-zero** [comment]
The code is still on my tree :) anybody willing to help me get it merged is welcome.

**Comment by oesteban-vx** [comment]
So, this is related (implemented?) by #380?

**Comment by Spacetown** [comment]
@oesteban-vx yes.
