### ISSUE TITLE
get coverage in a cross compilation environment

### ISSUE THREAD

**Issue by gocarlos** [gcovr/gcovr#259]
I'm trying to get the code coverage by cross compiling some unit tests, moving them into a  root file system  of the target platform (arm) and executing them using ssh. 

After this step I run gcovr from the host on the mounted root file system of the target platform (where the gcno files are) with: 
```
# connect to target and run tests
ssh root@target_ip
cd /opt/my_progr/bin/
./my_unit_test
exit
# get back to host
cd /home/user/target_filesystem/opt/my_progr/bin
gcovr -r  path/to/src_dir/on/host --exclude=".*/third_party/*." --exclude=".*/test/*." --exclude=".*/app/*."
# output is a list of files, all with 0.0% line coverage
```

gcovr run but does not show any coverage (0.0% lines) but only branches... 

the same executables compiled nativelly (x86) work well with gcovr

Could this be a bug? 
Using version 3.3

**Comment by latk** [comment]
There is no particular reason that would prevent gcovr from working with cross-compilation. However, this is a rather advanced use case. You will have to dig into this problem yourself. A few pointers:

 - Gcovr 3.3 is close to 2 years old and there have been many bugfixes since. I suggest you install the development version directly from GitHub (`pip install git+https://github.com/gcovr/gcovr.git`).

 - When you run the `./my_unit_test` executable, this instrumented program will try to create .gcda files in the build directory. These files contain the coverage counters. The .gcno files only contain the metadata necessary to interpret the coverage counters. Can you check whether the .gcda files gave been created?

    Taking a guess, it might be necessary that the build directory is on the target file system for this to work.

 - If the .gcda files exist, the question is whether gcovr is able to find them. Running gcovr in --verbose mode can be helpful to determine which files were found, and whether they are removed by your filters.

In order to debug this problem efficiently, consider trying to collect coverage for a cross-compiled hello-world program. If you can show the complete build process and directory layout, it might be easier to see what went wrong or whether this is even possible.

**Comment by gocarlos** [comment]
Thanks for the wuick reply, I’ll do a hello world example and come back with the debug output... 
Note to self for now: gcda files are not generated... 
Evtl similar to this one: https://discuss.circleci.com/t/problems-using-lcov-gcov-for-c-code/13898

**Comment by gocarlos** [comment]
Note to self: one has to add those environment variables in order to create gcda files if the build and run dir are different e.g. as in cross compulation: 
Ref: 


https://stackoverflow.com/a/7671693
https://gcc.gnu.org/onlinedocs/gcc-6.3.0/gcc/Cross-profiling.html#Cross-profiling

**Comment by latk** [comment]
Oh, that's a good to know! I'm glad you're making progress :)

If you get all of this to work, would you like writing a small “How to collect coverage for cross-compiled programs?” section for the [Cookbook page in the docs](https://gcovr.com/cookbook.html)?

**Comment by latk** [comment]
If it's OK I'm now marking this question as resolved.

**Comment by gocarlos** [comment]
‘’’bash
# The compiler is called in /builds/group/project/_build on the host machine

# The unit tests are run in /opt/project/_build on the target machine

# before run the tests export the following env vars: 
export GCOV_PREFIX=/opt/project/_build 
export GCOV_PREFIX_STRIP=4

# And run the tests on target:
cd /opt/project/_build 
./my_tests

# the copy the _build folder on the target back to the host:
scp -rpC root@$ip-address:/opt/project/_build /builds/group/project/

# execute gvocr on the _build directory on the host machine
sudo gcovr /builds/group/project/_build -r /builds/group/project/ -k --exclude=".*/third_party/*." --exclude=".*/test/*." --exclude=".*/app/*." --exclude=".*/example/*."
‘’’

**Comment by latk** [comment]
Sorry @gocarlos I didn't see the edits until now.

But this looks really helpful! With a bit less project-specific details and a bit more explanation, it would make for a wonderful addition to the docs. Please make that PR when you find the time :)

**Comment by nikhilbagul** [comment]
Hey @gocarlos thanks for the detailed response.  I am running into a similar issue. I am building and running a UnitTest app for shared libraries made in QT and using/bundling them in a C++ based Qt app. I am running it to on an arm_v8 platform running QNX 7.0

Below are the environment specs to help you understand better: 

Compiler toolchain: 
qmake (3.1) (Qt 5.12.0)

I followed the steps mentioned here : 
[https://www.qnx.com/developers/docs/7.0.0/#com.qnx.doc.neutrino.utilities/topic/g/gcov.html]

After playing around much I am still trying to get my head around why the .gcda files generated on target do not produce a **gcovr** code coverage report when moved back to the host. 

Below is the log for reference: 
`Filters for --root: (1)
- <_sre.SRE_Pattern object at 0x7facca83d200>
Filters for --filter: (1)
- DirectoryPrefixFilter(\/Users\/nikhil\.bagul\/QtProjects\/VPCluster\/InstrumentCluster\/InstrumentCluster\/DatahandlerUtil\/FixedID\/src\/)
Filters for --exclude: (0)
Filters for --gcov-filter: (1)
- AlwaysMatchFilter()
Filters for --gcov-exclude: (0)
Filters for --exclude-directories: (0)
Scanning directory . for gcda/gcno files...
Found 5 files (and will process 3)
Pool started with 1 threads
Processing file: /Users/nikhil.bagul/QtProjects/VPCluster/InstrumentCluster/InstrumentCluster/DatahandlerUtil/FixedID/src/fixed_id.gcda
Running gcov: 'gcov /Users/nikhil.bagul/QtProjects/VPCluster/InstrumentCluster/InstrumentCluster/DatahandlerUtil/FixedID/src/fixed_id.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory /Users/nikhil.bagul/QtProjects/VPCluster/InstrumentCluster/InstrumentCluster/DatahandlerUtil/FixedID/src' in '/var/folders/_2/pxhj8y854g54d1bzsqkbt0jj8_vp25/T/tmpeNuONP'
Processing file: /Users/nikhil.bagul/QtProjects/VPCluster/InstrumentCluster/InstrumentCluster/DatahandlerUtil/FixedID/src/moc_fixed_id.gcda
Running gcov: 'gcov /Users/nikhil.bagul/QtProjects/VPCluster/InstrumentCluster/InstrumentCluster/DatahandlerUtil/FixedID/src/moc_fixed_id.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory /Users/nikhil.bagul/QtProjects/VPCluster/InstrumentCluster/InstrumentCluster/DatahandlerUtil/FixedID/src' in '/var/folders/_2/pxhj8y854g54d1bzsqkbt0jj8_vp25/T/tmpeNuONP'
Processing file: /Users/nikhil.bagul/QtProjects/VPCluster/InstrumentCluster/InstrumentCluster/DatahandlerUtil/FixedID/src/moc_fixed_values.gcno
Running gcov: 'gcov /Users/nikhil.bagul/QtProjects/VPCluster/InstrumentCluster/InstrumentCluster/DatahandlerUtil/FixedID/src/moc_fixed_values.gcno --branch-counts --branch-probabilities --preserve-paths --object-directory /Users/nikhil.bagul/QtProjects/VPCluster/InstrumentCluster/InstrumentCluster/DatahandlerUtil/FixedID/src' in '/var/folders/_2/pxhj8y854g54d1bzsqkbt0jj8_vp25/T/tmpeNuONP'
Gathered coveraged data for 0 files`

I have also tried running gcov on an individual source file to run into the following issue: 

`Unexpected version: *405.
Invalid .gcno File!
`

I double checked my paths and environment variables on the target platform with no luck, I am running out of ideas here. If you had any luck on generating coverage in your cross-platform venture it will be super helpful if you can share some wisdom. 

Thanks bud!
