### ISSUE TITLE
Detail of license: "U.S. Government retains certain rights in this software"

### ISSUE THREAD

**Issue by maxbrito** [gcovr/gcovr#276]
Hello,

I'm creating an inventory of 3rd party items where gcovr is one of the items being used. The license is very standard and friendly (thank you for sharing the code), my doubt is about the text: "U.S. Government retains certain rights in this software".

Would it be possible to list which rights are retained?

Many thanks,
Max

**Comment by latk** [comment]
Gcovr was originally created as part of a research project. It is normal for such projects to keep a notice on the source of their funding. This is not intended to limit your rights under the BSD 3-clause license, but you may not remove the notice. You might also note that the license starts with “all rights reserved” but then continues to enumerate what specifically you are allowed to do.

But I wondered about this notice myself. Maybe @whart222  or @jsiirola can provide more background?
