### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by Zlatan1988** [gcovr/gcovr#287]
On my computer with windows 10, I can create following conda environment
```
conda create -n test-coverage python=3.6
activate test-coverage
pip install gcovr
```
Now, I want to create this conda environment on a Windows 7 computer with no internet connection. I checked this link

https://stackoverflow.com/questions/41577527/conda-offline-install-update

but I couldn't find the package

>     gcovr.tar.bz2

How can I install gcovr on an offline computer? Where can I find the current package of gcovr to download?

Thanks!

Original from https://stackoverflow.com/questions/53743751/conda-gcovr-offline-installation

**Comment by latk** [comment]
Neither Conda nor offline installation are directly supported by gcovr, though it should work without problem.

If you want to install gcovr offline you need to download the package and all dependent packages yourself, e.g. the wheel (.whl) on the project page on PyPI: <https://pypi.org/project/gcovr/4.1/#files>. Alternatively, you can download gcovr's git repo (or a snapshot), extract the files into some directory, and then instruct pip to install from a local path.

In any case you will also have to manually resolve the dependencies. This is currently `Jinja2` which in turns depends on `MarkupSafe`.
