### ISSUE TITLE
Feature Request: Generate xml and html outputs in a unique run

### ISSUE THREAD

**Issue by csauge** [gcovr/gcovr#291]
Today we need to run twice the gcovr to generate a xml and a html.
It would be great to generate both during a unique execution of gcovr.

"Gcovr prints a text report by default, but can switch to XML **or** HTML."

**Comment by csauge** [comment]
Thank you for this very good summary.
I am unfortunatly unable to help currently...
Thus i will wait for a future enhancement :)
Thank you for all your job.

**Comment by latk** [comment]
This feature has been implemented in 2fbbe6eb4d98ba543110d13aacdca507c184defb and will be part of gcovr 4.2, which should be released this week. Thank you for the suggestion!
