### ISSUE TITLE
Create directory hierarchy in HTML report

### ISSUE THREAD

**Issue by dscole** [gcovr/gcovr#295]
Currently the HTML report creates a single html page with all the source file listed in it. For our project where we have 1000s of source files, it makes the html report less useful. 

It would be much more useful to us, if you could at least create another level of indirection, so that the main html page only shows directories  (with statistics aggregated on the sources files in that directory). Basically, what genhtml does. If you want to see individual files, you click on the directory and get the listing and statistics of each file in that directory.
Even nicer would be to provide a complete directory hierarchy that mimics the source directory structure (which genhtml doesn't have).

**Comment by latk** [comment]
This is a long-requested feature, see also #160. However, before any features in that direction can be added, the HTML report generator code needs to be cleaned up first. As mentioned elsewhere I've done incomplete work in that direction but have yet to merge it. Furthermore, I first want to put other HTML and generator infrastructure improvements in place.

However, you could help by doing some design work:

* should hierarchical reports be the default, or should gcovr select the default depending on the number of files?
* how should filepaths like `../libfoo/foo.c` be handled in a hierarchical report?

I'm closing this issue to mark it as a duplicate, but that does not mean I'm rejecting the idea!

**Comment by dscole** [comment]
Even if it's incomplete work, can you please push it at least. It would be great to see what direction you want to take this to.
A colleague and I were considering using a javascript package to display the coverage table, as was suggested by @RPGillespie6 in https://github.com/gcovr/gcovr/issues/289#issuecomment-447425025.
