### ISSUE TITLE
Next gcovr release

### ISSUE THREAD

**Issue by kolrami** [gcovr/gcovr#297]
Hi, I am currently using gcovr from pypi with version 4.1. However, I saw that in the master branch here there is a new option `--exclude_throw_branches` and I would like to also use that option. Do you already know when a new gcovr 4.2 release will be made and when this option is available in the official pypi package?

**Comment by latk** [comment]
Thank you for the reminder. There were some things I wanted to do before the next release but I never came around to it. I guess I should prepare a new release with the status quo to get current improvements out there. A release implies an upload to PyPI. I'll update this issue when it's done (ETA 3 - 30 days).

However, do feel free to install a development version directly from GitHub. The master branch is always supposed to be in a releasable state, though secondary artefacts like docs might not be quite up to date.

**Comment by bracco23** [comment]
Any update on this? There are some features, namely throw branch exclusion, which would be helpful to have and I can rely only on installing through pip repository, so installing development version is not an option for me.

**Comment by latk** [comment]
Turns out my ETA for the 4.2 release was totally wrong, and multiple months have passed. But now it's done, and you can upgrade to gcovr 4.2 to access these features!
