### ISSUE TITLE
Use os.path.commonpath in guess_source_filename

### ISSUE THREAD

**Issue by clynamen** [gcovr/gcovr#299]
https://github.com/gcovr/gcovr/blob/a782972a0a1bba585c35c42d3977d3931b03b5ec/gcovr/gcov.py#L167

I ran into an error where not-existing filename where generated due to common prefix. Indeed this function will return an invalid directory in this case

```
data_fname=/cygdrive/my_source/my_main.cpp
currdir=/cygdrive/my_build
```

it will result in directory _/cygdrive/my_ due to the fact that commonprefix return the prefix string instead of the prefix path

I think the proper function to use here is 
https://docs.python.org/3/library/os.path.html#os.path.commonpath

A similar issue caused https://github.com/gcovr/gcovr/issues/52

**Comment by latk** [comment]
Thank you for finding that! Historically, the problem is that gcovr still supports Python 2.7 which doesn't have a commonpath() function in the standard library, we therefore have a custom implementation in the gcovr.util module.

I'll fix this right away!
