### ISSUE TITLE
Gcovr does not recognize some gcda files

### ISSUE THREAD

**Issue by zhankangbao** [gcovr/gcovr#305]
Use command gcovr -r . get coverage,but Gcovr does not recognize some gcda files,Gcovr only recognizes partial coverage information.such as
![image](https://user-images.githubusercontent.com/39553841/56577922-da4ba580-65fe-11e9-8ce1-df4282a897e0.png)
the number of gcda file is more than above:，These files have paired gcda files, gcno files, and source code.
![image](https://user-images.githubusercontent.com/39553841/56577931-e33c7700-65fe-11e9-9c93-c4094bd10e69.png)
Use Lcov + genhtml can recognize these missing gcda files.
![image](https://user-images.githubusercontent.com/39553841/56578407-34009f80-6600-11e9-94de-e868ef688163.png)
use -v args,output something
![image](https://user-images.githubusercontent.com/39553841/56578468-52669b00-6600-11e9-9f9d-f6e6417a3e6e.png)

Has anyone meet such a problem?

**Comment by zhankangbao** [comment]
Perhaps a problem with the file directory structure

**Comment by latk** [comment]
Your idea that this might a problem related to the directory structure is a good guess. Your image shows that gcovr starts multiple attempts to read the gcda file, but none seem to work. Each attempt should be trying a different directory so that the paths to the source files can be resolved.

If you could explain your directory structure and build system with more detail I might  be able to help, but note that gcovr currently cannot handle certain scenarios (like recursive Makefile based builds).

**Comment by joemaniaci** [comment]
@latk I'm having this exact same problem as OP. I'm curious what counts as a recursive Makefile based build? For my legacy codebase, I have a root Makefile, and build.mak files in directories throughout the codebase. I have a good number of files reported in these directories, and a good number of files that aren't reported with gcov -r.

**Comment by Spacetown** [comment]
@joemaniaci What exact error do you get?

**Comment by joemaniaci** [comment]
It's the exact same output as above pretty much. All of the applicable .o files go into a single directory, alongside the gcno files. I collect all of the gcda files after a run and move them to the exact same folder. I move my terminal into the exact same directory where make is executed from, and execute gcovr and it only analyzes a partial subset of all the possible files.

The interesting bit is that I'm doing cross compiling, if I don't specify my compiler used, things work better. If I explicitly use /usr/local/gcc-linaro-7.1.1-2017.08-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcov I get...

> devel@joeM-3630-Tower:/mnt/ws/mclinux$ gcovr --gcov-executable /usr/local/gcc-linaro-7.1.1-2017.08-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcov 
> ------------------------------------------------------------------------------
>                            GCC Code Coverage Report
> Directory: .
> ------------------------------------------------------------------------------
> File                                       Lines    Exec  Cover   Missing
> ------------------------------------------------------------------------------
> ------------------------------------------------------------------------------
> TOTAL                                          0       0    --%
> ------------------------------------------------------------------------------

If I explicitly use --object-directory and provide the exact same directory in which it appears gcovr is finding on its own I get...

> devel@joeM-3630-Tower:/mnt/ws/mclinux$ gcovr --object-directory /mnt/ws/build_IXM300_arm-linux-gnueabihf/obj/ > joes_test.out
> (WARNING) relative referencing in --object-directory.
>         this could cause strange errors when gcovr attempts to
>         identify the original gcc working directory.
> (WARNING) GCOV produced the following errors processing /mnt/ws/mclinux/tools/genEvtExplanations/gee_Enclosure.gcda:
>         Cannot open source file gee_Enclosure.cpp
> 

Whereas before(with only gcov), I got 

> tools/genEvtExplanations/gee_Enclosure.cpp
>                                                4       0     0%   34,36,39,41
> tools/genEvtExplanations/gee_Enclosure.h      24       9    37%   58,63,75,83,90,97,104,109-110,118,124-125,133,141-142

Now as you can tell, I'm now using an eight year old compiler(not by choice), and I can only assume that's at least partially responsible for the inconsistent results.

**Comment by Spacetown** [comment]
Can you remove the option `--object-directory` and execute the command in the directory where the compiler is executed?

**Comment by joemaniaci** [comment]
Yeh, for the most part gcovr seems to find things well. I did discover using gdb and info that some of my .o files have their compilation directory a level or two into the codebase. I'm trying to figure out how to use search_paths to see if that improves results. 

I might also try some older versions of gcovr since my compiler is from 2017.

**Comment by Spacetown** [comment]
With toolchain I meant all tools from the same binary folder and not mixing the tools of different gcc versions.

**Comment by joemaniaci** [comment]
Yes, which is weird, as shown above I appear to be getting some results for some files with apt-get installed gcov, and for other files I successfully get results using /usr/local/gcc-linaro-7.1.1-2017.08-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcov...even though everything I'm analyzing was generated by /usr/local/gcc-linaro-7.1.1-2017.08-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++/gcc.

....although I'm not sure about runtime, I'm assuming a libgcov is in use and I haven't laid eyes on that, it's part of our kernel teams area.

**Comment by Spacetown** [comment]
If some result files need the other gcov installation they were generated with the other toolchain. You need to check your build process here.

**Comment by latk** [comment]
> All of the applicable .o files go into a single directory, alongside the gcno files. I collect all of the gcda files after a run and move them to the exact same folder. I move my terminal into the exact same directory where make is executed from, and execute gcovr and it only analyzes a partial subset of all the possible files.
>
> The interesting bit is that I'm doing cross compiling

Getting coverage from cross-compiled code is difficult. The .gcda directory structure must match the .o and .gcno directory structure, and you must then move the .gcda files from the system under test back to the system where you compiled the code. Unless the system under test has the exact same directory structure, you must run the executable with environment variables like `GCOV_PREFIX`, as explained in <https://gcc.gnu.org/onlinedocs/gcc/Cross-profiling.html>.

To illustrate this better: After compilation, you might have a directory layout like:

```
build/
  foo/
    a.gcno
    a.o
  main.gcno
  main.o
src/
  foo/a.cpp
  main.cpp
```

You copy the object code over to the other system, execute it there with appropriate GCOV environment variables, and copy the resulting .gcda files back which contain the actual coverage data. The directory layout on your build system should now be:

```
build/
  foo/
    a.gcda
    a.gcno
    a.o
  main.gcda
  main.gcno
  main.o
src/
  foo/a.cpp
  main.cpp
```

You can then test running gcov on an individual file – I recommend giving it the path to a .gcda data file. In contrast, gcovr only needs a search path, but you have to take care about its working directory. This should correspond to where you invoked the compiler.

Using the `gcovr --object-directory` option is almost always wrong. It was a legacy workaround heuristic that only exists for backwards compatibility.

All of the examples in https://github.com/gcovr/gcovr/issues/305#issuecomment-2621854742 show that you have a .gcno file (which the compiler generates alongside the object files), but either your .gcda files are empty, or they're in the wrong place.

If you're having problems with partial data or with files that only work with one gcov version but not another, clean your build directory before compiling for coverage. If you have to share the build directory between multiple build configurations, that's probably still a bad idea, but you may be able to tell gcovr where to look by specifying different search paths (but this may impact heuristics), or by selecting/excluding files via `--gcov-filter` or `--gcov-exclude`.

**Comment by Spacetown** [comment]
Sorry, I got the error message about the segmentation fault wrong. I understood that the error occurs with the cross compiling toolchain.

**Comment by joemaniaci** [comment]
So yeh, there is an area of our code that was compiling x86 code to do code generation. Once I excluded that directory, all was well. Thank you.
