### ISSUE TITLE
GCOVR run is not recognising the source in version 4.1

### ISSUE THREAD

**Issue by the-code-cult** [gcovr/gcovr#306]
I have simple project with one source file. Corresponding *.gcda, *.gcno files.
*gcda, *.gcno files are placed in <ProjectRoot>/gcov_intermediate.
source file is present in <ProjectRoot>/src/abc.cpp

I run gcovr via batch scripts as below:

set datafiles=gcov_intermediate
set gcovr_src=deliverables\src\
gcovr %datafiles% %gcovr_src% -s -p --html --html-details -o Test.html --verbose

**Error I am facing is:**
Traceback (most recent call last):
  File "c:\toolbase\python\3.6.6.2\python-3.6.6.amd64\lib\site-packages\gcovr\workers.py", line 71, in worker
    work(*args, **kwargs)
  File "c:\toolbase\python\3.6.6.2\python-3.6.6.amd64\lib\site-packages\gcovr\gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "c:\toolbase\python\3.6.6.2\python-3.6.6.amd64\lib\site-packages\gcovr\gcov.py", line 655, in run_gcov_and_process_files
    stderr=subprocess.PIPE).communicate()
  File "c:\toolbase\python\3.6.6.2\python-3.6.6.amd64\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\toolbase\python\3.6.6.2\python-3.6.6.amd64\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by the-code-cult** [comment]
I have simple project with one source file. Corresponding *.gcda, *.gcno files.
*gcda, *.gcno files are placed in <ProjectRoot>/gcov_intermediate.
source file is present in <ProjectRoot>/src/abc.cpp

I run gcovr via batch scripts as below:

set datafiles=gcov_intermediate
set gcovr_src=deliverables\src\
gcovr %datafiles% %gcovr_src% -s -p --html --html-details -o Test.html --verbose



**Error I am facing is:**
Traceback (most recent call last):
  File "c:\toolbase\python\3.6.6.2\python-3.6.6.amd64\lib\site-packages\gcovr\workers.py", line 71, in worker
    work(*args, **kwargs)
  File "c:\toolbase\python\3.6.6.2\python-3.6.6.amd64\lib\site-packages\gcovr\gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "c:\toolbase\python\3.6.6.2\python-3.6.6.amd64\lib\site-packages\gcovr\gcov.py", line 655, in run_gcov_and_process_files
    stderr=subprocess.PIPE).communicate()
  File "c:\toolbase\python\3.6.6.2\python-3.6.6.amd64\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\toolbase\python\3.6.6.2\python-3.6.6.amd64\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by latk** [comment]
I'm not entirely sure what the cause of the problem here is. The error could indicate that you do not have the `gcov` tool installed or available in your %PATH%.

While gcov is part of GCC, it might be installed under another name (like `gcov-7`). If so, provide the correct name (or the full path to the gcov executable) via the `GCOV` environment variable or the `--gcov-executable` option.

**Comment by the-code-cult** [comment]
> 
> 
> I'm not entirely sure what the cause of the problem here is. The error could indicate that you do not have the `gcov` tool installed or available in your %PATH%.
> 
> While gcov is part of GCC, it might be installed under another name (like `gcov-7`). If so, provide the correct name (or the full path to the gcov executable) via the `GCOV` environment variable or the `--gcov-executable` option.


**---------------------------------------------------------------------------------------------------------------**
I have gcov installed, gcovr utility is also available as part fof PIP installation.
I have below version for all the three utilities.
gcovr 4.1
gcov (MinGW.org GCC-6.3.0-1) 6.3.0
Python 3.6.6

And in my scripts I have set the paths for all these tools before using them.

set GCovrpath=C:\toolbase\python\3.6.6.2\python-3.6.6.amd64\Scripts\
set GCovpath=C:\Users\%username%\qnx700\host\win64\x86_64\usr\bin\

set datafiles=gcov_intermediate
set gcovr_src=deliverables\src

%GCovpath%ntox86_64-gcov.exe %%i %datafiles% >> DefaultCoverage.log
gcovr %datafiles% %gcovr_src% -s -p --html --html-details -o Test.html --verbose


Interestingly, I found that i do not have set the environment path for Python exe. But it still runs fine in my machine.

**Comment by latk** [comment]
OK, if I read that correctly then adding the option `--gcov-executable %GCovpath%ntox86_64-gcov.exe` to the gcovr call should do the trick for your script. Because gcov is installed under a non-standard name, you need to tell gcovr explicitly which executable to call.

You don't have to set a path for python.exe because pip creates a wrapper executable for gcovr that takes care of locating the Python interpreter you are using. Only that `gcovr` wrapper needs to be in your path. I'm not sure that your `GCovrpath` variable is being used for that, maybe you had already set the path accordingly.

**Comment by the-code-cult** [comment]
> 
> 
> OK, if I read that correctly then adding the option `--gcov-executable %GCovpath%ntox86_64-gcov.exe` to the gcovr call should do the trick for your script. Because gcov is installed under a non-standard name, you need to tell gcovr explicitly which executable to call.
> 
> You don't have to set a path for python.exe because pip creates a wrapper executable for gcovr that takes care of locating the Python interpreter you are using. Only that `gcovr` wrapper needs to be in your path. I'm not sure that your `GCovrpath` variable is being used for that, maybe you had already set the path accordingly.

Thanks alot **latk**,
The solution you provided works very well.

**this how my instruction looks now.**

%GCovpath%ntox86_64-gcov.exe %%i %datafiles% >> DefaultCoverage.log
gcovr %datafiles% %gcovr_src% -s -p --html --html-details  **--gcov-executable %GCovpath%ntox86_64-gcov.exe**  -o Test.html --verbose
