### ISSUE TITLE
Documentation offline

### ISSUE THREAD

**Issue by robinvalk** [gcovr/gcovr#309]
Hi,

It seems that the documentation on [http://gcovr.com/guide.html](http://gcovr.com/guide.html) is offline. Idk if you are aware of this issue, therefore this issue ^^

Thanks for your work!

**Comment by robinvalk** [comment]
Hmm it seems that the www. subdomain is only mapped to the website. Although multiple location link to the domain directly without the www prefix.

**Comment by latk** [comment]
Thank you for reporting this! Yes, there is a known DNS issue with the
website. Unfortunately I don't have direct access to the DNS so I don't
have an ETA for a fix.

Workarounds:

* https://www.gcovr.com
* https://gcovr.readthedocs.io/

**Comment by blueyed** [comment]
Could/should the README be updated to include the `www.` prefix then?
