### ISSUE TITLE
How to generate *.gcov selectivily within & | outside a Project.

### ISSUE THREAD

**Issue by the-code-cult** [gcovr/gcovr#310]
I m working on code coverage automation via GCov(with GCovr combo)... And I am getting too many unwanted *.gcov generated in the project. 
**_I suspect, some how "exclude " does not seem to work._**

The question here is:
1. *.gcov files are getting generated for files which are out of the project root folder.(but required for project to build) How to ignore them?

2. How to ignore  specific files / folders within the project also?

I tried 
1. -e=/some/folder/path/*
2. --exclude=*.\hpp 

What is missing here?

Regards,
Basu A S

**Comment by latk** [comment]
This is just the way GCC's profiling/code coverage functionality works.

1. a gcno/gcda file pair is created *per compilation unit* (.o file). These coverage data files may include coverage information for every source file that was compiled into the compilation unit.
2. for each gcda file:
    1. gcovr runs the gcov tool. This tool processes the gcno/gcda files and creates one gcov report *per source file*.
    2. gcovr opens every gcov file, tries to reconstruct the path to the source file, and then applies the filter/exclude mechanism to decide whether to fully parse the gcov file.
3. gcovr takes all the aggregated coverage information and renders it as a report

There is no way (that I know of) to apply filters within gcov. All of the filters are post-processing.

**Comment by the-code-cult** [comment]
> 
> 
> This is just the way GCC's profiling/code coverage functionality works.
> 
>     1. a gcno/gcda file pair is created _per compilation unit_ (.o file). These coverage data files may include coverage information for every source file that was compiled into the compilation unit.
> 
>     2. for each gcda file:
>        
>        1. gcovr runs the gcov tool. This tool processes the gcno/gcda files and creates one gcov report _per source file_.
>        2. gcovr opens every gcov file, tries to reconstruct the path to the source file, and then applies the filter/exclude mechanism to decide whether to fully parse the gcov file.
> 
>     3. gcovr takes all the aggregated coverage information and renders it as a report
> 
> 
> There is no way (that I know of) to apply filters within gcov. All of the filters are post-processing.

Thanks Lukas.
that would actually help user to to get rid of unnecessary gcov generation for almost entire project.
will wait and see if GCOV tool developers consider this point.
