### ISSUE TITLE
*.gcda:stamp mismatch with notes file

### ISSUE THREAD

**Issue by the-code-cult** [gcovr/gcovr#314]
I am working on code-coverage part, in which there is a step where upon running the UnitTest binary files on QNX target(VMWare workstation). I get intermediate files (*.gcda) attributed with its generation time stamp.

 

**Background**:

GCOV tool runs considering the objects files(*.gcno) and data files(*.gcda) which are result of project build and binary execution on the target respectively.

 

**Problem**:

Since there is a coupling between time stamp of both *gcno and *gcda order. Code coverage result is not produced for few of the files.

i.e gcda files' timestap is lagging behind than gcno due to QNX(VMWare workstation) time settings.

 

**What I have tried:**

**1.** I have changed the time by "date" command and I get proper display with new time set.

How to change date and time in QNX machine

Date <MonthDayHourMinuteCenturyYear> 5Th May 2:50 20th century 2019

date 052914502019
 

**2.** I have changed the TIMEZONE also from GMT to Indian Standard TIME.

env TZ=PST8PDT

export TZ=PST8PDT

setconf _CS_TIMEZONE PST8PDT (I failed to run this step)

 **3.** When I run "date" command I get --> Wed May 29 09

Unfortunately: When I execute the binaries, I always get the *gcda files with lagging time stamp from the QNX target machine?

 **4.** I have **touched** the files by touch command, it changes the time stamp. But still gcov give same results.

 I tried touch command, it changes the time stamp attribute of the respective file. But somehow gcov does not recognize this new time stamp.

I think now its GCOV's issue to read and address the attribute changes?

Regards,
Basavaraj A S

**Comment by latk** [comment]
The time stamp should not be relevant for the coverage process.

* the gcno files are created at compilation time
* the gcda files are created when the instrumented code runs

It is therefore normal that the gcda files are younger. The time should not be the problem, and your message contains no indication that the timestamps cause any problems.

I looked into the gcov source code (which is **not** affiliated with gcovr) and can tell you that the timestamp of the gcda files is ignored. The timestamp of the gcno file is only used to warn if a corresponding source file has been modified in the meanwhile.

---

You have not stated the actual problem clearly. From your message, I am assuming:

* that you are using two separate system for compilation and execution of the tests
* that you are copying the gcda files back to the system on which you compiled the software
* that gcovr runs without error messages
* that the coverage reports miss some or all of your project files.

If so, this is a kind of cross-compilation. Please see issue #259 for a report on how to do that. It seems you must set some environment variables when running the tests, so that the coverage data is stored in the correct place.

If I misunderstood the problem, please clearly describe clearly:

* what your environment is (gcovr version, gcc version, operating systems, …)
* what your rough project layout is (where your build directory is, from where you run gcovr)
* what behaviour you expected
* what is actually happening (ideally, with the help of `gcovr --verbose` output)

**Comment by the-code-cult** [comment]
> 
> 
> The time stamp should not be relevant for the coverage process.
> 
>     * the gcno files are created at compilation time
> 
>     * the gcda files are created when the instrumented code runs
> 
> 
> It is therefore normal that the gcda files are younger. The time should not be the problem, and your message contains no indication that the timestamps cause any problems.
> 
> I looked into the gcov source code (which is **not** affiliated with gcovr) and can tell you that the timestamp of the gcda files is ignored. The timestamp of the gcno file is only used to warn if a corresponding source file has been modified in the meanwhile.
> 
> You have not stated the actual problem clearly. From your message, I am assuming:
> 
>     * that you are using two separate system for compilation and execution of the tests
> 
>     * that you are copying the gcda files back to the system on which you compiled the software
> 
>     * that gcovr runs without error messages
> 
>     * that the coverage reports miss some or all of your project files.
> 
> 
> If so, this is a kind of cross-compilation. Please see issue #259 for a report on how to do that. It seems you must set some environment variables when running the tests, so that the coverage data is stored in the correct place.
> 
> If I misunderstood the problem, please clearly describe clearly:
> 
>     * what your environment is (gcovr version, gcc version, operating systems, …)
> 
>     * what your rough project layout is (where your build directory is, from where you run gcovr)
> 
>     * what behaviour you expected
> 
>     * what is actually happening (ideally, with the help of `gcovr --verbose` output)

Your understanding is almost same as how exactly the set up is.
1. I agree(gcda files are younger), and wonder why should the stamp should be relevant here?
   But I get an error message while running gcov as mentioned below.
  gcov_intermediate\qnx_x86_64/Str_Base64.gcda:stamp mismatch with notes file
  gcov_intermediate\qnx_x86_64/Str_Base64.gcda:stamp mismatch with notes file
  gcov_intermediate\qnx_x86_64/Str_Base64.gcda:stamp mismatch with notes file

2. When I browsed for for root of such error I got to know:
    You may get "stamp mismatch" when the .gcda files are newer than the .gcno files.
    It can happen mostly for 2 reasons: 
    1. You might have re-build the code after running the test and before trace file generation. 
    2. The binary might be built in one machine and test was ran in other machine, whose time is ahead of         the build machine.
    For these two cases you have to just make sure the file creation time of .gcda is greater than .gcno and    .c* files.
    You can do that by just doing "touch *.gcda" and then run the lcov command.

![image](https://user-images.githubusercontent.com/10877255/58700507-d5c49a80-83bd-11e9-8e6a-9ae2e216a73b.png)

About code coverage environment:
1. Yes, I am compiling on windows(x86) host. Test binaries are run on the VMWare workstation for QNX-x86_64 target to get the *.gcda files.
2. gcov (MinGW.org GCC-6.3.0-1) 6.3.0 And gcovr 4.1
3. Rest of your understanding is correct.

![image](https://user-images.githubusercontent.com/10877255/58700507-d5c49a80-83bd-11e9-8e6a-9ae2e216a73b.png)

1. I have set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fprofile-arcs -ftest-coverage -fprofile-dir=tmp")
on the target i am getting the *.gcda getting generate at /tmp/tmp/*.gcda
2. I get *.gcno at differenct location in project area, **but** I have collected all *.gcno and placed under a separate folder "gcov_intermediate"
3. From target machine also, i collect all *.gcda and put them under "gcov_intermediate".
4. I run gcovr from project root, providing gcov_intermediate as argument input.

Issue [#259](url) in fact gives a good hint, but some how not able to map to my issue, i will jave to adopt some things. I will give a try.

![image](https://user-images.githubusercontent.com/10877255/58700507-d5c49a80-83bd-11e9-8e6a-9ae2e216a73b.png)

Regards,
Basu A S

**Comment by latk** [comment]
A “stamp mismatch” error is shown when the compilation time stamp *within* the gcno and gcda files doesn't match. The stamp must match exactly. File metadata isn't used for this check, so `touch` can't help. The stamp is also not depended on system time, it's more like a random number that is compiled into the instrumented object code and the gcno file.

My guess is that you are trying to use gcda files from one compilation with gcno files from a different compilation. This will not work, you must use both from the same compilation run.

In any case, this seems to be a problem with using gcc/gcov. The gcovr tool is just a wrapper around gcov and cannot help here. I'm therefore closing this issue.
