### ISSUE TITLE
gcovr RelativeFilter is relative to os.getcwd, should be relative to --root

### ISSUE THREAD

**Issue by tsondergaard** [gcovr/gcovr#319]
--exclude filters were not working for me, because I did not expect them to be relative to the current working directory. I expected them to be relative to the option provided with --root.

**Comment by latk** [comment]
This is a design decision that can't be changed without breaking backwards compatibility.

However, the documentation could be more explicit about this so I'm leaving this issue open as a reminder.

**Comment by tsondergaard** [comment]
@latk thanks for the fast response. I think you are right that it would be a good idea to document that the current working directory is important regardless of whether --root is passed.
