### ISSUE TITLE
Filters don't work across Windows drive boundaries

### ISSUE THREAD

**Issue by latk** [gcovr/gcovr#320]
I have _project in D drive_, the _compiler tool chain in C drive_.
When I try generating code coverage, it tries to generate coverage report for the files from compiler tool chain also, Even after explicitly mentioning the --root=<ProjectRoot> from D drive.

How can I inform GCOVR tool that changing the drive for reports is crime:-).

**This actually causing some python utility error in my machine**
ValueError: path is on mount 'c:', start on mount 'D:'

_Originally posted by @the-code-cult in https://github.com/gcovr/gcovr/issues/293#issuecomment-507248288_

**Comment by latk** [comment]
Gcovr is Unix-first software, so it's unsurprising that there are further Windows compatibility issues. Unfortunately I have no idea how to test and fix this.

If someone can investigate this and perhaps fix it with a pull request, that would be most welcome :)

**Comment by AbdManian** [comment]
I've had the same issue when using `--filter` switch in windows. I create a very simple workaround but have no idea is it correct way to fix this issue?

**Comment by latk** [comment]
@AbdManian Now that you've shown the fix, the solution seems obvious. Thank you! Would you like to submit a pull request?

However, it might be better to avoid just swallowing all errors, and instead make this fix specific to Windows. For example, something like this might work?

```python
def match(self, path):
    abspath = os.path.realpath(path)

    # On Windows, a relative path can never cross drive boundaries.
    # If so, the relative filter cannot match.
    if sys.platform == 'win32':
        our_drive, _ = os.path.splitdrive(abspath)
        root_drive, _ = os.path.splitdrive(self.root)
        if our_drive != root_drive:
            return None

    relpath = os.path.relpath(abspath, self.root)
    return super(RelativeFilter, self).match(relpath)
```

**Comment by AbdManian** [comment]
> @AbdManian Now that you've shown the fix, the solution seems obvious. Thank you! Would you like to submit a pull request?
> 
> However, it might be better to avoid just swallowing all errors, and instead make this fix specific to Windows. For example, something like this might work?
> 
> ```python
> def match(self, path):
>     abspath = os.path.realpath(path)
> 
>     # On Windows, a relative path can never cross drive boundaries.
>     # If so, the relative filter cannot match.
>     if sys.platform == 'win32':
>         our_drive, _ = os.path.splitdrive(abspath)
>         root_drive, _ = os.path.splitdrive(self.root)
>         if our_drive != root_drive:
>             return None
> 
>     relpath = os.path.relpath(abspath, self.root)
>     return super(RelativeFilter, self).match(relpath)
> ```
Platform specific issue, platform specific fix. Good idea. I will test it in my windows machine and inform you if there is any issue.
