### ISSUE TITLE
Gcovr total line count different from lcov

### ISSUE THREAD

**Issue by charleyw** [gcovr/gcovr#327]
Hi there, 
I'm using gcovr to generate coverage data on exist .gcov files. It's very good tool.

But I found there is a small diference in counting total lines according to lcov results. 
Gcovr always show more total line than lcov results (in html results).
I found it's because lcov totally respect "-" marker in .gcov file, but Gcovr not, see the source code below,

```python
        if firstchar == '-' or (self.excluding and firstchar in "#=0123456789"):
            # remember certain non-executed lines
            if self.excluding or is_non_code(code):
                self.coverage.line(self.lineno).noncode = True
            return True

```
Because this piece of code there are lots of code (comments, include statements, declaration) that lcov not deem as executable code but gcovr seem to treat as executable code. 
This caused a big issue that the line coverage is very low in gcovr compare with lcov which is due to the total line in gcovr is bigger.

I googled that "-" in .gcov file means no code, so i just edit gcovr source code(list above) to following. Then the line coverage calculated in gcovr is same as lcov.
```python
        if firstchar == '-':
            self.coverage.line(self.lineno).noncode = True
            return True

        if (self.excluding and firstchar in "#=0123456789"):
            # remember certain non-executed lines
            if self.excluding or is_non_code(code):
                self.coverage.line(self.lineno).noncode = True
            return True
```
So. I doubt that is lcov calculation is wrong or there are some mistakes in gcovr?

**Comment by latk** [comment]
Thank you for investigating this problem. But I'm not sure I understand it correctly. Could you show a small example program where gcovr produces wrong coverage? Which version of gcovr (release 4.1 or the development version)?

Per my understanding of gcovr's current behaviour, only covered and uncovered lines are used to determine the total number of lines. Noncode lines are excluded from that number. So I'm not sure whether your proposed change could have any effect.

**Comment by charleyw** [comment]
@latk Sorry i just checked my env, found it's my own fault. Due to i'm using master branch and i changed a little but not awared that change.

**Comment by latk** [comment]
No problem! Opening the issue was still good because it might have been a real bug in gcovr. I definitely want to fix those :)
