### ISSUE TITLE
Uncovered files not reported when using gcov 4.7

### ISSUE THREAD

**Issue by markwil** [gcovr/gcovr#33]
gcovr 3.1 does not include uncovered files in its report when used in conjunction with gcov 4.7.2 (on Ubuntu 12.10).

From examination, it seems the issue might stem from gcov 4.7.2 not producing .gcov files for source files that do not have corresponding .gcda files.

Separately invoking gcov on an uncovered source file produces output indicating that no .gcov file is generated.  E.g.:
`gcov src/Foo.cpp --branch-counts --branch-probabilities --preserve-paths --object-directory build/src` 
produces output containing:

> File 'src/Foo.cpp'
> No executable lines
> No branches
> No calls
> Removing 'src#Foo.cpp.gcov'

Where Foo.cpp is not exercised by test code.

**Comment by itavero** [comment]
Did anyone manage to work around this?
I'm still running into this issue.

````
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
gcov (Ubuntu 4.8.2-19ubuntu1) 4.8.2
gcovr 3.2
````

**Comment by schlauch** [comment]
From the options listed above, I selected  "Force to include all header files into the test executable":
* Basically, we have a test executable for every module (simply a sub-directory).
* We make sure that all headers of this module are included.
* Thus, we are able to see all files in the report.
