### ISSUE TITLE
4.1: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [gcovr/gcovr#332]
<pre>+ cd gcovr-4.1
+ /usr/bin/python3 setup.py test
running test
running egg_info
writing gcovr.egg-info/PKG-INFO
writing dependency_links to gcovr.egg-info/dependency_links.txt
writing entry points to gcovr.egg-info/entry_points.txt
writing requirements to gcovr.egg-info/requires.txt
writing top-level names to gcovr.egg-info/top_level.txt
reading manifest file &apos;gcovr.egg-info/SOURCES.txt&apos;
writing manifest file &apos;gcovr.egg-info/SOURCES.txt&apos;
running build_ext
test_gcovr (unittest.loader._FailedTest) ... ERROR
gcovr.tests.test_gcovr (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_gcovr (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_gcovr
Traceback (most recent call last):
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/home/tkloczko/rpmbuild/BUILD/gcovr-4.1/gcovr/tests/test_gcovr.py&quot;, line 11, in &lt;module&gt;
    from pyutilib.misc.pyyaml_util import compare_repn as compare_xml
ModuleNotFoundError: No module named &apos;pyutilib&apos;

======================================================================
ERROR: gcovr.tests.test_gcovr (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: gcovr.tests.test_gcovr
Traceback (most recent call last):
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 377, in _get_module_from_name
    __import__(name)
  File &quot;/home/tkloczko/rpmbuild/BUILD/gcovr-4.1/gcovr/tests/test_gcovr.py&quot;, line 11, in &lt;module&gt;
    from pyutilib.misc.pyyaml_util import compare_repn as compare_xml
ModuleNotFoundError: No module named &apos;pyutilib&apos;

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
Test failed: &lt;unittest.runner.TextTestResult run=2 errors=2 failures=0&gt;
error: Test failed: &lt;unittest.runner.TextTestResult run=2 errors=2 failures=0&gt;
error: Bad exit status from /var/tmp/rpm-tmp.ddQtY5 (%check)
</pre>

**Comment by latk** [comment]
There are some development requirements you have to install for running the tests. You can do so by running `pip install -r requirements.txt` (replacing `pip` with the correct name for your installation, e.g. `python3 -m pip`). Please also note that invoking the tests via `pytest` is recommended over `setup.py test`.

Please also see the CONTRIBUTING document which contains details about [How to set up a development environment](https://github.com/gcovr/gcovr/blob/master/CONTRIBUTING.rst#how-to-set-up-a-development-environment) and [Running the test suite](https://github.com/gcovr/gcovr/blob/master/CONTRIBUTING.rst#test-suite).
