### ISSUE TITLE
--sonarqube option does not work

### ISSUE THREAD

**Issue by rianf2** [gcovr/gcovr#337]
I am trying to use gcovr to get some coverage statistics which will be parsed by SonarQube. It seems the ```--sonarqube``` option is not supported but is documented.  

For example, when I run this command: 
```gcovr -r . -r someUnwantedDir/ --sonarqube``` 

I get the following output: 
```usage: gcovr [options] [search_paths...]```
```gcovr: error: unrecognized arguments: --sonarqube```

I am using gcovr version 4.1.

Can somebody please help?

**Comment by latk** [comment]
The SonarQube output format is implemented, but has not yet been released.
I hope to cut a new release (including that functionality) as gcovr 4.2 on
Wednesday. If you want to use this format now, please install the
development version directly from GitHub (see the README for details).

The documentation (https://gcovr.com/) is available for multiple versions.
The “master” documentation refers to the development version, whereas
“stable” or “4.1” refer to released versions.

As an additional pointer, it seems that your gcovr invocation is wrong: you
cannot have multiple -r/--root arguments, and should write the SonarQube
report to a file. Instead, try "gcovr --exclude someUnwantedDir/
--sonarqube coverage.xml"

**Comment by rianf2** [comment]
Thanks for the swift reply and the information

**Comment by latk** [comment]
Yesterday, gcovr 4.2 was released with support for the `--sonarqube` option. You can install this version from PyPI using the `pip` tool.
