### ISSUE TITLE
Aggregation of coverage measurements for code with ifdef

### ISSUE THREAD

**Issue by peter-toft-greve** [gcovr/gcovr#338]
I have tried to raise a question on how to aggregate coverage measures for code with ifdef
in https://stackoverflow.com/questions/58632496/how-to-get-100-coverage-with-gcovr-with-ifdef-code
Basically - how can I summarize or aggregate test results from my code when tested with different 
compile options. I cannot make this work.

I guess that I probably should have asked here directly.
If answered I will cross-answer the stackoverflow my self.

**Comment by latk** [comment]
I saw your StackOverflow question, and it motivated me to finally release
the necessary functionality (it had already been implemented for a while).

Please see the documentation on combining/merging coverage data:
https://gcovr.com/en/stable/guide.html#combining-tracefiles
In a nutshell, you create a JSON report with the coverage of each
configuration,
and can then use the -a/--add-tracefile option to merge the JSON files, and
create your desired report format.
This requires that you update to gcovr 4.2.

**Comment by peter-toft-greve** [comment]
@latk This sounds brilliant. Will test as the first thing tomorrow morning. Thanx a mil. More to follow :)

**Comment by peter-toft-greve** [comment]
@latk This is a PURE homerun - thanx a mil!! 
I will answer on StackOverflow and credit you (+reference the documentation)

For sake of completeness - I take it that this cannot be done prior to gcovr 4.2?

**Comment by latk** [comment]
Thank you. Yes, the necessary features (JSON output, merging) were first released with gcovr 4.2.

**Comment by peter-toft-greve** [comment]
@latk  One suggestion for further updates; that 
gcovr --add-tracefile run-*.json
is supported - to avoid to name the *json files

**Comment by peter-toft-greve** [comment]
@latk as promised > I have updated https://stackoverflow.com/questions/58632496/ and credited you. THANX!!!
