### ISSUE TITLE
Early fail when HTML details output directory does not exist

### ISSUE THREAD

**Issue by 0ge** [gcovr/gcovr#346]
If `gcovr` is run with `--html-details`, but the designated output directory does not exist, gcovr will run the analysis (which may take some time). It will only then discover that the output directory does not exist, and fail with `IOError: [Errno 2] No such file or directory`.

From a user perspective, it would be great if this was checked prior to the analysis. It may need some consideration if multiple output formats are specified.

**Comment by latk** [comment]
Absolutely, it would be a good idea to check up front that the output files can be written, without already creating them.

However, I'm not sure whether this can be done in a cross-platform manner. On Unix, I'd check whether the target directory exists and that the write-bit is set in the mode of the target directory, as retrieved by the stat() function. Maybe just checking that the target directory exists would be sufficient.

I'd be glad to merge a pull request with a best-effort check that does something like:

``` python
# pseudocode
for outfile in [options.output, options.html, options.html_details, options.xml, ...]:
    if outfile is empty:
       continue
    if not writeable(dirname(outfile)):
        error("directory {} is not writeable", dirname(outfile))
```
