### ISSUE TITLE
Allow generating text report in addition to any of the other output formats

### ISSUE THREAD

**Issue by Ram-Z** [gcovr/gcovr#347]
Currently when choosing any of the other output formats it's not possible to get the text report printed to stdout or even a file.

I've tried the following, but neither work.

```
$ gcovr --sonarqube coverage.xml --output
usage: gcovr [options] [search_paths...]
gcovr: error: argument -o/--output: expected one argument
$ gcovr --sonarqube coverage.xml --output -
(WARNING) --output='-' option was provided but not used.
$ gcovr --sonarqube coverage.xml --output /dev/stdout
(WARNING) --output='/dev/stdout' option was provided but not used.
$ gcovr --sonarqube coverage.xml --output report.txt
(WARNING) --output='report.txt' option was provided but not used.
```

**Comment by latk** [comment]
Thank you for pointing this out! You're right, there is no `--txt` option. Text output is the default whereas all other formats must be explicitly selected. The `--output` option just provides the default target for the first active output that wasn't given an explicit output file, and is not specific to text output.

The `-s/--print-summary` option predates support for multiple output formats and produces something like the text report, but always on stdout.

So what is your intention here?

* To get a quick coverage summary on the console, please try `--print-summary`.

* If you want to save the text report for further processing/later consumption, we can discuss whether to add a `--txt` option. That would be nice for consistency's sake, but I don't really see the use case: all other formats include significantly richer data.

**Comment by Ram-Z** [comment]
I'd like the text output also. It's mostly to be printed out to stdout for a quick overview from a CI build. All the other outputs cannot be parsed by a human.

`--print-summary` is what I'm using now, but I think it doesn't provide enough information.

I've opened the issue mostly to address the inconsistency.

**Comment by Spacetown** [comment]
@Ram-Z In the test the options `--xml` and `--txt` are used together and both outputs are produced.
