### ISSUE TITLE
make it optional to use inline css or not

### ISSUE THREAD

**Issue by derived-coder** [gcovr/gcovr#349]
Some CI servers has disabled inline css by default:
https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

please make it possible to generate a HTML report where the css is not inlined.

**Comment by latk** [comment]
This is a duplicate of #125 and I am therefore closing the issue.

With #348 the inline `style=""` attributes have been removed from the HTML reports, so now linking the CSS as a separate file has become reasonable. That way, the CSP would have to allow same-origin styles, but not unsafe inline styles. I hope I'll get around to the necessary work in about a week, no time right now.
