### ISSUE TITLE
Gcovr generate empty coverage report

### ISSUE THREAD

**Issue by lifreshman** [gcovr/gcovr#352]
gcovr version 4.2
src dir: `/opt/examples/src/test/test1/example.cpp`
gcda dir: `/opt/examples/build/test/test1/example.gcda`
gcno dir: `/opt/examples/build/test/test1/example.gcno`
cd /opt/examples
1. `gcovr -r ./src ./build`  generate **empty** coverage report
2. `gcovr -r ./src/* ./build`  generate **empty** coverage report
3. `gcovr -r ./src/*/* ./build`  get **correct** coverage report

Why are the coverage reports 1 & 2 empty?

**Comment by latk** [comment]
I'm not entirely sure why that's happening. It can be helpful to run gcovr in `-v` (verbose) mode, which outputs information about which files and filters are considered.

Command 1 should work, whereas the arguments in commands 2 and 3 are likely wrong:

* The `-r` (root) argument must be a path to your source directory. Using glob patterns like `src/*` doesn't do anything useful here.

* These glob patterns might also be expanded by your shell, which could pass completely wrong arguments to gcovr.

Could you perhaps show the output of running `gcovr -v -r src test`? If the output contains sensitive details such as usernames or project names, please redact them.

**Comment by lifreshman** [comment]
> I'm not entirely sure why that's happening. It can be helpful to run gcovr in `-v` (verbose) mode, which outputs information about which files and filters are considered.
> 
> Command 1 should work, whereas the arguments in commands 2 and 3 are likely wrong:
> 
> * The `-r` (root) argument must be a path to your source directory. Using glob patterns like `src/*` doesn't do anything useful here.
> * These glob patterns might also be expanded by your shell, which could pass completely wrong arguments to gcovr.
> 
> Could you perhaps show the output of running `gcovr -v -r src test`? If the output contains sensitive details such as usernames or project names, please redact them.

![image](https://user-images.githubusercontent.com/3888136/75347672-3bf23580-58dc-11ea-8fb6-bce4c8eee1de.png)

**Comment by latk** [comment]
That `-v` output indicates that gcovr is searching for the correct directory and cannot find it. The issue is this: the .gcno files contain a relative path to the source file. The source path is relative to the directory in which you ran the compiler. Gcovr doesn't know where that was. So what gcovr does is to just try out various paths to see if they work. In the above log, we see:

* a temp dir, hoping that the .gcno actually contains an absolute path
* the `-r` root dir
* any parent dir of the .gcda file

You should always run gcovr from the same directory that you ran your build process from. Here, it seems that you are running the compiler from the `src/test/test1` directory.

So in your specific case, this should work: first go into that `src/test/test1` directory, then run gcovr with the correct paths. You could use relative paths, but here absolute paths seem easier to read:

``` bash
cd /opt/examples/src/test/test1
gcovr -r /docker/opt/examples/src /docker/opt/examples/build
```

And again: do not use glob patterns like `*` in your arguments to gcovr. That does not do what you think it does. Here, it only works accidentally because all of your directories only contain a single entry.

**Comment by lifreshman** [comment]
> That `-v` output indicates that gcovr is searching for the correct directory and cannot find it. The issue is this: the .gcno files contain a relative path to the source file. The source path is relative to the directory in which you ran the compiler. Gcovr doesn't know where that was. So what gcovr does is to just try out various paths to see if they work. In the above log, we see:
> 
> * a temp dir, hoping that the .gcno actually contains an absolute path
> * the `-r` root dir
> * any parent dir of the .gcda file
> 
> You should always run gcovr from the same directory that you ran your build process from. Here, it seems that you are running the compiler from the `src/test/test1` directory.
> 
> So in your specific case, this should work: first go into that `src/test/test1` directory, then run gcovr with the correct paths. You could use relative paths, but here absolute paths seem easier to read:
> 
> ```shell
> cd /opt/examples/src/test/test1
> gcovr -r /docker/opt/examples/src /docker/opt/examples/build
> ```
> 
> And again: do not use glob patterns like `*` in your arguments to gcovr. That does not do what you think it does. Here, it only works accidentally because all of your directories only contain a single entry.

I must run gcovr in build process path，otherwise coverage will empty ?  If i don't know the build path, how can i get the coverage

**Comment by Cherish-Gww** [comment]
@lifreshman I think you show read gcovr user guide: parameter -f is tell gcovr where to find your source code.

**Comment by latk** [comment]
> I must run gcovr in build process path，otherwise coverage will empty ? If i don't know the build path, how can i get the coverage

What the correct path is depends on the build system you are using. For example, if you're writing Makefiles by yourself then the compiler is usually executed from the same directory where the Makefile is. Gcovr is closely related to the compiler and should use the same path.

Gcovr does not know about your build system and can only guess. Invoking gcovr from the correct directory helps gcovr guess correctly.

@Cherish-Gww The `-f` (filter) and `-e` (exclude) options are slightly different: they don't help gcovr *find* the source files. They just tell gcovr to include/exclude coverage for matching files in the output. E.g. coverage on autogenerated files or vendored libraries is uninteresting. By default, if no `-f` option is given, the output is restricted to the `-r` project root.

**Comment by Thallamsaisowmya23** [comment]
(ERROR) Error occurred while reading reports:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\__main__.py", line 389, in main
    covdata: CovData = gcovr_formats.read_reports(options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\__init__.py", line 68, in read_reports
    covdata = GcovHandler(options).read_report()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\__init__.py", line 202, in read_report
    return read_report(self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\read.py", line 79, in read_report
    with Workers(
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\workers.py", line 173, in __exit__
    self.wait()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\workers.py", line 164, in wait
    raise self.exceptions[0][1]
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\read.py", line 86, in read_report
    contexts = pool.wait()
               ^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\workers.py", line 164, in wait
    raise self.exceptions[0][1]
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\workers.py", line 80, in worker
    work(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\read.py", line 450, in process_datafile
    raise RuntimeError(errors_output)
RuntimeError: GCOV produced the following errors processing F:\add\add.gcda:
        Trouble processing 'F:/add/add.gcda' with working directory 'F:\\add'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        Trouble processing 'F:/add/add.gcda' with working directory 'F:/add'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        Trouble processing 'F:/add/add.gcda' with working directory 'F:/'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        (gcovr could not infer a working directory that resolved it.)
To ignore this error use option --gcov-ignore-errors=no_working_dir_found.

GCOV produced the following errors processing F:\add\add.gcda:
        Trouble processing 'F:/add/add.gcda' with working directory 'F:\\add'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        Trouble processing 'F:/add/add.gcda' with working directory 'F:/add'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        Trouble processing 'F:/add/add.gcda' with working directory 'F:/'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        (gcovr could not infer a working directory that resolved it.)
To ignore this error use option --gcov-ignore-errors=no_working_dir_found.
