### ISSUE TITLE
--json ignores output file and prints to stdout

### ISSUE THREAD

**Issue by readmodifywrite** [gcovr/gcovr#357]
gcovr 4.2

The --json option doesn't write to a given output file (per the docs).  It will either ignore it and print results to stdout, or in some cases come up with an unknown directory error.

gcovr -s -j --json stuff.json

**Comment by latk** [comment]
Thank you for reporting this. This is a known bug that was fixed in #351 and will be part of the next release (as soon as I get around to it :sweat_smile:). As a workaround, you can name the output file with the -o/--output option.

**Comment by readmodifywrite** [comment]
Ah, missed that, my bad.  Thanks!
