### ISSUE TITLE
Possible to speed up gcovr on big projects?

### ISSUE THREAD

**Issue by holycacao** [gcovr/gcovr#36]
hi,

i've written a tool, which uses gcovr to generate coverage reports for a big project. i am selectively instrumenting files based on a diff file users pass in (ie if the user changed file1, file2, file3, then touch these files and do a make with gcov flags enabled). in some cases, especially when a user touches a commonly included header file, hundreds of gcno files are created (i presume wherever these header files are included and possibly recursively?). in these cases, gcovr takes up to 3 hours to complete its analysis. i'm curious if there's a safe (maintains coverage accuracy) way for me to speed things up?

**Comment by mrx23dot** [comment]
GCOV.exe could be easily called parallel, based on number of CPU cores.

**Comment by itavero** [comment]
@tsondergaard Did you ever manage to figure out why the numbers for the conditionals are being messed up?
We tried the same approach and our testing time went from over 9 minutes to approximately 3 minutes, which is a big difference if you ask me.
Unfortunately Gcovr now says our conditional coverage is just about half of what it used to be, even though the system under test and the tests have not been changed.

**Comment by tsondergaard** [comment]
@itavero Unfortunately not.

**Comment by itavero** [comment]
I checked and, in our case, the report claims to have *exactly* twice as much branches as they actual have (what the previous reports show).
However the number of branches reached is not doubled.

What we are doing is running all the different tests for our entire code base and then we run `gcov`, similar to what was mentioned before.
After that `gcovr` is ran, again, similar to what was mentioned before.

If anyone has an idea about what might be causing this, I'd love to hear it.
