### ISSUE TITLE
Vote: giving everyone* write access

### ISSUE THREAD

**Issue by latk** [gcovr/gcovr#391]
For the last two years of gcovr development there have been many great contributions from the community, but I haven't always managed to stay atop of things and keep things flowing smoothly. I am therefore looking for ways to become less of a bottleneck, in particular by giving out write access more actively.

Proposal:
* Starting 2020-06-15, I will begin inviting previous contributors to the @gcovr organization, which will give them **write access** to the gcovr/gcovr repository.
* Instead of a heavyweight process, I'll act at my discretion to decide whether giving someone write access is appropriate. E.g. I expect that nearly all pull requests indicate that the contributor would use write access for good.
* This policy will primarily trigger on future contributions, but I also expect to look at some existing contributors.

Per the voting procedure suggested in #176, all **existing members** (@gcovr/developers, @gcovr/owners) are asked to **cast a vote** on this proprosal by writing a comment. Voting closes after one week, at 2020-06-15 12:00 UTC.

Details / Background / Safeguards:

* People with write access (“developers”) can manage issues, review pull requests, merge them, and cut releases.

* The master branch is a protected branch, meaning that developers cannot push to it directly. Pull requests can only be merged if a different developer approves the PR. This serves as a safeguard to prevent abuse of write access.

* The gcovr project has yet to adopt a formal Code of Conduct. In the meanwhile:
  * Everyone (whether developer or other) is expected to act respectfully.
  * Developers act on behalf of the project and must hold themselves to a higher standard.
  * Trolling and rule-lawyering is not welcome in this context.
  * I pledge to investigate and sanction unacceptable behaviour with due care, and can be reached at opensource at lukasatkinson.de (please mention `[CoC]` in the subject).
  * This is not subject to the vote because I take this for granted.

* There previously was a [process](https://gcovr.com/en/4.2/contributing.html#become-a-gcovr-developer) to get developer access, but it was never invoked. If this proposal is accepted, the old process will be retired.

**Comment by Spacetown** [comment]
I agree with this. What I'm missing is how new releases are planned.

**Comment by jsiirola** [comment]
+1

I agree with @Spacetown that there should be a written release process (mostly to document who can initialize the process and who has actual rights / authority to “push” the release), but I am not entirely sure that that needs to be handled here.

**Comment by latk** [comment]
The vote passed unanimously on Jun 15.

To get started, I sent out invitations to @CezaryGapinski, @chrta, @mayeut, @opikalo, @Spacetown. Please see this issue for background. I'll be available for questions/discussions, but progress must not hinge on my availability.

Release process is roughly:

1. update the changelog (takes a lot of effort)
1. prepare a release on the GitHub releases tab with a summary of the changelog (but don't publish it yet)
1. bump the version number (use `admin/release_checklist` to detect common problems)
1. publish the release, which will create a tag and push a new package to PyPI via Travis CI

Unfortunately, the last release was so long ago that I'm not confident the process will work smoothly.
