### ISSUE TITLE
how to generate gcda files from shared libraries

### ISSUE THREAD

**Issue by dnpawate** [gcovr/gcovr#403]
I have generated .gcno files, however not sure on how to generate .gcda files

I have pushed the .so file into device & running a usecase, expecting .gcda files to 
generate however it doesn;'t generate. Not sure what step i'm missing here.

can anyone provide details on how to generate .gcda file from shared lib.

**Comment by Spacetown** [comment]
Hi, I think thts more a issue of the instrumentation/gcov and not gcovr.

You've pushed the files to the device so I guess youe are cross compiling and running using .so in a different file system. Please try the environment variables mentioned in https://gcc.gnu.org/onlinedocs/gcc/Cross-profiling.html to get the correct paths in your target system..

**Comment by deepaknpawate** [comment]
Thank you for suggestion.

GCOV_PREFIX=/sdcard
GCOV_PREFIX_STRIP=10

Do we need to add this flag on HOST before compiling the module ?
after compilation does the .so will include the above absolute path to cross check ? 

Reason: I have compiled with above flags and transferred .so lib to device & ran the usecase
.gcda files were not generated, Please help on this.

**Comment by deepaknpawate** [comment]
default in .so I can see path prefix with /proc/self/cwd/
GCOV_PREFIX := /data/local/tmp/gcov
GCOV_PREFIX_STRIP := 10

I added this path in Android.mk but still after compilation
I can see .gcda path in .so is /proc/self/cwd/host_so_path/gcda_file

**Comment by Spacetown** [comment]
> default in .so I can see path prefix with /proc/self/cwd/
> GCOV_PREFIX := /data/local/tmp/gcov
> GCOV_PREFIX_STRIP := 10
> 
> I added this path in Android.mk but still after compilation
> I can see .gcda path in .so is /proc/self/cwd/host_so_path/gcda_file

According to the mentioned link above:
If you compile your objects into `/proc/self/cwd/host_so_path` you've to set the variables `GCOV_PREFIX_STRIP=4` in your target system befor running your executable to strip of the whole host directory component.

**Comment by Spacetown** [comment]
@dnpawate @deepaknpawate Can this be closed?
