### ISSUE TITLE
[debian] Help wanted, what is gcov option for dpkg-buildpackage --buildinfo-option=? when do debian compile?

### ISSUE THREAD

**Issue by tim-rj** [gcovr/gcovr#406]
Hi gcov team, we want to enable gcov in debian environment, can you help share the option for it, i have tried below option, all failed:
```
--buildinfo-option=--enable-gcov
```
```
--buildinfo-option=--enable-coverage
```

**Comment by Spacetown** [comment]
Hi,
you're asking the wrong team. This here is the issue tracker for gcovr, a tool to create reports from the gcov data.

**Comment by tim-rj** [comment]
can you share the gcov project link? i want to create this issue to them.

**Comment by jenswet** [comment]
@tim-rj see https://gcc.gnu.org/onlinedocs/gcc/Gcov.html

It's part of https://gcc.gnu.org/ I think there is only a mailing list you can ask. But probably you will als find help in the archives of the mailing list or on stackoverflow.
