### ISSUE TITLE
Why does gcovr not generate coverage for overrides

### ISSUE THREAD

**Issue by tlw85** [gcovr/gcovr#412]
I have a class that implements an interface eg

Interface 

virtual bool someFunction() =0;

class

bool someFunction () override;

I have written a test for 

bool someFunction () override;

But it seems gcovr does not see the call into the class method and does not generate the coverage for it.
If I commented out the virtual method and remove override it works. 

Is this an issue with gcovr or gcov  ?

**Comment by latk** [comment]
This is odd. Could you show a small runnable example that could be used to verify the issue? Which compiler version are you using.

The most likely explanations are that either gcovr is getting confused by your project layout, or the compiler generates code in unexpected ways (gcov works on the level of machine code).

**Comment by tlw85** [comment]
Hi thanks for reply, if gcov and gcov is expected to cover this I will investigate some more before I post, it could be like you say my project layout as it does include shared libraries so a crossover between the classes could cause this.

**Comment by tlw85** [comment]
it was my project layout all sorted now thanks
