### ISSUE TITLE
Discussion: use gcovr with other coverage tools than gcov

### ISSUE THREAD

**Issue by Jugst3r** [gcovr/gcovr#414]
Hello,
I am looking for a way to reuse some parts of gcovr, mainly the HTML rendering; and use it as a renderer of coverage result not obtained with gcov and not for C code. I have some questions:

* How easily (if you have the slightest idea) could it be adapted to other trace files format for other languages?
* How easily could the coverage data structure be extended to support some additional features (MCDC coverage info).
* How easily could the HTML rendering part could be improved to output additional information (MCDC coverage).

Thanks in advance if you take the time to answer to these very vague questions (and if you have any idea of a tool more adapted to this use case, do not hesitate)

**Comment by latk** [comment]
Hi! Gcovr does not have a modular design that would be directly suitable for reuse (no API stability guarantees), though you may be able to extract some useful components. The HTML report generator could certainly be modified to show additional data, but it's not very pretty code.

You can render coverage data from other data sources by providing them in gcovr's JSON format (--add-tracefile) or in the .gcov format (--use-gcov-files), but this is limited by gcovr's internal data model. For example, gcovr has a concept of decisions/branches, but no concept of conditions (atomic boolean expressions) or functions. Thus, the data model would have to be extended to support the MCDC coverage criterion.

Gcovr itself is almost completely language-agnostic and just treats programs as plaintext, but the collection of coverage data with gcov only works with programs compiled with the GCC compiler suite (or clang/LLVM). C/C++ are just the most common use cases.

**Comment by Jugst3r** [comment]
Thank you for the clear and detailed answer !

**Comment by latk** [comment]
I'm closing the issue for now. But if you need to integrate a specific source of coverage data, do open another issue. E.g. one thing I've been pondering is how hard it would be to import data from lcov, which is less buggy than gcovr in some respects.

**Comment by Spacetown** [comment]
@mrx23dot I don't get your question.

**Comment by Jugst3r** [comment]
@mrx23dot I used GNATcoverage (I work on the tool development)
