### ISSUE TITLE
Change JSON_FORMAT_VERSION to String 

### ISSUE THREAD

**Issue by Jugst3r** [gcovr/gcovr#417]
Having a float as a version number may not be a good idea, what do you think about changing it to a string? (it is a quick fix)

**Comment by latk** [comment]
Yes, that sounds very sensible. Dotted version numbers aren't floats.

PR welcome :)

**Comment by Jugst3r** [comment]
Will do. Could i ask you the option to give to the test_driver (when `make test`) to update tests accordingly?
