### ISSUE TITLE
Prepare gcovr 5.0 release

### ISSUE THREAD

**Issue by latk** [gcovr/gcovr#424]
Towards the next gcovr release, the following steps have to be done:

* [x] ensure all relevant changes (fixed issues, merged PRs) are noted in the changelog
* [x] check that the docs are roughly up to date, organize the changelog
* [x] prepare a draft GitHub release (same content as changelog, but rephrased/reformatted in a way that makes sense as an email)
* [x] temporary feature freeze, last update to the docs
* [x] bump the version number, including in documentation and screenshots
* [x] publish the GH release, which will create a tag and trigger the deployment workflow, uploading a wheel to PyPI

Updating the changelog is gargantuan task, fortunately it can be done in steps and parallelized across people with **write access**. To this end, I've created a new 4.3 milestone.

**If you assign a completed issue/PR to the 4.3 milestone**, this indicates either
* that the issue is already mentioned in the changelog,
* or a commitment that you will submit a PR that adds the issue to the changelog,
* or that the issue will be part of the release but is too minor to be mentioned in the changelog.

To limit merge conflicts, do not reorganize the changelog, but add new entries as a single block (can be organized into sections later). 

It could make sense to also create milestones for past releases, so that it's easier to find issues that have yet to be looked at. Issues tagged Question or wontfix can likely be skipped.

This issue can be used for further release planning. General process discussion should be done at #400, where the idea to use the “milestone” feature was suggested.

**Comment by Spacetown** [comment]
Have all PRs listed in the changelog?
E.g. #407 is only a fix of #328 which is mentioned in the changelog. I prefer not to add it to the changelog.

**Comment by latk** [comment]
The changelog is for humans, so it makes sense to only mention changes that are of interest to anyone who doesn't want to trawl through the commit history – so primarily for end users, but to some degree also for other gcovr developers.

So I wouldn't mention #407. Docs changes can be mentioned if there's new material that someone would be interested to read or re-read. #405 is a bit too minor I think. At most something like “clarified how filters work in the --help message”.

**Comment by Spacetown** [comment]
But we link e.g. #407 and #405 to see that that the are already checked, ok?

We can also add a milestone for the next UpcomingRelease where we can do this work as part of the PR review.

**Comment by latk** [comment]
Linking the issues/PRs sounds sensible, I've updated the top comment. (Later, the experience from this thread can be condensed as docs on the release process).

Right now I'm concerned with catching up on “organizational debt” regarding the changelog/release process. Looking forward, you're completely right that more of this should be shifted into PR review, so that future releases are simpler.

Btw, do you have any idea how we could add a GH action that ensures that all PRs either update the changelog or have a magic string like `[no changelog]`?

**Comment by Spacetown** [comment]
> Linking the issues/PRs sounds sensible, I've updated the top comment. (Later, the experience from this thread can be condensed as docs on the release process).
:+1:

> Right now I'm concerned with catching up on “organizational debt” regarding the changelog/release process. Looking forward, you're completely right that more of this should be shifted into PR review, so that future releases are simpler. Do create any milestones you consider to be sensible.
I'll create a milestone UpcomingRelease

> Btw, do you have any idea how we could add a GH action that ensures that all PRs either update the changelog or have a magic string like `[no changelog]`?
What about checking the log back to master for the magic string, if it isn't found the issue must be part of the changelog. Maybe we cann add it to the `release_checklist`.

**Comment by chrta** [comment]
Since a lot of stuff changed since 4.2 (regarding supported python version etc), would it make sense to create a 5.0 instead of a 4.3?

**Comment by Spacetown** [comment]
I took a look at the last version and from the number of commits it was almost the same. There were many changes in the HTML report and new output formats, but no incompatible changes.
However, since Python 2 is no longer supported we could make a new major version.

**Comment by chrta** [comment]
> However, since Python 2 is no longer supported we could make a new major version.

I also think that this is the major point here. I am ok with 4.3 or 5.0, but i wanted to raise this so it is a deliberate decision.

**Comment by latk** [comment]
I am in favour of a soft semver, where incrementing the major version number indicates major breaking changes. In general, dropping support of a Python version cannot be a major braking change, because it happens to frequently.

But I had forgotten that we've dropped support for Python 2.7. That is a pretty substantial change that will definitely break stuff for some of our users, so I'd be fine with going to 5.0 next.

**Comment by Spacetown** [comment]
I've added #475 to the milestone because of the missing meter style in Crome. I'll create a PR for this.
Shall #474 be removed from the milestone?

**Comment by latk** [comment]
@Spacetown If you think the release is ready let's just do it, no waiting for additional *features*. However, we might want to include available *bugfixes*. In particular, getting the fix in #480 merged would be good. I wanted to test it when I stumbled over the broken Docker tests.

I see the suggestion to create bundled executables as a packaging issue that will not affect users who install via pip or other downstream packagers like Debian. So this doesn't have to be tied to a particular version or release.

This reminds me that I should change the milestone name and name of this issue to "5.0" as per the above discussion.

**Comment by Spacetown** [comment]
I'm on vacation and can bump the prepared version in two weeks. @latk as mentioned above, I'll change everything to 5.0.

**Comment by Spacetown** [comment]
I've changed the version and updated the files and the screenshots. I'll try to do the release on Friday.

**Comment by Spacetown** [comment]
@latk Please can you check the coverage report? On master there is now also the upload error, I've no glue.

Can someone check the documents and the draft release?

**Comment by chrta** [comment]
Regarding the draft release:

> Dropped support for Python 2 and Python 3.5.
> From now on, gcovr will only support Python versions
> that enjoy upstream support.

Maybe explicitly mention the releases that are supported here.

> Add --html-theme to change the color theme. (#381)

I think this should link to the pr #393 instead.

> Add support for clang-10 to docker tests. (#484)

This pr is not merged and should be removed from the changelog and the milestone.

Otherwise the page looks good to me. The screenshots i the docs also seem to be fine.

**Comment by Spacetown** [comment]
@chrta The python versions are mentioned in the [installation section](https://gcovr.com/en/master/installation.html). The change of the issue ID in the changelog was accidentialy pushd directly on master because the tracking branch was wrong. Sorry for that.

**Comment by latk** [comment]
> @latk Please can you check the coverage report? On master there is now also the upload error, I've no glue.

Regarding the missing coverage, it seems that codecov tool is somehow running into problems? When uploading from Github Actions an auth token SHOULD NOT be necessary. I would have suggested replacing the codecov tool with the codecov Github Action, but it seems we ran into some problems with this earlier this year (https://github.com/gcovr/gcovr/pull/455#issuecomment-763884971). Not sure if they're still relevant though.

<details><summary>Excerpt of logs from our Actions run:</summary>

```none
codecov --flags ubuntu-18.04 -X gcov search
  shell: /bin/bash -e {0}
  env:
    USE_COVERAGE: true
    CC: gcc-6
    CXX: g++-6
    PYTHON: python
    pythonLocation: /opt/hostedtoolcache/Python/3.8.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.10/x64/lib

      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.1.11

==> Detecting CI provider
    GitHub Actions CI Detected
==> Preparing upload
XX> Skip processing gcov
==> Collecting reports
XX> Searching for reports disabled
    Generating coverage xml reports for Python
    + /home/runner/work/gcovr/gcovr/coverage.xml bytes=114467
==> Uploading
    .url https://codecov.io
    .query commit=0fa879a7f1ff40548dee36ec761fcbacaef76e0a&branch=master&build_url=http%3A%2F%2Fgithub.com%2Fgcovr%2Fgcovr%2Factions%2Fruns%2F919645256&service=github-actions&build=919645256&slug=gcovr%2Fgcovr&flags=ubuntu-18.04&package=py2.1.11
    Gzipping contents..
    Compressed contents to 13836 bytes
    Pinging Codecov...
    Retrying 1/5 in 2s..
    Retrying 2/5 in 2s..
    Retrying 3/5 in 2s..
    Retrying 4/5 in 2s..
    Retrying 5/5 in 2s..
    Direct to s3 failed. Using backup v2 endpoint.
    Uploading to Codecov...
    Retrying 1/5 in 2s..
    Retrying 2/5 in 2s..
    Retrying 3/5 in 2s..
    Retrying 4/5 in 2s..
    Retrying 5/5 in 2s..
    {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
Error: 404 Client Error: Not Found for url: https://codecov.io/upload/v2?commit=0fa879a7f1ff40548dee36ec761fcbacaef76e0a&branch=master&build_url=http%3A%2F%2Fgithub.com%2Fgcovr%2Fgcovr%2Factions%2Fruns%2F919645256&service=github-actions&build=919645256&slug=gcovr%2Fgcovr&flags=ubuntu-18.04&package=py2.1.11
Tip: See all example repositories: https://github.com/codecov?query=example
```

Source: https://github.com/gcovr/gcovr/runs/2777961083

</details>

Confusingly, codecov does seem to generate comments.  And more recent builds seem to work normally: https://github.com/gcovr/gcovr/runs/2786812731
Not sure if adding the CODECOV_TOKEN had anything to do with it, since the workflow YAML file doesn't actually reference this secret.

**My suggestion: do nothing.** Seems to have fixed itself, or at least doesn't seem to have real impact.

FYI we were not affected by the Codecov security incident that was disclosed in April because we don't make any secrets available to the test workflow.

**Comment by latk** [comment]
Regarding the release itself, it seems that all the things are now in place and all that's missing is creating the tag. And if we forgot something, we can always push out a 5.0.1 release later.

Thank you @Spacetown for making this possible. I'm looking forward to Friday!

**Comment by Spacetown** [comment]
> Not sure if adding the CODECOV_TOKEN had anything to do with it, since the workflow YAML file doesn't actually reference this secret.

The token was already configured. For me it seems that code ob had a problem because today it's working again.

If the deploy workflow isn't working is it possible to remove the tag and rerelease or do we have to create a 5.0.1?

**Comment by latk** [comment]
> If the deploy workflow isn't working is it possible to remove the tag and rerelease or do we have to create a 5.0.1?

Removing a release is not a good idea, even if it were possible. If the workflow fails, we will find a way to run it again. And as a fallback, I can always upload to PyPI manually. I really want to have it automated though so that *future* releases can be made more rapidly :)

Ultimately, releases, tags, and workflows are just means to an end, and the end is to upload something installable to PyPI.

I've looked at the deploy.yml workflow though and think we need to fix some things.

* Python version is hardcoded to 3.5 which we no longer support, should use something more recent like 3.8 (the maximum which we run normal tests under)
* GCC version is referenced as `matrix.gcc` variable, yet no matrix exists.
* we probably need to install the `wheel` PyPI package so that `bdist_wheel` command is available. Should we add it to `requirements.txt`?

Related observations:

* classifiers in setup.cfg reference outdated Python versions.
* in setup.py we require pygments without any version constraints, in requirements.txt we pin version 2.7.4. What was the background of that pinning? Is it only related to our tests, or also to API changes?

**Comment by Spacetown** [comment]
> Removing a release is not a good idea, even if it were possible. If the workflow fails, we will find a way to run it again. And as a fallback, I can always upload to PyPI manually. I really want to have it automated though so that _future_ releases can be made more rapidly :)

Ok.

> I've looked at the deploy.yml workflow though and think we need to fix some things.
> 
> * Python version is hardcoded to 3.5 which we no longer support, should use something more recent like 3.8 (the maximum which we run normal tests under)
> * GCC version is referenced as `matrix.gcc` variable, yet no matrix exists.
> * we probably need to install the `wheel` PyPI package so that `bdist_wheel` command is available. Should we add it to `requirements.txt`?

Will update this today. I'll try to run the deploy workflow on all branches and split the step `Build and publish` . The `publish` will only be called if the trigger was a new tag.

> * classifiers in setup.cfg reference outdated Python versions.

OK.

> * in setup.py we require pygments without any version constraints, in requirements.txt we pin version 2.7.4. What was the background of that pinning? Is it only related to our tests, or also to API changes?

Our tests failed because of a changed CSS in a new pygments version, see https://github.com/gcovr/gcovr/pull/413.

**Comment by chrta** [comment]
> @chrta The python versions are mentioned in the [installation section](https://gcovr.com/en/master/installation.html). The change of the issue ID in the changelog was accidentialy pushd directly on master because the tracking branch was wrong. Sorry for that.

OK, i missed that. This is fine for me. No need to apologize for anything. Thank you that you are doing all the work for the release. :+1:

**Comment by Spacetown** [comment]
@latk GitHub doesn't annotate the tags and the release check failed. Should I force push the tag?

**Comment by latk** [comment]
> @latk GitHub doesn't annotate the tags and the release check failed. Should I force push the tag?

We either need to force-push or update the release-checklist script. Maybe the latter could be more useful? I liked annotated tags since they're git objects with a clear date, not just aliases for a commit. But if we want to continue to use them, it seems the annotated tag would have to be created within the CI.

> Also the upload isn't executed. The state is success because of the uploaded dist files as artifacts but it seems that the `event_name` isn't `release`. Can you upload the dist from the artifacts by hand?

I'm on it. PyPI rejected the upload due to RST problems in the readme. Turns out ``:option:`--foo` `` is a Sphinx role, not part of standard RST :roll_eyes: 
I will edit this by hand, rebuild the wheel, and re-attempt the upload.

**Comment by latk** [comment]
Upload is live at <https://pypi.org/project/gcovr/5.0/>!

I also had to edit the image paths in the README.rst so that the screenshots are rendered on PyPI. I selected permalinks of the form `https://raw.githubusercontent.com/gcovr/gcovr/5.0/doc/images/screenshot-html.png`.

**Comment by Spacetown** [comment]
> We either need to force-push or update the release-checklist script. Maybe the latter could be more useful? I liked annotated tags since they're git objects with a clear date, not just aliases for a commit. But if we want to continue to use them, it seems the annotated tag would have to be created within the CI.

This is a chicken egg problem because the publish of the release creates the tag which will trigger the workflow. But from documentation point it should be possible to create the tag and then publish the release for this existing tag.

I'll chekc the event name in the deploy pipeline with my fork.

Regarding the pictures, how should we do this? Change the links and add this to the release checklist? Will you create a PR for the changes done in the documentation?

**Comment by latk** [comment]
> This is a chicken egg problem because the publish of the release creates the tag which will trigger the workflow.

Maybe it makes more sense to trigger the release workflow manually (`workflow_dispatch` event)?

> Regarding the pictures, how should we do this? Change the links and add this to the release checklist? Will you create a PR for the changes done in the documentation?

Using relative paths as we do currently is correct for the README on GH to reflect the current state, and for deployment to ReadTheDocs. Similarly, using the `:option:` role is correct for the rendered docs. Since all of this is good I'd rather not commit my PyPI-related edits.

I'm not quite sure how to handle this for the releases. I'd rather not have more stuff that needs to be updated manually and checked. I think it might be feasible to apply a couple of regexes to the files in order to translate between RST dialects, this can be done when creating package metadata in the setup.py. My changes were more or less:

* ``:option:`(.*?)<gcovr.*?>` `` → ``` ``\1`` ```
* ``^\.\. image:: ./`` → ``.. image:: https://raw.githubusercontent.com/gcovr/gcovr/TAGNAME/``

Correct rendering can be checked by running `rst2html.py` from `doctools`, though I only noticed the wrong paths for the screenshots upon visual inspection of the resulting page.

> Will you create a PR

I find the idea of creating a PR very exhausting and don't want to promise anything. But now that the release is done I might find more motivation again :)

**Comment by Spacetown** [comment]
@latk I can do the changes together with the fix of the deploy workflow.
