### ISSUE TITLE
How to generate checksum for coveralls

### ISSUE THREAD

**Issue by Spacetown** [gcovr/gcovr#428]
In #423 I had differences in the checksum of the file (key `source_digest`). I guess that's because of the line endings on windows. In the [documentation](https://docs.coveralls.io/api-introduction) the handling of line endings isn't specified but I think we shall normalize the linebreaks for getting the checksum.

**Comment by dbywalec** [comment]
You can normalize the line endings of this file to Unix style and then force checkout as-is of this particular file in `.gitattributes`

**Comment by Spacetown** [comment]
I've done this for our tests. But what about if a project is tested on different OSes with native line endings and uploading data to the same Coverall server?

**Comment by Spacetown** [comment]
I'll add a hint to the documentation.
