### ISSUE TITLE
Generate external CSS file

### ISSUE THREAD

**Issue by oesteban-vx** [gcovr/gcovr#432]
Not really an issue, but a possible Enhancement. I'd appreciate the possibility of getting a .css file, and have the .html files use it. Besides solving my problem, that would make .html files a bit smaller.

### The context
I was used to Sonarqube to get coverage reports, but for different reasons it's not available now.
As a workaround, I am running (in a Jenkins job) gcovr to get a html report, zip it and keep it in the build (as an artifact). I have to download and uncompress it to see it in my browser.

The next step is, why not keep the whole report directory as an artifact, so I don't have to download it and instead see it directly?

It kind of works, but Jenkins (at least, for me) delivers artifacts with `Content-Security-Policy | sandbox; default-src 'none'; img-src 'self'; style-src 'self';`. This forbids the internal CSS rules

```html
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <title>Head</title>
  <style media="screen" type="text/css">
    body
    {
      color: #000000;
      background-color: #FFFFFF;
    }
    ...
```
So we get this kind of reports:

![imagen](https://user-images.githubusercontent.com/60652318/95565647-ca0ccd80-0a20-11eb-822b-af7cd8b26083.png)

Note that we can't tell if a line is covered or not (besides the branch ticks in conditions). The summary provides information, but hard to read:

![imagen](https://user-images.githubusercontent.com/60652318/95564514-38509080-0a1f-11eb-92dd-4d1518b906e5.png)

This might be related to https://github.com/gcovr/gcovr/issues/25; It looks to me it's about being able to choose a style, not using an external style sheet, though.

#### Releases:
gcovr: 4.2-py2.py3
jinja2: 2.0.3

**Comment by Spacetown** [comment]
Hi,
in the upcoming release there is already an option to control the css (#348). You are using detailedreports, than the css will be extern as default. 
With #380 you can also use a own css.
