### ISSUE TITLE
use with LLVM .cov files?

### ISSUE THREAD

**Issue by ExpandingMan** [gcovr/gcovr#433]
Hello all, I feel like I'm probably doing something incredibly stupid here, but for the life of me I can't figure out how to get it to generate output from LLVM generated `*.cov` files.  I'm doing, for example
```
gcovr --gcov-executable llvm-cov .
```
I've tried this with and without the `-g` option, but in all cases it just picks up zero of my `*.cov` files.

Is this even supported?  I apologize if this turns out to be a really dumb question, but help appreciated.

**Comment by latk** [comment]
I haven't used LLVM-based coverage, but it should work like this:

* compile your software with the `--coverage` flag (`-g` and `-O0` are also recommended)
* the compiler should have created .gcno files next to the object files
* run your software
* this should create .gcda files next to the object files
* run gcovr with `--gcov-executable "llvm-cov gcov"`. The gcov subcommand is important to put llvm-cov into its compatibility mode.

Could you confirm if this works?

Gcovr intends to support LLVM-based coverage, but it's not yet part of a test suite so regressions are possible.

**Comment by ExpandingMan** [comment]
Ok, this whole thing has been incredibly confusing.

So, I'm trying to generate an XML for Julia (an LLVM language).  Julia outputs annotated source code as `*.cov` files, and there doesn't seem to be any intermediate format.  As far as I can tell, this mostly just seems to work with `lcov`.

I'm still totally confused about whether something like `gcovr` should work, however, for the time being, I am generating output with `lcov` and then using the Python module `lcov_cobertura` to generate an XML (which I think, but still am not 100% sure, is in the right format).

Maybe this is a use case that `gcovr` should or already supports? :shrug:  But really, I don't know, maybe it's just a completely different format and I was barking up the wrong tree here.

Anyway, I'm sure everyone else here is in a far better position than I am to judge whether this is something that `gcovr` theoretically supports.  Please feel free to close this issue if you feel it's just not a valid use case.  Thanks.

**Comment by latk** [comment]
Sorry for the confusion, I thought you were using Clang and not Julia.

Gcovr currently supports the following input formats:

* existing .gcov files, which is buggy when things like C's `#include` directive are used
* .gcda and .gcno files generated by GCC or Clang/LLVM, which needs gcov (or llvm-cov gcov) for conversion
* .json files that have been generated by gcovr's --json option

There is currently no support for Julia .cov files. If they happen to have a .gcov-compatible syntax, then renaming the file ending should allow gcovr to pick them up. However, I can't find any documentation on Julia's coverage file format.

I would be open to further input formats (e.g. native LLVM, lcov .info files, or also language-specific formats like Julia .cov), but I'm not interested in doing that work myself. In the meanwhile, continuing to use lcov is probably your best bet.

**Comment by ExpandingMan** [comment]
I *think* that Julia's annotated source files must be some sort of standard LLVM thing because of the fact that LCOV seems to understand them, but yeah, I'm still not sure what's going on.  Anyway, sounds like this isn't really a use case you intended to cover, so I'll close this issue.
