### ISSUE TITLE
Cannot pass gcov and genhtml options

### ISSUE THREAD

**Issue by zhangysh1995** [gcovr/gcovr#434]
I have the following example options:

````
$ lcov --directory . -c -o mysql.info --no-external
$ genhtml -o . mysql.info --ignore-errors source
````

I found I cannot use the same options in gcovr:

````
coverage@2d302c0ea87a:~/mysql/bld$ ~/.local/bin/gcovr -r .. --html -o coverage.html --no-external --ignore-errors source
usage: gcovr [options] [search_paths...]
gcovr: error: unrecognized arguments: --no-external --ignore-errors
````

How could I have the same options for gcovr?

**Comment by latk** [comment]
Gcovr is not intended to be directly compatible with lcov, but it does have some similar options.

Lcov uses `--directory PATH` and `--no-external` to decide whether coverage for a file should be included. Instead, gcovr uses its filter system. The `-r`/`--root` argument serves as a default filter, so `lcov --directory . --no-external` should be *roughly* equivalent to `gcovr -r .` which already is the default. (Actually, gcovr's --root is more like lcov's --base-directory).

Gcovr does not have `--ignore-errors source`. However, during the coverage collection phase, gcovr can ignore unknown coverage data syntax with `--gcov-ignore-parse-errors`. The `--html` output format doesn't access source files so lcov's `source` error class wouldn't apply here, but it would be an issue for `--html-details`. The only option with gcovr would be to exclude coverage for files that cannot be opened.
