### ISSUE TITLE
If Gcovr is run multiple times on the same program, are the branches statically enumerated?

### ISSUE THREAD

**Issue by hammadar** [gcovr/gcovr#436]
My team is using Gcovr to track unique coverage within programs that we are testing. My question is, when new coverage files are generated each time, are the branches enumerated in the same order as before? Thanks.

**Comment by Spacetown** [comment]
The branches are enumerated in the order of GCOV. GCOV enumerates the branches always in the same order from the top of compile unit to the end.

**Comment by hammadar** [comment]
Awesome, thank you!

**Comment by latk** [comment]
To add a remark, the order of branches is ultimately determined by GCC (branches correspond directly to the generated machine code). So the branch numbering is *guaranteed* to remain stable until you recompile. Even then, GCC's branch ordering is very predictable and will likely stay stable but you shouldn't rely on this.
