### ISSUE TITLE
--exclude not working

### ISSUE THREAD

**Issue by freesurfer-rge** [gcovr/gcovr#440]
I'm having trouble getting some `--exclude` filters to work in my code coverage build, and I'm wondering what I'm doing wrong. I would like to exclude an `apps/` directory and anything inside a `lib.+/test/` directory from the results. To this end, I have a command line (in an Ubuntu VM on AzureDevOps):

```bash
gcovr --root /home/vsts/work/1/s . --xml cobetura.xml --html-details html/details.html --print-summary --exclude 'apps/' --exclude 'lib.+/test/' --verbose
```
This is run from the same directory as `cmake` was run.

In the verbose log, I see things like:
```
Filters for --exclude: (2)
- RelativeFilter(apps/ root=/home/vsts/work/_temp/bld)
- RelativeFilter(lib.+/test/ root=/home/vsts/work/_temp/bld)
```
which means that my filters have been loaded. However, I subsequently see messages such as:
```
Processing file: /home/vsts/work/_temp/bld/apps/servocalibration/CMakeFiles/ServoCalibration.dir/runonconsole.cpp.gcno
Running gcov: 'gcov /home/vsts/work/_temp/bld/apps/servocalibration/CMakeFiles/ServoCalibration.dir/runonconsole.cpp.gcno --branch-counts --branch-probabilities --preserve-paths --object-directory /home/vsts/work/_temp/bld/apps/servocalibration/CMakeFiles/ServoCalibration.dir' in '/tmp/tmp61x2c44r'
Finding source file corresponding to a gcov data file
  currdir      /home/vsts/work/_temp/bld
  gcov_fname   /tmp/tmp61x2c44r/#home#vsts#work#1#s#apps#servocalibration#runonconsole.cpp.gcov
               ['        -', '    0', 'Source', '/home/vsts/work/1/s/apps/servocalibration/runonconsole.cpp\n']
  source_fname /home/vsts/work/_temp/bld/apps/servocalibration/CMakeFiles/ServoCalibration.dir/runonconsole.cpp.gcno
  root         /home/vsts/work/1/s
  fname        /home/vsts/work/1/s/apps/servocalibration/runonconsole.cpp
Parsing coverage data for file /home/vsts/work/1/s/apps/servocalibration/runonconsole.cpp
Finding source file corresponding to a gcov data file
  currdir      /home/vsts/work/_temp/bld
  gcov_fname   /tmp/tmp61x2c44r/#usr#include#c++#7#iostream.gcov
               ['        -', '    0', 'Source', '/usr/include/c++/7/iostream\n']
  source_fname /home/vsts/work/_temp/bld/apps/servocalibration/CMakeFiles/ServoCalibration.dir/runonconsole.cpp.gcno
  root         /home/vsts/work/1/s
  fname        /usr/include/c++/7/iostream
```
And the files I thought were supposed to be excluded still in the coverage report.

Please can you tell me what I'm missing about the operation of these filters? The first at least (for the `apps/` directory) is very similar to one of the examples in the manual so I'm really confused about that one not working.

**Comment by latk** [comment]
The examples in the manual generally use the same directory for the source files and object files, whereas you use a separate directory. The important part is that filters are always relative to the current directory, and relate to source files (not to coverage data files). Thus, `--exclude apps/` is here meaning the absolute path `/home/vsts/work/_temp/bld/apps/`. Instead:

* use a relative path in the filter like `--exclude '\.\./\.\./1/s/apps/'`
* use an absolute path in the filter like `--exclude /home/vsts/work/1/s/apps/`

**Comment by freesurfer-rge** [comment]
Changing to `--exclude '$(Build.SourcesDirectory)/apps/'` worked, but I don't understand why. The manual states "These options take filters. A filter is a regular expression that matches a file path." Well, the regular expression `apps/` would match both the relative and absolute paths in your sample.

**Comment by latk** [comment]
That is correct, with the caveat that the matches are anchored at the start of the path. Also, the docs expand on relative vs absolute paths a few paragraphs later:

> If the filter looks like an absolute path, it is matched against an absolute path. Otherwise, the filter is matched against a relative path, where that path is relative to the current directory.

Together, this means that the relative path `../../1/s/apps/servocalibration/runonconsole.cpp` does NOT match the filter `apps/`

If you want a filter to match any path that contains a string, you explicitly have to skip the leading characters, e.g. `--exclude '.*/apps/'`.

**Comment by kevr** [comment]
This really does not seem to be working as intended. I get different results on different systems which use the same project structure.

Structure: `/home/kevr/project/src/file.cpp`

While working in `/home/kevr/project`, using an exclude of `.*/src/file.cpp` does not exclude that file from coverage outputs. In contrast, `src/file.cpp` does. However, when running the exact same structure on Github workflows, I still get coverage from `src/file.cpp`, which doesn't happen on my local system.

This is all very confusing, to be honest. The doc says one thing, but it doesn't seem to always hold true.
