### ISSUE TITLE
Add extra option to specify both lines and branch coverage thresholds in html export

### ISSUE THREAD

**Issue by tibaugasc** [gcovr/gcovr#442]
Current html summary page can help to have a quick overview of a project in term of both line and branch coverage.
However it's only possible to provide a common threshold for coloration. On real projects, constrains regarding minimal coverage for lines and for branches are rarely identical. This constrains either comes from applicable normative standards or project policy.

A simple way to provide this feature is to add extra mirror option, similar to `--html-high-threshold` and forward change to the html generation methods.

I have implemented a draft for internal uses and I will be please to integrate if it make sense.

**Comment by Spacetown** [comment]
I'm working on embedded projects for automotive industry and we don't distinguish between this. Our goal is 100% in unit test and lower in SIL tests.

Which standard claims line coverage? 
All branches should be covered the number of lines in a branch don't matters. E.g. if you have two branches, one with one line and one with 100 lines, the first branch is uncovered and the second is covered, the line coverage will be 99,9%. 
This number has nothing to do with code quality. 

But if there is a real need for this and it 's downward compatible you can create a PR for this.

**Comment by latk** [comment]
I was going to argue that extra features for branch coverage don't make a lot of sense since branch coverage is notoriously unreliable (especially in C++), but that would actually be an argument for being able to set laxer branch coverage thresholds.

So OK, I think we can have different branch coverage thresholds in the HTML output format. Things to consider:

* do we need two colorization legends in the HTML report header?
  * I think we should only show two legends if there are different line & branch settings
* how should the options work?
  * should we add a new option `--html-high-branch-threshold` and have the existing `--html-high-threshold` refer to line coverage?
  * or should we add two new options `--html-high-branch-threshold`, `--html-high-line-threshold` that default to the value of `--
html-high-threshold`?
  * or should we add the two new options, but have the high-line-threshold be an alias of the high-threshold option?
  * and how exactly should the new options be named?
* and of course, please add a test case – it just needs a HTML output though

**Comment by Spacetown** [comment]
>  * do we need two colorization legends in the HTML report header?
>       
>    * I think we should only show two legends if there are different line & branch settings

I'm with you

> * or should we add two new options `--html-high-branch-threshold`, `--html-high-line-threshold` that default to the value of `-- html-high-threshold`?

That's my prefered way. The new options shall Not be used togeter with the existing Option. The old options shall set the threshold for the lines and Branche. 

> * and how exactly should the new options be named?

I prefer to append the `-brach` and `-line`.

**Comment by tibaugasc** [comment]
Thanks for your feedback and suggestions for default choices,  naming or backward compatibility. I'll implement as suggested and submit PR when ready.

>Which standard claims line coverage?

For your curiosity, medical device software standard (62304) suggests that the effort in code coverage should be consistent with the level of criticality of the software items, classified as A, B or C, which mainly relying on risk analysis. So basically, software with high level of criticality (C) should be covered with requirement similar to what is expected in automotive for example, but for software not associated to any serious risk (A), requirement can be lower to normal cases or plausible error case only, which might lead to 75% lines, 50% branches for example. However, exact percentage are not explicitly provided by the standard and can be chosen internally provided sufficient rationale.

**Comment by GitMensch** [comment]
> I'll implement as suggested and submit PR when ready.

@tibaugasc  That sounds nice! As this was posted quite some time ago and I wonder about branch coverage as I've not found anything in the docs for it related to HTML output (the only entry is for text output) I wanted to check about its current state.

@Spacetown Do you remember anything about this or can comment if a PR for https://github.com/gcovr/gcovr/compare/master...tibaugasc:gcovr:html_optionnal_branch_threshold would be reasonable?

**Comment by Spacetown** [comment]
It seems to be a starting point. I'm thinking about adding the command line arguments in a loop. Maybe also do the checks in a loop.

**Comment by tibaugasc** [comment]
Sorry, the PR was not finished due to lack if time, and I forgot it a bit also.

From what I can remember, it was somehow functionnal. But it requires unit test for the feature and a bit of cleaning to match the quality standard of the project.
It is now more than 150 commit behind

**Comment by Spacetown** [comment]
@tibaugasc  please keep your private branch. I'll try to find time to look into it.

**Comment by tibaugasc** [comment]
Oops, sorry for closing the issue by miss clicking.

Don't worry, there is no rational for deleting any branch before merging it somewhere.

I might find time to work a bit on it by myself but it will not be before november.

**Comment by Spacetown** [comment]
I've already debased and working on it.

**Comment by Spacetown** [comment]
@tibaugasc You can remove your branch. Thanks for working on this.
