### ISSUE TITLE
Vote for admin rights

### ISSUE THREAD

**Issue by Spacetown** [gcovr/gcovr#456]
As suggested by @latk in https://github.com/gcovr/gcovr/pull/423#pullrequestreview-540727210 I like to call a vote for admin access. I think two weeks are enough for the vote so it will end on 3th of Februar.

**Comment by latk** [comment]
I vote in favour :)

Spacetown/Michael has been doing the majority of development/maintenance/triage work for some time now, and is doing a great job at that.

In contrast, I'm increasingly blocked with other stuff and have not been able to dedicate enough time to keep things flowing smoothly. Giving Spacetown admin access would help *immensely*.

**Comment by theKBro** [comment]
+1 for @Spacetown 👍

**Comment by CezaryGapinski** [comment]
This is definitely good decision!
I vote in favor.

**Comment by latk** [comment]
All @gcovr/developers and @gcovr/admins are invited to vote on giving admin access to @Spacetown. The vote will end on Feb 10.

I'm extending the vote because I forgot to tag eligible voters earlier, sorry!

**Comment by chrta** [comment]
:+1:

**Comment by jsiirola** [comment]
+1

**Comment by latk** [comment]
The voting period has ended. Thank you for all voices!

Eligible votes were 5 : 0 in favour of giving @Spacetown admin access (counting an implicit self-vote). I have executed the outcome and adjusted permissions accordingly.

Congratulations!

**Comment by Spacetown** [comment]
Thanks for the trust.
