### ISSUE TITLE
Assertion failure: "gcovr_json_data['gcovr/format_version'] == JSON_FORMAT_VERSION"

### ISSUE THREAD

**Issue by macetw** [gcovr/gcovr#462]
After installing the latest gcovr from git, I cannot run gcovr like I could with the installed 4.2 package installed by pip.
`pip3 install --upgrade --user git+https://github.com/gcovr/gcovr.git`
After installing, I get this during usage:
```
+ gcovr -r /code --add-tracefile full_json_output.json --html --html-details -o report/index.html
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/gcovr/__main__.py", line 273, in main
    collect_coverage_from_tracefiles(covdata, options, logger)
  File "/home/user/.local/lib/python3.6/site-packages/gcovr/__main__.py", line 306, in collect_coverage_from_tracefiles
    gcovr_json_files_to_coverage(datafiles, covdata, options)
  File "/home/user/.local/lib/python3.6/site-packages/gcovr/json_generator.py", line 135, in gcovr_json_files_to_coverage
    assert gcovr_json_data['gcovr/format_version'] == JSON_FORMAT_VERSION
```

**Comment by Spacetown** [comment]
Are you using a JSON file from the old version? The  internal format was changed from a number to a string.  If so, can you try to add a str(...)  around the left argument of the comparison in the assert to test a possible fix?

**Comment by macetw** [comment]
Yes, that is likely the case. I will try this when I am able.

**Comment by macetw** [comment]
@Spacetown was correct, this resolved the issue:
        assert str(gcovr_json_data['gcovr/format_version']) == JSON_FORMAT_VERSION
