### ISSUE TITLE
gcovr.writer module missing after installation

### ISSUE THREAD

**Issue by avtolstoy** [gcovr/gcovr#464]
Latest master is non-functional after installation with setuptools/pip (due to the recent change in https://github.com/gcovr/gcovr/pull/443):

```
ModuleNotFoundError: No module named 'gcovr.writer'
```

To reproduce simply install gcovr from the current master using pip and the resulting installation in `site-packages` will be missing the `writer` package:
```
$ ls -1 /usr/local/lib/python3.6/dist-packages/gcovr/
configuration.py
coverage.py
gcov.py
__init__.py
__main__.py
__pycache__
templates
utils.py
version.py
workers.py
```

A simple patch that replaces fixed `packages` value in `setup.py` with `find_packages()` call from setuptools does resolve the problem:
```diff
diff --git a/setup.py b/setup.py
index 943356e..c73db7c 100644
--- a/setup.py
+++ b/setup.py
@@ -21,7 +21,7 @@ Script to generate the installer for gcovr.
 """
 
 from runpy import run_path
-from setuptools import setup
+from setuptools import setup, find_packages
 
 
 version = run_path('./gcovr/version.py')['__version__']
@@ -30,7 +30,7 @@ setup(name='gcovr',
       version=version,
       platforms=["any"],
       python_requires='>=3.5',
-      packages=['gcovr'],
+      packages=find_packages(),
       install_requires=[
           'jinja2',
           'lxml',
```

**Comment by latk** [comment]
Oops, thanks for finding that! Sorry for any inconvenience caused.

Would you like to submit a PR that fixes this? Preferably, use `find_packages(include=['gcovr*'], exclude=['gcovr.tests'])` though since the tests should not be deployed.

**Comment by avtolstoy** [comment]
Sure, created PR https://github.com/gcovr/gcovr/pull/465
