### ISSUE TITLE
make qa not working out of the box

### ISSUE THREAD

**Issue by macetw** [gcovr/gcovr#468]
**Describe the bug**
Running `make qa` shows some formatting errors. Like this:
```
would reformat gcovr/configuration.py
Oh no! 💥 💔 💥
16 files would be reformatted, 4 files would be left unchanged, 6 files would fail to reformat.
make: *** [Makefile:78: black] Error 123
```

I saw this running Ubuntu 20 Linux, in a python3 environment.

**Comment by Spacetown** [comment]
You're right, in the GitHub pipeline this is ignored. But if you're running the whole tests in the command line it should be also ignored. I'll check this and create a PR.

**Comment by Spacetown** [comment]
Ok. That's an error on your side. The check aborts because of `6 files would fail to reformat.` I think there are syntax errors.

**Comment by Spacetown** [comment]
@macetw Can this be closed?
