### ISSUE TITLE
sonarqube report path issue

### ISSUE THREAD

**Issue by dsakilesh** [gcovr/gcovr#478]
**Describe the bug**
The SonarQube report does not have the same file path compared to the html report file path.

PFB the html details:
```
<tr>
<td class="coverFile" ><a href="index.src_BootloaderSelector_test_BootloaderSelector_BootStateMachine_sm.cpp.html">build/unittest-clang/BRC36xx-5/Debug/src/BootloaderSelector/test/BootloaderSelector/BootStateMachine_sm.cpp</a></td>
...
</tr>
```

PFB the SonarQube details:
```
<coverage version="1"><file path="src/BootloaderSelector/test/BootloaderSelector/BootStateMachine_sm.cpp"><lineToCover lineNumber="28" covered="true"/><lineToCover lineNumber="29" covered="true"/><lineToCover lineNumber="30" covered="true"/><lineToCover lineNumber="31" covered="true"/><lineToCover lineNumber="32" covered="true"/><lineToCover lineNumber="33" covered="true"/><lineToCover lineNumber="34" covered="true"/><lineToCover lineNumber="36" covered="false"/><lineToCover lineNumber="38" covered="false"/> 
...
</coverage>
```

**To Reproduce**
1. `python -m gcovr --gcov-executable="llvm-cov gcov" -v --branches -f '${worksapce}/build/(src|include)/' -f 'src/(src|include)/' --object-dir=. --html-details=gcovreport/index.html --sonarqube=gcovreport/sonarqube.xml`

**Expected behavior**
Sonarqueb.xml should contain:
Content: `<file path="build/unittest-clang/BRC36xx-5/Debug/src/BootloaderSelector/test/BootloaderSelector/BootStateMachine_sm.cpp">`

**Desktop (please complete the following information):**
 - OS: Linux
 - GCC version = 9.2.1
 - llvm = 11.0.0
 - GCOVR version = 4.2
 - Project directory layout:
   - src/src
   - src/include
   - build/

**Additional context**
We have src and include folders inside a src folder. And we also have few files in build folder. We see the file path for src directory as absolute path and ones in build directory as relative path in sonarqube.xml. And there is a mismatch in the build directory file path. It shows **src/BootloaderSelector/test/BootloaderSelector/BootStateMachine_sm.cpp** in **_sonarqube.xml_** file whereas it is **build/unittest-clang/BRC36xx-5/Debug/src/BootloaderSelector/test/BootloaderSelector/BootStateMachine_sm.cpp** in **_index.html_** file.

The Sonarqube report does not have the values but HTML has values. This is happening for the file paths which are different from that of html report.

**Comment by latk** [comment]
From which working directory are you invoking gcovr? The results might indicate you're running from within the `build/unittest-clang/BRC36xx-5/Debug` folder, but it's not totally clear to me.

The Sonarqube report is intended to be machine-readable. Paths within the --root directory are shown as relative paths, other paths as absolute paths. The --root directory defaults to the current working directory. Maybe this can be fixed just by adding a `--root ${workspace}` argument?

The HTML report tries to fabricate useful paths, which is not entirely predictable. For example, it tries to strip the common prefix of all source file paths. It is thus understandable that the HTML report won't produce the same paths as a machine-readable report.

**Comment by dsakilesh** [comment]
Hi @latk  Thanks for the solution.

`--root ${workspace}` seems to work like a charm.
