### ISSUE TITLE
gcovr cannot find source files with gcov 4.8.2

### ISSUE THREAD

**Issue by wogrady11** [gcovr/gcovr#49]
The fix from https://software.sandia.gov/trac/fast/ticket/3860 no longer works with gcov 4.8.2.

*****\* 3860 Description *****
I'm having problem with gcovr which don't see my source code. I have my code organized in following way

$ROOT/src -> all *.cpp files
$ROOT/include -> all *.h files
$ROOT/obj -> all *.o files
$ROOT/lib -> for libs
$ROOT/bin -> for binaries
- tests are organized in this way (not important)

$ROOT/test/src
$ROOT/test/bin
$ROOT/test/obj

Now, I run gcovr in the following way:

cd $ROOT
gcovr_wrapper -x -b -r $ROOT -e $ROOT/test
gcovr complains that he couldn't find the source code. Quick solution is to copy $ROOT/src and $ROOT/include to $ROOT/obj, but this only works with small projects. It would be much better to tell gcovr where to look for source files. Do you know if it is possible in current implementation of gcovr? If not then does anybody has an idea if it would be feasible to implement? 
****\* end 3860 Description *****

****\* original 3860 resolution ******
r2378 introduces new gcovr logic: if gcov tosses an error, gcovr will attempt to re-run gcov from higher in the directory tree (specifying the original directory through the --object-directory argument). gcovr will traverse up to the system root directory if necessary (and then throw a warning summarizing all errors tossed by gcov if gcov is still not happy).

This now correctly runs the provided test case.
****\* end original 3860 resolution ******

Research shows that gcov 4.8.2 changed the stderr message format to

"Cannot open source file"

whereas gcov 4.5.2 and previous stderr message was 

"cannot open source file".

Resolved by changing line 63 from "cannot" to "[Cc]annot".

**Comment by kuldeepmarker-eaton** [comment]
@wogrady11  I am facing the issue you have mentioned in gcovr 5.0. Could you please share with me the command line arguments used by you

**Comment by Spacetown** [comment]
@kuldeepmarker-eaton Please open a new issue since this issue is 9 years old and the codebase is completly different.
