### ISSUE TITLE
Not able to generate a .gcno file from .gcda file 

### ISSUE THREAD

**Issue by ilayavimal10** [gcovr/gcovr#499]
How to generate a .gcno file from .gcda file in block box testing on windows platform.
Getting below error 
C:\Users\xxxxx\Desktop\xxxxxx\Test>gcov test_ctrl.c
test_ctrl.gcno:cannot open notes file

>.gcda file we have generated from testing tool but when we are trying to generate a .gcno file from .gcda file getting above error
>And also need to generate a .gcov file

**Comment by latk** [comment]
The gcno (notes) file is generated by the compiler, not by gcov or gcovr. The following diagram illustrates the data flow:

![gcov data flow](https://user-images.githubusercontent.com/1782927/124289139-83787980-db41-11eb-9d24-23beb5257a2a.png)

In any case, your question does not seem to relate to gcovr directly. The gcov program is part of the GCC project.
