### ISSUE TITLE
Gcovr Windows Invoking Cygwin Gcov with Absolute Paths Failing Due to Backslashes

### ISSUE THREAD

**Issue by jhcasco** [gcovr/gcovr#501]
I am struggling with an issue with on Windows where gcovr is producing an empty html report while reporting individual coverage correctly.  I have tracked this down to a behavior with how gcovr invokes gcov for each gcda file produced by my unit testing suite (ceedling), and it may be caused by my project structure on Windows and how gcovr decides to use absolute paths with backslashes when invoking gcov.

I am unsure if this is an issue meant to be solved by gcovr or Cygwin gcov itself, but it seems easiest to approach from gcovr.

My project utilizes Ceedling unit testing suite to automatically build and test individual modules of my code using Cygwin gcc and invoke gcovr for a test coverage report.

 - Simplified project directory layout (no spaces in any paths):
   - project_name
      - build
         - artifacts
            - gcov (target directory for gcovr outputs)
               - report.xml
               - GcovCoverageResults.html
               - Report_Detail_Files_If_Successful.html
         - gcov
            - out (object directory)
               - foo.gcda/gcno/o/out
               - bar.gcda/gcno/o/out
      - src
         - foo_module
            - foo.c
            - foo.h
         - bar_module
            - bar.c
            - bar.h
      - test
         - test_foo_module
            - test_foo.c
         - test_bar_module
            - test_bar.c

Ceedling builds my test code, executes the code with coverage tracking enabled, and invokes gcovr with the following command from the project directory:
```
gcovr --root "." --exclude "^vendor.*|^build.*|^test.*|^lib.*" --gcov-exclude ".*mock_.*|.*test_.*|.*helper.*|.*cmock.*|.*unity.*" --branches --sort-percentage --html-details --html-medium-threshold 75 --html-high-threshold 90 --html  "build/artifacts/gcov/GcovCoverageResults.html"
```

This results in an empty coverage report ("Gathered coveraged data for 0 files"), but followup commands to gcov indicate individual files have coverage results.

When I run this command with -v from the same project directory in command line, I see each *.gcda file is sent to gcov with the following command style:
```
Running gcov: 'gcov C:\absolute_path_to_project\project_name\build\gcov\out\foo.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory C:\ absolute_path_to_project\project_name\build\gcov\out' in 'C:\Users\my.user\AppData\Local\Temp\some_temp_folder’
```

When I invoke gcov in the same way on a single file, the output reveals some interesting behavior:
```
gcov C:\absolute_path_to_project\project_name\build\gcov\out\foo.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory C:\absolute_path_to_project\project_name\build\gcov\out
C:\absolute_path_to_project\project_name\build\gcov\out/C:\absolute_path_to_project\project_name\build\gcov\out\foo.gcno:cannot open notes file

C:\absolute_path_to_project\project_name\build\gcov\out/C:\absolute_path_to_project\project_name\build\gcov\out\foo.gcda:cannot open data file, assuming not executed
```

It appears to me that the file path is not handling backslashes while the object directory path is handling them.  Somehow gcov then decides to concatenate the filepath with the object directory and suddenly it can't find the gcda file anymore.  Using double backslashes in one or both of the filepath and/or object directory has the same behavior and confirms the concatenation occurring.

However, if I simply invoke gcov with just the gcda file without a filepath, it returns correct results and generates the *.gcov file, even with single backslashes in the object directory.
```
gcov foo.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory C:\absolute_path_to_project\project_name\build\gcov\out
```

This also works when invoking gcov with an absolute filepath _using forward slashes_ even with single backslashes in the object directory.
```
gcov C:/absolute_path_to_project/project_name/build/gcov/out/foo.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory C:\absolute_path_to_project\project_name\build\gcov\out
```

I was able to work around this problem by rebuilding gcovr with the following modification to pass the gcov commands using only forward slashes, but I don't know if this is the correct solution for the problem:
![image](https://user-images.githubusercontent.com/87436231/125653700-ee128a97-c866-49ef-a590-f72be076d681.png)

Is there something I'm missing here?  Is there any possibility of fixing this error from gcovr side of things?

**Desktop:**
 - OS: Windows 10
 - GCC version Cygwin gcc version 10.2.0
 - GCOVR version 5.0

**Comment by Spacetown** [comment]
Are ,out running feeling from a cygwin she'll or from a windows command prompt? Is the gcovr command working if you use forward slashes and a /cygdrive/c instead of c:?

**Comment by jhcasco** [comment]
Cygwin is being used entirely from command prompt.  I get the same backslash gcov calls if I invoke gcovr from a cygwin shell though.  Note that gcovr is deciding how to format the absolute paths passed to gcov, not me, so I can't make it use a cygdrive.

**Comment by Spacetown** [comment]
>  Note that gcovr is deciding how to format the absolute paths passed to gcov, not me, so I can't make it use a cygdrive.

Not gcovr, the OS. The problem is that cygwin doesn't understand Windows paths, MinGW does.

Can you call gcov before running gcovr and add the option `--use-gcov-files` to gcovr? This will use the existing gcovr files instead of running gcov on the raw files.

**Comment by jhcasco** [comment]
This is a possible workaround, but requires looping through the gcda files with my own script when gcovr can do this already.  Ceedling already has a gcovr plugin, so it's build, test, and generate coverage report in a single command.  Is there any specific reason or other environment where gcovr must pass the paths to gcov using OS specific separators rather than forward slashes?

**Comment by Spacetown** [comment]
In Windows the separator is a backslash and the alternative separator is the forward slash. To be usable on several OSs we use the python functions for path handling. I don't want to hardcode a slash in a system call. Maybe changing the path to a relative on is better here.
Please can you run the gcov command in following directory, giving the path in the form `out\foo.gcda`?
```
C:\absolute_path_to_project\project_name\build\gcov
```

**Comment by jhcasco** [comment]
No dice.  Any combination of a filepath using backslashes with an object directory option results in concatenation of the filepath and object directory.  The following works correctly:

1. Forward slashes in filepath (absolute or relative) with object directory (backslashes or forward slashes)
`gcov C:/absolute_path_to_project/project_name/build/gcov/out/foo.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory C:\absolute_path_to_project\project_name\build\gcov\out`
2. Filename only with object directory (backslashes or forward slashes)
`gcov foo.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory C:\absolute_path_to_project\project_name\build\gcov\out`
3. Filepath (backslashes or forward slashes) omitting object directory
`gcov C:\absolute_path_to_project\project_name\build\gcov\out\foo.gcda --branch-counts --branch-probabilities --preserve-paths`

I'm less familiar with the project structures you have developed for in the past.  Would options 2 or 3 break anything?

**Comment by Spacetown** [comment]
Please can you check the commit of my private branch? The paths to the gcda file and the object directory are converted to relative paths to the working directory.

**Comment by Spacetown** [comment]
> Would options 2 or 3 break anything?

If a gcov executable accepts only windows seperators and not the alternative separator there will be the same problem you got.
I saw that there is a cygwin package for gcovr and in the examles a python in the cygwin directory is used. Do you use a python which is delivered with cygwin or a separate one?

**Comment by jhcasco** [comment]
I have been using pip to install gcovr (or building setup.py and installing locally for any modifications I am testing).  The gcovr provided with cygwin appears to only be the python script attempting to run the gcovr module which is _not_ included in the normal installation, and installing it with source places the source files in a different directory anyways which can't be found by this script (yet more workarounds just to get it functioning at all!).

gcovr included with cygwin (not an executable):
```
#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from gcovr.__main__ import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

From cygwin terminal:
```
$ gcovr --version
Traceback (most recent call last):
  File "/usr/bin/gcovr", line 7, in <module>
    from gcovr.__main__ import main
ModuleNotFoundError: No module named 'gcovr'
```

As far as your private branch commit da01dc7... wooooow gcovr and python don't like my project structure at all.  Same problem with backslashes in the filepath while defining an object directory as shown in my previous post, but just in a very, very, very unexpected way.
```
Running gcov: 'gcov ..\..\continue_up_until_C_drive\absolute_path_to_project\project\build\gcov\out\foo.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory ..\..\continue_up_until_C_drive\absolute_path_to_project\project\build\gcov\out' in 'C:\Users\my_user\AppData\Local\Temp\some_temp_folder'
```

**Comment by Spacetown** [comment]
Strange behaviour of relpath function in python. In perl it's different. I'll take a deeper look at this in the next days.

**Comment by Spacetown** [comment]
Ok, my fault the working directory is a temporary directory and therefore the `..\` in the paths are correct.
From the dcoumentation of cygwin
- https://cygwin.com/cygwin-ug-net/using.html#using-pathnames
```
Although the Cygwin DLL supports Win32 paths, not all Cygwin applications support them.
```
- https://cygwin.com/cygwin-ug-net/using.html#pathnames-win32
```
Using native Win32 paths in Cygwin, while often possible, is generally inadvisable.
```

The only solution for me would be a option to use `cygpath` to convert native windows paths to cygwin paths where they are needed but I don't want to implement this special edge case.
I've checked the documentation of `ceedling` and it also supports MinGW instalations instead of cygwin. Is it possible for you to use MinGW?

**Comment by Spacetown** [comment]
@jhcasco Can you check this with the current master branch?

**Comment by Spacetown** [comment]
Closing because no response for a while. If problem persist, please reopen.
