### ISSUE TITLE
Import gcovr into python and allow editing of coverage data before html/xml generation

### ISSUE THREAD

**Issue by tgs266** [gcovr/gcovr#504]
**Is your feature request related to a problem? Please describe.**
I am having a real issue with branch coverage being messed up by nonexistent branches. I know there are exclusion markers I could use that could possibly overcome some of these issues, but I dont want to cover my c++ code with a bunch of unnecessary comments.

**Describe the solution you'd like**
Is there a way that gcovr could be imported into python and allow editing of the coverage data using custom filters designed by the user to then exclude anything like a function call that creates a random branch or a line that is just a curly brace? 

For example, I import gcovr, call a function that tells it where my gcda and gcno files are and get the computed coverage returned to me. Then, since the coverage data (as far as I can tell) is just held in a standard python dictionary, edit it using whatever method I want to remove whatever I want. Then pass it back to gcovr, telling it to compute the coverage statistics and generate a report in whatever format I want.

**Comment by latk** [comment]
Gcovr does not currently offer an API or plugin system, and I don't see a near-term path to changing this.

However, the JSON format is a 1:1 representation of the internal data model. So the supported way to filter coverage is:

* run gcovr and create a JSON report
* modify the JSON file with your program as needed
* run gcovr using the `-a`/`--add-tracefile` option to load the JSON again, and create your desired reports.

The limitation is that the coverage data model does not contain the source code itself, only file names.

Note that gcovr already includes some built-in mechanisms for filtering potentially unintended coverage:

* `--exclude-throw-branches` excludes branches for exception handling, which may or may not be useful
* `--exclude-unreachable-branches` parses the source code and will disregard branch coverage on lines that don't seem to contain useful code. E.g. lines that only contain curly braces are excluded.

The `--exclude-unreachable-branches` option sounds very similar to what you're trying to do. Please let me know if you have suggestions for improving the current heuristics:

https://github.com/gcovr/gcovr/blob/c0f1da2f9f1fa78bbe4dc093da0c953d2d3a3550/gcovr/gcov.py#L409-L416

In any case, consider reading our FAQ entry [Why does C++ code have so many uncovered branches?](https://gcovr.com/en/stable/faq.html#why-does-c-code-have-so-many-uncovered-branches) which describes in detail why dealing with branch coverage in C++ code is a really difficult problem.

**Comment by tgs266** [comment]
I figured out a way to import gcovr and for now I have copied the main method and I am intercepting the dictionary there. Once I find a result I like, I can report back better heuristics or atleast better options to use to exclude branches
