### ISSUE TITLE
Inconsistent warning with `--object-directory`

### ISSUE THREAD

**Issue by Pesa** [gcovr/gcovr#510]
When using the `--object-directory` option with a relative path, the following warning is triggered (or not) depending on whether the path ends with a slash (or not).

> (WARNING) relative referencing in --object-directory.
        this could cause strange errors when gcovr attempts to
        identify the original gcc working directory.

**To Reproduce**
```
$ gcovr --root=. --object-directory build
...

$ gcovr --root=. --object-directory build/
(WARNING) relative referencing in --object-directory.
        this could cause strange errors when gcovr attempts to
        identify the original gcc working directory.
...
```

**Expected behavior**
The trailing slash should be irrelevant.

Moreover, the way the help text for `--object-directory` is phrased:
> This option specifies either the path from gcc to the gcda file (i.e. gcc's '-o' option), or the path from the gcda file to gcc's working directory.

makes me think that a relative path is expected there. Is that not the case? Maybe the warning is wrong?

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - GCC 10.3.0
 - GCOVR 5.0

**Comment by Pesa** [comment]
The warning is caused by this check: https://github.com/gcovr/gcovr/blob/e0b7afef00123b7b6ce4f487a1c4cc9fc60528bc/gcovr/__main__.py#L213

I'm not sure what the check is trying to accomplish or why the warning is there in the first place, but if you just need to know whether a relative or absolute path was given, you should use `os.path.isabs()` instead of `normpath()`.

**Comment by Spacetown** [comment]
> But the particular warning you've stumbled upon seems to be entirely useless, and the code literally makes no sense. I think that particular check and the `tmp` variable leading up to it can be safely removed.

Shall I remove this warning?
