### ISSUE TITLE
HTML printer bugs with large source files

### ISSUE THREAD

**Issue by argonaut30** [gcovr/gcovr#519]
**Describe the bug**
When gcovr analyzes a g notes file for a large source file (this example is 130 MB for the source file and 27.4 MB for the corresponding gcno file), the HTML printer crashes while producing a report. Text and XML output do not crash.

**To Reproduce**

1. Use a large source file; no unit tests cover this file.
2. Compile using gcc w/ the necessary compiler flags for coverage.
3. Execute gcov for the project.
4. Execute gcovr. The specific command used is below:

`gcovr -g -k --exclude-unreachable-branches --root /builds/<XXX>/<XXX>/<XXX>/<XXX>/<XXX> --html-details coverage_report_webpage.html --exclude ".*\.h"` 

**Expected behavior**
A ValueError will be thrown with its body stating `max() arg is an empty sequence`. This traces back to the `print_html_report` function in gcovr. The text and XML outputs, when run, do not crash. The detailed traceback is pasted below while the output from the text report can be seen in the screenshots section.

```
Traceback (most recent call last):
  File "/home/<XXX>/.local/bin/gcovr", line 11, in <module>
    sys.exit(main())
  File "/home/<XXX>/.local/lib/python3.6/site-packages/gcovr/__main__.py", line 280, in main
    error_occurred = print_reports(covdata, options, logger)
  File "/home/<XXX>/.local/lib/python3.6/site-packages/gcovr/__main__.py", line 432, in print_reports
    if generator(covdata, output.abspath, options):
  File "/home/<XXX>/.local/lib/python3.6/site-packages/gcovr/writer/html.py", line 397, in print_html_report
    max_line_from_cdata = max(cdata.lines.keys())
ValueError: max() arg is an empty sequence
```

**Screenshots**

![gcovr output](https://user-images.githubusercontent.com/92760900/137816209-c51ba173-7027-4df0-85a7-583791c19ce8.png)

**Desktop (please complete the following information):**
 - GCC version 8.4.1
 - GCOVR version 5.0

**Comment by sonicyang** [comment]
I am working with a large repo, and this bug occurred.

I think @latk's theorem is correct.
We do have translation unit compiled into files with no actual machine code.
I can confirm that setting default=0 to max do solve the issue.

**Comment by Spacetown** [comment]
Do you have an example for:
> We do have translation unit compiled into files with no actual machine code.

I'm trying to setup a test case but if I only put a variable inside the file no gcov output is generated and a inline function generate an output without coverage.

**Comment by sonicyang** [comment]
I don't have one for at the moment which can be posted here.
I think have to make an artificial one.

**Comment by Spacetown** [comment]
What kind of definitions are in that file. With a external variable no coverage file is generated and if a uncovered function is in the file coverage data is created correct.
