### ISSUE TITLE
Support the LCOV-Info output format

### ISSUE THREAD

**Issue by latk** [gcovr/gcovr#523]
The LCOV Info format is a widely used coverage format. It would be great if Gcovr can generate Info-files so that more downstream tools can be used. For example, #522 showed that the Coveralls Github Action expected LCOV-Info files, which currently makes it impossible to use gcovr together with that Action.

Expected solution: There is an `--lcov` output format.

Design constraint: being able to *parse* LCOV-Info would also be very nice, but is more complicated. The naming of command line options should make it possible to have both input + output LCOV files in the future.

The Lcov-Info format is documented in [`man 1 geninfo`](http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php). It is a simple text-based format.

**Comment by Spacetown** [comment]
I can work on this but prefer to close #474 first.

**Comment by Spacetown** [comment]
@latk For the lcov format we need to include the block information for the branches into the data model. I prefer to do this in a separate PR. What's your opinion?

**Comment by pjyan** [comment]
Hi，
    I'm using lcov to generate an LCOV-Info file,  like `lcov -c -o abc.info`.
    Just want to know, is possible will gcovr support to use the LCOV-Info file as an input?

**Comment by Spacetown** [comment]
The intention was to generate the output format only. I need to check if we can also add it as input format.

**Comment by pjyan** [comment]
> The intention was to generate the output format only. I need to check if we can also add it as input format.

sure. that would be great if gcovr can handle the input format

**Comment by Spacetown** [comment]
Need to check this if the output format is implemented.
