### ISSUE TITLE
gcovr could not open output file

### ISSUE THREAD

**Issue by maiductuan** [gcovr/gcovr#530]
when i run gcovr --sonarqube cover.xml
then i received the following error when **gcovr could not open the output file**
I don't know why it's like that
I tried gcovr -k --sonarqube cover.xml but it doesn't keep the .gcov files so I can check their contents

**Comment by Spacetown** [comment]
Which error message exactly?

**Comment by maiductuan** [comment]
**this is what i get and this error repeats a lot**
WARNING) GCOV produced the following errors processing /home/jenkins/workspace/NXT.PROD.SVM/scan-coverity-test/build_linux/SVM_lib/view_module/CMakeFiles/View.dir/src/BasicViewReconstructor.cpp.gcda:
	Could not open output file '#home#jenkins#workspace#NXT.PROD.SVM#scan-coverity-test#build_linux#SVM_lib#view_module#CMakeFiles#View.dir#src#BasicViewReconstructor.cpp.gcda###home#jenkins#workspace#NXT.PROD.SVM#scan-coverity-test#core#modules#SVM_lib#view_module#src#BasicViewReconstructor.cpp.gcov'
Could not open output file '#home#jenkins#workspace#NXT.PROD.SVM#scan-coverity-test#build_linux#SVM_lib#view_module#CMakeFiles#View.dir#src#BasicViewReconstructor.cpp.gcda###home#jenkins#workspace#NXT.PROD.SVM#scan-coverity-test#core#modules#SVM_lib#view_module#include#BasicViewReconstructor.h.gcov'

	Could not open output file '#home#jenkins#workspace#NXT.PROD.SVM#scan-coverity-test#build_linux#SVM_lib#view_module#CMakeFiles#View.dir#src#BasicViewReconstructor.cpp.gcda###home#jenkins#workspace#NXT.PROD.SVM#scan-coverity-test#core#modules#SVM_lib#view_module#src#BasicViewReconstructor.cpp.gcov'
Could not open output file '#home#jenkins#workspace#NXT.PROD.SVM#scan-coverity-test#build_linux#SVM_lib#view_module#CMakeFiles#View.dir#src#BasicViewReconstructor.cpp.gcda###home#jenkins#workspace#NXT.PROD.SVM#scan-coverity-test#core#modules#SVM_lib#view_module#include#BasicViewReconstructor.h.gcov'

**Comment by maiductuan** [comment]
I don't know if it is affected by permissions, I tried sudo gcovr and it doesn't work

**Comment by Spacetown** [comment]
Ok. It seems that this will be fixed with #528 and is releated to the long file names.

**Comment by maiductuan** [comment]
i am using ubuntu, is this problem doc solvable, or is it only for windows

**Comment by Spacetown** [comment]
Can you try to comment following two lines?
https://github.com/gcovr/gcovr/blob/044b5c9f884262286b17199832bf98392f7fb59b/gcovr/gcov.py#L388-L389

**Comment by 0xfff0** [comment]
Hello! I'm running into the same problem however this is on native Amazon Linux. #528 seems to indicate this is issue is specific to Windows, is that correct?

**Comment by Spacetown** [comment]
I think it depends also on the used file system but I've no experience with Amazon Linux.

**Comment by Spacetown** [comment]
Closing because no progress since a while. If problem persists, please reopen.

**Comment by Thallamsaisowmya23** [comment]
(ERROR) Error occurred while reading reports:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\__main__.py", line 389, in main
    covdata: CovData = gcovr_formats.read_reports(options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\__init__.py", line 68, in read_reports
    covdata = GcovHandler(options).read_report()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\__init__.py", line 202, in read_report
    return read_report(self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\read.py", line 79, in read_report
    with Workers(
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\workers.py", line 173, in __exit__
    self.wait()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\workers.py", line 164, in wait
    raise self.exceptions[0][1]
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\read.py", line 86, in read_report
    contexts = pool.wait()
               ^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\workers.py", line 164, in wait
    raise self.exceptions[0][1]
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\workers.py", line 80, in worker
    work(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gcovr\formats\gcov\read.py", line 450, in process_datafile
    raise RuntimeError(errors_output)
RuntimeError: GCOV produced the following errors processing F:\add\add.gcda:
        Trouble processing 'F:/add/add.gcda' with working directory 'F:\\add'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        Trouble processing 'F:/add/add.gcda' with working directory 'F:/add'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        Trouble processing 'F:/add/add.gcda' with working directory 'F:/'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        (gcovr could not infer a working directory that resolved it.)
To ignore this error use option --gcov-ignore-errors=no_working_dir_found.

GCOV produced the following errors processing F:\add\add.gcda:
        Trouble processing 'F:/add/add.gcda' with working directory 'F:\\add'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        Trouble processing 'F:/add/add.gcda' with working directory 'F:/add'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        Trouble processing 'F:/add/add.gcda' with working directory 'F:/'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Exception was >>[WinError 2] The system cannot find the file specified<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended information.
        (gcovr could not infer a working directory that resolved it.)
To ignore this error use option --gcov-ignore-errors=no_working_dir_found.
