### ISSUE TITLE
Prepare next release

### ISSUE THREAD

**Issue by Spacetown** [gcovr/gcovr#534]
I want to plan the release 5.1. I updated the labels of the issues in the current [milestone](https://github.com/gcovr/gcovr/milestone/9), renamed the milestone to 5.1 and set a target date of 2022-01-07.
At the moment there are 9 issues which are waiting for a review. It would be great if you find a time slot to review an issue.
If a issue shall be moved to the next release please leave a comment.

**Comment by gsemet** [comment]
Hi. When do you think 5.1 will be released? I would like to have function coverage and it seems available on HEAD

**Comment by Spacetown** [comment]
I think we have to shift the release by one or two weeks. At the moment there are 5 open PRs and I have one local WIP. Additional there are 2 more ideas for the HTML details report.

**Comment by Spacetown** [comment]
I'm still waiting for someone to review the the changes.
@latk I think #535 and #549 can be closed since #565 is fixing the problem without affecting existing test data.

**Comment by latk** [comment]
Thank you @Spacetown, I'll take a look this evening.

Sorry that I'm holding everything up, this feels a bit like #176 all over again where the project suffers from an unresponsive maintainer. At least now, more people have commit access. I would *like* to review everything, but that's not realistically possible – if I'm silent for a while it might be better to proceed without waiting for me.

**Comment by Spacetown** [comment]
@latk I think for #569, #566 and maybe #563 it's OK to bypass the review workflow.
For #565 and #554 a review is needed.
For #555 there is an open point in the discussion.
#561 is also finished but there was a question with the merge order. If you update the documentation (#552) I can merge it.

**Comment by Spacetown** [comment]
@latk After merging #552, #554 and #555 I want to apply black to all files.
After this we can add the pending changes to the docs and finish the release.

**Comment by latk** [comment]
Ok, I'm working on finishing #552. Review remarks are done, now I just have to rebase.

**Comment by latk** [comment]
As far as I can see, the release is almost ready.

* [ ] #581
* [ ] tag the release, hope the automatic upload to PyPI works, or do a manual upload
* [ ] associate the tag with the GH release (I have created a draft for this)

**Comment by latk** [comment]
Done! Everyone can run `pip install -U gcovr` now to upgrade :)
