### ISSUE TITLE
--exclude filters have no effect on current working directory - part 2

### ISSUE THREAD

**Issue by peter-toft-greve** [gcovr/gcovr#551]
**Describe the bug**
I cannot get gcovr 4.2 to exlude a source file visible in my build folder using "gcovr -e"

**To Reproduce**
1.  Clone https://github.com/peter-toft-greve/gcovr_exclude onto e.g. an Ubuntu 20.04 with gcovr 4.2 and gcc
2. Run "run_me.sh"
3. Open a browser with the build/index.html - I do not want to see the build/fct3.c since it emulates autogenerated files, but I do not know how to force gcovr using the -e options to ignore the file.
4. In the run_me.sh I have comments how to ignore external and test files - that seems to work. THANX to the nice friends in https://github.com/gcovr/gcovr/issues/323

**Expected behavior**
I like to add some expression to ignore the build/* files

**Screenshots**
![image](https://user-images.githubusercontent.com/48215001/148561122-c85a7f1b-5aae-45b6-93c1-928c71a74b3c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - GCC version 9.3
 - GCOVR version 4.2
 - Project directory layout: See https://github.com/peter-toft-greve/gcovr_exclude

**Comment by peter-toft-greve** [comment]
Note that I have some experiments:


build/      ->      -e "(.*/)*build/"   ->    does NOT WORK
src/test/  ->      -e "(.*/)*src/test/"  ->  works 
external/  ->        -e "(.*/)*external/" ->  works

**Comment by latk** [comment]
Thank you for that excellent test case.

Relative filters are matched to paths relative to the current working directory. A relative --exclude filter will see paths like the following:

```none
fct3.c
../src/fct1.c
../src/fct1.h
../src/test/testfct1.c
../external/fct4.c
```

We could represent an appropriate filter as “match a path that DOES NOT start with `..`”:

```bash
$ gcovr -r .. -e '(?!\.\./)'
```

This uses a `(?!...)` “negative lookahead assertion” as documented in the [Python regular expression syntax](https://docs.python.org/3/library/re.html#regular-expression-syntax).

If you use an absolute path, the intention might be easier to understand (but it might not work if you have creative directory names that include regex metacharacters):

```bash
$ gcovr -r .. -e "$(pwd)"
```

The `pwd` command outputs the current working directory (`build/`) as an absolute path.

Alternatively, we can use a `--filter` to INCLUDE coverage only if the paths match a pattern:

```bash
$ gcovr -r .. -f '\.\./'
```

If you mix include filters and exclude patterns, remember that at least one --filter must match, and no --exclude can match.

Resulting txt report in either case:

```none
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: ..
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
external/fct4.c                                2       2   100%   
src/fct1.c                                     6       5    83%   10
src/test/testfct1.c                            5       5   100%   
------------------------------------------------------------------------------
TOTAL                                         13      12    92%
------------------------------------------------------------------------------
```

The `--root` and `--filter` arguments do subtly different things: The root is a *directory*. This directory also serves as a default filter if none is given, in which case all of the files must be within that root directory or a subdirectory. In contrast, the filter is a *pattern* that is matched as a regular expression. The tests “is in directory” and “matches regex” are different.

In the future, it might be nice to implement an extensible syntax that allows for more natural filter specifications, e.g. `gcovr --exclude +path:.` which wouldn't be interpreted as a regex. I remember that I suggested similar things back in #323 but I haven't gotten around to implementing something like that yet.

Additional note: do not use `--object-directory`. It is almost always wrong. It has some subtle internal effects like switching to different internal heuristics. If you just want to provide a search path in which gcda/gcno files are located, list the path without an argument (`gcovr [OPTIONS...] SEARCH_PATHS...`). The path `.` is searched by default so it doesn't have to be mentioned explicitly. A bare `gcovr` is equivalent to "`gcovr --root=. .`".

**Comment by peter-toft-greve** [comment]
THANX a mil @latk - great comment and solved... BUT :)
If you - like I - want to interface the commands via cmake it becomes quite hard with all of the escape problems between cmake, the shell and finally into gcovr, thus work on adding support for specifying e.g. the absolute paths could be golden since absolute paths are often easy to write/setup/parse.

I am very happy that you took the time to comment on this.
