### ISSUE TITLE
Support overrides to the default EXCL patterns (LINE/START/STOP) to allow builds to exclude different sets of code as needed

### ISSUE THREAD

**Issue by zphensley42** [gcovr/gcovr#557]
**Is your feature request related to a problem? Please describe.**
I work on a project that has a need to exclude certain types of coverage that is not conditionally compiled for various reasons. We cannot functionally increase coverage across build types to match expectations because we will always have sections of code that never expect to execute for certain clients. A way to resolve this would be to allow us to change the patterns used when marking code as excluded (via LINE/START/STOP markers).

**Describe the solution you'd like**
An easy solution is to just add a configuration option to override this default regex as necessary. I already have a fork that does this.

**Describe alternatives you've considered**
Obviously the alternative would be to conditionally compile to prevent this code being in the executable to begin with. This is not always possible (mainly due to constraints with agreed-upon interfaces / features for the builds with code we need to exclude).

**Additional context**
Primarily, this hits hardest, for our usages, in places where the interface is expected to remain the same but naturally upgrade / progress when clients move to newer hardware using our codebase.

The branch I am using for this: https://github.com/zphensley42/gcovr/tree/task/flexible_exclusions

I will make a PR into mainline if acceptable as an option.

**Comment by Spacetown** [comment]
Have you tried the option `--exclude-lines-by-pattern`? With this option you can specify a regex to exclude matching lines, `--exclude-lines-by-pattern CUSTOM_EXCL_LINE` should work.

**Comment by zphensley42** [comment]
Yes, but we would have to put that on all lines, not just by markers. I discovered it while working on this one.

**Comment by Spacetown** [comment]
I took a look at your branch and for me this seems a little bit to complicated. It would be easier to change the prefix pattern of the following regex by an option.
https://github.com/gcovr/gcovr/blob/b6e185036d197b50d351299e3927f95421c9546d/gcovr/gcov_parser.py#L56

For example `--exclude-pattern-prefix=MY_PROJECT` using a default of `[GL]COVR?`.

**Comment by zphensley42** [comment]
Made a new branch with the suggested path: https://github.com/zphensley42/gcovr/tree/issue_557

**Comment by Spacetown** [comment]
Please create a PR to discuss the change.

**Comment by zphensley42** [comment]
Done.
