### ISSUE TITLE
SonarQube no longer parse <functionToCover> tags in XML report

### ISSUE THREAD

**Issue by tnkerber** [gcovr/gcovr#590]
We use the following gcovr command to produce a SonarQube XML coverage report
`gcovr --exclude-throw-branches --exclude-unreachable-branches -r . --sonarqube -o gcov_coverage.xml`

SonarQube all of the sudden complains about the XML syntax

> `14:41:58  ERROR: Error during SonarScanner execution
> 14:41:58  ERROR: Error during parsing of the generic coverage report '/mnt/jenkins/workspace/SWR-1186-improve-galwem-ingestor/sw/gcov_coverage.xml'. Look at SonarQube documentation to know the expected XML format.
> 14:41:58  ERROR: Caused by: Unknown XML node, expected "lineToCover" but got "functionToCover" at line 2
> 14:41:58  ERROR: 
> 14:41:58  ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
> [Pipeline] }`

The error occurs in both of the following versions of SonarQube
_

> 14:41:07  INFO: Scanner configuration file: /home/sonar/conf/sonar-scanner.properties
> 14:41:07  INFO: Project root configuration file: NONE
> 14:41:07  INFO: SonarScanner 4.6.0.2311
> 14:41:07  INFO: Java 11.0.3 AdoptOpenJDK (64-bit)
> 14:41:07  INFO: Linux 3.10.0-1062.12.1.el7.x86_64 amd64
> 14:41:07  INFO: User cache: /root/.sonar/cache
> 14:41:09  INFO: Scanner configuration file: /home/sonar/conf/sonar-scanner.properties
> 14:41:09  INFO: Project root configuration file: NONE
> 14:41:09  INFO: Analyzing on **SonarQube server 7.9.4**
> 14:41:09  INFO: Default locale: "en_US", source code encoding: "US-ASCII" (analysis is platform dependent)
> 14:41:09  INFO: Load global settings
> 14:41:09  INFO: Load global settings (done) | time=155ms

> INFO: Scanner configuration file: /home/jenkins/agent/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonar-scanner/conf/sonar-scanner.properties
> INFO: Project root configuration file: NONE
> INFO: SonarScanner 4.7.0.2747
> INFO: Java 11.0.14.1 Red Hat, Inc. (64-bit)
> INFO: Linux 3.10.0-1160.53.1.el7.x86_64 amd64
> INFO: User cache: /root/.sonar/cache
> INFO: Scanner configuration file: /home/jenkins/agent/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonar-scanner/conf/sonar-scanner.properties
> INFO: Project root configuration file: NONE
> INFO: Analyzing on **SonarQube server 9.2.4**
> INFO: Default locale: "en_US", source code encoding: "US-ASCII" (analysis is platform dependent)
> INFO: Load global settings
> INFO: Load global settings (done) | time=84ms

Removing the _<functionToCover>_ tags manually gets rid of this error.

Attached is an example of the coverage XML report gcovr currently generates
![gcov_coverage](https://user-images.githubusercontent.com/37457648/160621883-063d2998-aadc-4bf4-ad49-39b6b126cdba.png)
.

**Comment by latk** [comment]
The issue should be fixed in the development version. If you want to help test this, please consider installing gcovr from GitHub:

    pip install git+https://github.com/gcovr/gcovr.git
