### ISSUE TITLE
ValueError in gcov_parser.py

### ISSUE THREAD

**Issue by subdiff** [gcovr/gcovr#607]
I'm running gcovr on CI. Since recent update to 5.1 gcovr fails:
```
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 724, in _parse_line
    key, value = source_code.split(":", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```
https://gitlab.com/kwinft/kwinft/-/jobs/2316330009#L2

The command I'm invoking gcovr with is:
```
gcovr -s --xml-pretty --xml coverage-cobertura.xml --html-details coverage-html-output/coverage.html $GCOVR_ARGS -e build -r . build
```

where `$GCOVR_ARGS` is substituted by GitLab with `-e tests`.

Any direct idea what the issue could be? Otherwise I'll try next to reproduce it locally.

**Comment by latk** [comment]
Thank you for reporting this, and for providing all relevant information!

The issues seems to be the same problem as #596. You can fix this by either downgrading to gcovr 5.0, or by installing the gcovr development version until a new version is released.

If you want to pin the current gcovr development version on the master branch, you could install

```bash
pip install git+https://github.com/gcovr/gcovr.git@bfd364e4162c94e2d4536b09771f6acb81e3e210
```

**Comment by subdiff** [comment]
Thanks for the quick reply! I'll try a pipeline with the development version in the evening and report back if this fixed the issue.

**Comment by subdiff** [comment]
With the development version the error is indeed gone: https://gitlab.com/romangg/kwinft/-/jobs/2320175364

I can use the development version until the next bugfix release or I could also ask the Arch maintainer to backport the four commits from the development version. What do you prefer?

**Comment by latk** [comment]
Glad to see that it worked!

> I guess a bugfix release won't be far in the future

I don't want to commit to any timeline. Ideally, I'd like to include additional bugfixes into the next release, but that has to be balanced against the harm done by already-fixed bugs.

If a downstream distributor has different priorities from me that's perfectly fine and they can patch their versions if they want, but gcovr itself only supports `pip install` from PyPI or from this Github project.
