### ISSUE TITLE
Using "search-path" in config file, __main__.py iterates over the individual characters of the path as a list of paths to search

### ISSUE THREAD

**Issue by kkaja123** [gcovr/gcovr#608]
**Describe the bug**
In my config file, I have a single entry for the key "search-path" (e.g. `search-path = build/`). When I try to run gcovr using that configuration, I'll get an OSError for `Unknown directory 'b'`. It looks like it is breaking down the string for the search-path value. I've confirmed this when I tried to set the path to `./build/`. With the verbose output on, you can see gcovr search the path `.`, then move onto the path `/`.

[I've tracked this down to \_\_main\_\_.py where the list of search paths will be built.](https://github.com/gcovr/gcovr/blob/master/gcovr/__main__.py#L352) By default, this is the root path and the objdir. \_\_main\_\_.py expects this option to be a list type. Therefore, it tries to iterate through the list. When a user is setting the options value using the config file, it is set to the options dictionary as a `str`. \_\_main\_\_.py should check to see if `options.search_paths` is a `str` or `list` before trying to use it as a list.

Current code:
```
for search_path in options.search_paths:
    datafiles.update(find_files(search_path, options.exclude_dirs))
```

Suggested change:
```
if isinstance(options.search_paths, str):
  datafiles.update(find_files(options.search_paths, options.exclude_dirs))
else:
    for search_path in options.search_paths:
        datafiles.update(find_files(search_path, options.exclude_dirs))
```

**To Reproduce**
1. Create a config file where the only value for the key `search-path` is a single path (e.g. `build/`).
2. Run gcovr.
3. Observe that an exception is raised (happens pretty quickly).

**Expected behavior**
A user should be able to put in a single search path from the config file. gcovr should detect that only a single path is being used and search only that one path entry.

**Comment by Spacetown** [comment]
Thank you for reporting this bug. I've to take a deeper look. It seems that the configuration parser should treat positional arguments the same way as options with the action append. I'll check this next week.
