### ISSUE TITLE
support Jacoco report

### ISSUE THREAD

**Issue by patown** [gcovr/gcovr#630]
**Is your feature request related to a problem? Please describe.**
So far GCOVR could generate report in Cobertura format. But Jacoco is much more popular now in Java field.
**Describe the solution you'd like**
I hope GCOVR could support Jacoco report besides Cobertura so I can handle C++ coverage info the same as Java in my DevOps platform. 
**Describe alternatives you've considered**

**Additional context**

**Comment by Spacetown** [comment]
I find no documentation of the data format and in the examples it looks like it's tied to java classes and packages. This information isn't available in gcov output format.

**Comment by patown** [comment]
> I find no documentation of the data format and in the examples it looks like it's tied to java classes and packages. This information isn't available in gcov output format.

I used gcovr to generate coverage report in Cobertura format. My idea is that Cobertura xml is almost the equivalent with Jacoco xml,why not gcovr generate coverage report in Jacoco format. I tried to find tools to do the coveration but just found tooks like https://github.com/chirag-ji/Jacotura which covert just covert jacoco report into cobertura but not vice versa.

**Comment by latk** [comment]
The JaCoCo site has a [DTD schema for download](https://www.jacoco.org/jacoco/trunk/coverage/report.dtd). The format looks simple enough. So creating a new report format might be a good first issue. The Cobertura and Sonarqube writers are fairly small and could be used as a template.

**Comment by Spacetown** [comment]
@patown Please can you verify #823 and review the PR?
