### ISSUE TITLE
How to --exclude a file on Win10?

### ISSUE THREAD

**Issue by wqking** [gcovr/gcovr#634]
Win10, gcovr v5.0

There is a `tests/catch.hpp` I want to exclude from the report.  
I tried command,
`gcovr -r ../.. --html --html-details -o coverage.html --exclude tests/catch\.hpp`  
But it doesn't work.  
If I change the last part to `tests/catch.hpp`, or `tests/catch`, it doesn't work too.

How can I exclude that file? Thanks

**Comment by Spacetown** [comment]
Can you post the output with option `--verbose`?

**Comment by wqking** [comment]
I tried `--verbose` and got the problem solved.  
Seems the path in `--exclude` is relative to current working directory, I need to use `--exclude ../catch\.hpp` since catch.hpp is in upper directory. I thought the path in `--exclude` is the file column in the coverage report which is `tests/catch\.hpp`.  
I suggest the document for `--exclude` specifies that the path is relative to current working directory.

**Comment by latk** [comment]
> I suggest the document for `--exclude` specifies that the path is relative to current working directory.

Hmm, the `gcovr --help` message does try to explain this – but it's only mentioned once in the filter section introduction, not separately for each command line flag that uses filters:

> Filter Options:
> Filters decide which files are included in the report. Any filter must match, and no exclude filter must match. A filter is a regular expression that matches a path. Filter paths use forward slashes, even on Windows. If the filter looks like an absolute path it is matched against an absolute path. Otherwise, the filter is matched against a relative path, where that path is relative to the current directory […]

**Comment by wqking** [comment]
> Hmm, the `gcovr --help` message does try to explain this – but it's only mentioned once in the filter section introduction, not separately for each command line flag that uses filters:

Thanks, seems I overlooked it. :-)
