### ISSUE TITLE
Replace writer.html.Lazy with functools.cache

### ISSUE THREAD

**Issue by UlrichEckhardt** [gcovr/gcovr#636]
**Is your feature request related to a problem? Please describe.**

There is no problem that I'm aware of. However, the existing code has two downsides:

- It's reinventing the [wheel](https://docs.python.org/3/library/functools.html#functools.cache) that already comes with Python 3.9. Yes, 3.9 may be more bleeding edge than you want it to.
- The second call to `get_formatter()` will return the previous result, regardless of the given options. This would be fixed.

**Describe the solution you'd like**

```
try:
    from functools import cache
except ImportError:
    # own implementation for Python < 3.9
    ... # existing `Lazy` class renamed to `cache`
```
Then you can replace `@Lazy` with `@cache` and at some point throw out the old code.

**Comment by Spacetown** [comment]
Why shall we change a running system? This can be done when support for 3.7 and 3.8 is dropped. As long as this versions are supported it's easier to use the same solution vor all versions.
