### ISSUE TITLE
gcovr does not work with CMake out-of-source builds

### ISSUE THREAD

**Issue by sakra** [gcovr/gcovr#64]
gcovr is not able to locate source files when doing an out-of-source build with cmake whose build directory is not in the source tree, i.e.:

```
mkdir /home/user/build
cd /home/user/build
cmake /home/user/source/project
make
ctest
```

This will generate the *.gcno and *gcda in target-specific subdirectories of the directory `/home/user/build/CMakeFiles`. Running 

```
gcovr -v -r /home/user/source/project
```

does not locate any coverage data files.

```
gcovr -v --object-directory=/home/user/build/CMakeFiles -r /home/user/source/project
```

does not locate any coverage data files, either.

**Comment by nickbroon** [comment]
Possibly related to #61

**Comment by latk** [comment]
Does this work when you invoke gcovr from within your build directory? Does using the `--verbose` option produce interesting output, e.g. explaining why any files were filtered out? Gcovr should support this use case. But without clear steps to reproduce, I cannot determine the problem.

I am closing this issue for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.
