### ISSUE TITLE
How to rewrite path

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [gcovr/gcovr#641]
Hi,

I'm in context of Gitlab CI and conan to package a C++ project, for which I use sonar-scanner to upload a code quality analysis to SonarQube.
I use gcovr to convert lcov gcda files to cobertura XML format.
My issue is that sonar-scanner must be called in context of git clone but conan make the cmake build in context of its cache.
And generally with CMake, build is done by convention in another directory than source.
Consequently sonar-scanner will skip the coverage reports because it can't match filename of coverage corbertura report with source files in my git clone:

```
WARN: Cannot find the file 'build/Debug/src/tsl/CMakeFiles/StkCptTslServer.dir/src/interfaces/TslTypes.h' in project 'TslServer' with baseDir '/builds/stk/tablesetuplibrary/tslServer', skipping
```

A workaround could be to have an option to gcovr to rewrite package and filename XML tags of cobertura reports.
What do you think of that?

Regards.

**Comment by latk** [comment]
Could you explain a bit more about your directory structure and project structure? I'm not deeply familiar with CMake or Conan, so I'm confused why there's a source file within your build directory. If this is an autogenerated file, do you want it to be excluded from coverage?

More generally, gcovr cannot support any combination of tools. In some niche scenarios, it may be necessary to post-process the output. For example, you could write a script to adjust the paths in the XML file. If JSON is easier for you to work with, you could modify gcovr's internal JSON format – see [*Merging Coverage Data* in the gcovr manual](https://gcovr.com/en/5.1/guide/merging.html), even though you'd only have one JSON file.
