### ISSUE TITLE
Gcovr fails with: This is indicative of a gcov output parse error.

### ISSUE THREAD

**Issue by mmmtastymmm** [gcovr/gcovr#643]
- Command: `gcovr -s --exclude-unreachable-branches --exclude-throw-branches --sonarqube cpp_coverage_sonarqube.xml -f <src dir 1>-f <src dir 2> -r .`
- Src dir 1 has the includes, and src dir 2 has the source files, and it is a cmake project.
- gcovr version: 5.1
- compiler: GCC 11.2.1
- OS: NAME="Red Hat Enterprise Linux" VERSION="8.6 (Ootpa)"
- The error produced was the following: 
`(WARNING) Unrecognized GCOV output for <file>
	  branch  1 taken -3
	  branch  2 taken -1 (fallthrough)
	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <https://github.com/gcovr/gcovr/issues>.
	`
and gcovr 5.0 doesn't produce this error.

**Comment by Spacetown** [comment]
This is a gcov error already discussed in #583. This error can be ignored as described in https://github.com/gcovr/gcovr/issues/583#issuecomment-1080352048.
