### ISSUE TITLE
Method level coverage in the xml generated

### ISSUE THREAD

**Issue by ybagarka1** [gcovr/gcovr#654]
Issue:

The xml file generated from gcovr is not having method/function level coverage.

```
<class branch-rate="0.285714285714" complexity="0.0" filename="src/absc/mno/xyz/ahgs.cpp" line-rate="0.231481481481" name="os_clib_hxx">
<methods/>
<lines>
<line branch="false" hits="0" number="200"/>
<line branch="false" hits="0" number="202"/>
<line branch="false" hits="3" number="208"/>
<line branch="false" hits="3" number="210"/>
<line branch="false" hits="63" number="213"/>
<line branch="true" condition-coverage="50% (1/2)" hits="63" number="215">
<conditions>
<condition coverage="50%" number="0" type="jump"/>
</conditions>
</line>
<line branch="false" hits="0" number="218"/>
.........
..........
```

Expected:

Function level coverage to be visible in xml

**Comment by ybagarka1** [comment]
@Spacetown thanks for considering this in the upcoming release. It will be a good enhancement to have. Any timelines for the upcoming release ?

**Comment by Spacetown** [comment]
No timeline yet. 😄

**Comment by ybagarka1** [comment]
@Spacetown https://github.com/gcovr/gcovr/pull/655 - this did the trick. I am able to view the method level in the xml.

**Comment by Spacetown** [comment]
@ybagarka1 But are the values correct?
@latk What do you think about the code to get the lines which belong to a function? I was thinking about adding this functionality to `coverage.py`.  A function like
```python
def split functions(data: FileCoverage) -> List(FileCoverage):
```

**Comment by latk** [comment]
@Spacetown I think that runs into the problems of nested functions, as outlined in my PR review. In addition to the nested function concern, I'm also not sure how that would deal with static initialization:

```c
int foo() { ... }

int variable = initialization_function();
```

I think we remove compiler-generated functions like initializers/“constructors”, which would stand in the way of proper attribution of lines to functions.

**Comment by Spacetown** [comment]
As mentioned in #655 this is not possible yet.

**Comment by Spacetown** [comment]
The data model now contains the branch rate stated by gcov but since the line rate is also required it's still not possible.
