### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by usinelogicielle** [gcovr/gcovr#659]
Hello,

I'm trying to find the official docker gcovr image.
If the image exists, Is it possible to write it in the README?

**Comment by Spacetown** [comment]
We use Docker only for development. There is no image for Usinger gcovr.

Do you expect an image containing also the compiler?

**Comment by usinelogicielle** [comment]
Not really,

I tried to install with pip on python:3.8.4-alpine3.12 but have an error because I didn't install libxml2.
But the install works with python:3.8.4-slim-buster so it's good for me if you want to close the issue. You can.

**Comment by latk** [comment]
To add a bit more background:

No official Docker image exists. The [only supported installation](https://gcovr.com/en/stable/installation.html)  is via PIP, the Python package manager: `pip install gcovr`.

A fundamental problem with containerizing gcovr would be that gcovr must call the `gcov` tool provided by your exact compiler version. For example, if you use GCC-9, gcovr needs GCC 9's `gcov`. But containers can't access external programs. We don't want to maintain one image for each supported compiler version.

Of course, you can build Docker images easily yourself that includes both gcovr and your compiler. For example, a Debian- or Ubuntu-based image might include:

```Dockerfile
# install Python and your GCC version
RUN apt-get install -y python3.10 gcc-9 && apt-get clean
# install gcovr
RUN pip install gcovr==5.2
# tell gcovr to use the GCC-9 gcov
ENV GCOV=gcov-9

WORKDIR /myproject
```

Then, the container can be used as ``docker run --rm -it -v `pwd`:/myproject my-gcovr-container gcovr OPTIONS``
