### ISSUE TITLE
How to generate function coverage in html report？

### ISSUE THREAD

**Issue by yefen123** [gcovr/gcovr#660]
Hi, Mrs/Mr
I want to get function coverage in html report， but only branches coverage and lines coverage are generated in html report
Which parameter should we use？
BR//Fen

**Comment by latk** [comment]
If you have gcovr 5.1 or better, the HTML report should automatically include function coverage information. You can see example reports in the [*HTML Output* chapter of the gcovr User Guide](https://gcovr.com/en/5.2/output/html.html).

* On the HTML summary page, function coverage across the entire project and for each file is shown.
* If you enabled HTML-Details, the summary page contains a link to a page with a list of all functions in your project.
* If you enabled HTML-Details, you get one page for each source code file. The total function coverage for that file is shown at the top. There is also an expandable list of functions in that file.

So in principle, `gcovr OTHER_OPTIONS --html report.html` or `gcovr OTHER_OPTIONS --html-details report.html` should just work to see function coverage information.

If you have an older gcovr version (for example if you installed via a Linux package manager), then you can install an up to date version via the Python pip package manager. See our [installation guide](https://gcovr.com/en/stable/installation.html).

**Comment by yefen123** [comment]
My gcovr version is 4.2, so I should update the version.
thank you very much.

**Comment by yefen123** [comment]
> If you have gcovr 5.1 or better, the HTML report should automatically include function coverage information. You can see example reports in the [_HTML Output_ chapter of the gcovr User Guide](https://gcovr.com/en/5.2/output/html.html).
> 
> * On the HTML summary page, function coverage across the entire project and for each file is shown.
> * If you enabled HTML-Details, the summary page contains a link to a page with a list of all functions in your project.
> * If you enabled HTML-Details, you get one page for each source code file. The total function coverage for that file is shown at the top. There is also an expandable list of functions in that file.
> 
> So in principle, `gcovr OTHER_OPTIONS --html report.html` or `gcovr OTHER_OPTIONS --html-details report.html` should just work to see function coverage information.
> 
> If you have an older gcovr version (for example if you installed via a Linux package manager), then you can install an up to date version via the Python pip package manager. See our [installation guide](https://gcovr.com/en/stable/installation.html).

Hi,
I updated my gcovr version from 4.2 to 5.2 recently. I found some differences：
1）the report name of each file has changed：
     **before**：include file path
![image](https://user-images.githubusercontent.com/111563279/189065785-c06b4ae7-d8a1-4c31-bd1f-592b6d71ff4d.png)

     **after**：not include file path， but inlude sha value.
![1662623118552](https://user-images.githubusercontent.com/111563279/189065163-8e480e95-3b9d-42a6-9067-abb33d964004.png)
 Is there any method to generate a report name according to the file path，not sha value？

**Comment by Spacetown** [comment]
Please don't use screenshots, add the text verbatim.
It's MD5 and not SHA, there is no way to change this. This was introduced with #375 to have OS independent filenames.

**Comment by yefen123** [comment]
OK, thanks.

**Comment by Spacetown** [comment]
Please close the issue if the report contains the expected data.
