### ISSUE TITLE
coverage report shows inline method at *.h as untested althought it was tested multiple times

### ISSUE THREAD

**Issue by yefen123** [gcovr/gcovr#667]
**Describe the bug**
coverage report shows inline method at *.h as untested althought it was tested multiple times

**Expected behavior**
I wrote a methon in .h file, it shows as untested althought it was tested multiple times
But if I mv the method to .cc file, It showes as tested

**Screenshots**
![1662098868154](https://user-images.githubusercontent.com/111563279/188071706-030b4c04-78bc-42a2-b065-6882aeac0db5.jpg)

**Desktop (please complete the following information):**
 - OS:**redhat**
 - GCC version **10.3.0**
 - GCOVR version **5.2**
 - Project directory layout:
   - Object directories

**Comment by Spacetown** [comment]
Where all cc files which use the function compiled with `--coverage`?

**Comment by yefen123** [comment]
> Where all cc files which use the function compiled with `--coverage`?



> Where all cc files which use the function compiled with `--coverage`?

Sorry，I don't get it. see more detal below:

**Comment by yefen123** [comment]
![1662107664166](https://user-images.githubusercontent.com/111563279/188102112-9862128f-1244-4c46-8cdd-62c7b5641980.jpg)

**Comment by latk** [comment]
Possible causes I can think of:

* The header file is in a different directory, which is excluded by gcovr filters.
  * From which directory are you running gcovr and with which options?
* The compilation unit(s) which include the header have not been compiled with `--coverage`.
  * To check this, see if the lines that call this function are also marked as covered.
* You have violated the C++ One Definition Rule which could mess up accounting for coverage metrics.
  * But this looks like an inline member function definition so that should be fine.

**Comment by Spacetown** [comment]
> * The compilation unit(s) which include the header have not been compiled with `--coverage`.
>   
>   * To check this, see if the lines that call this function are also marked as covered
 That was my intention. Is the unit test also compiled with `--coverage`?

**Comment by yefen123** [comment]
> Possible causes I can think of:
> 
> * The header file is in a different directory, which is excluded by gcovr filters.
>   
>   * From which directory are you running gcovr and with which options?
**My code directory is repo/sw/*， I run gcovr in repo/.**
options:
![image](https://user-images.githubusercontent.com/111563279/188132253-8ec03347-cb46-4811-a7b5-ca0df8d36fad.png)

> * The compilation unit(s) which include the header have not been compiled with `--coverage`.
>   
>   * To check this, see if the lines that call this function are also marked as covered.
**In the same file, Other lines are marked as covered**
![1662118922900](https://user-images.githubusercontent.com/111563279/188132424-4ab7150c-55fe-4fa0-9f69-e0764d5dce72.jpg)


> * You have violated the C++ One Definition Rule which could mess up accounting for coverage metrics.
>   
>   * But this looks like an inline member function definition so that should be fine.

**Comment by yefen123** [comment]
> 

**I compile units with "-fprofile-arcs -ftest-coverage"**
![Uploading 1662119920218.png…]()

**Comment by latk** [comment]
Could you please edit your comments to replace the screenshots with text? Images are hard for me to read, and prevent others from finding relevant information in the future via the search function.

**Comment by Spacetown** [comment]
Same for me.
In the comand line you exclude everything from unit test directory. Are the missing functions only called from the unit test? Can you call for testing purpose a uncovered function from a covered one?

**Comment by yefen123** [comment]
I edited it manually because I can't copy it.

_sw/backend/inc/infoBbjListIf.h_
bool isMatchingType（InfoObjType type） const
const std::set<TagName> & getTagNames() const
as show as redish(untested)

Both of them are tested by unit test:
_sw/backend/unittest/radiaDateColl/infoObjListImplTest.cc_

ASSERT_EQ(io1.getInfoObject("carrier_txpower").**getTagNames**()), std::set<TagName>({"TXPOWER"}));
ASSERT_EQ(io1.getInfoObject("carrier_rxpower").**getTagNames**()), std::set<TagName>({"RXPOWER"}));
ASSERT_EQ(io1.getInfoObject("mcb_rxpower").**getTagNames**()), std::set<TagName>({"RXPOWER"});
EXPECT_TRUE(io1.getInfoObject("carrier_txpower").**isMatchingType**(Rdc::Backend::InfoObjectType::MEASUREMENT));
EXPECT_TRUE(io1.getInfoObject("carrier_rxpower").**isMatchingType**(Rdc::Backend::InfoObjectType::MEASUREMENT));
EXPECT_TRUE(io1.getInfoObject("mcb_rxpower").**isMatchingType**(Rdc::Backend::InfoObjectType::MEASUREMENT));

Both methods are implemented at _infoBbjListIf.h_(so "**inline**"), if move their implementation to
_sw/backend/src/infoObjListImplIf.cc_
(so **not "inline"**), the unit test coverage shows them as tested, and both _infoObjListImplIf.cc_, and _infoBbjListIf.h_ show more than 90%.

And all the methods at _infoBbjListIf.h_ are inline and showen as tested, but only these two are shown as not tested

**Comment by Spacetown** [comment]
I guess the covered functions are called from ``

**Comment by Spacetown** [comment]
@latk I think, we should create a test to show this behaviour. What do you think?

**Comment by yefen123** [comment]
> I guess the covered functions are called from `infoObjListImplIf.cc` or from another file which isn't excluded. Can you check this?

the covered functions are called from _sw/backend/src/radiaDateColl.cc_

**Comment by Spacetown** [comment]
And the uncovered functions are only called from the unittest?

**Comment by yefen123** [comment]
> > I guess the covered functions are called from `infoObjListImplIf.cc` or from another file which isn't excluded. Can you check this?
> 
> the covered functions are called from _sw/backend/src/radiaDateColl.cc_

**correct:** the uncovered function _isMatchingType_ is called from _sw/backend/src/radiaDateColl.cc_
and tested by _sw/backend/unittest/radiaDateColl/infoObjListImplTest.cc_

**Comment by yefen123** [comment]
> > > I guess the covered functions are called from `infoObjListImplIf.cc` or from another file which isn't excluded. Can you check this?
> > 
> > 
> > the covered functions are called from _sw/backend/src/radiaDateColl.cc_
> 
> **correct:** the uncovered function _isMatchingType_ is called from _sw/backend/src/radiaDateColl.cc_ and tested by _sw/backend/unittest/radiaDateColl/infoObjListImplTest.cc_

The covered function _isSubset_ at infoBbjListIf.h is inline and called by _sw/backend/src/radiaDateColl.cc_ (the same with _isMatchingType_  , but not called from unnitest) and showen as tested

sorry, I have no permission to copy text, see screenshoot:
![1662372367509](https://user-images.githubusercontent.com/111563279/188424432-b597693e-7721-4f4f-9575-88c50bd6af3d.jpg)

![1662372428320](https://user-images.githubusercontent.com/111563279/188424485-92f6b4a3-e700-4412-b0e6-7c9cb9782ff6.jpg)

![1662372428320](https://user-images.githubusercontent.com/111563279/188424634-c7a03be6-6405-4526-9a9a-89b66295849f.jpg)

**Comment by Spacetown** [comment]
> **correct:** the uncovered function _isMatchingType_ is called from _sw/backend/src/radiaDateColl.cc_ and tested by _sw/backend/unittest/radiaDateColl/infoObjListImplTest.cc_

Can you show the report from the line where _isMatchingType_ is called?

What permission is needed to copy text? Copy from the editor and paste to the input field doesn't need a permission.

**Comment by yefen123** [comment]
Internal documents can't be copied outside.

 _sw/backend/src/radiaDateColl.cc_ **report**:
![image](https://user-images.githubusercontent.com/111563279/188449742-45351ed8-bc4e-45b2-a7a3-ae12fdeda083.png)

**Comment by Spacetown** [comment]
Can you comment out the unittests for the two functions and run the test again? Is the function also uncovered in this case?

**Comment by yefen123** [comment]
> 

Yes. I've tested it.

**Comment by Spacetown** [comment]
Can you inspect the gcov output files (option `--keep`) for the counters? From the description and screenshots I don't see a problem in gcovr.

**Comment by Spacetown** [comment]
I thought that the function isn't inlined and the first implementation is used which isn't with active coverage.

**Comment by farshid616** [comment]
I have the same issue.

I have some functions that are defined and implemented inside .h file. They're calling by test functions. When I checked the coverage result, it showed that these functions are not called, but when I moved the function body to .cpp file, the coverage result changed to the covered state.

**Note:**
- My .h and .cpp file are next to each other in the same directory
- I'm using exclude option for my test directory
- I'm using --coverage and -o0 for whole project

When I'm running gcovr without exclude option, it is showing functions inside .h file is covered.
**It seems a bug to me because test folder should not be counted as project coverage and when I'm trying to exclude it, gcovr is not able to detect header functions anymore.**

**Comment by Spacetown** [comment]
@farshid616 Can you post your command line?

**Comment by farshid616** [comment]
In the root of project directory:

- gcovr -r .  --exclude-directories build/private/src/gtest/
- gcovr --html  --exclude-directories build/private/src/gtest/

When I'm using --filter instead of --exclude result is empty.

**Comment by Spacetown** [comment]
> * gcovr -r .  --exclude-directories build/private/src/gtest/

Can you try `gcovr -r .  --exclude build/private/src/gtest/.*`?

**Comment by farshid616** [comment]
I tried, and it's not excluding gtest anymore.

**Comment by Spacetown** [comment]
Can you run with `--verbose` and check the filters?

**Comment by Spacetown** [comment]
Ok, you should change the filter to match the src directory and not the build directory.

**Comment by Spacetown** [comment]
@yefen123 Does your problem still occur?

**Comment by Spacetown** [comment]
Closing because of no response. Please reopen if problem still exists.
