### ISSUE TITLE
Function coverage not seen by cobertura plugin in jenkins

### ISSUE THREAD

**Issue by bmzztt** [gcovr/gcovr#670]
**Describe the bug**
Cobertura plugin in jenkins does not show function coverage based on xml created from gcovr 5.2.
I am aware that this may be a bug in cobertura plugin. Or just an interface issue between xml from gcovr and the expected xml.
For instance gcovr uses the word "function" and cobertura "method". 
Unfortunately I havent found a description of how a cobertura xml shall be.

**To Reproduce**
1. call gcovr --cobertura
2. pass the generated file to cobertura

**Expected behavior**
Cobertura is able to show function coverage

**Screenshots**
![cobertura_func_cov](https://user-images.githubusercontent.com/65807521/189345517-06b252b1-7947-4f95-b998-136d20384c2b.png)

**Desktop (please complete the following information):**
 - OS: windows
 - GCOVR 5.2
- Cobertura 1.17

**Additional context**

**Comment by Spacetown** [comment]
It seems, that the function coverage values where added with #362 the same way as branch and line coverage. According to the [DTD](http://cobertura.sourceforge.net/xml/coverage-04.dtd) this was wrong.
I'll fix this.

**Comment by Spacetown** [comment]
I remove the wrong attributes from the XML. The methods can't be added, see #655 for more info.

**Comment by Spacetown** [comment]
Duplicate #654

**Comment by bmzztt** [comment]
Hi @Spacetown , thanks for the fast response and for trying :)
