### ISSUE TITLE
Some versions of gcov assume relative path when --object-directory is used

### ISSUE THREAD

**Issue by sebastianraizer** [gcovr/gcovr#672]
**Describe the bug**
On windows, GCOVR always calls gcov with absolute path of gcda file and --object-directory parameter. The cygwin version of gcov assumes that the gcda path is relative and always appends the --object-directory parameter. This leads to it not finding the files.

**To Reproduce**
1. Compile/instrument and execute a program with gcc on cygwin
2. run GCOVR with no argument in the directory where the c/gcda/gcno files are

**Expected behavior**
GCOVR should work in this case, even if gcov is buggy. There should be at least one option to remove the --object-directory parameter when calling gcov, or to keep the gcda file path relative.

**Screenshots**
```
(DEBUG) Running gcov: 'gcov C:\Temp\test_gcovr\hello.gcda --branch-counts --branch-probabilities --d
emangled-names --hash-filenames --object-directory C:\Temp\test_gcovr' in 'C:\Temp\test_gcovr'
(DEBUG) Gathered coveraged data for 0 files
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
------------------------------------------------------------------------------
TOTAL                                          0       0    --%
------------------------------------------------------------------------------
```
```
$ gcov C:\\Temp\\test_gcovr\\hello.gcda --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory C:\\Temp\\test_gcovr
C:\Temp\test_gcovr/C:\Temp\test_gcovr\hello.gcno:cannot open notes file
C:\Temp\test_gcovr/C:\Temp\test_gcovr\hello.gcda:cannot open data file, assuming not executed
$ gcov C:\\Temp\\test_gcovr\\hello.gcda --branch-counts --branch-probabilities --demangled-names --hash-filenames
File 'hello.c'
Lines executed:77.78% of 9
Branches executed:100.00% of 2
Taken at least once:50.00% of 2
Calls executed:66.67% of 3
Creating 'hello.c##0fba0eab2c0a1c0fdea332d6efaeae74.gcov'
```

**Desktop (please complete the following information):**
 - OS: windows
 - GCC version: cygwin gcc (GCC) 10.2.0 and 11.3.0
 - GCOVR version: 5.2
 - Project directory layout: C:\Temp\test_gcovr

**Additional context**

**Comment by Spacetown** [comment]
For Windows the best way is to use MinGW.

As mentioned in https://github.com/gcovr/gcovr/issues/501#issuecomment-882108408 the use of Windows paths in Cygwin is inadvisable. We use the OS specific paths and do not handle paths in a special way for cygwin.

We're running gcov in different directories. Maybe the option isn't needed if the working directory is the same.

**Comment by sebastianraizer** [comment]
Thanks for your reply. The problem is not about Cygwin. I can reproduce it in MinGW. The problem is that the version of gcov delivered with Cygwin is always appending the --object-directory path in front of the .gcda file, even if this file is already absolute path. This is kind of a buggy behavior of gcov and I think gcovr should have a workaround for it. I can see 2 ways to handle this issue:
1. have an option to call gcov with relative path instead of absolute
2. have an option to not use the --object-directory when calling gcov. I think the --object-directory parameter should not be passed to gcov if it's not passed in the call of gcovr
Currently gcovr is not usable with that version of gcov.

**Comment by sebastianraizer** [comment]
btw, gcovr is suppressing the error output of gcov, which makes it hard to debug any integration issue with gcov. I did not see a way to show the error directly and I have to copy-paste the gcov command generated by gcovr in order to see the error message. I think in verbose mode, gcovr should not suppress the output of gcov. I might create another ticket for this.

**Comment by Spacetown** [comment]
> Thanks for your reply. The problem is not about Cygwin. I can reproduce it in MinGW. The problem is that the version of gcov delivered with Cygwin is always appending the --object-directory path in front of the .gcda file, even if this file is already absolute path. This is kind of a buggy behavior of gcov and I think gcovr should have a workaround for it....

We use os specific patho routines for path handling but cygwin doesn't use. `C:\temp` is in cygwin `/cygdrive/c/temp` or `tmp`. In your example above we call gcov with `C:\\Temp\\test_gcovr\\hello.gcda` which is a correct windows path.

On the master branch the error handling is improved, can you check it with this version?

**Comment by Spacetown** [comment]
@sebastianraizer Where you able to verify the issue with the master branch?

**Comment by Spacetown** [comment]
@sebastianraizer Please can you check the branch of the liked PR?
