### ISSUE TITLE
gcovr5.2 stays stuck

### ISSUE THREAD

**Issue by yefen123** [gcovr/gcovr#673]
**When I excute gcovr command, logs as follow:**

executing:time gcovr -r/repo .--exclude '.*/unitTest/.*' -exclude-directories '.*/unitTest.*' --exclude-throw-branches -exclude-unreachable-branches --gcov-executable app/RHEL7-x86_64/gcc/10.3.0/bin/gcov-j 8--html--html-details -o coverage.html 
(ERROR) Trouble processing'/repo/radioswci/coverage_dir/sw/drv/dl/src/testInitializer-dlFilterEngineSrcImpl.gcda' with working directory 
Stdout of gcov was>>File '/repo/radioswci/dfe/sw/drv/dl/src/dlFilterEngineSrcImpl.cc'
Lines executed:2.40% of 292 
Branches executed:2.58% of 466 
Taken at least once:1.29% of 466 
Calls executed:2.63% of 380
Creating 'dlFilterEngineSrcImpl.cc##787d9550729fffdf4f08cd3e9c5ab75a.gcov'

File '/repo/radioswci/coverage_dir/sw/unitTest/generated/krypton/inc/registerBlock/D1FbUc.h' 
No executable lines
No branches
No calls
Removing 'D1FbUc.h##d06b338430cb9f8ab7a14591f5f516b3.gcov'

File'/afs/sero.gic.ericsson.se/app/vbui1d/RHEL7-x86_64/gcc/10.3.0/include/c++/10.3.0/new' Lines executed:0.00% of 3
No branches
No calls
Creating 'new##lac56069d705793b2479ee92f58d172b.gcov' 

<<End of stdout
Stderr of gcov was>><< End of stderr

Current processed gcov file was'/repo/radioswci/dfe/dlFi1terEngineSrcImp1.cc##787d9550729fffdf4f08cd3e9c5ab75a.gcov'. 
Use option--verbose to get extended informations.

**Then gcovr dosen't exit and dosen't print other logs, just stays stuck.
Before updating to gcovr 5.2, We use gcovr 4.2 which works normally.**

**Comment by latk** [comment]
Does the issue persist if you remove the `-j 8` option? This option doesn't make gcovr any faster in most cases, but has led to similar bugs in the past.

**Comment by yefen123** [comment]
I remove the -j 8 option and the same problem still exists.

**Comment by Spacetown** [comment]
Did you truncate the error? There is some text missing, see:
https://github.com/gcovr/gcovr/blob/398aaff4c0d7fb6c445e6742627570d5bedd251f/gcovr/gcov.py#L517-L523

**Comment by yefen123** [comment]
Stderr of gcov was >><< End of stderr, the error log shows null, I have no idea why it gets into the exception.

**Comment by Spacetown** [comment]
> Stderr of gcov was >><< End of stderr, the error log shows null, I have no idea why it gets into the exception.

That was the part I'm interested in. Can you try the mentioned option `--verbose`?

**Comment by eefienw** [comment]
I have tried with the --verbose, the stderr still null.
<img width="545" alt="Capture" src="https://user-images.githubusercontent.com/54132659/191171926-5ec29a63-0f82-4c89-817f-7a836d9e7622.PNG">

**Comment by eefienw** [comment]
and the weird thing is the gcov.py seems to be stuck in "Use option--verbose to get extended informations.". It was supposed to execute "raise" in line 524 and exit the script with error, but it seems not. We need to execute "Ctrl +Z" to kill it.
and one more question, we have used the -exclude-directories '.*/unitTest.*', why it still collect the coverage data for files under unitTest directory?

**Comment by eefienw** [comment]
Could somebody help check this issue? The err is null so that we have no idea about why it failed to process this gcov file.
I tried to add some print message in the gcov.py, but still don't know why it goes into the except. 

By the way, we can use the gcovr 4.2 to generate the coverage report for the same code, but failed with gcovr 5.2.

**Comment by yefen123** [comment]
**I mean when I remove -j8， gcovr doesn't stay stuck, but show error log as follow:**

(ERROR) Uncaught EXCEPTION

Traceback (most recent call last):

File "/proj/crbs/zyexfen/virtual_env/bin/gcovr", line 11, in <module> sys.exit(main())

File"/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/_main_.py", line 317, in main covdata = collect_coverage_from_gcov(options)

File "/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/_main_.py", line 376, in collect_coverage_from_gcov contexts=pool.wait()

File "/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/workers.py", line 171, in_exit self.wait()

File "/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/workers.py", line 162, in wait raise self.exceptions[0][1]

File"/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/_main_.py", line 376, in collect_coverage_from_gcov contexts=pool.wait()

File"/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/workers.py", line 162, in wait raise self.exceptions[0][1]

File"/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/workers.py", line 78, in worker work(*args,**kwargs)

File "/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/gcov.py", line 343, in process_datafile chdir=wd,

File "/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/gcov.py", line 513, in run_gcov and process_files process gcov data(fname, covdata, abs filename, options)

File "/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/gcov.py", line 165, in process_gcov_data insert file coverage(covdata,coverage)

File"/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/merging.py", line 159, in insert_file_coverage return _insert_coverage_item(target, file.filename, file, merge_file, options)

File "/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/merging.py",line 135, in_insert_coverage_item merged item = merge item(target dict[key], new item, options)

File"/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/merging.py", line 179, in merge_file left.functions, right.functions, merge function, options

File"/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/merging.py", line 99, in_merge_dict insert_coverage_item(left, key, right _item, merge_item, options)

File "/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/merging.py", line 135, in_insert_coverage_item merged_item = merge_item(target_dict[key], new_item, options)

File"/proj/crbs/zyexfen/virtual_env/lib/python3.7/site-packages/gcovr/merging·py", line 268, in merge_function assert left.lineno ==right.lineno

AssertionError

**Comment by Spacetown** [comment]
@latk Is it possible, that the directory lock isn't exception save?
https://github.com/gcovr/gcovr/blob/398aaff4c0d7fb6c445e6742627570d5bedd251f/gcovr/gcov.py#L485

I mean, is the lock removed if an exception is raised or do the other threads still waiting?
