### ISSUE TITLE
--object-directory is not able to set related to gcno/gcda files

### ISSUE THREAD

**Issue by xeniumlee** [gcovr/gcovr#674]
**Describe the bug**
`--object-directory` is an option with type `relative_path`, which is set to a path related to `os.getcwd()` after processed.
https://github.com/gcovr/gcovr/blob/b5103e14adc6b73caa90df3876902ba9fc9f3bac/gcovr/configuration.py#L85

But in `find_potential_working_directories_via_objdir`:
https://github.com/gcovr/gcovr/blob/b5103e14adc6b73caa90df3876902ba9fc9f3bac/gcovr/gcov.py#L373
It's not possible to match `os.path.dirname(abs_filename)` which is the dir holding gcno/gcda files.

**Comment by Spacetown** [comment]
Sorry, I don't get your point. Di you have an error message which shows your Problem?

**Comment by xeniumlee** [comment]
```
project
- module-a
  - src
  - build
    (obj, gcno/gcda)
- module-b
  - src
  - build
    (obj, gcno/gcda)
```
How to set `--object-directory` to the `build` dir?

**Comment by Spacetown** [comment]
Never saw such a structure. I would recommend to not set `--object-directory` and call `gcovr` from your working directory of your build.

**Comment by Spacetown** [comment]
@xeniumlee Was this the solution?
