### ISSUE TITLE
`--exclude-lines-by-pattern` can be specified multiple times, but only last pattern is used

### ISSUE THREAD

**Issue by h-2** [gcovr/gcovr#675]
**Describe the bug**
It is possible to specify `--exclude-lines-by-pattern` multiple time, but all patterns except the last are ignored.

**To Reproduce**
1. specify multiple `--exclude-lines-by-pattern`

**Expected behavior**
All patterns except the last are ignored.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - GCC version: 11
 - GCOVR version: 5.0

**Comment by latk** [comment]
The option is intended to *override* Gcovr's default exclusion pattern. This may be used to add more patterns, but also to disable the existing pattern. It is a normal command line interface convention that the “last one wins”.

Since the pattern is a [Python-flavoured](https://docs.python.org/3/library/re.html#regular-expression-syntax) regex, you can combine multiple patterns for this option, e.g.

```bash
gcovr --exclude-lines-by-pattern 'PATTERN1|PATTERN2|PATTERN3|...'
```

(Yes, I know this is annoying for scripting, or for “inheriting” defaults from a config file. But it's difficult to change the CLI in a backwards-compatible manner here, or to add a warning. I'm also worried that looping through a list of patterns could slow down exclusion processing.)

**Comment by h-2** [comment]
>  It is a normal command line interface convention that the “last one wins”.

While this is true in general, it is not true for other options of gcovr. The CMake file I inherited came with multiple `--filter` s set and multiple `--exclude-lines-by-pattern`.  Since I knew that all filter directories were parsed, it seemed obvious that options in general can be specified multiple times for gcovr––especially since providing multiple patterns seems like a valid use-case.

> Yes, I know this is annoying for scripting, or for “inheriting” defaults from a config file.

Indeed...

>  But it's difficult to change the CLI in a backwards-compatible manner here, or to add a warning.

You could always add a differently named option and deprecate the existing one. Or add this to a TODO list for the next major release or so... but that's of course up to you.

> I'm also worried that looping through a list of patterns could slow down exclusion processing.

You can combine the patterns into one pattern and evaluate that instead of looping.

**Comment by Spacetown** [comment]
> While this is true in general, it is not true for other options of gcovr. The CMake file I inherited came with multiple `--filter` s set and multiple `--exclude-lines-by-pattern`. Since I knew that all filter directories were parsed, it seemed obvious that options in general can be specified multiple times for gcovr––especially since providing multiple patterns seems like a valid use-case.

Is it forbidden to have both option types in the same script?

> You could always add a differently named option and deprecate the existing one. Or add this to a TODO list for the next major release or so... but that's of course up to you.

Many user who are using the existing options will need to update the commands. If they are only called in a CI the deprecation warning isn't seen. The build will fail if the option is removed.
 
> You can combine the patterns into one pattern and evaluate that instead of looping.

That's not possible, back references in the RegEx won't work. E.g. `--exclude-lines-by-pattern '(foo)bar\1' --exclude-lines-by-pattern '(bar)foo\1'` will result in `(?:(foo)bar\1|(bar)foo\1)` but the back reference in the second RegEx should be changed to `\2`. Also overriding values (some project can depend on this) won't work anymore.

As @latk pointed out, this is the intended behavior.
