### ISSUE TITLE
Branches of unknown origin

### ISSUE THREAD

**Issue by h-2** [gcovr/gcovr#677]
![image](https://user-images.githubusercontent.com/2996863/193807896-5de4c18c-803c-4f2c-a900-c4424b12ae2c.png)

What is happening here, i.e. where are all those branches coming from? Shouldn't there be only one branching point in line 31/32?

**Comment by latk** [comment]
The coverage data available to gcovr/gcov considers assembly-level branches, not source code level branches. C++ code tends to have tons of compiler-generated branches, in particular for exception handling. You're invoking a lot of constructors and destructors on those lines, and they might all fail. It is generally impossible to achieve 100% branch coverage on C++ code.

For details, see the FAQ entry [Why does C++ code have so many uncovered branches?](https://gcovr.com/en/master/faq.html#why-does-c-code-have-so-many-uncovered-branches)

Gcovr has a couple of options to remove unwanted branches, such as

* `--exclude-throw-branches`
* `--decisions` (calculates a separate metric that can be more interpretable than branch coverage, but is known to have a ton of bugs)

**Comment by h-2** [comment]
Thanks for the explanation :+1:

**Comment by Spacetown** [comment]
Can you run with options `--verbose --keep` and post the part of the gcov file for this line?

**Comment by h-2** [comment]
> Can you run with options --verbose --keep and post the part of the gcov file for this line?

Thanks for following up. Do you mean this:

```
        -:   25://!\brief An exception typically thrown by bio::alphabet::assign_char_strict.
        -:   26:struct invalid_char_assignment : std::runtime_error
        -:   27:{
        -:   28:    //!\brief Constructor that takes the type name and the failed character as arguments.
function _ZN3bio8alphabet23invalid_char_assignmentC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEc called 0 returned 0% blocks executed 0%
    #####:   29:    invalid_char_assignment(std::string const & type_name, char const wrong_char) :
    #####:   30:      std::runtime_error{std::string{"Assigning "} +
call    0 never executed
call    1 never executed
branch  2 never executed
branch  3 never executed
call    4 never executed
branch  5 never executed
branch  6 never executed
call    7 never executed
call    8 never executed
call    9 never executed
call   10 never executed
call   11 never executed
    #####:   31:                         (std::isprint(wrong_char) ? std::string("\"") + std::string(1, wrong_char) + "\""
call    0 never executed
call    1 never executed
branch  2 never executed
branch  3 never executed
call    4 never executed
call    5 never executed
branch  6 never executed
branch  7 never executed
call    8 never executed
branch  9 never executed
branch 10 never executed
call   11 never executed
branch 12 never executed
branch 13 never executed
call   14 never executed
branch 15 never executed
branch 16 never executed
call   17 never executed
branch 18 never executed
branch 19 never executed
call   20 never executed
branch 21 never executed
branch 22 never executed
call   23 never executed
branch 24 never executed
branch 25 never executed
call   26 never executed
branch 27 never executed
branch 28 never executed
call   29 never executed
branch 30 never executed
branch 31 never executed
call   32 never executed
call   33 never executed
branch 34 never executed
branch 35 never executed
call   36 never executed
branch 37 never executed
branch 38 never executed
call   39 never executed
branch 40 never executed
branch 41 never executed
call   42 never executed
branch 43 never executed
branch 44 never executed
call   45 never executed
branch 46 never executed
branch 47 never executed
call   48 never executed
    #####:   32:                                                   : std::to_string((int)wrong_char)) +
call    0 never executed
branch  1 never executed
branch  2 never executed
call    3 never executed
call    4 never executed
    #####:   33:                         " to an alphabet of type " + type_name +
call    0 never executed
branch  1 never executed
branch  2 never executed
call    3 never executed
branch  4 never executed
branch  5 never executed
call    6 never executed
call    7 never executed
call    8 never executed
call    9 never executed
call   10 never executed
        -:   34:                         " would incur information loss. If you want implicit conversion, use "
    #####:   35:                         "bio::alphabet::assign_char instead of bio::alphabet::assign_char_strict."}
branch  0 never executed
branch  1 never executed
call    2 never executed
branch  3 never executed
branch  4 never executed
    #####:   36:    {}
        -:   37:
        -:   38:    //!\overload
    #####:   39:    invalid_char_assignment(std::string const & type_name, std::convertible_to<char> auto const wrong_char) :
    #####:   40:      invalid_char_assignment(type_name, static_cast<char>(wrong_char))
    #####:   41:    {}
------------------
_ZN3bio8alphabet23invalid_char_assignmentC2IDiEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_:
function _ZN3bio8alphabet23invalid_char_assignmentC2IDiEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_ called 0 returned 0% blocks executed 0%
    #####:   39:    invalid_char_assignment(std::string const & type_name, std::convertible_to<char> auto const wrong_char) :
    #####:   40:      invalid_char_assignment(type_name, static_cast<char>(wrong_char))
call    0 never executed
    #####:   41:    {}
------------------
_ZN3bio8alphabet23invalid_char_assignmentC2IwEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_:
function _ZN3bio8alphabet23invalid_char_assignmentC2IwEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_ called 0 returned 0% blocks executed 0%
    #####:   39:    invalid_char_assignment(std::string const & type_name, std::convertible_to<char> auto const wrong_char) :
    #####:   40:      invalid_char_assignment(type_name, static_cast<char>(wrong_char))
call    0 never executed
    #####:   41:    {}
------------------
_ZN3bio8alphabet23invalid_char_assignmentC2IDsEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_:
function _ZN3bio8alphabet23invalid_char_assignmentC2IDsEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_ called 0 returned 0% blocks executed 0%
    #####:   39:    invalid_char_assignment(std::string const & type_name, std::convertible_to<char> auto const wrong_char) :
    #####:   40:      invalid_char_assignment(type_name, static_cast<char>(wrong_char))
call    0 never executed
    #####:   41:    {}
------------------
        -:   42:};
        -:   43:
        -:   44:} // namespace bio::alphabet
```

**Comment by Spacetown** [comment]
Hmm, this seem not to be throw branches because they are annotated with the suffix `(throw)`.

**Comment by h-2** [comment]
> Hmm, this seem not to be throw branches because they are annotated with the suffix (throw).

They are throw branches or they are not? Sorry, didn't understand that from your reply.

**Comment by Spacetown** [comment]
Sorry, they are not annotated. This are real branches.

**Comment by grregd** [comment]
Hi

Since the gcov file you have posted shows 0 coverage at all, while the report shows ~half of the branches to be covered then perhaps there is more than one gcov file for your source file.

This may happen when you compile more than one executable from the same file/s (at least in case of CMake build).

I have very similar problem - branches of unknown origin.

I'm compiling several test executables that share some source files. This results in generating several gcov files for the same source file. After running the tests, gcov file for one executable shows no coverage for some function (which is correct in my case), and gcov file for the other executable shows full coverage for the same function (which is also correct in my case).
Some branches in the second file are marked as (throw), and are removed with `--exclude-throw-branches` flag. The matching branches in first file don't have any annotations and is not filtered out.
So, when gcovr merges branches from this line, it only sees branches without coverage.

For example, suppose we have two gcov files for the same source, with branches as follows.

    file.gcov (first)           | file.gcov (second)
    ------------------------------------------------------------------------
    branch  2 never executed    |  branch  2 taken 500 (fallthrough)
    branch  3 never executed    |  branch  3 taken 0 (throw)

After processing first file gcov sees 2 branches with 0 coverage. Then it processes the second file, where it removes `branch 3`. After that, it performs merging, where input is as follows

    file.gcov (first)           | file.gcov (second)
    ------------------------------------------------------------------------
    branch  2 never executed    |  branch  2 taken 500 (fallthrough)
    branch  3 never executed    |  

and the result is:

    branch  2 taken 500 (fallthrough)
    branch  3 never executed 


@h-2  could you perhaps check if you have more than one gcov file, and share it as well?

**Comment by h-2** [comment]
That explanation makes sense, and the respective file is definitely included by many different build targets. But I don't think that I have multiple `.gcov` files.

Is it possible that cmake overwrites the file when creating newer targets? The gcov file I posted here was created in the build directory and named `#home#USERNAME#DIRECTORY#filename.hpp.gcov`. So I don't see how multiple gcov files can exist for the same header.

**Comment by grregd** [comment]
In my case, each test executable is build in separate subfolder of build directory. And each executable has its own version of gcov file associated with the same source file.

Following is the list of gcov files associated with the same source file in my build directory (names changed)

```
./test/module/test_first/CMakeFiles/test_binary_first.dir/__/__/__/src/<path_to_source_file>/source_file.cpp##316fd046ede9dba155bd49226c898e23.gcov

./test/module/test_second/CMakeFiles/test_binary_second.dir/__/__/__/src/<path_to_source_file>/source_file.cpp##316fd046ede9dba155bd49226c898e23.gcov
```

Also, I can see in gcovr's output (I have added some prints) that both of those files are processed, and indeed, one contains only 'never executed' remarks, while the other has some non-zero coverage.

**Comment by h-2** [comment]
OK, I might have posted the wrong file(s) that were leftover when trying to setup gcovr properly. Because I realised, after cleaning up the directory, that the `.gcov` files are automatically deleted (even when running with `--keep`):

```
/usr/bin/gcovr --root /home/hannes/devel/biocpp-core/test/coverage /home/hannes/devel/biocpp-core-build/coverage --filter '/home/hannes/devel/biocpp-core/include/bio/.*' --filter '/home/hannes/devel/biocpp-core/test/include/bio/test/.*' --exclude-unreachable-branches --exclude-throw-branches -j 1 --exclude-lines-by-pattern '(^\s*assert\(.*$)|(^.*GCOVR_EXCL_LINE.*$)|(^\s*BIOCPP_UNREACHABLE\s*$)' --verbose --keep --xml --output /home/hannes/devel/biocpp-core-build/coverage/biocpp_coverage.xml
Filters for --root: (1)
- re.compile('^/home/hannes/devel/biocpp\\-core/test/coverage/')
Filters for --filter: (2)
- AbsoluteFilter(/home/hannes/devel/biocpp-core/include/bio/.*)
- AbsoluteFilter(/home/hannes/devel/biocpp-core/test/include/bio/test/.*)
Filters for --exclude: (0)
Filters for --gcov-filter: (1)
- AlwaysMatchFilter()
Filters for --gcov-exclude: (0)
Filters for --exclude-directories: (0)
Scanning directory /home/hannes/devel/biocpp-core-build/coverage for gcda/gcno files...
Found 182 files (and will process 91)
Pool started with 1 threads
Processing file: /home/hannes/devel/biocpp-core-build/coverage/ranges/views/CMakeFiles/view_as_const_test.dir/view_as_const_test.cpp.gcda
Running gcov: 'gcov /home/hannes/devel/biocpp-core-build/coverage/ranges/views/CMakeFiles/view_as_const_test.dir/view_as_const_test.cpp.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory /home/hannes/devel/biocpp-core-build/coverage/ranges/views/CMakeFiles/view_as_const_test.dir' in '/tmp/tmpbocbqtqa'
Finding source file corresponding to a gcov data file
  currdir      /home/hannes/devel/biocpp-core-build/coverage
  gcov_fname   /tmp/tmpbocbqtqa/#home#hannes#devel#biocpp-core#test#unit#ranges#views#view_as_const_test.cpp.gcov
               ['        -', '    0', 'Source', '/home/hannes/devel/biocpp-core/test/unit/ranges/views/view_as_const_test.cpp\n']
  source_fname /home/hannes/devel/biocpp-core-build/coverage/ranges/views/CMakeFiles/view_as_const_test.dir/view_as_const_test.cpp.gcda
  root         /home/hannes/devel/biocpp-core/test/coverage
  fname        /home/hannes/devel/biocpp-core/test/unit/ranges/views/view_as_const_test.cpp
[...]
```
They end up in '/tmp/tmpbocbqtqa' which is removed automatically. Anyway I can prevent this?

**Comment by Spacetown** [comment]
@latk The explanation https://github.com/gcovr/gcovr/issues/677#issuecomment-1282355159 is valid but it seems to be a gcov problem then the `(throw)` information is missing if the branches are uncovered (see https://github.com/gcc-mirror/gcc/blob/50bc9185c2821350f0b785d6e23a6e9dcde58466/gcc/gcov.c#L2861).
I checked your #663 but saw that also there the exclusion processing is done after reading the gcov file and the `(throw)` information is thrown away.
I've no idea for a workaround and suggest to create a PR for `gcov`. What do you think?

**Comment by Spacetown** [comment]
@grregd Thanks for the bug report https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107537. I've attached a patch to it.

**Comment by Spacetown** [comment]
Patch is uploaded to mailing list.

**Comment by Spacetown** [comment]
...and merged to master branch of gcc.
