### ISSUE TITLE
Decision couldn't be analyzed on an 'if' followed by a 'for'

### ISSUE THREAD

**Issue by czoltan1026** [gcovr/gcovr#679]
**Describe the bug**
The following code produces an unanalyzable decision at the `if` statement:
``` c++
void f(const bool b) {
  if (b) {
    for (int i = 0; i < 10; i++) {
    }
  }
}

int main() {
  f(false);
  f(true);
}
```

**To Reproduce**
g++ -o example example.cpp -O0 --coverage
./example
gcov example
gcovr --decision --html-details --output=coverage.html --object-directory .

**Expected behavior**
The `if` statement should be analyzable

**Screenshots**
I'll add them whenever github allows me to upload pictures

**Desktop (please complete the following information):**
 - OS: Windows/linux
 - GCC 9.40, GCC 11.1.0, CLANG 12.0.0
 - GCOVR 5.2

**Additional context**
Interestingly this workaround fixes the issue
``` c++
void f(const bool b) {
  if (b) {
    const int var = 0;
    for (int i = 0; i < 10; i++) {
    }
  }
}

int main() {
  f(false);
  f(true);
}
```

**Comment by Spacetown** [comment]
Confirmed, I need to investigate deeper. For now, `gcc-5` seems to work even if the gcov files look identical in this case.

**Comment by Spacetown** [comment]
@czoltan1026 Can you try the branch from the PR and give a feedback?

**Comment by czoltan1026** [comment]
@Spacetown Checked, works fine!
Thanks

**Comment by czoltan1026** [comment]
In the meantime we've found some other cases where decisions break down:
Base example, works fine:
```c++
int main(int ac, char **av) {
    bool a = false;
    bool b = true;
    if ( a && b ) { // decision analyzed
      for(int i=0; i < 1; ++i)
      {}
   }
}
```

```c++
int main(int ac, char **av) {
    bool a = true;
    bool b = true;


   if ( a && b ) { // decision not analyzed
      for(int i=0; i < 1; ++i)
      {}
   }
}
```

```c++
int main(int ac, char **av) {
    bool a = true;
    bool b = true;


   if ( a && b   // decision not analyzed
)

   
   {
      for(int i=0; i < 1; ++i)  // decision not analyzed
      {}
   }
}
```

```c++
int main(int ac, char **av) {
    bool a = true;
    bool b = true;


   if (a && b)  // decision not analyzed
   {
      for(int i=0;  // decision not analyzed
      i < 1; ++i)
      {}
   }
}
```

```c++
void func(){}



int main(int ac, char **av) {

    bool a = true;
    bool b = true;


   if (a && b // decision not analyzed
   )  
   {
        func();
   }
}
```
