### ISSUE TITLE
gcovr 5.2 report a not called template function

### ISSUE THREAD

**Issue by fchn289** [gcovr/gcovr#680]
**Describe the bug**
UT (PriDominoTest.cpp) tests 3 template types: 1)MinPriDom, 2)MaxNofreeDom, 3)MaxDom. The issue func (getPriority) is called 4 times in testcase setPriority_thenGetIt & defaultPriority.

**To Reproduce**
- all info: https://github.com/nokia/domino-library/actions/runs/3231169474/jobs/5290402843
- "github action" of this project can reproduce the issue
- issue occur: commit=3a11524 pushed by fchn289
- issue log: https://github.com/nokia/domino-library/suites/8728209783/artifacts/394721063

**Expected behavior**
RLib::PriDomino<RLib::HdlrDomino<RLib::Domino> >::getPriority(unsigned long) const, this function IS called in UT (PriDominoTest.cpp)

**Screenshots**
![image](https://user-images.githubusercontent.com/100677967/195237088-9ebbaaa2-a34d-439a-ac05-c05a7cf6c482.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5
 - GCC 9.4.0
 - GCOVR 5.2
 - Project directory layout:
   - issue func in: src/domino/PriDomino.hpp (UT in ut/domino/PriDominoTest.cpp)

**Comment by latk** [comment]
Hmm, that's definitely a bug on our side. Thank you for reporting this.

On a hunch: does the problem fix itself if you disable the `gcov-parallel` option? That was only ever intended for huge projects with complex directory structures, and has caused some similar bugs in the past. In particular, GCC-gcov handles coverage data on a per-object-file basis, so that coverage data for header files is split across multiple compilation units.

But I have no consistent theory about gcovr's behaviour here. In particular, I find it confusing that the function table has no entry for `setPriority()`, yet we know that it was called and that the lines in that function were covered.

**Comment by fchn289** [comment]
same result: https://github.com/nokia/domino-library/suites/8733423951/artifacts/395139969

**Comment by fchn289** [comment]
GCC up to 11.3.0 now. This issue still there (but some other coverage issues improved)

**Comment by Spacetown** [comment]
Can you provide a gcov file (use option `gcovr --keep ...`) where the lines are cover but the functions not?

**Comment by fchn289** [comment]
all files are in https://github.com/nokia/domino-library/suites/9838934035/artifacts/474070571

including the file you need: PriDomino.hpp##b3b0423d55bcebd69d2e33d069d62631.gcov

**Comment by Spacetown** [comment]
@fchn289 In this file the function and lines are all uncovered. I think with the option `--keep` only the gcov file of the last object which reference a header is kept.

**Comment by Spacetown** [comment]
Can you produce the same file with my development branch https://github.com/Spacetown/gcovr/tree/improve_option_keep?

**Comment by fchn289** [comment]
> @fchn289 In this file the function and lines are all uncovered. I think with the option `--keep` only the gcov file of the last object which reference a header is kept.

then you can check PriDominoTest.cpp##58c362ab05a621736b240671750a63b0.gcov

**Comment by Spacetown** [comment]
I need the gcov file from the header. In the PriDominoTest.cpp is only the call of the function but not the function itself.

**Comment by Spacetown** [comment]
Can you provide the file?

**Comment by fchn289** [comment]
https://github.com/nokia/domino-library/suites/9838934035/artifacts/474070571, unzip & you can find `PriDomino.hpp##b3b0423d55bcebd69d2e33d069d62631.gcov`

**Comment by Spacetown** [comment]
> https://github.com/nokia/domino-library/suites/9838934035/artifacts/474070571, unzip & you can find `PriDomino.hpp##b3b0423d55bcebd69d2e33d069d62631.gcov`

Are you really sure that it's called and not another function? The gcov file shows uncovered function. Can you add a `exit 1` or something else to test this?

**Comment by Spacetown** [comment]
I saw this comment in the documentation of `gcov`:

```
Note that GCC can completely remove the bodies of functions that are not needed – for instance if they are inlined everywhere. Such functions are marked with ‘-’, which can be confusing. Use the -fkeep-inline-functions and -fkeep-static-functions options to retain these functions and allow gcov to properly show their execution_count. 
```

Do you use inlining?

**Comment by fchn289** [comment]
- do you use inlining? no but template (like inline, template implementation is also in header file (must)
- -fkeep-inline-functions & -fkeep-static-functions are interesting, but can't solve the issue. I can't find similar option for template.

**Comment by Spacetown** [comment]
There are no special options for templates. Your behavior looks exactly as the one described in the docs

**Comment by fchn289** [comment]
- sth wrong with nested template, eg PriorityDomino::setPriority()
- sth wrong with nested template & virtual, eg PriorityDomino::getPriority()

**Comment by Spacetown** [comment]
Gcovr is only displaying the data from gcov. Please check your gcov files first.

**Comment by fchn289** [comment]
would be gcov issues, I close this ticket, thanks
