### ISSUE TITLE
decision cannot be analyzed for loop with multiple conditions 

### ISSUE THREAD

**Issue by bence42** [gcovr/gcovr#688]
**Describe the bug**
A loop that has multiple conditions reports decision cannot be analyzed.

**To Reproduce**
* gcvor 5.2 + fix from #681
* gcc 11.1
```c++
int main(int ac, char **av) {
    bool a = true;
    for( int i = 0; i < 10 && a ; ++i) { // decision not analyzed
        a = false;
    }
}
```

**Expected behavior**
The decision for the loop shall be analyzed.

**Desktop**
 - OS: Win10 / Ubuntu 20.04
 - gcc 11.1
 - gcovr 5.2 + fix from #681

**Comment by Spacetown** [comment]
As mentioned in #681 the parsing depends on the format and is experimental.
After looking at the test data complex for loops are not checkable.

**Comment by Spacetown** [comment]
Only two branches (one logical expression) are supported in for loops.

**Comment by bence42** [comment]
Is this going to be fixed? The decision coverage feature is released, and is not marked as experimental, there's a only hint about "reasonable formatting". It's a bit misleading, given that switch cases and loops are a challenge. If it's experimental, it should be marked as such.

**Comment by Spacetown** [comment]
From CHANGELOG:
```rst
Can report decision coverage with :option:`--decisions` option (reasonably formatted C/C++ source files only, HTML and JSON output) (:issue:`350`)
```

Unfortunately, it's not documented what "reasonably" means.
