### ISSUE TITLE
Unrecognized GCOV output for /home/jenkins/workspace/prj/mem/ddr.hpp 

### ISSUE THREAD

**Issue by JayeCheng** [gcovr/gcovr#689]
Describe the bug
I wanted to check code_coverage, after " gcovr -r , -x coverage.xml --xml-pretty -f '/home/jenkins/workspace/prj/*' " something went wrong.  

The error message:

(WAENING) Exception during parsing:
                 UnknownLineType: call       9 returned -296
(ERROR) Exiting because of parse errors.
              You can run gcovr with --gcov-ignore-parse-errors
              to continue anyway.

**Comment by Spacetown** [comment]
This is a gcov error already discussed in #583. This error can be ignored as described in https://github.com/gcovr/gcovr/issues/583#issuecomment-1080352048.
