### ISSUE TITLE
strange partially coverred line

### ISSUE THREAD

**Issue by igagis** [gcovr/gcovr#691]
I've tried to move from `lcov` to `gcovr` and I found that I get a different coverage report with `gcovr`, it contains strangely partially covered code lines which were fully covered with `lcov`.

Here is the example:
`lcov`:
https://app.codecov.io/github/cppfw/utki/blob/master/src/utki/time.cpp

`gcovr`:
https://app.codecov.io/gh/cppfw/utki/blob/gcovr/src/utki/time.cpp

as one can see, line 38 is marked as partially covered.
Any idea why is that? Do I misunderstand something?

**Comment by Spacetown** [comment]
Do you have the output of gcov for this code?

**Comment by igagis** [comment]
Here is the cobertura report:

`lcov`:
https://github.com/cppfw/utki/suites/9271745795/artifacts/434316125

`gcovr`:
https://github.com/cppfw/utki/suites/9271742688/artifacts/434315103

**Comment by Spacetown** [comment]
Not the generated report (I've no permission). The gcov output file with the branches or the HTML report of gcovr.

**Comment by igagis** [comment]
Here is how it looks in `gcovr` HTML report:
![image](https://user-images.githubusercontent.com/783401/201496446-dfd75c5b-28b3-4a2b-a524-2eb8520e8d57.png)

i.e. for some reason it thinks that there are 2 branches and one of them is not taken... not sure what those branches are...

**Comment by Spacetown** [comment]
What options do you use? Can you try `--exclude-unreachable-branches`?

**Comment by igagis** [comment]
Ok, `--exclude-throw-branches` helped, thanks!

**Comment by igagis** [comment]
By the way, wouldn't it make sense to set `--exclude-unreachable-branches` to true by default? Since it excludes unreachable dead code generated by compiler?

**Comment by Spacetown** [comment]
> By the way, wouldn't it make sense to set `--exclude-unreachable-branches` to true by default? Since it excludes unreachable dead code generated by compiler?

I think the default is for backwards compatible. @latk What do you think?
