### ISSUE TITLE
Filename length on Windows

### ISSUE THREAD

**Issue by whart222** [gcovr/gcovr#7]
Users have reported an issue with very long filenames on Windows.  This needs to be checked, but no test cases have been provided

**Comment by mrx23dot** [comment]
ANSI C standard says 31 character long filenames should be accepted at least.

Another question is how long is going to be, when gcov.exe appends the path to it (must be less than 255 chars, e.g. C##Windows##folder1##folder2##name.gcno)

**Comment by Spacetown** [comment]
Fixed with #375.
