### ISSUE TITLE
"relative referencing in --object-directory" false positive if path ends with slash

### ISSUE THREAD

**Issue by mkonig** [gcovr/gcovr#70]
Hi

If one uses a path ending with a slash than this error message appears:
WARNING: relative referencing in --object-directory; this could"  cause strange errors when gcovr attempts to identify"  the original gcc working directory.

Even though there is no relative referencing in the path.
Problem:
os.path.normpath() strips the last / but objdir.replace('/',os.sep) does not.

**Comment by Spacetown** [comment]
I can't reproduce this error with the 5.0.
