### ISSUE TITLE
Option `--exclude-unreachable-branches` & `--exclude-throw-branches` not working

### ISSUE THREAD

**Issue by Zvicii** [gcovr/gcovr#706]
**Describe the bug**
My coverage report has many lines with invisible branches, after reading FAQ, I add `--exclude-unreachable-branches --exclude-throw-branches` to command, but it doesn't seem to be working.
I add `--decisions` as well, the result in decision is correct. But I need it in xml format for `sonarqube` which does not support `decisions`.
Forgive me if I'm missing something simple, I'm quite new to this.

**To Reproduce**
1. without `--exclude-unreachable-branches --exclude-throw-branches`
```
/opt/homebrew/bin/gcovr --html coverage/index.html --html-details -r /Users/zouyiqi/projects/my_project --object-directory=/Users/zouyiqi/projects/my_project/build --decisions
```
![image](https://user-images.githubusercontent.com/36950948/211266441-c6ce10aa-601b-49d4-a709-b945b505f955.png)
![image](https://user-images.githubusercontent.com/36950948/211265202-67d0db0a-b9c4-4cf4-90c0-0bfd6007b653.png)

2. with `--exclude-unreachable-branches --exclude-throw-branches`
```
/opt/homebrew/bin/gcovr --html coverage/index.html --html-details -r /Users/zouyiqi/projects/my_project --object-directory=/Users/zouyiqi/projects/my_project/build --exclude-unreachable-branches --exclude-throw-branches --decisions
```
![image](https://user-images.githubusercontent.com/36950948/211265643-73e7ca0e-2eb2-4583-b21a-d59e4ad95b36.png)
![image](https://user-images.githubusercontent.com/36950948/211265706-ef2c2586-ec98-48ed-921b-b6eaa42498c5.png)

**Expected behavior**
1. Function call should not report branch.
2. `if` expression should has only 2 branches instead of 4.

**Desktop (please complete the following information):**
 - OS: macOS 13.1
 - GCC version: 
```
zouyiqi@zouyiqideMacBook-Pro build % gcc -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
 - GCOVR version 5.2
 - Project directory layout:
   - Roots /Users/zouyiqi/projects/my_project
   - Object directories /Users/zouyiqi/projects/my_project/build

**Comment by Zvicii** [comment]
```
/opt/homebrew/bin/gcovr --html coverage/index.html --html-details -r /Users/zouyiqi/projects/my_project --object-directory=/Users/zouyiqi/projects/my_project/build --decisions --exclude-unreachable-branches --exclude-throw-branches --keep
```
coverage/index.html:
![image](https://user-images.githubusercontent.com/36950948/211703085-705d1b58-d34d-400f-af3e-4312ed30e2b7.png)

talk_manager.cpp.gcov.html:
![image](https://user-images.githubusercontent.com/36950948/211703328-36ac8ccc-d3dd-42f7-bef5-e0601a545590.png)

**Comment by Zvicii** [comment]
gcov reports same result
![image](https://user-images.githubusercontent.com/36950948/211706260-7ddee1c6-360a-4ad6-9f8a-6f516f8d5075.png)

**Comment by Spacetown** [comment]
Please copy the content instead of using screenshots. Since the call annotation is missing it looks like branches from inclined code. In the assembler code you should see more.

**Comment by Zvicii** [comment]
do you mean `inlined code`?
I checked the `Init()` Function

**Comment by Zvicii** [comment]
do you mean `inlined code`?
I checked the `Init()` function, its called zero time. So yes, I believe it's inlined, but I don't see any branches in these codes either.
```
function nim::TalkManager::Init() called 0 returned 0% blocks executed 0%
    #####:   85:    void Init() {
    #####:   86:        sending_msgs_.clear();
    #####:   87:        cached_read_timetag_.clear(); 
    #####:   88:        cached_read_loaded_ = false;
    #####:   89:    }
```
Also the `if-else` expression on line 82 generates 4 branches, is it because the `GetInstance` call ?
```
function nim::TalkManager::TalkManager() called 1 returned 100% blocks executed 40%
function nim::TalkManager::TalkManager() called 1 returned 100% blocks executed 100%
        2:   57:TalkManager::TalkManager() {
branch  0 taken 1
branch  1 taken 0
branch  2 taken 1
branch  3 taken 0
        1:   58:    send_msg_ack_cb_ = nullptr;
        1:   59:    send_sysmsg_ack_cb_ = nullptr;
        1:   60:    receive_msg_cb_ = nullptr;
        1:   61:    receive_sysmsg_cb_ = nullptr;
        1:   62:    msg_status_changed_cb_ = nullptr;
        1:   63:    receive_msgs_cb_ = nullptr;
        1:   64:    team_notification_filter_ = nullptr;
        1:   65:    recall_msg_cb_ = nullptr;
        1:   66:    receive_broadcast_cb_ = nullptr;
        1:   67:    receive_broadcasts_cb_ = nullptr;
        1:   68:    message_filter_ = nullptr;
        1:   69:    message_filter_user_data_ = nullptr;
        1:   70:    Init();
branch  0 taken 0
branch  1 taken 1
        2:   71:}
        -:   72:
function nim::TalkManager::InvokeStopSendMsg(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) called 1 returned 100% blocks executed 40%
        1:   73:void TalkManager::InvokeStopSendMsg(const std::string& json_msg) {
        -:   74:    // QLOG_PRO("lty.InvokeStopSendMsg:\r\n%s", json_msg.c_str());
        -:   75:
        1:   76:    NIMMessageType msg_type = (NIMMessageType)FetchValueFromJsonString(json_msg, kNIMMsgKeyType).asUInt();
branch  0 taken 1
branch  1 taken 0
branch  2 taken 1
branch  3 taken 0
        1:   77:    if (msg_type != kNIMMessageTypeFile) {
branch  0 taken 0
branch  1 taken 1
    #####:   78:        QLOG_WAR("Not support stopping sending msg({0}) for now!") << msg_type;
branch  0 never executed
branch  1 never executed
branch  2 never executed
branch  3 never executed
branch  4 never executed
branch  5 never executed
    #####:   79:        return;
        -:   80:    }
        1:   81:    std::string msg_id = FetchValueFromJsonString(json_msg, kNIMMsgKeyClientMsgid).asString();
branch  0 taken 1
branch  1 taken 0
branch  2 taken 0
branch  3 taken 1
        1:   82:    if (GlobalConfig::GetInstance()->enable_fcs_) {
branch  0 taken 1
branch  1 taken 0
branch  2 taken 0
branch  3 taken 1
    #####:   83:        nim::FCSManager::GetInstance()->InvokeStopUploadByResID(msg_id);
branch  0 never executed
branch  1 never executed
branch  2 never executed
branch  3 never executed
    #####:   84:    } else {
        1:   85:        HttpManager::GetInstance()->StopUploadResourceRange(msg_id);
branch  0 taken 1
branch  1 taken 0
branch  2 taken 1
branch  3 taken 0
        -:   86:    }
```
What can I do to avoid both of these situations and make the `branch` result close to the `decision` result?
Should I disable `inline` and `exception`?

**Comment by Spacetown** [comment]
The inline is only a guess. If you generate the assembler code you can should be able to see the branches and can check this. You can try to deactivate the inlining.

**Comment by Zvicii** [comment]
![image](https://user-images.githubusercontent.com/36950948/212227346-3383c4de-af98-4df9-bbbd-4d563d2da890.png)

well it seems that its not inlined. 
I will try run coverage under linux, hopefully I will get better result.

**Comment by Zvicii** [comment]
Good news, the report is accurate under linux. Seems that `--exclude-unreachable-branches` & `--exclude-throw-branches` are workig now!
