### ISSUE TITLE
Unexpected failure to generate coverage under github CI

### ISSUE THREAD

**Issue by benny-edlund** [gcovr/gcovr#707]
**Describe the bug**
Hi there, hoping someone can help point out my mistake to me.

I've got this C++ [project](https://github.com/benny-edlund/task-pool) and I'm trying to sort out the coverage generation to codecov from the CI.

Seems the run statements in my [CI](https://github.com/benny-edlund/task-pool/actions/runs/3973245918/workflow) do not behave the same as my own local execution of them and I can not see what mistake I have made.

```
- name: Unix - Test and coverage
  if: runner.os != 'Windows'
  working-directory: ./build
  run: |
    ctest -C ${{matrix.build_type}}
    gcovr  --delete --root ../lib/ --print-summary --exclude-unreachable-branches --exclude-throw-branches --xml-pretty --xml coverage.xml . --gcov-executable '${{ matrix.gcov_executable }}'

```

This works perfectly fine when run locally from the same working folder and the source is in the expected place yet in the CI it behaves as it the wrong root folder was given or as if it was not build with the right flags. If checked build flags (-g --coverage for all) and running verbose shows me gcovr finds the .gcno files generated from the test run yet is unable to match it to the source in the project

**To Reproduce**
Steps to reproduce the behavior (perhaps there is a different way?):
1. fork the project
2. run the ci
3. Check the "Unix - Test and coverage" job on the `Test (ubuntu-20.04, gcc-11, Ninja Multi-Config, Debug, OFF)`

**Expected behavior**
Expected to get non-zero coverage results from this CI job like I do when running on locally

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - GCC version 11
 - GCOVR version 4.2
 - Project directory layout:
   - lib, test

**Comment by latk** [comment]
Hmm. It's not clear from the description where the problem lies, but typically it's something relating to filtering.

* Can you verify that it works on desktop when installing an up to date gcovr from PyPI? I think you're using the outdated APT package on your desktop, whereas the GH Action installs the most recent version from PyPI. See the installation docs at https://gcovr.com/en/5.2/installation.html . Alternatively, you might want to pin the version in the CI environment to the same version you're using locally.
* Can you verify whether building your project and running your tests generates the coverage data files? For example, running `find . -type f -name '*.gcn?'` before gcovr. For details about the relevance of `.gcno`/`.gcda` files, see https://gcovr.com/en/5.2/guide/compiling.html#working-with-multiple-object-files
* Can you run gcovr in `--verbose` mode? This will produce a ton of output, but makes it possible to understand which input files are seen and which ones are excluded.

**Comment by benny-edlund** [comment]
Yes I just updated to 5.2 on my desktop and it also works and produces the expected result

```
benny@LAPTOP-LHODMM4E:~/projects/task-pool/build$ gcovr --root ../lib --print-summary --exclude-unreachable-branches --exclude-throw-branches --xml-pretty --xml coverage.xml . --gcov-executable 'gcov'
lines: 91.8% (537 out of 585)
functions: 98.8% (401 out of 406)
branches: 63.9% (400 out of 626)
benny@LAPTOP-LHODMM4E:~/projects/task-pool/build$ gcovr --version
gcovr 5.2

Copyright (c) 2013-2022 the gcovr authors
Copyright (c) 2013 Sandia Corporation.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
```
[this](https://github.com/benny-edlund/task-pool/actions/runs/3974153658/jobs/6813260410) is an example of where coverage was expected to be generated but did not.

Its all run verbosely....here are some parts to logs. Please follow the links to read logs in full. As you said they are quite verbose

Build
```
[1/7] /usr/bin/ccache /usr/bin/g++-11 -DTASKPOOL_STATIC_DEFINE -DCMAKE_INTDIR=\"Debug\" -I/home/runner/work/task-pool/task-pool/lib/public -I/home/runner/work/task-pool/task-pool/build/lib -I/home/runner/work/task-pool/task-pool/build/configured_files/include -g -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -g -coverage -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wimplicit-fallthrough -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wuseless-cast -std=gnu++14 -MD -MT lib/CMakeFiles/task_pool_static.dir/Debug/task_pool.cpp.o -MF lib/CMakeFiles/task_pool_static.dir/Debug/task_pool.cpp.o.d -o lib/CMakeFiles/task_pool_static.dir/Debug/task_pool.cpp.o -c /home/runner/work/task-pool/task-pool/lib/task_pool.cpp
```
Unix - Test & Coverage
```
87/89 Test #87: unittests.is_future ...................................................   Passed    0.01 sec
      Start 88: unittests.is_promise
88/89 Test #88: unittests.is_promise ..................................................   Passed    0.01 sec
      Start 89: unittests. submit<my_promise>( ... )
89/89 Test #89: unittests. submit<my_promise>( ... ) ..................................   Passed    0.03 sec

100% tests passed, 0 tests failed out of 89

Total Test time (real) =   0.60 sec
(DEBUG) Filters for --root: (1)
(DEBUG)  - re.compile('^/home/runner/work/task\\-pool/task\\-pool/lib/')
(DEBUG) Filters for --filter: (1)
(DEBUG)  - DirectoryPrefixFilter(/home/runner/work/task\-pool/task\-pool/lib/)
(DEBUG) Filters for --exclude: (0)
(DEBUG) Filters for --gcov-filter: (1)
(DEBUG)  - AlwaysMatchFilter()
(DEBUG) Filters for --gcov-exclude: (0)
(DEBUG) Filters for --exclude-directories: (0)
(DEBUG) Scanning directory . for gcda/gcno files...
(DEBUG) Found 5 files (and will process 3)
(DEBUG) Pool started with 1 threads
(DEBUG) Processing file: /home/runner/work/task-pool/task-pool/build/lib/CMakeFiles/task_pool.dir/Debug/task_pool.cpp.gcno
(DEBUG) Running gcov: 'gcov --help' in '.'
(DEBUG) Running gcov: 'gcov --help-hidden' in '.'
(DEBUG) Running gcov: 'gcov /home/runner/work/task-pool/task-pool/build/lib/CMakeFiles/task_pool.dir/Debug/task_pool.cpp.gcno --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /home/runner/work/task-pool/task-pool/build/lib/CMakeFiles/task_pool.dir/Debug' in '/home/runner/work/task-pool/task-pool/lib'
(DEBUG) Finding source file corresponding to a gcov data file
  gcov_fname   /home/runner/work/task-pool/task-pool/lib/tuple##0a6a4889d68996f02db364336a079f7a.gcov
  currdir      /home/runner/work/task-pool/task-pool/build
  root         /home/runner/work/task-pool/task-pool/lib
  starting_dir /home/runner/work/task-pool/task-pool/build
  obj_dir      None
  gcda_fname   /home/runner/work/task-pool/task-pool/build/lib/CMakeFiles/task_pool.dir/Debug/task_pool.cpp.gcno
  --> fname    /usr/include/c++/11/tuple
(DEBUG) Parsing coverage data for file /usr/include/c++/11/tuple
(DEBUG)   Filtering coverage data for file /usr/include/c++/11/tuple
(DEBUG) Finding source file corresponding to a gcov data file
  gcov_fname   /home/runner/work/task-pool/task-pool/lib/invoke.h##7cc68d7262a4ba0a26143e668e705662.gcov
  currdir      /home/runner/work/task-pool/task-pool/build
  root         /home/runner/work/task-pool/task-pool/lib
  starting_dir /home/runner/work/task-pool/task-pool/build
  obj_dir      None
  gcda_fname   /home/runner/work/task-pool/task-pool/build/lib/CMakeFiles/task_pool.dir/Debug/task_pool.cpp.gcno
  --> fname    /usr/include/c++/11/bits/invoke.h

....

(DEBUG) Finding source file corresponding to a gcov data file
  gcov_fname   /home/runner/work/task-pool/task-pool/lib/atomic##7b0efb97df455517666cc8743c286bf4.gcov
  currdir      /home/runner/work/task-pool/task-pool/build
  root         /home/runner/work/task-pool/task-pool/lib
  starting_dir /home/runner/work/task-pool/task-pool/build
  obj_dir      None
  gcda_fname   /home/runner/work/task-pool/task-pool/build/lib/CMakeFiles/task_pool_static.dir/Debug/task_pool.cpp.gcda
  --> fname    /usr/include/c++/11/atomic
(DEBUG) Parsing coverage data for file /usr/include/c++/11/atomic
(DEBUG)   Filtering coverage data for file /usr/include/c++/11/atomic
(DEBUG) Gathered coveraged data for 3 files
lines: 0.0% (0 out of 563)
functions: 0.0% (0 out of 406)
branches: 0.0% (0 out of 940)
```

My project is small so gcovr does seem to locate the three sources that are relevant however does not seem to be able to match them to any of the files generated by the test run.

Myself I can not see anything in the gcovr logs telling me that there was any problem so Im a bit stumped

**Comment by Spacetown** [comment]
Can you try to build without cache? I don't know if cache is aware of the additional output files.

**Comment by benny-edlund** [comment]
I did disable ccache without any change.

I also change to more standard project layout with `root/src`  & `root/include` structure on the off chance my nonstandard layout was causing some issues...also without any chance in behavior

Latest iteration is found on [this](https://github.com/benny-edlund/task-pool/actions/runs/3981246696/jobs/6824851263) branch

Would be great if the `gcovr --verbose` flag could be more descriptive about why some source could not be matched if sources where found I think. 

If the program did find coverage data files and it does find sources in the root but no coverage could be matched this is likely an error right? You either did not instrument the code or something is wrong in the matchers / filters so it would be very helpful to myself in this situation if the logging could report actually what the matchers are and why they did or did not match the data files with the sources files.

Consider this log statement
```
(DEBUG) Finding source file corresponding to a gcov data file
  gcov_fname   /home/runner/work/task-pool/task-pool/src/task_pool.h##84ff5dcb37c3813a71ae9a19cfa1fd55.gcov
  currdir      /home/runner/work/task-pool/task-pool/build
  root         /home/runner/work/task-pool/task-pool/src
  starting_dir /home/runner/work/task-pool/task-pool/build
  obj_dir      None
  gcda_fname   /home/runner/work/task-pool/task-pool/build/src/CMakeFiles/task_pool_static.dir/Debug/task_pool.cpp.gcda
  --> fname    /home/runner/work/task-pool/task-pool/include/task_pool/task_pool.h
(DEBUG) Parsing coverage data for file /home/runner/work/task-pool/task-pool/include/task_pool/task_pool.h
(DEBUG)   Filtering coverage data for file /home/runner/work/task-pool/task-pool/include/task_pool/task_pool.h
```
This seems to tell me that a gcov file was found (task_pool.h is my main header) and it found a `gcda` was able to associate it with the `task_pool.h` include but then tells me nothing of what the outcome was of this exchange...did it produce some results? was the task_pool.h file filtered out?

**Comment by Spacetown** [comment]
The following line shows that the file is excluded:
```
(DEBUG)   Filtering coverage data for file /home/runner/work/task-pool/task-pool/include/task_pool/task_pool.h
```

You define `--root ../lib` which results in a filter for the root directory:
```
(DEBUG)  - DirectoryPrefixFilter(/home/runner/work/task\-pool/task\-pool/lib/)
```

Your file is in `/home/runner/work/task-pool/task-pool/include` which is excluded by this filter.

**Comment by benny-edlund** [comment]
This turns out to be the GCC version...the CI was running gcc-11 and after coming across this [ticket](https://github.com/gcovr/gcovr/pull/597) that you were assisting on @Spacetown I reverted the CI to use gcc-9 for the reporting job and then magically it worked fine.

So perhaps the linked commit was a red herring as I was trying to change repo structure around but it certainly is not the actual problem.

Before reverting the GCC version I also tried `fastcov` and after using that for a while (they have a bit more helpful verbose reporting) I could exclude my project being the culprit and that the problem must lie with gcov itself or gcc which then led me to the ticket above.

I do see some work was committed against that in April which should be in the 5.2 release i think however it would seem to me that the problem still persists.

**Comment by Spacetown** [comment]
??? Is the problem solved?

**Comment by benny-edlund** [comment]
This is not causing me trouble any longer as using an older version of gcc avoids the issue. Seems still there might be trouble with using gcovr with gcc versions greater then 9 which seems to be a problem

**Comment by Spacetown** [comment]
Gcovr works with this versions. The problem is that the version of gcov has to match the version of GCC. If you use gcc-11 you also need to use gcov-11.
