### ISSUE TITLE
All reports are empty

### ISSUE THREAD

**Issue by MichaelBMiner** [gcovr/gcovr#709]
Hello,

I am using ceedling and gcov in my jenkins pipeline.  When I run the command 
`ceedling clobber gcov:all utils:gcov`

I get the output
```
--------------------------
GCOV: OVERALL TEST SUMMARY
--------------------------
TESTED:  20
PASSED:  20
FAILED:   0
IGNORED:  0


---------------------------
GCOV: CODE COVERAGE SUMMARY
---------------------------
StopArm_Average.c Lines executed:100.00% of 29
StopArm_Average.c Branches executed:100.00% of 2
StopArm_Average.c Taken at least once:100.00% of 2
StopArm_Average.c Calls executed:100.00% of 1

keazxx_temp.c Lines executed:50.00% of 34
keazxx_temp.c Branches executed:100.00% of 4
keazxx_temp.c Taken at least once:75.00% of 4
keazxx_temp.c No calls

StopArm_Analog.c Lines executed:64.29% of 126
StopArm_Analog.c Branches executed:80.00% of 30
StopArm_Analog.c Taken at least once:63.33% of 30
StopArm_Analog.c Calls executed:62.86% of 70

Could not find coverage results for pneumatic_production/src/Heath_Check.c
Could not find coverage results for pneumatic_production/src/Production_Control.c
Could not find coverage results for pneumatic_production/src/main.c

```

When I open GcovCoverageCobertura.xml or GcovCoverageCobertura.html. The files are just shells. I have attached the reports and my project.yml. 

I am using a similar setup in another project and the coverage reports are generated just fine. Can anyone help me get these up and running?

[GcovCoverageCobertura.xml.txt](https://github.com/gcovr/gcovr/files/10539842/GcovCoverageCobertura.xml.txt)
[GcovCoverageResults.html.txt](https://github.com/gcovr/gcovr/files/10539844/GcovCoverageResults.html.txt)
[report.xml.txt](https://github.com/gcovr/gcovr/files/10539845/report.xml.txt)
[project.yml.txt](https://github.com/gcovr/gcovr/files/10539850/project.yml.txt)

**Comment by Spacetown** [comment]
Your YML files and report do not help for investigation.
We need a full log with the command line of gcovr (maybe with additional option `--verbose`).

**Comment by MichaelBMiner** [comment]
Here is the output log of my command. 
[test_out.txt](https://github.com/gcovr/gcovr/files/10540072/test_out.txt)

**Comment by Spacetown** [comment]
Your gcovr command is:
```
gcovr --root "." --exclude "^vendor.*|^build.*|^test.*|^lib.*" --branches --sort-percentage --xml-pretty --xml  "build/artifacts/gcov/GcovCoverageCobertura.xml" --html-details --html-medium-threshold 70 --html-high-threshold 90 --html  "build/artifacts/gcov/GcovCoverageResults.html
```

And as I can see your source files are in the directory `build` and `libraries` which both match your exclude RegEx.

**Comment by MichaelBMiner** [comment]
I do not call gcovr myself. This is called with ceedling clobber gcov:all utils:gcov. I need to find why this is happening.

**Comment by MichaelBMiner** [comment]
Got it resolved. The default setting for gcovr is    ` :report_exclude: "^vendor.*|^build.*|^test.*|^lib.*"`
I edited my project.yml. I changed the report exclude setting to `:report_exclude: "^vendor.*|^test.*|^lib.*"`. My reports now show properly!

**Comment by MichaelBMiner** [comment]
I spoke too soon. I now get code coverage reports for the mocks and runners not the code itself.

**Comment by MichaelBMiner** [comment]
Updating it to `    :report_exclude: "^vendor.*|^build.*|^test.*"` fixed it. I get reports for the source files only now!
