### ISSUE TITLE
Coverage is randomly 0%

### ISSUE THREAD

**Issue by MartinDelille** [gcovr/gcovr#722]
**Describe the bug**

I have unconsistent coverage computation with gcovr on my CI powered by gitlab-runner.

**To Reproduce**
1. I have a Qt project that I compile on Mac using clang using the following configuration:

```
QMAKE_CXXFLAGS += --coverage
QMAKE_LFLAGS += --coverage
```

2. Compilation and test execution happens on the CI
3. The CI then run gcovr with the following commands: `gcovr --verbose --print-summary --output coverage.xml
` and configuration:
```
filter = libs/
exclude = .*/test/.*
exclude-unreachable-branches = yes
exclude-throw-branches = yes
```
4. The gcovr execution randomly fails:

```
lines: 0.0% (0 out of 11361)
functions: 0.0% (0 out of 2081)
branches: 0.0% (0 out of 30884)
```
5. If I restart the CI job, it usually succeeds.

I'm using the shell executor for gitlab-runner so the job are not totally isolated (no idea how to run virtual containers on mac), but I haven't suffer any issue with it for now but there might be a way to investigate if I had an idea how to proceed.

**Expected behavior**

Here is the coverage result when it is computed successfully
```
lines: 75.6% (9578 out of 12674)
functions: 73.1% (1521 out of 2081)
branches: 38.4% (11868 out of 30884)
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.5.1
 - GCC version : apple-clang 14.0
 - GCOVR version : 5.2
 - Project directory layout:
   - Roots: /Users/build3/builds/UFDawepC/0/myorg/myproject
   - Object directories: /Users/build3/builds/UFDawepC/0/myorg/myproject

**Additional context**

I of course tried to enabled `--verbose` option and tried to diff the result but unfortunately the diff was to huge since the files weren't processed in the same order making hard to understand what is the difference between the two executions.

**Comment by Spacetown** [comment]
Sorry, without any log we can't check this.

**Comment by MartinDelille** [comment]
Ok I can't manage to reproduce it. I might had a configuration issue that is solved now so I just close the issue and I'll reopen it if it happens again.
