### ISSUE TITLE
gcovr is showing wrong coverage when there is `throw` statement even after "--exclude-throw-branches"

### ISSUE THREAD

**Issue by honey-speaks-tech** [gcovr/gcovr#724]
**Describe the bug**
gcovr is showing branches uncovered when there is a throw statement even after having unit tests written covering the throw statement and having `--exclude-throw-branches` as option.

**To Reproduce**
1. Class and its unit test available in https://godbolt.org/z/jT7sEc1h3
2. Please check the coverage of this code using gcovr.

**Expected behavior**
100% line coverage and 100% branch coverage.

**Screenshots**
![image](https://user-images.githubusercontent.com/2928745/220115475-5ac6eada-f133-43a4-b949-7ec83079c642.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - GCC version 12.0 used for coverage testing / for compiler explorer example, worked with 10.1 as unit tests are not compiling in 12.0
 - GCOVR version 5.0

**Additional context**
Not applicable

**Comment by Spacetown** [comment]
Please provide a log with gcovr option `--verbose`.

**Comment by Spacetown** [comment]
@honey-speaks-tech Can this be closed?

**Comment by Spacetown** [comment]
Closing because of no response.
