### ISSUE TITLE
Automatically use `SOURCE_DATE_EPOCH`

### ISSUE THREAD

**Issue by Pesa** [gcovr/gcovr#728]
**Is your feature request related to a problem? Please describe.**

The `--timestamp` option added in 5.1 is great. However, it would be even better for gcovr to use the standardized `SOURCE_DATE_EPOCH` environment variable by default, if defined, without having to specify a command-line flag. With this small enhancement, gcovr will be able to generate reproducible results out-of-the-box.

**Describe the solution you'd like**

If `SOURCE_DATE_EPOCH` is defined in the environment, use it as default value for the `--timestamp` option. If `--timestamp` is specified on the command line, it should override the env variable.

**Describe alternatives you've considered**

N/A

**Additional context**

https://reproducible-builds.org/docs/source-date-epoch/
https://reproducible-builds.org/specs/source-date-epoch/

**Comment by latk** [comment]
I love Reproducible Builds. This is a great idea, thank you.

**Comment by latk** [comment]
Oh nice, lcov also implemented this feature in https://github.com/linux-test-project/lcov/commit/cdde0d68ec6ac00fb326541e5a03d152fd629b29 (see https://github.com/linux-test-project/lcov/issues/197)
