### ISSUE TITLE
`--keep` should be the default

### ISSUE THREAD

**Issue by SixthDot** [gcovr/gcovr#730]
files generated by the executable should not be deleted "by default".

**Comment by Spacetown** [comment]
The intention here is that you need to delete them before the next run. If you miss this the counters are ifor the next run are added.

**Comment by SixthDot** [comment]
I dont agree because the language runtime may delete them or accumulate results.

**Comment by Spacetown** [comment]
But the report generation is a reset of the counters. If a project doesn't want this behaviour it can uses the option `--keep`.  That was a design decision in the past and I don@t want to change the behaviour. @latk what's your opinion here?

**Comment by SixthDot** [comment]
alright then !
