### ISSUE TITLE
gcovr is showing wrong coverage during the initialization of a variable

### ISSUE THREAD

**Issue by argonautha90** [gcovr/gcovr#732]
**Describe the bug**
gcovr is showing wrong coverage during the initialization of a variable

**To Reproduce**
1. Code and related unit test available here: https://godbolt.org/z/6Ghboezff
2. Please check the coverage of this code using gcovr.

**Expected behavior**
100% line coverage and 100% branch coverage.

**Screenshots**
![image](https://user-images.githubusercontent.com/49536164/221378926-b6abc1d5-08e5-41ca-b27f-57bc72e01378.png)

**Desktop:**
 - OS: Linux
 - GCC 12
 - GCOVR 5.2
 
**Additional context**
Not Applicable

**Comment by Spacetown** [comment]
Can you provide the gcov file instead of the link?

**Comment by argonautha90** [comment]
Thanks for your reply. What do you mean with "gcov file" exactly?

**Comment by Spacetown** [comment]
If you run `gcovr` with the option `--keep` the created files with the extension `.gcov` will not be deleted. In one of this files your code should be mentioned with the branches. This file we need.

**Comment by honey-speaks-tech** [comment]
Can you please let us know the name of the file which you are specifically interested in? As we know, gcovr artifacts is a folder containing many files, just need to understand which file you will be interested in.

**Comment by Spacetown** [comment]
The name of the file depends on your project. You need to grep the gcov files containing the sourceline from your screenshot.

**Comment by Spacetown** [comment]
Close because resolved by reporter.
