### ISSUE TITLE
"Directory" in HTML report header is always `./`

### ISSUE THREAD

**Issue by Pesa** [gcovr/gcovr#744]
**Describe the bug**
I would expect "Directory:" in the HTML report header (using `--html-nested` or `--html-details`) to use the value of the `--root` option, but it seems that it's always `./`

**To Reproduce**
1. just run `gcovr --html-nested out/ --root src build` or similar

**Screenshots**
<img width="340" alt="Screenshot 2023-03-08 at 11 11 20 PM" src="https://user-images.githubusercontent.com/83452/223915529-e51f7adc-eea0-4e96-88ac-da2086de4e64.png">

**Desktop (please complete the following information):**
 - OS: Linux
 - GCC version 12.2.0
 - GCOVR version 6.0

**Comment by Spacetown** [comment]
It's always the common path of the files in the report and this part is removed from the file listings below.
Before getting the common path the value of `--root` is removed from the file paths. I thought there we have an example for this but that's not the case.

**Comment by Pesa** [comment]
> It's always the common path of the files in the report and this part is removed from the file listings below. 

Ah, then what I'm seeing is the intended behavior, I guess. I am indeed seeing the behavior you describe if I use `--filter src/` instead of `--root src/`. However, not using `--root` makes gcovr 2.5x slower on this codebase.

**Comment by Pesa** [comment]
> I am indeed seeing the behavior you describe if I use `--filter src/` instead of `--root src/`.

Correction: the above was with `--html-details --filter ...`. With `--html-nested --filter ...` I am seeing a different behavior: there is a single directory at the top level of the report, "Directory" in the header is still `./`, and I don't see the common path (the lone top-level dir) being stripped from the file names in the list below.

**Comment by Pesa** [comment]
I am simply saying that, with `--html-nested`, I do *not* see the behavior you described in your earlier comment regarding the "common path" and all that. I'll try and send a screenshot later today if it's still unclear.

**Comment by Spacetown** [comment]
Do you mean e.g. in https://github.com/gcovr/gcovr/blob/master/gcovr/tests/html-nested-nonsort/reference/gcc-5/coverage_nested.A.7fc56270e7a70fa81a5935b72eacbe29.html? There is no ./A/ as directory because this value is evaluated over all files and not for each directory level.

**Comment by Pesa** [comment]
### Output of `--html-details --filter ndn-cxx/`

<img width="1000" alt="details" src="https://user-images.githubusercontent.com/83452/224187594-4b8ba350-08d4-4c4f-8695-60cdc385968a.png">

### Output of `--html-nested --filter ndn-cxx/`

<img width="1000" alt="nested" src="https://user-images.githubusercontent.com/83452/224187608-b72e68bd-ae58-4d55-94ba-e55b4e1b5912.png">

**Comment by Spacetown** [comment]
Now I understand. I need to check this but have an idea:
The common path is removed in the HTML report generation where the evaluation of the directory coverage is done in the data model.

**Comment by Pesa** [comment]
TBH, I'm not really sure what the behavior should be in this case and I don't really have any preference. Maybe the current behavior is already ok.

In fact, my original issue/question was about `--root` instead of `--filter`. I think it would be reasonable to add the directory specified in the `--root` option to the "Directory" line in the header of the HTML report (in addition to the calculated "common path", if there is any). But as you said, this behaves as designed right now, so if you don't want to change the current behavior, I understand.

**Comment by Spacetown** [comment]
I'm investigating but agregating the directory coverage is a little bit wired. Instead of a object structure a local dict is used.

**Comment by Spacetown** [comment]
@Pesa Pleas can you verify the linked PR?
