### ISSUE TITLE
`--print-summary` and `--decisions`

### ISSUE THREAD

**Issue by Pesa** [gcovr/gcovr#745]
**Describe the bug**
`gcovr --decisions --print-summary` prints:

```
lines: 90.1% (13347 out of 14816)
functions: 91.2% (2338 out of 2565)
branches: 56.9% (14099 out of 24788)
calls: 0.0% (0 out of 0)
```

i.e., a summary of decision coverage is *not* printed.
On the other hand, the "calls:" line is always printed, regardless of the `--calls` option.

**Expected behavior**
* Show decision coverage summary when `--decisions` is specified.
* Do not print (nonsensical) calls coverage unless `--calls` is specified.

**Desktop (please complete the following information):**
 - OS: Linux
 - GCC version 12.2.0
 - GCOVR version 6.0

**Comment by Spacetown** [comment]
Thank you for reporting this. I'll take a deeper look the next days.

**Comment by Spacetown** [comment]
To be straight forward we should only print the branch summary if option `--branches` is used. Or what do you think?

**Comment by Pesa** [comment]
Technically that would be an incompatible change, albeit minor? Moreover, the doc for `--branches` says:

> Report the branch coverage instead of the line coverage. For text report only.

The "instead of" semantics makes it problematic to use (though personally I don't use `--txt` output)... Unless you're proposing to change that behavior too... That being said, branch coverage is always enabled for all other output formats.

**Comment by Pesa** [comment]
So, my humble suggestion is to not change anything regarding branch summary, since it's longstanding behavior.

In fact, you could always print all coverage types, including calls and decisions, with `--print-summary`, unless there are performance implications in calculating them. This would be a valid resolution IMHO, since `--decisions` and `--calls` are documented to affect only the HTML and JSON outputs...

**Comment by Spacetown** [comment]
Okbthat sounds reasonable. Lines functions and branches are always printed. The decisions and calls only if the option is given.

**Comment by Spacetown** [comment]
The decision and call information is only available if the option is given. Decisions cost time because the code is analyzed. Calls cost no time but in your example it has no information.
I tend to print them depending on the options.

**Comment by Pesa** [comment]
That's fine with me.
