### ISSUE TITLE
gcovr is showing uncovered line after final return statement

### ISSUE THREAD

**Issue by MartinDelille** [gcovr/gcovr#746]
**Describe the bug**

gcovr is showing uncovered line after final return statement.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2023-03-09 at 12 05 54](https://user-images.githubusercontent.com/879889/224006430-80500e91-10bc-4146-8752-b58802be0d42.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.1
 - Apple clang version 14.0.0
 - GCOVR version 6.0
 - Project directory layout:
   - Roots: .
   - Object directories: libs

**Additional context**

**Comment by Spacetown** [comment]
This behavior is mentioned in the changelog of the `6.0`:
- New option `--exclude-noncode-lines` to exclude noncode lines. Noncode lines are not excluded by default anymore. (#704, #705)

This is because to have the same coverage than gcov by default.
