### ISSUE TITLE
What is the default output for gcovr branch coverage?

### ISSUE THREAD

**Issue by eb-jotr** [gcovr/gcovr#748]
When testing GCOVR it looks like that the output for branch coverage not only takes care about the C1 coverage (Decision coverage where each path is executed once in an if condition for example) but additionally MC/DC (Modified Condition / Decision Coverage)
As per the FAQ the real C1 for C/C++ is reported using the gcovr -- decisions flag as "Decisions" coverage. Is it somewhere documented what gcovr reports as branch coverage by default?

Note: The term branch coverage is used differently and there are multiple definitions.

Thanks in advance for your help

**Comment by Spacetown** [comment]
We're using the branches which `gcov` is showing. Since `gcov` is counting the branches generated by the compiler it is like MC/DC coverage.

**Comment by eb-jotr** [comment]
Thanks @Spacetown  so C1 branch coverage referenced by ISO can be done using flag --decisions

**Comment by Spacetown** [comment]
> Thanks @Spacetown so C1 branch coverage referenced by ISO can be done using flag --decisions

Yes.
