### ISSUE TITLE
verbose output vs multithreading

### ISSUE THREAD

**Issue by mulawamichal** [gcovr/gcovr#751]
When running gcovr with `--verbose` option and `-j <whatever>` it is hard to read the log, as multiple thread overlap their output. It would be nice to be able to filter it somehow. 

Simples solution that comes into my mint os simply add some thread "id" (number) at line begin. something short - `TH-01` or whatever else simillar

**Comment by Spacetown** [comment]
Thank you for reporting this. The logging is thread safe but the lines itself can be mixed. I'll create a PR for this.

**Comment by Spacetown** [comment]
@mulawamichal Is the linked PR what you expect?

**Comment by mulawamichal** [comment]
looks fine
