### ISSUE TITLE
Mac: unable to generate html

### ISSUE THREAD

**Issue by lpapp** [gcovr/gcovr#753]
Does not work: gcovr --html-details coverage_mac.html

```
(WARNING) File build/GzeGen/CMakeFiles/DecryptFile.dir/DecryptFile_autogen/mocs_compilation.cpp not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File build/GzeGen/CMakeFiles/GzeGen.dir/GzeGen_autogen/mocs_compilation.cpp not found: FileNotFoundError(2, 'No such file or directory')

(ERROR) Error occurred while printing reports
```

This only happens on my Mac. Linux works.

Also, on Mac, generating self-contained html without the details also works, but then I do not get the details:

`gcovr --html coverage_mac.html`

Interestingly enough, cobertura xml generation also works. Not sure what is particular about the html details.

Would it be possible to exclude some offending details as a workaround?

**Comment by lpapp** [comment]
`--exclude '(.+/)?mocs_compilation\.cpp$'` worked the issue around on my Mac.

Yep, ran verbose earlier, the last three lines of the generated files were:

```
(WARNING) File build/x64-Release/GzeGen/CMakeFiles/DecryptFile.dir/DecryptFile_autogen/mocs_compilation.cpp not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File build/x64-Release/GzeGen/CMakeFiles/GzeGen.dir/GzeGen_autogen/mocs_compilation.cpp not found: FileNotFoundError(2, 'No such file or directory')
(ERROR) Error occurred while printing reports

```
It is something to do with these mocs_compilation.cpp files, that are auto-generated, because if I exclude them, it works.

**Comment by Spacetown** [comment]
And the same project is working on Linux???

**Comment by macetw** [comment]
If it is working on Linux, could it be that this file occurs twice because of a case-sensitivity difference? (Most MacOS volumes are case-insensitive, which make for different behavior)

Those files `mocs_compilation.cpp.o` and `mocs_compilation.cpp.gcno` are derived from `mocs_compilation.cpp`. Could it be this file is entirely in a different place? Could there be a symlink that exists but points to a file that doesn't exist?  (setting aside the bash-<TAB> result, bash auto-completion might ignore those kinds of files)

**Comment by Spacetown** [comment]
> If it is working on Linux, could it be that this file occurs twice because of a case-sensitivity difference? (Most MacOS volumes are case-insensitive, which make for different behavior)

That's wrong, by default they are case sensitive (I'm working with MacOS).

Can you compare the verbose log of cmake? On Linux the files should also be used the same way.

**Comment by Spacetown** [comment]
On the Mac you use a LLVM based gcc and `"llvm-cov gcov` to generate the `.gcov` files. Can you use the option `--keep` on both systems and compare the `.gcov` files?

**Comment by lpapp** [comment]
Thanks.

I ran this command on both systems:

`gcovr --html-details=coverage.html --keep --gcov-ignore-parse-errors`

E.g. this is what I get on Linux:

```
find . -name \*.gcov | grep GzeGen
./GzeGen.cpp##a4310cee0ee0322bb43982b29426c1d0.gcov
./build/x64-Release/Plugins/Geometry/CMakeFiles/GeoCube.dir/src/GzeGen.cpp##a4310cee0ee0322bb43982b29426c1d0.gcov

```
And then this on Mac:

```
find . -name \*.gcov | grep GzeGen
./GzeGen.cpp.gcno.pointer_traits.h##4ae3cbbd3c247fa2a454aa5359424651.gcov
./GzeGen.cpp.gcno.unique_ptr.h##faaf6c60421268e41765c7cd8a592ba2.gcov
./GzeGen.cpp.gcno.GzeGen.cpp##288b971845a35c20b9c79ef6029fd6c7.gcov
./GzeGen.cpp.gcno.forward.h##4d245d795dd97adc43f8cd857a883c88.gcov
./GzeGen.cpp.gcno.comp.h##3ab634489ea62e69d8ecf9de865faac5.gcov
./GzeGen.cpp.gcno.fstream##e210ffd6a76d3f3fc9a7d1910849bafc.gcov
./GzeGen.cpp.gcno.move.h##b962364907a70df241b2652f8b750ca9.gcov
./GzeGen.cpp.gcno.__locale##6931866373648ea3efb5ff23897a601d.gcov
./GzeGen.cpp.gcno.locale##6a9c925a88672b1a024ae11411cfb218.gcov
./GzeGen.cpp.gcno.string##4914da67b4dc835e467440e04d551b78.gcov
./GzeGen.cpp.gcno.addressof.h##dce7a1b8fe065448982cce248989b45a.gcov
./GzeGen.cpp.gcno.new##c8248d0c10c8a902d7ffa4776cad83da.gcov
./GzeGen.cpp.gcno.__string##5308f569ee7da86bb4f7a7d2e3bf0fea.gcov
./GzeGen.cpp.gcno.allocator.h##054382a03463af1d8a7b35d24d728e31.gcov
./GzeGen.cpp.gcno.typeinfo##fc56b3d51a59dc23f2e5aef8c29ab8f2.gcov
./GzeGen.cpp.gcno.ios##71a98a0ebdfe57418d96324cc92f38c4.gcov
./GzeGen.cpp.gcno.allocator_traits.h##32e4317e691d1c286f1fa4216cf66803.gcov
./GzeGen.cpp.gcno.ostreambuf_iterator.h##c142c692fd0b5495354d5cc1e0e783ff.gcov
./GzeGen.cpp.gcno.compressed_pair.h##478becee3202634787394b26fa4fb4df.gcov
./GzeGen.cpp.gcno.ostream##3fd775785662b3b7b50a86a8fb483ab6.gcov
./GzeGen.cpp.gcno.stdexcept##289e97eed83d397e80e6401a6b269265.gcov
./GzeGen.cpp.gcno.istream##c1e06682e9f4696078dff9962a328bcf.gcov
./GzeGen.cpp.gcno.max.h##aa6bc4c0d21ae76caf8a2376a65c149b.gcov
./GzeGen.cpp.gcno.min.h##64a67f7f623490d07af02f41d45a406e.gcov
./build/x64-Release/GzeGen/mocs_compilation.cpp.gcno.mocs_compilation.cpp##9ae504acc66862374e5926e3debe6f20.gcov
./build/x64-Release/GzeGen/mocs_compilation.cpp.gcno.mocs_compilation.cpp##edbabdffac6b82414bfc3199616e89da.gcov
./GzeGen.cpp.gcno.iosfwd##cd5e2ef1a1fec69637f34be5e0f113e1.gcov
./GzeGen.cpp.gcno.streambuf##e2657e47f88bd433422a67ba0e93f722.gcov
```

**Comment by Spacetown** [comment]
Here you can see that on Mac the coverage for this file is generated but not on Linux. You've to dig into your build here.

**Comment by Spacetown** [comment]
@lpapp Any progress here?
