### ISSUE TITLE
Optimising the report generation for one source file

### ISSUE THREAD

**Issue by lpapp** [gcovr/gcovr#754]
Hi,

Is it possible to speed up the coverage html generation?

I am trying to filter for one particular source file in my project which has less than 1000 LOC. But I still need to wait for 10-15 minutes that the html for it gets generated. I am using the following command:

`gcovr --html-details=coverage.html --gcov-ignore-parse-errors --filter foo/bar/baz.cpp -v > gcovr.log 2>&`

This is on Mac, but it is also slow on Linux.

I started reading https://gcovr.com/en/stable/guide/filters.html#speeding-up-coverage-data-search -> but I have not fully understood it. Sorry about that.

The use case for my optimisation: I am writing some automated tests against a specific source file and would like to get the results to see how much my automated tests have improved the coverage for that particular file.

Thank you in advance!

**Comment by Spacetown** [comment]
As mentioned in the docs which you've linked, the call of the `gcov` tool is the time consuming part.
If you need to wait 10-15 minutes you probably have a lot of instrumented files in your output directory. If you only want to get the result for a specific C/CPP file you can call `gcovr` in the directory where the object of this file is generated.

**Comment by lpapp** [comment]
Thanks. For some reason, that does not seem to catch the coverage in the file. Do you know why?

```
(devenv) lpapp@FLMBP001 src % gcovr --html-details=coverage.html --gcov-ignore-parse-errors 
(devenv) lpapp@FLMBP001 src % open coverage.html
(devenv) lpapp@FLMBP001 src % ls
GeoCube.cpp.gcda        GeoCube.cpp.o           coverage.functions.html
GeoCube.cpp.gcno        coverage.css            coverage.html
(devenv) lpapp@FLMBP001 src % pwd
/Users/lpapp/Projects/nuke/build/x64-Release/Plugins/Geometry/CMakeFiles/GeoCube.dir/src
(devenv) lpapp@FLMBP001 src % 
```

![Screenshot 2023-03-21 at 10 42 54](https://user-images.githubusercontent.com/141957/226583489-9b917910-919a-437b-a548-5fcdc5380580.png)

**Comment by Spacetown** [comment]
With the option `--exclude=...` you can exclude files from being used. If that's not possible for you you can run `gcov` for the needed `gcda` files on your own and use the option `--use-gcov-files`.

**Comment by lpapp** [comment]
Thanks. I will try that tomorrow. Never used gcov before, so I do not know how to run it on my own. Will try to figure out.

This raises some usability issues with gcovr though. Would it make sense to add some options / control to gcovr to achieve it without having to go directly to gcov?

Opting out with --exclude is not scalable with over 2000-3000 files. I would need an option instead to opt into a specific coverage.

**Comment by Spacetown** [comment]
Option `--exclude-directories` you can exclude directories by using regular expression. Why do you generate coverage for 2000-3000 files if you're only interested in one.

**Comment by lpapp** [comment]
1. I would prefer a simple opt-in with exactly match instead of a really complex regex.

2. I am generating 2000-3000 files because I am interested in all of them one at a time subsequently without the huge overhead of rebuilding the project every single time and each 2000-3000 files taking 90 minutes.

**Comment by Spacetown** [comment]
@lpapp Can you check the linked PR?
