### ISSUE TITLE
Failure when several gcovr instances are launched concurrently

### ISSUE THREAD

**Issue by oleurodecision** [gcovr/gcovr#756]
**Describe the bug**
The issue occurs in our CI (jenkins), when trying to generate reports for several coverage data at the same time (one report per configuration).

**To Reproduce**

1. gitclone the project, the root directory contains (mainly) CMakeLists.txt, source folder
2. build the source for several configurations, the root directory now contains builds/conf1, builds/conf2, ...
3. launch tests in parallel  to produce coverage data, gcda/gcno files are in the builds/conf1, builds/conf2, etc...
4. launch gcovr in parallel to produce coverage reports, see it fails
  - command line (that can probably  be improved ?) for configX is like  
```bash
gcovr \
  --gcov-executable /usr/bin/gcov \
  --root /my/project/root \
  --object-directory /my/project/root/builds/configX \
  --exclude ".*/tests/src/.*" \
  --exclude ".*/unit_tests/src/.*" \
  --exclude ".*/func_tests/src/.*" \
  --branches \
  --exclude-unreachable-branches \
  --exclude-throw-branches \
  --sort-percentage \
  --html --html-details /my/project/root/builds/configX/coverage-reports/gcovr/index.html \
  --xml --xml-pretty --output /my/project/root/builds/configX/coverage-reports/gcov-results.xml \
  # end of args
```

**Expected behavior**
Calling gcovr on different object directory, at the same time, should not be an issue.

Gcovr 5.0 did not have the issue. Tracing behaviour changes (with `--verbose` call shows that gcovr 5.0 calls gcov in some temporary directory

```
Running gcov: '/usr/bin/gcov /my/project/root/builds/configX/src/lib1/CMakeFiles/mylib.dir/src/SomeSrc.cpp.gcda \
	--branch-counts \
	--branch-probabilities \
	--preserve-paths \
	--object-directory /my/project/root/builds/configX/src/lib1/CMakeFiles/mylib.dir/src' in '/tmp/tmp1sck169l'
```

while 5.1 and later calls gcov in the project source tree (that is quite ... unpretty ;)) ...
```
(DEBUG) Running gcov: '/usr/bin/gcov /my/project/root/builds/configX/src/lib1/CMakeFiles/mylib.dir/src/SomeSrc.cpp.gcda \
	--branch-counts \
	--branch-probabilities \
	--demangled-names \
	--hash-filenames \
	--object-directory /my/project/root/builds/configX/src/lib1/CMakeFiles/mylib.dir/src' in '/my/project/root'
```
Working directly in the (same) source tree should then trigger some race condition between gcov generated .gcov files 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Debian 11.6 (same behaviour on 9.13)
 - GCC version 10.3.0 
 - GCOVR version 5.1, 5.2, 6.0
 - Project directory layout:
```
.                                      <- root
├── builds 
│   ├── config1                        <- object-directory for config1
│   │   ├── cmake
│   │   ├── CMakeFiles
│   │   ├── coverage-reports
│   │   │   ├── gcovr
│   │   │   └── lcov
│   │   └── src
│   └── config2                        <- object-directory for config2
│       ├── cmake
│       ├── CMakeFiles
│       ├── coverage-reports
│       │   ├── gcovr
│       │   └── lcov
│       └── src
├── cmake
├── scripts
└── src
    ├── exe
    ├── lib1
    ├── lib2
    └── unit_tests
```  

**Additional context**
Note that enabling/disabling gcov parallel calls does not modify the behaviour.

**Comment by oleurodecision** [comment]
By the way, thanks for all the 'recent' enhancements, gcov parallel calls, multiple output formats, gcovr has always be a pleasure to work with this tool :+1:

**Comment by oleurodecision** [comment]
wow ! such a quick answer ! thanks.

Reworked the args as suggested, no improvement alas.

Pushed some [test project](https://github.com/oleurodecision/gcovr_parallel_call) that is failing as described in the issue, if it can help.  
Note that the github actions was more for my own knowledge than as a real exemple.

**Comment by Spacetown** [comment]
Can you also remove the option `--root`? This option is used as default search directory.

**Comment by oleurodecision** [comment]
# Short answer

Thanks for your advices. Using them, playing with the command line and looking at the (gcovr) source code, I finally managed to find proper ways of doing things.

I was confused by some parts of the documentation ([Command Line Reference](https://gcovr.com/en/stable/manpage.html#command-line-reference), [Out-of-Source Builds with CMake](https://gcovr.com/en/stable/cookbook.html#id3)), thus having incorrect (well, missing) arguments.

Fell free to close the issue, and/or ask me if you want me to submit proposal for documentation update (in the Cookbook section ?)

Thanks anyway for the time spent, we'll be happily moving to more recent gcovr versions now :clap: 

# Long answer

## Project layout

```text
project
├── src
│   ├── my_lib
│   └── my_exe
└── builds
    ├── config1
    ├── config2
    └── ...
```

In the next sections, the `project` directory is refered as `$SOURCE_DIR`, and the `builds/configX` directories as `$BUILD_DIR`.

## If workdir is the root directory

I succeded launching parallel gcovr calls using the following command line :

```bash
cd $SOURCE_DIR
gcovr --gcov-executable "/usr/bin/gcov" \
	--object-directory $BUILD_DIR \
	$BUILD_DIR		
```

- `--object-directory $BUILD_DIR` is required to have the *expected* object files found
- `$BUILD_DIR` (as search path) is required to specify where to search the object files 

If `$BUILD_DIR` (a search path) is omitted, object files from other build directories are processed (thus, incorrect coverage values)
If `--object-directory` is omitted, the potential working directories are root directory (aka $SOURCE_DIR), followed by object file parent directories, then gcov is called using the root directory (first candidate) as a working directory, 
which implies all gcov result files will be generated as the root directory, which implies race conditions when triggering several gcovr calls.  

## If workdir is the build directory

I succeded launching parallel gcovr calls using the following command line :

```bash
cd $BUILD_DIR
gcovr --gcov-executable "/usr/bin/gcov" \
	--root $SOURCE_DIR \
	--object-directory $BUILD_DIR \
	$BUILD_DIR
```

- `--root $SOURCE_DIR` is required to have the source files found
- `--object-directory $BUILD_DIR` is required to have the *expected* object files found
- `$BUILD_DIR` (as search path) is required to specify where to search the object files 


If `$BUILD_DIR` (a search path) is omitted, object files from other build directories are processed.  
If `--object-directory` is omitted, the potential working directories are root directory (aka $SOURCE_DIR), followed by object file parent directories, then gcov is called using the root directory (first candidate) as a working directory, which implies all gcov result files will be generated as the root directory, which implies race conditions when triggering several gcovr calls.  
If `--root $SOURCE_DIR` is omitted, source files are not found ;)

**Comment by Spacetown** [comment]
I'm wondering why our cake test is working without this options. It seems that they are only relevant for parallel processing. In this case this problem isn't related to cmake.

Can you check if it's possible to generate the reports with your old options without parallel execution?

I can try to create a test for the parallel execution without cmake.
I appreciate if you can raise a PR for describing the setup of this use case.

**Comment by Spacetown** [comment]
@oleurodecision Can this be closed?

**Comment by oleurodecision** [comment]
Hi,

Thanks for the reminder, I was (really) busy last months (lots of hot subjects to work on, my partner was transferred thus we had to move, perfect 😉), I was planning to work on the subject this end of week or next week.

I'll prioritize it for this end of week then.
Thanks for the (too long) waiting, and thanks for the tool itself !

OL.
________________________________
De : Michael Förderer ***@***.***>
Envoyé : vendredi 15 septembre 2023 22:08
À : gcovr/gcovr ***@***.***>
Cc : Olivier LIESS ***@***.***>; Mention ***@***.***>
Objet : Re: [gcovr/gcovr] Failure when several gcovr instances are launched concurrently (Issue #756)


@oleurodecision<https://github.com/oleurodecision> Can this be closed?

**Comment by Spacetown** [comment]
Close this since the PR for the test case is opened.
