### ISSUE TITLE
what do these data mean in gcovr 6.0?

### ISSUE THREAD

**Issue by fchn289** [gcovr/gcovr#757]
![image](https://user-images.githubusercontent.com/100677967/227755022-174056c4-1fc6-420c-a43c-a2226c9017bb.png)

src code is here: https://github.com/nokia/domino-library/blob/main/src/domino/PriDomino.hpp

**Comment by Spacetown** [comment]
If you click on the error a popup is shown with detailed information. The first column shows the gcc compiler branches, the second column the result from the decision analysis if possible and the third line shows how often the line was executed.

**Comment by fchn289** [comment]
for example line#46,
- 277 means it's executed 277 times
- but what does call=0/2 mean? it should be called twice but actually not at all? it conflicts to exec=277
- branch=0/2 means there're 2 branches here but no branch is executed/covered? it conflicts with exec=259 on line#47 and exec=18 on line#49

**Comment by fchn289** [comment]
raw gcov files can be found in https://github.com/nokia/domino-library/suites/11805184675/artifacts/616195435

**Comment by Spacetown** [comment]
If you run the command `grep -F "EMsgPriority PriDomino" -C5 * > _test.txt` on the data you see that that the formats of the outputs differ. There are also some `call ... newer executed`.
