### ISSUE TITLE
Support `fail_under_decision` option in CLI

### ISSUE THREAD

**Issue by cameronbracco** [gcovr/gcovr#759]
I saw that https://github.com/gcovr/gcovr/pull/749 introduced the decisions metric produced in summary report, but that there does not seem to be a way to fail with an exit code specifically on the decision coverage percentage.

**Describe the solution you'd like**
I would be interested in a `--fail-under-decision` option being added to the CLI. In addition to the CLI itself, this would require updating the [fail_under](https://github.com/gcovr/gcovr/blob/master/gcovr/__main__.py#L61) function to properly fail under a certain decision coverage amount. This would also require updating the error codes to maintain the ability to OR them together.

**Describe alternatives you've considered**
It's possible to extract this percentage out of the reported summary and run my own check to fail under a desired percent, but that seems less elegant than adding this as a feature that would potentially be useful for others.

**Comment by Spacetown** [comment]
It would be possible but the decision coverage is more in a beta state. How shall unparsable decisions be counted?

**Comment by Codym48** [comment]
I don't immediately know how to answer this question. (What's an unparsable decision?)

We just noticed `--decisions` seems to give a more reasonable indication of issues we should go fix than `--branches`, and were hoping to use a `--fail-under-decisions` option to fail our pipeline if it drops below a threshold, similar to how we've been using `--fail-under-branch`.

With gcovr 6.0, this decision percentage is only visible in the TOTAL row of the text output, not the summary. It seems like #749 would [add it to the summary row](https://github.com/gcovr/gcovr/pull/749/files#diff-2d66856635eec1eb3a06bde33683e6164d1cec59711d1ccc6fafc0dbac82320aR4), which is great:
```
lines: 80.0% (8 out of 10)
functions: 100.0% (2 out of 2)
branches: 50.0% (4 out of 8)
decisions: 50.0% (2 out of 4)
calls: 66.7% (2 out of 3)
```
As a user, I'd expect the `--fail-under-decisions` option to use the percentages printed in the TOTAL row (and, in an upcoming release, the summary row) in its failure calculations. So I'd suggest counting unparsable decisions the same way they're counted when calculating [`stats.decision`](https://github.com/gcovr/gcovr/pull/749/files#diff-a4a43e608c44e2fef1a5e7b8dce38ca7c190d71658b96b4e6eb590dc5bac8f32R42)?

**Comment by Spacetown** [comment]
> I don't immediately know how to answer this question. (What's an unparsable decision?)

A decision with more than two branches can'tt be analyzed, see the detailes for line 249 in https://github.com/gcovr/gcovr/blob/d6cd30bc8727da6fa0a28e5567252cd3cefaa098/gcovr/tests/decisions/reference/gcc-5/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html.

**Comment by Codym48** [comment]
I see, so things like ternary operators after compound if statements show up in branch (D) and line (L) coverage metrics but are completely skipped as unparseable in decision (D) coverage:

![image](https://user-images.githubusercontent.com/34431661/229702305-1a125e80-4ebc-4128-aa8f-8c915e4ffdad.png)

I think my suggestion still holds: count unparsable decisions the same way they're counted when calculating [stats.decision](https://github.com/gcovr/gcovr/pull/749/files#diff-a4a43e608c44e2fef1a5e7b8dce38ca7c190d71658b96b4e6eb590dc5bac8f32R42).

**Comment by Spacetown** [comment]
Not the ternary operator is the problem. The problem is the logical `&&`.

**Comment by Codym48** [comment]
Thank you for the clarification.

Is there some resistance to adding --fail-under-decisions because of the existence of unparseable decisions?

**Comment by Spacetown** [comment]
Shall there also be an option for the minimum function coverage?

**Comment by Codym48** [comment]
That seems reasonable as an extension of this feature request. Stated generally: for any summary percentage gcovr reports (line, branch, decision, and function), allow the user to fail the script if that type of coverage drops below a threshold input at the command line.
