### ISSUE TITLE
The total number of rows of coverage data generated during gcov Cross Profiling and the same platform compilation runtime is inconsistent.

### ISSUE THREAD

**Issue by Ronhy0** [gcovr/gcovr#762]
I'm trying to get the code coverage by cross compiling. 
After consulting a lot of information, most of them follow the steps below:

1.Machine A completes compilation, 
2.transfers application program to machine B, 
3.machine B performs testing and generates gcda files. 
4.The gcda files are then transferred back to machine A, 
5.Based on gcda and gcno files, generating complete coverage data on machine A.

However, this does not meet our application scenario. We need to directly generate coverage data on machine B in step 4.

I now encounter a problem where the data can be generated normally, but the total number of lines of code in the data differs significantly from the actual number.
ex: 
Complete all tasks on machine A, including compiling tests and generating coverage data， the data is
14:32:45 lines: 23.8% (67538 out of 283758)
14:33:03 functions: 19.6% (7773 out of 39624)
14:33:03 branches: 13.8% (23900 out of 172627)
14:33:03 calls: 0.0% (0 out of 0)

But Compile on machine A, test on machine B, and generate coverage data. The data is as follows：
18:11:18 lines: 17.1% (23282 out of 136323)
18:11:44 functions: 20.1% (2552 out of 12708)
18:11:44 branches: 9.3% (8070 out of 86493)
18:11:44 calls: 0.0% (0 out of 0)

Do you have any suggestions or solutions？ Thanks.

**Comment by Spacetown** [comment]
Your scenario can be possible if you use the **same** GCC version on both machines. The difference can be a result of different versions. You can use the option `--keep` and compare the gcov files from both machines.

I'm not sure but as I know the gcna files are not needed for execution.

**Comment by Ronhy0** [comment]
> Your scenario can be possible if you use the **same** GCC version on both machines. The difference can be a result of different versions. You can use the option `--keep` and compare the gcov files from both machines.
> 
> I'm not sure but as I know the gcna files are not needed for execution.

I use the same GCC version, because I use the same docker image, the docker image downloaded fixed gcc version. However, thank you for your ideas on the keep parameter. I will try it.
Regarding the second point, yes, I know that testing actually only requires copying executable applications.

**Comment by Spacetown** [comment]
Is this still valid?

**Comment by Spacetown** [comment]
Closed because of no response.
