### ISSUE TITLE
How to tell gcovr to only consider files having coverage info

### ISSUE THREAD

**Issue by smod** [gcovr/gcovr#765]
Hi,

I'm having some troubles porting my build framework to gcovr from lcov, I'm interested in the cobertura report generation feature.

My project is a set of source files written by human, source files generated by robots, and source files coming from various 3rd party git submodules. I'm only interested in coverage on code written by us, and concretly I have a CMake `add_library()` target which contains all our files, onto which I add the `--coverage` compile and link flags, so that `.gcno` files are only generated for them.

Then I just want to tell gcovr "generate coverage for all files having an associated .gcda and ignore all the others".

For now, with `lcov` I just do, in my build folder:

```
lcov -c -d . -o coverage.info
```

And it just works. Is there a simple way to tell gcovr to work that way? I'm trying to play with the various filter/exclude rules but I feel like I'm missing something.

Thanks.

**Comment by Spacetown** [comment]
Do you also call gcovr in the build diorectory? What proble do you have that you tried to play with the filter/exclude options?

**Comment by Spacetown** [comment]
Close because of no response.
