### ISSUE TITLE
coverage block mismatch   , after project published ,sometimes .

### ISSUE THREAD

**Issue by thylinner** [gcovr/gcovr#774]
while running >>goc profile --center="http://xxxxx" --coverfile xxx    
return   level=fatal msg="Goc server http://xxxxx return an error: {\\"error\\":\\"error merging xxx.go: coverage block mismatch: block 
if i find  the server in  "goc list"  and remove it . it will be ok.. 
how can i avoid this happend?

**Comment by Spacetown** [comment]
Sorry, this is the gcovr project and not goc.
