### ISSUE TITLE
could not output coverage infomations

### ISSUE THREAD

**Issue by oathupdate** [gcovr/gcovr#777]
test.cpp
```
#include <stdio.h>
#include <cstdlib>
#include "test.h"
using namespace std;
class A {};
int main(int argc, char* argv[]) {
    A a;
    A *b = &a;
    if (b) {
        printf("%p\n", b);
    }
    func();
    return 1;
}
```
test.h
`
#include <stdio.h>
void func() {
    printf("test_h\n");
}
`

then i compile and run the code, generated test.gcda test.gcno
but when i rename test.h to test.hpp , and run gcovr command. there have a error
"Cannot open source file test.h"

__in my case i want ignore this error and just generate test.cpp coverage info, i do not care test.h__

![image](https://user-images.githubusercontent.com/17470690/236594583-9580c681-6ef7-4b59-9b42-3876a0e900a4.png)

**Comment by oathupdate** [comment]
like lcov i can ignore this error using  the under options
```--ignore-errors source```

**Comment by Spacetown** [comment]
This error can be ignored but then you don't get a coverage. The file is needed by gcov to generate a report.

**Comment by oathupdate** [comment]
@Spacetown but i want get other files coverage when this error occured. I just delete the regex key words to circumvent this issue, and it worked wright
https://github.com/gcovr/gcovr/commit/2b65423f4cdf429df00a680f526250bcac724590

**Comment by Spacetown** [comment]
But this is needed for the heuristic to find the correct working directory of gcc. Ignoring this error will loss data needed for later processing.

**Comment by oathupdate** [comment]
> But this is needed for the heuristic to find the correct working directory of gcc. Ignoring this error will loss data needed for later processing.

could you give me an example ? or could have an option to solve this case

**Comment by Spacetown** [comment]
In your case ignoring this error ignores the whole data of `test.cpp.gcda`.

**Comment by oathupdate** [comment]
i mean with this fix , i will get correct result which i want. and did not ignore test.cpp.gcda
https://github.com/gcovr/gcovr/commit/2b65423f4cdf429df00a680f526250bcac724590
@Spacetown 
![image](https://user-images.githubusercontent.com/17470690/236720353-c50fdf69-ae3d-4bfd-999a-678fd25e9f6b.png)


![image](https://user-images.githubusercontent.com/17470690/236720289-9c6c9580-e420-49f8-8410-b2ea356b5e6f.png)

**Comment by Spacetown** [comment]
You use the data but ignore the control comments if there would be some of them in the file. 
If you change the input by renaming a file you should rerun your test to get correct data.

Btw: Please use verbatim blocks instead of copying scrennshots of the console.

**Comment by oathupdate** [comment]
I just want to say: our project was compiled on a platform,  which  includes some third package that has xxx.h
But I run gocvr on another platform which didn't have xxx.h, so I want to ignore xxx.h to generate the coverage

**Comment by Spacetown** [comment]
You always need to run gcovr an the system which compiled the files since the internally called `gcov` is shipped with the compiler and using another version is not a good idea.

**Comment by oathupdate** [comment]
okay. you are right. but if gcovr has an option such as  `lcov --ignore-errors source`, it may be a optional way to make users handle this case which the different platform with the same compiler environment

**Comment by Spacetown** [comment]
On master the option `--gcov-ignore-errors=source_not_found` was introduced with #787. This will be available with the upcoming release.

**Comment by oathupdate** [comment]
@Spacetown oh, that's perfect.
