### ISSUE TITLE
Gcovr generate empty coverage report

### ISSUE THREAD

**Issue by jotiram** [gcovr/gcovr#78]
I used following command to generate code coverage report for ios application but it generate empty report .
gcovr  -r . --html -o ~/Desktop/example1.html

 It says 0 lines executed and 0% coverage even if  .gcno  and .gcda files are generated .

**Comment by mike-loo** [comment]
Try this:

    object_dir="~/Library/Developer/Xcode/DerivedData/<project>-<random hash>/Build/Intermediates/<project>.build/Debug-iphonesimulator/<project>.build/Objects-normal/x86_64/"
    gcovr ${object_dir} -r . --html -o ~/Desktop/example1.html

be sure to fix the path in `object_dir`

**Comment by jotiram** [comment]
Tthanks @mike-loo  this worked for me .

**Comment by lemonkey** [comment]
Thanks @mike-loo from me as well :+1: This solved an issue I was having where the --object-dir parameter was always generating 0 results, but when I simply use the object directory as the first argument after "gcovr", it works as expected.

**Comment by mrx23dot** [comment]
Please give warning if non exitsting path is given in parameter.
