### ISSUE TITLE
TypeError Exception while decision analysis for switch-statement

### ISSUE THREAD

**Issue by genossefloyd** [gcovr/gcovr#783]
I have got the following exception while running gcovr 6.0 on our project using the flags "--html-details" and "--decisions":
>   File "/home/build/.local/lib/python3.9/site-packages/gcovr/decision_analysis.py", line 228, in parse_one_line
>     lineno, max(lineno + 1, *self.coverage.lines.keys())
> TypeError: 'int' object is not iterable

One of the switch-statements, causing the exception was looking like this:
```
switch (step) {
    case Step::Start: return 0;
    case Step::DownloadDocuments: return 24.0;
    case Step::EncryptDocuments: return 10.0;
    case Step::SubmitDocuments: return 25.0;
    case Step::Finished: return 0;
}
```
Another one was:
```
switch(level) {
    case LogLevel::DEBUG:
        label = "DEBUG";
        break;
    case LogLevel::INFO:
        label = "INFO";
        break;
    case LogLevel::WARN:
        label = "WARN";
        break;
    case LogLevel::ERROR:
        label = "ERROR";
        break;
    default:
        break;
}
```

I have debugged the issue locally and found out, that the dictionary `self.coverage.lines` could be empty, which will cause the exception to be thrown by the *-operator on the empty key list.

I have fixed the issue locally by calculating the max line number beforehand and checking the dictionary length:
```
-            for next_lineno in range(
-                lineno, max(lineno + 1, *self.coverage.lines.keys())
-            ):
+            maxlines = max(lineno + 1, *self.coverage.lines.keys()) if len(self.coverage.lines) > 0 else lineno +1
+            for next_lineno in range(lineno, maxlines):
```

**Comment by Spacetown** [comment]
Thanks for finding the fix. Can you raise a pull request for this?

**Comment by genossefloyd** [comment]
#784 My very first contribution to foreign Github repo. Hope it is alright this way 😅

**Comment by Spacetown** [comment]
PR is already merged.
