### ISSUE TITLE
Does GCOVR report line or branch coverage by default?

### ISSUE THREAD

**Issue by MaabSaleeem** [gcovr/gcovr#788]
Hi!

I am using GCOVR to generate coverage reports to be displayed on SonarQube.

Currently, I am only using the "--sonarqube " and "-e" options, but the reports on SonarQube show branch coverage as well as line coverage.

After reading the documentation, I assumed that GCOVR doesn't report branch coverage by default, only line coverage. But that doesn't seem to be the case for me.

Can someone please confirm what GCOVR defaults to -- line or branch coverage? And if it's branch, is there a way to disable branch coverage, and only show line coverage? If it's line, what could I be doing wrong?

Thanks in advance!

**Comment by Spacetown** [comment]
For the text report the default is line coverage but can be switched to branch coverage. For sonarqube always both coverage values are generated as you saw in your report.

**Comment by MaabSaleeem** [comment]
@Spacetown , thanks for the response. So, is there no way to generate only line coverage for SonarQube?

**Comment by Spacetown** [comment]
No.

**Comment by Spacetown** [comment]
Searched for the the format definition. According to [Generic test coverage report format](https://docs.sonarqube.org/latest/analyzing-source-code/test-coverage/generic-test-data/) the covered attribute for the line is required but the branch values are optional.
