### ISSUE TITLE
HTML report github style test

### ISSUE THREAD

**Issue by mfont-bz17** [gcovr/gcovr#791]
Hi,

I've made a test ([branch](https://github.com/mfont-bz17/gcovr/tree/feature/html-report-github-style)) using [github primer.css](https://primer.style/css/) to make the html reports with the style of github. 
You can see attached the screenshots. If you think than can be useful for the project, then I can continue working on it ;) some details are not finished yet...

**Only html report**

![Screenshot 2023-06-03 at 12-02-18 GCC Code Coverage Report](https://github.com/gcovr/gcovr/assets/121682800/4bd57f35-1a06-4db5-bba7-cb1ad89ccfae)

**Directory page**

![Screenshot 2023-06-03 at 11-55-58 GCC Code Coverage Report](https://github.com/gcovr/gcovr/assets/121682800/76502c62-a6c1-48aa-bac2-afa679df7926)

**Source page**

![Screenshot 2023-06-03 at 12-10-01 GCC Code Coverage Report](https://github.com/gcovr/gcovr/assets/121682800/d2ee41d2-74fe-437e-86ba-16d548b77454)

**Functions page**

![Screenshot 2023-06-03 at 11-57-30 GCC Code Coverage Report](https://github.com/gcovr/gcovr/assets/121682800/8d2064ee-8210-408e-8d20-51733366f83b)

**Functions page**

**Comment by Spacetown** [comment]
Looks great but we've to think about the structure of the templates if we provide several themes. There is also a PR for a doxygen theme open (#785).
At the moment we have the option `--html-theme` which affects the class attribute in the HTML report  and we use the same stylesheet. I guess in your case it's better to exchange the whole stylesheet. It would also be great to provide a blue theme here.

**Comment by mfont-bz17** [comment]
To avoid misunderstandings for me:

- theme: the layout change
- flavor: only the palette colors change

In my case not only the stylesheet must be changed, the html templates too. Is a new directory inside format/html. 
I think that each theme should have a specific folder and each theme can have different flavors, for now green and blue but can exists more.

- gcovr/formats/html/templates/    -> Default theme
- gcovr/formats/html/github/templates/ -> Github theme 
- gcovr/formats/html/doxygen/templates/ -> Doxygen theme 

As you pointed in #785 the part of highlight is important, one option should be that every theme has a mini config to overwrite the default values:

```
pygments-style: arduino
falvors: green, blue, dark_blue, dark_green
```

And then use the --html-theme option to choose the theme and flavor for example
```
 --html-theme blue (to keep compatibility default theme)
 --html-theme github.blue
 --html-theme doxygen.dark_green
```

Another simpler option can be create a new argument and pass your custom theme directory and change html_syntax_highlighting to accept a [pygments style](https://pygments.org/styles/ )

```
--html-theme-dir /home/m/gcovr/themes/github
--html_syntax_highlighting arduino
```

These are just some ideas ...

And here the screenshot of blue flavor

**Source page blue**
![Screenshot 2023-06-03 at 18-32-36 GCC Code Coverage Report](https://github.com/gcovr/gcovr/assets/121682800/c30a86a9-9bb7-431b-bc4a-c8b4c191a689)

**Comment by Spacetown** [comment]
> To avoid misunderstandings, in the comment:
> 
>     * theme: the layout change
>     * flavor: only the palette colors change
That's sounds reasonable.
> I think that each theme should have a specific folder and each theme can have different flavors, for now green and blue but can exists more.
I'm with you
>     * gcovr/formats/html/templates/    -> Default theme
> 
>     * gcovr/formats/html/github/templates/ -> Github theme
> 
>     * gcovr/formats/html/doxygen/templates/ -> Doxygen theme
Here I prefer:

* gcovr/formats/html/templates/default/    -> Default theme
* gcovr/formats/html/templates/github/ -> Github theme
* gcovr/formats/html/templates/doxygen/ -> Doxygen theme

If the the theme is selected by `<theme>.<colour>` we can always use the part before the `.` to select the template folder.


> Another simpler option can be create a new argument and pass your custom theme directory and change html_syntax_highlighting to accept a [pygments style](https://pygments.org/styles/)

This is already in progress (#758).

**Comment by Spacetown** [comment]
One thing to keep in mind is also the browser compatibility. The default theme is tested with Firefox, Safari and Chrome on Mac OS.

Your work looks pretty good and if you add the alternating background or highlighting of the selected line we can consider to use this as the new default.

**Comment by mfont-bz17** [comment]
Yes we should to test browser compatibility. I'm working on GNU/Linux I've tested Firefox and Chromium browser at the moment.

Sorry I'm not sure what you mean in the second part:

- Alternating background :  Change light and dark [mode](https://primer.style/css/support/theming) for all site or only for source code part ???
- Highlighting of the selected line: Change the style of source code part. ???

Here I did some tests with different highlight styles (only source code part). Light styles can work with default covered line and uncovered line color but dark styles don't work as we said.

**arduino**
![Screenshot 2023-06-04 at 10-06-06 GCC Code Coverage Report](https://github.com/gcovr/gcovr/assets/121682800/e6451f40-c709-4ca6-9ca0-d76e74e024ee)

**emacs**
![Screenshot 2023-06-04 at 10-08-48 GCC Code Coverage Report](https://github.com/gcovr/gcovr/assets/121682800/be433a17-3fcb-42f8-a685-c67d053d5fdd)

**gruvbox-light**
![Screenshot 2023-06-04 at 10-06-18 GCC Code Coverage Report](https://github.com/gcovr/gcovr/assets/121682800/39e5373e-a7ab-41a1-a87f-602979031a3a)

**github-dark**
![Screenshot 2023-06-04 at 10-20-21 GCC Code Coverage Report](https://github.com/gcovr/gcovr/assets/121682800/6a804129-25c5-40bd-80c3-aa59a7bd6b56)

**Comment by Spacetown** [comment]
On the main page and the directory pages the table rows have different background for even and odd rows. The row under the mouse cursor changes also the background.

**Comment by mfont-bz17** [comment]
I pushed in the [branch](https://github.com/mfont-bz17/gcovr/tree/feature/html-report-github-style) the alternate background rows and the highlight of the row on mouse over. I added support for dark theme blue and green. You can see it in the attached screenshots.

**--html-theme green**
![imatge](https://github.com/gcovr/gcovr/assets/121682800/f2c93586-e6bf-4c8a-9ba8-a8b497645eed)
![imatge](https://github.com/gcovr/gcovr/assets/121682800/e276a1b5-bb7c-4b0c-85d9-15cbc700c3ea)


**--html-theme blue**
![imatge](https://github.com/gcovr/gcovr/assets/121682800/30b773e0-4805-469c-b963-a70eea5ed4f5)
![imatge](https://github.com/gcovr/gcovr/assets/121682800/cc0dc454-76d0-4477-b1c9-72c8f9ac8dc7)



**--html-theme dark-green**
![imatge](https://github.com/gcovr/gcovr/assets/121682800/dd5ec767-60d8-4fbf-8721-a8bc927eac39)
![imatge](https://github.com/gcovr/gcovr/assets/121682800/a68571d3-74cc-4bc6-aeb2-ff6911846c65)


**--html-theme dark-blue**
![imatge](https://github.com/gcovr/gcovr/assets/121682800/e1370f1c-daf0-43e0-864a-ca79a1acf585)
![imatge](https://github.com/gcovr/gcovr/assets/121682800/158d3a8a-933e-4ab6-bb7c-1abbf5a8381c)

**Comment by Spacetown** [comment]
Can you raise a PR for further discussion? As I saw in a quick walkthrough the switching between the different themes is missing yet. I'm also not sure if the hilighting style should be part of the templates instead of hardcoded.
