### ISSUE TITLE
Docker env: docker_build_compiler(gcc-12): failed and docker_build_compiler(gcc-13): failed

### ISSUE THREAD

**Issue by mfont-bz17** [gcovr/gcovr#798]
**Describe the bug**
Impossible to create docker container gcc-12 and gcc-13

**To Reproduce**
`python3 -m nox --session "docker_build_compiler(gcc-12)"`
or
`python3 -m nox --session "docker_build_compiler(gcc-13)"`

**Expected behavior**
The docker container should be created.

**Screenshots**
![imatge](https://github.com/gcovr/gcovr/assets/121682800/72937ff7-ddf3-4bcb-8cc2-cd7652ee3c26)
![imatge](https://github.com/gcovr/gcovr/assets/121682800/9a625d9f-d64e-45db-8c67-d5795d849d5f).
![imatge](https://github.com/gcovr/gcovr/assets/121682800/11ad63de-087a-4d4b-8d5d-c58f6b974f0d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS (Focal Fossa)

**Comment by mfont-bz17** [comment]
Seems that the docker image of ubuntu:23.04 has a user ubuntu with uid 1000 

```
#11 [ 8/11] RUN cat /etc/passwd
#11 0.217 root:x:0:0:root:/root:/bin/bash
#11 0.217 daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
#11 0.217 bin:x:2:2:bin:/bin:/usr/sbin/nologin
#11 0.217 sys:x:3:3:sys:/dev:/usr/sbin/nologin
#11 0.217 sync:x:4:65534:sync:/bin:/bin/sync
#11 0.217 games:x:5:60:games:/usr/games:/usr/sbin/nologin
#11 0.217 man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
#11 0.217 lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
#11 0.217 mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
#11 0.217 news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
#11 0.217 uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
#11 0.217 proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
#11 0.217 www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
#11 0.217 backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
#11 0.217 list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
#11 0.217 irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
#11 0.217 _apt:x:42:65534::/nonexistent:/usr/sbin/nologin
#11 0.217 nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
#11 0.217 ubuntu:x:1000:1000:Ubuntu:/home/ubuntu:/bin/bash
#11 DONE 0.2s

```
Workaround to build gcc-12 and gcc-13

```
diff --git a/admin/Dockerfile.qa b/admin/Dockerfile.qa
index f1df3c12..091c4bd2 100644
--- a/admin/Dockerfile.qa
+++ b/admin/Dockerfile.qa
@@ -76,6 +76,11 @@ RUN \
       python3 -m pip install --no-cache-dir nox ; \
     fi;
 
+RUN \
+    if [ "$DOCKER_OS" = "ubuntu:23.04"  ]; then \
+        userdel ubuntu ; \
+    fi;
+
 # Create new user "docker" and set password to "docker"
 RUN addgroup docker
 RUN useradd -d $HOME $(if [ -n "$USERID" ] ; then echo "-u $USERID" ; fi) -g docker -g sudo -s /bin/bash docker
```
![imatge](https://github.com/gcovr/gcovr/assets/121682800/a03f5a3a-b609-49cb-bb3a-b079f6d6569a)
![imatge](https://github.com/gcovr/gcovr/assets/121682800/da5aa5bb-28ce-412c-8be3-9cacee3456ef)

**Comment by mfont-bz17** [comment]
> Would it be better to delete always the user 1000 independent from the name?

I think the right option should be delete the USERID passed by argument if exists. But normally the problem only will happen with the 1000 uid because is the first user in some systems and  in the ubuntu docker 23.04 in this case (if not change in the future). For me both are ok delete for name or delete for id.

**Comment by Spacetown** [comment]
I prefer delete for ID because this is what's needed.
