### ISSUE TITLE
Merging coverage example

### ISSUE THREAD

**Issue by EugeneKagan-eaton** [gcovr/gcovr#802]
Hello,

Few questions regarding usage of '--json-add-tracefile':

1. Is this option actually implemented in 6.0?
2. Is it possible to provide comprehensive example on the merge usage in the context of the following use case?

- Two test runs of the same set of files but different #define
- Each test run generates executable in different build folders under different name. GCOV produces *.gcov files with the same base file name under test because the same source files are tested. The difference is in conditionally compiled parts of the functions and some functions as well.
- Each test run generates JSON coverage file by using running gcovr '--json' option on the output

How would one combine coverage to produce visual summary as in single run across all test executable?

Regards,
Eugene

**Comment by Spacetown** [comment]
In the 6.0 the prefix `json` is missing:
https://github.com/gcovr/gcovr/blob/1221ef62ff0de15bbeaf79e68e08a65d62c73ff4/gcovr/configuration.py#L705

We have an example in our tests:
https://github.com/gcovr/gcovr/blob/eb4332abb28166f9657312c3a789c07ea6797472/gcovr/tests/add_coverages/Makefile#L1-L27

The merging is also described in https://gcovr.com/en/stable/guide/merging.html#merging-coverage

**Comment by EugeneKagan-eaton** [comment]
Thank you for the response.

In the example 'testcase_foo' and 'testcase_bar' are generated into the same folder. What if runners are in different folders? How would example change? What files except JSON output are needed to generate visual HTML coverage as for individual run?

Eugene

**Comment by Spacetown** [comment]
I've the next few weeks no computer to check this but there should be no difference since the paths to the source files are relative.
Please give it a try.

**Comment by EugeneKagan-eaton** [comment]
Yep, it works. The issue was on my side. Messed up PYTHON path for gcovr.

Eugene
