### ISSUE TITLE
Detailed HTML report looks for non-existent files

### ISSUE THREAD

**Issue by Mno-hime** [gcovr/gcovr#804]
**Describe the bug**

Creating a _detailed_ HTML coverage report with gcovr 6.0 from PyPI on Debian 12 over BIND 9 sources fails. XML, TXT, and non-detailed HTML reports are fine. gcovr 5.2 from Debian 12 is the same.

```
/usr/local/bin/gcovr --verbose --exclude-directories bin/tests --exclude-directories doc --exclude-directories fuzz --exclude tests --html-details -o coverage.html
...
(WARNING) File lib/lib/isc/include/isc/buffer.h not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/job.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/dns/geoip2.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/md.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/include/isc/ascii.h not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/siphash.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/ratelimiter.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/uv.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/include/isc/tid.h not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/netmgr/socket.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/netmgr/udp.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/netmgr/http.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/dns/include/dns/compress.h not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/hmac.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/dns/rbtdb.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/netmgr/tcp.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/ht.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/loop.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/dns/update.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/include/isc/dnsstream.h not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/async.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/time.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/timer.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/work.c not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/include/isc/hash.h not found: FileNotFoundError(2, 'No such file or directory')
(WARNING) File lib/lib/isc/hashmap.c not found: FileNotFoundError(2, 'No such file or directory')
(ERROR) Error occurred while printing reports
```

For some reason, the non-existent `lib/` path is being prepended to some files, e.g., there's no such thing as `lib/lib/isc/hashmap.c`, but `lib/isc/hashmap.c` surely exists.

See [3495936.log](https://github.com/gcovr/gcovr/files/11903093/3495936.log) for full verbose output, and also here: https://gitlab.isc.org/isc-projects/bind9/-/jobs/3495936.

**To Reproduce**
1. Clone the `main` branch of BIND 9: https://gitlab.isc.org/isc-projects/bind9.git
2. Build it:
```
autoreconf -fi
CC=gcc CFLAGS="-fno-omit-frame-pointer -fno-optimize-sibling-calls -O1 -g -Wall -Wextra --coverage -O0" ./configure --disable-maintainer-mode --enable-developer --enable-option-checking=fatal --enable-dnstap --enable-dnsrps --with-cmocka --with-libxml2 --with-json-c --enable-leak-detection --with-libidn2 --with-readline=libedit
make -j
```
3. Run tests: `make -j check`
4. Remove unrelated files: `rm a-conftest.gc*`
5. Build the detailed HTML report: `/usr/local/bin/gcovr --verbose --exclude-directories bin/tests --exclude-directories doc --exclude-directories fuzz --exclude tests --html-details -o coverage.html`

I must admit I can't reproduce it locally, only in our CI - even when I use the same CI image and steps locally.

**Expected behavior**

A detailed HTML report is built.

**Desktop (please complete the following information):**
 - OS: Debian 12
 - GCC version: 12.2.0 (Debian 12.2.0-14)
 - GCOVR version 5.2 and 6.0

**Comment by Spacetown** [comment]
I'll try to reproduce it.

**Comment by Spacetown** [comment]
I've no `autoreconf` and can't reproduce it.

I've searched the log and the file comes from this block:
```
(DEBUG) Finding source file corresponding to a gcov data file
  gcov_fname   /builds/isc-projects/bind9/lib/isc/tests/hashmap.c##38c4307bfb29eae1648814f9ea12b11c.gcov
  currdir      /builds/isc-projects/bind9
  root         /builds/isc-projects/bind9
  starting_dir /builds/isc-projects/bind9
  obj_dir      None
  gcda_fname   /builds/isc-projects/bind9/lib/isc/tests/hashmap_test.gcda
  --> fname    /builds/isc-projects/bind9/lib/isc/tests/../../lib/isc/hashmap.c
(DEBUG) Parsing coverage data for file /builds/isc-projects/bind9/lib/isc/tests/../../lib/isc/hashmap.c
```

This path is reported from GCOV form this execution:
```
(DEBUG) Running gcov: 'gcov /builds/isc-projects/bind9/lib/isc/tests/hashmap_test.gcda --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /builds/isc-projects/bind9/lib/isc/tests' in '/builds/isc-projects/bind9/lib/isc/tests'
```

On master we are checking more error messages produced by GCOV. Can you try tor run the pipeline with tha master branch?

**Comment by Mno-hime** [comment]
I can't reproduce it either anymore. With version 6.0 we have two hacks for gcovr to work, but nothing that warrants an issue.

**Comment by Spacetown** [comment]
What hacks do you have?

**Comment by Mno-hime** [comment]
These two are needed on Debian 12: https://gitlab.isc.org/isc-projects/bind9/-/blob/main/.gitlab-ci.yml#L1705.

**Comment by Spacetown** [comment]
And even removing the hacks will not reproduce the error?

**Comment by Spacetown** [comment]
Ok. But this warnings shouldn't be omitted. What do you expect here?

Is the file `.dtrace-temp.956f3c90.c` connected to the `DTrace` tool? It seems that this file is used as forced include or do you really include a c file?

A solution can be to add a special option to specify a file pattern where the warning shall be ignored (like `--gcov-ignore-errors=source_not_found:.dtrace-temp.*`).

**Comment by Spacetown** [comment]
I've checked deeper, can you try to use the option `--exclude=lib/lib/.*` on current main branch? This should filter the sources and the HTML report shouldn't have a problem anymore.

**Comment by Spacetown** [comment]
Closed because of no response.
