### ISSUE TITLE
gcovr 6.0 does not render an absolute source path in XML output even if one is given to --root

### ISSUE THREAD

**Issue by detly** [gcovr/gcovr#806]
I've been trying to wrangle `gcovr` Cobertura XML output into Gitlab. Gitlab has [its own logic](https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html#automatic-class-path-correction) around path mangling, and maybe eventually I'll figure it out. But, tangentially, I noticed that I simply cannot get `gcovr` to render an absolute path in the XML output, which would probably make a lot of my guesswork moot.

Comments in #177 and #207 seem to suggest that using an absolute path for the `--root` argument would make this happen, but in my experience it does not. I don't think it's explicitly documented though, so I don't quite know if it's a bug.

Steps to reproduce the behavior (I did this in the `python:latest` Docker image on 12/7/23):

```none
root@23f4e6bca5c0:/# mkdir build && cd build
root@23f4e6bca5c0:/build# gcovr --version
gcovr 6.0

Copyright (c) 2013-2023 the gcovr authors
Copyright (c) 2013 Sandia Corporation.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
root@23f4e6bca5c0:/build# pwd
/build
root@23f4e6bca5c0:/build# gcovr --root $(pwd) --xml-pretty --output -
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE coverage SYSTEM 'http://cobertura.sourceforge.net/xml/coverage-04.dtd'>
<coverage line-rate="0.0" branch-rate="0.0" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0" complexity="0.0" timestamp="1689124739" version="gcovr 6.0">
  <sources>
    <source>.</source>
  </sources>
  <packages/>
</coverage>
```

Note the `<source>.</source>` value.

System: 
 - OS: Debian GNU/Linux 12 (bookworm)
 - GCOVR version: 6.0

**Comment by Spacetown** [comment]
Do I understand the problem? You want to have absolute paths in the report?
That's not possible. All paths are made relative to the root directory. This is needed because the generation of the report is done in a temporary directory and this dynamic part needs to be removed in the report.

**Comment by detly** [comment]
Yes, that's what I was misunderstanding.

I was comparing the behaviour to other coverage reports which seem to work out of the box with CI and happen to use absolute paths for the project directory (but relative paths for everything else).

Anyway, I will keep trying to shoehorn things into whatever Gitlab is expecting, or use `xmlstarlet` to force it if need be. This is probably not a valid issue then.
