### ISSUE TITLE
Nicer Function List view and output

### ISSUE THREAD

**Issue by chaitanyaBhargava** [gcovr/gcovr#808]
**Is your feature request related to a problem? Please describe.**
Lcov supports showing "Line Coverage" and "Branch Coverage" percentage **Per Function**. Gcov's "List Of Functions" output lacks that. It only shows the function line number and "Number Of Calls". We want to use gcovr (Cause python!) but also get coverage stats per function rather than just whole file

**Describe the solution you'd like**
This isn't the full solution but its what I was able to get to work somewhat easily. GCovr already pulls out "gcov blocks executed" from gcov files, puts in an object and does nothing with it.... The solution is to just push that data up to the html, json and xml files and put it in them. "gcov blocks executed" is very close to line and branch coverage so it should work. If not I might propose further improvements but this is a simple start.

**Describe alternatives you've considered**
I thought about not touching gcovr but use one of its existing outputs to then add something on top of that, but the "blocks executed" data is not published to any file type.

**Additional context**
Lcov output - 
![Lcov output](https://github.com/gcovr/gcovr/assets/5873250/7e7527b1-9024-4a84-8250-397b87b3573c)

Current gcov "List Of Functions" output - 
![Gcov Current output](https://github.com/gcovr/gcovr/assets/5873250/f1838831-adb9-4e05-aa48-15c2c98e3c82)

Proposed gcovr  "List Of Functions" output -
![Gcov proposed](https://github.com/gcovr/gcovr/assets/5873250/97f942ae-2126-4687-b85e-a5d8397dde18)

**NOTEI** also got rid of "File" column and made it a header. It would make me scroll to the right to see other columns (had to zoom out to get the snapshot) which was a bit annoying.

**Comment by chaitanyaBhargava** [comment]
"_We currently read the text output where we do not have the information which function a line belongs to._" --> Not sure I follow, is this in support of adding "Blocks executed" to html, xml and json or not?
"Blocks executed" is available for all functions in any gcov output eg 
![image](https://github.com/gcovr/gcovr/assets/5873250/c085db3c-13b2-4ad9-a1d4-b0c7f7d936b2)
 and is already read in by gcovr in to an object. Just that data is not published in to any output file which is the main thing I want to do for this enhancement.

"**_If you add the file column as header you have to scroll more because the list gets longer for everyone. I'm not sure if this is better._**" --> If everyone feels strongly about this I can not do this change. The above point is the main ask anyway. This was more what I felt would be cleaner.

**Comment by chaitanyaBhargava** [comment]
So should I go ahead and just submit a PR now? I am not clear on the process. Will this issue be voted on?

**Comment by Spacetown** [comment]
How to contribute is described in https://gcovr.com/en/stable/contributing.html. T update the reference data I suggest to use the Docker environment.

In my opinion it's better to split it into two Pars. The first one to update the data model and the internal JSON format and the second one to update the other output formats.

**Comment by chaitanyaBhargava** [comment]
@Spacetown Thank you so much for taking care of this. I apologize, I started on this but got pulled in to a different project.

**Comment by Spacetown** [comment]
@chaitanyaBhargava Is the result what you expect?

**Comment by chaitanyaBhargava** [comment]
Yes. The big win the the addition of blocks executed to the json output. We will be making the most use of that. 
The only thing remaining is "_**got rid of "File" column and made it a header. It would make me scroll to the right to see other columns (had to zoom out to get the snapshot) which was a bit annoying.**_" which was a cosmetic requirement anyway and doesn't matter at all.

Thank you again!

**Comment by chaitanyaBhargava** [comment]
@Spacetown  - Is there a release scheduled or planned? Would prefer to use a proper versioned release rather than the dev version but no rush as such.

**Comment by Spacetown** [comment]
No fix schedule. There are still some PRs open.
