### ISSUE TITLE
Unrecognized gcov output, exceptions during parsing.

### ISSUE THREAD

**Issue by kash0lt** [gcovr/gcovr#809]
(WARNING) Unrecognized GCOV output for /home/kelly/workspace/dev/SmartReader/libraries/SharedHeaders/nlohmann/json.hpp
          branch  9 taken -1
          branch  1 taken -1
        This is indicative of a gcov output parse error.
        Please report this to the gcovr developers
        at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
        UnknownLineType: branch  9 taken -1
(WARNING) Exception during parsing:
        UnknownLineType: branch  1 taken -1
(WARNING) Unrecognized GCOV output for /home/kelly/workspace/dev/SmartReader/libraries/SharedHeaders/nlohmann/json.hpp
          branch 43 taken -1
        This is indicative of a gcov output parse error.
        Please report this to the gcovr developers
        at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
        UnknownLineType: branch 43 taken -1
(WARNING) Unrecognized GCOV output for /home/kelly/workspace/dev/SmartReader/libraries/SharedHeaders/PathIterator.hpp
          branch  0 taken -59 (fallthrough)
        This is indicative of a gcov output parse error.
        Please report this to the gcovr developers
        at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
        UnknownLineType: branch  0 taken -59 (fallthrough)**Describe the bug**

Using a config file with the following:
filter=../../SmartReader/libraries/
html=yes
html-details=yes
output=../../testouts/coverage.html
exclude=../../SmartReader/libraries/MGWeb/base64.h
exclude=../../SmartReader/libraries/MGWeb/base64.cpp
exclude=../../SmartReader/libraries/SharedHeaders/vendor/json.hpp
exclude=../../SmartReader/libraries/MGWeb/mongoose/*
exclude=../../SmartReader/libraries/SharedHeaders/asio-1.18.1/*
exclude=../../SmartReader/libraries/SharedHeaders/cereal/*
exclude=../../SmartReader/libraries/SharedHeaders/date/*
exclude=../../SmartReader/libraries/SharedHeaders/utfcpp/*
exclude=../../SmartReader/libraries/SharedHeaders/websocketpp/*
exclude=../../SmartReader/libraries/SharedHeaders/Zippy/*
exclude-unreachable-branches=yes
exclude-throw-branches=yes
gcov-ignore-parse-errors=yes

**Comment by Spacetown** [comment]
This is a bug of gcov as mentioned in #583. You can ignore this error with the option `--gcov-ignore-parse-errors negative_hits.warn`.

**Comment by kash0lt** [comment]
> This is a bug of gcov as mentioned in #583. You can ignore this error with the option `--gcov-ignore-parse-errors negative_hits.warn`.

@Spacetown 
We use a config file that has:
gcov-ignore-parse-errors=yes

in it. Shouldn't that work the same? If so, it is not happening.

**Comment by Spacetown** [comment]
In version 6.0 it should be `gcov-ignore-parse-errors=all` because it was changed to an enumeration. In this case the yes should raise an error. I need to check this.

**Comment by Spacetown** [comment]
It seems that for this option the error isn't catched. We need to fix this.
