### ISSUE TITLE
Show uncovered lines first in a report

### ISSUE THREAD

**Issue by ligurio** [gcovr/gcovr#810]
**Is your feature request related to a problem? Please describe.**

Code coverage reports are need for elimination of places in a source code which coverage is worse.
Gcovr has options `--sort-percentage` and `--sort-uncovered`, but when these options are enabled report shows lines with better coverage first.

**Describe the solution you'd like**

Sort lines in reverse order, show lines with worse coverage first.

**Describe alternatives you've considered**

lcov has JS code embedded to HTML report that can sort columns in both orders.

**Additional context**

Enabled `--sort-percentage` and `--sort-uncovered`:

![image](https://github.com/gcovr/gcovr/assets/1151557/e9dad3eb-6ddf-465d-b0dd-bbb33bb51147)

Enabled `--sort-percentage`:

![image](https://github.com/gcovr/gcovr/assets/1151557/529d4bf9-886e-43c6-b978-ab1f9d319bf9)

**Comment by Spacetown** [comment]
I need to check this in deep. If `--sort-uncovered` is given the `--sort-percent` is ignored. According to the documentation the it's sorted by increasing number of uncovered lines/branches or percentage of uncovered lines.

**Comment by Spacetown** [comment]
@ligurio Can you try the branch from the PR?

**Comment by ligurio** [comment]
Sure, I'll try. Just for curious: why sort this in a build time, not in a report itself like it was done in reports generated by lcov [1] or coverage.py [2]?

1. https://dev-builds.libreoffice.org/lcov_reports/archive/master~2012-08-24_11.55.28/index-sort-f.html
2. https://stackoverflow.com/questions/62221654/how-to-get-coverage-reporting-when-testing-a-pytest-plugin

**Comment by Spacetown** [comment]
We avoided using of javascript for now. Maybe we can change thin in the future.
