### ISSUE TITLE
decisions-json Fails integration tests for msys2 with gcc 13.1

### ISSUE THREAD

**Issue by ajpenner** [gcovr/gcovr#811]
**Describe the bug**
Some integration tests fail when using msys2 with gcc 13.1.

**To Reproduce**
1. clone the gcovr respository
2. in a cmd terminal run `set CC=gcc-13`
3. in the same cmd terminal run `nox --session tests -- -k "json and not ninja"`
4. Majority of tests pass but we get one failure:
`gcovr/tests/test_gcovr.py::test_build[decisions-json] FAILED`
With the following output
=============================================================================== FAILURES ================================================================================
______________________________________________________________________ test_build[decisions-json] _______________________________________________________________________

compiled = 'decisions', format = 'json', available_targets = {'all': set(), 'clean': set(), 'html': {'coverage.json'}, 'json': {'coverage.json'}, ...}
generate_reference = False, update_reference = False, archive_differences = False

    def test_build(
        compiled,
        format,
        available_targets,
        generate_reference,
        update_reference,
        archive_differences,
    ):
        name = compiled
        scrub = SCRUBBERS[format]
        output_pattern = OUTPUT_PATTERN[format]

        encoding = "utf8"
        if format == "html" and name.startswith("html-encoding-"):
            encoding = re.match("^html-encoding-(.*)$", name).group(1)

        os.chdir(os.path.join(basedir, name))
        assert run(["make", format])

        if generate_reference:  # pragma: no cover
            generate_reference_data(output_pattern)

        whole_diff_output = []
        for test_file, reference_file in find_reference_files(output_pattern):
            with open(test_file, encoding=encoding) as f:
                test_scrubbed = scrub(f.read())

            # Overwrite the file created above with the scrubbed content
            if generate_reference:  # pragma: no cover
                with open(reference_file, "w", encoding=encoding) as f:
                    f.write(test_scrubbed)
                reference_scrubbed = test_scrubbed
            else:
                with open(reference_file, encoding=encoding) as f:
                    reference_scrubbed = scrub(f.read())

            try:
                assert_equals(
                    reference_file,
                    reference_scrubbed,
                    test_file,
                    test_scrubbed,
                    encoding,
                )
            except AssertionError as e:  # pragma: no cover
                whole_diff_output += str(e) + "\n"
                if update_reference:
                    reference_file = update_reference_data(
                        reference_file, test_scrubbed, encoding
                    )
                if archive_differences:
                    archive_difference_data(name, test_file, reference_file)

            if generate_reference or update_reference:  # pragma: no cover
                remove_duplicate_data(
                    encoding, scrub, test_scrubbed, test_file, reference_file
                )

        diff_is_empty = len(whole_diff_output) == 0
>       assert diff_is_empty, "Diff output:\n" + "".join(whole_diff_output)
E       AssertionError: Diff output:
E         --- reference\gcc-13\coverage.json
E         +++ coverage.json
E         @@ -1561,13 +1561,13 @@
E                                  {
E                                      "blockno": 0,
E                                      "count": 4,
E         -                            "fallthrough": true,
E         -                            "throw": false
E         -                        },
E         -                        {
E         -                            "blockno": 0,
E         -                            "count": 1,
E         -                            "fallthrough": false,
E         +                            "fallthrough": false,
E         +                            "throw": false
E         +                        },
E         +                        {
E         +                            "blockno": 0,
E         +                            "count": 1,
E         +                            "fallthrough": true,
E                                      "throw": false
E                                  }
E                              ],
E
E
E       assert False

C:\dev\GitRepos\gcovr\gcovr\tests\test_gcovr.py:527: AssertionError
------------------------------------------------------------------------- Captured stdout setup -------------------------------------------------------------------------
STDOUT - START ['make', 'clean']
rm -f testcase
rm -f *.gc*
rm -f coverage*.*
rm -f *.json
STDOUT - END
STDOUT - START ['make', 'clean']
rm -f testcase
rm -f *.gc*
rm -f coverage*.*
STDOUT - END
STDOUT - START ['make', 'all']
C:/msys64/mingw32/bin/g++.EXE -fprofile-arcs -ftest-coverage main.cpp -o testcase
STDOUT - END
------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------
STDOUT - START ['make', 'json']
./testcase
C:/dev/GitRepos/gcovr/.nox/tests_compiler-gcc-13/Scripts/python.EXE -m gcovr --keep --verbose --decisions --json-pretty --json -o coverage.json
(DEBUG) File system is case insensitive.
(DEBUG) Filters for --root: (1)
(DEBUG)  - re.compile('^C:\\\\dev\\\\GitRepos\\\\gcovr\\\\gcovr\\\\tests\\\\decisions\\\\')
(DEBUG) Filters for --filter: (1)
(DEBUG)  - DirectoryPrefixFilter(C:/dev/GitRepos/gcovr/gcovr/tests/decisions/)
(DEBUG) Filters for --exclude: (0)
(DEBUG) Filters for --gcov-filter: (1)
(DEBUG)  - AlwaysMatchFilter()
(DEBUG) Filters for --gcov-exclude: (0)
(DEBUG) Filters for --gcov-exclude-directories: (0)
(DEBUG) Scanning directory . for gcda/gcno files...
(DEBUG) Found 2 files (and will process 1)
(DEBUG) Pool started with 1 threads
(DEBUG) Processing file: C:\dev\GitRepos\gcovr\gcovr\tests\decisions\testcase-main.gcda
(DEBUG) Running gcov: 'C:/msys64/mingw32/bin/gcov.EXE --help' in '.'
(DEBUG) Running gcov: 'C:/msys64/mingw32/bin/gcov.EXE --help-hidden' in '.'
(DEBUG) Running gcov: 'C:/msys64/mingw32/bin/gcov.EXE C:/dev/GitRepos/gcovr/gcovr/tests/decisions/testcase-main.gcda --branch-counts --branch-probabilities --all-blocks --demangled-names --hash-filenames --object-directory C:/dev/GitRepos/gcovr/gcovr/tests/decisions' in 'C:\dev\GitRepos\gcovr\gcovr\tests\decisions'
(DEBUG) Finding source file corresponding to a gcov data file
  gcov_fname   C:\dev\GitRepos\gcovr\gcovr\tests\decisions\main.cpp##118fcbaaba162ba17933c7893247df3a.gcov
  current_dir      C:\dev\GitRepos\gcovr\gcovr\tests\decisions
  root         C:\dev\GitRepos\gcovr\gcovr\tests\decisions
  starting_dir C:\dev\GitRepos\gcovr\gcovr\tests\decisions
  obj_dir      None
  gcda_fname   C:/dev/GitRepos/gcovr/gcovr/tests/decisions/testcase-main.gcda
  --> fname    C:/dev/GitRepos/gcovr/gcovr/tests/decisions/main.cpp
(DEBUG) Parsing coverage data for file C:/dev/GitRepos/gcovr/gcovr/tests/decisions/main.cpp
(DEBUG) Starting the decision analysis
(DEBUG) Uncheckable decision at line 249
(DEBUG) Uncheckable decision at line 254
(DEBUG) Uncheckable decision at line 290
(DEBUG) Decision Analysis finished!
# pass
STDOUT - END
======================================================================== short test summary info ========================================================================
FAILED gcovr/tests/test_gcovr.py::test_build[decisions-json] - AssertionError: Diff output:
============================================ 1 failed, 25 passed, 2 skipped, 415 deselected, 1 xpassed in 105.82s (0:01:45) =============================================
nox > Command python -m pytest -k 'json and not ninja' -- doc gcovr failed with exit code 1
nox > Session tests_compiler(gcc-13) failed.
nox > Ran multiple sessions:
nox > * tests: success
nox > * tests_compiler(gcc-13): failed

**Expected behavior**
I would expect the integration tests to pass using msys2 and gcc 13.1

**Desktop (please complete the following information):**
 - OS: Windows
 - GCC version: gcc.exe (Rev7, Built by MSYS2 project) 13.1.0
 - GCOVR version: master
 - Project directory layout:
   - Cloned from repository

**Comment by Spacetown** [comment]
It seems that you've a version of gcov containing my patch described in https://github.com/gcovr/gcovr/issues/677#issuecomment-1284417325. Our tests use a version without the patch.

**Comment by Spacetown** [comment]
Not a issue since a different version of GCC was used.
