### ISSUE TITLE
Wrong description for the option --branches

### ISSUE THREAD

**Issue by ligurio** [gcovr/gcovr#813]
**Describe the bug**

gcovr has an option `--braches` with the following description:

```
  -b, --branches        Report the branch coverage instead of the line coverage. For text report only. Config key: txt-branch.               
```

However, when `--branches` is specified, JSON report (option `--coveralls <json>`) contains only line coverage and XML report (option `--cobertura`) contains both line and branch coverage. This behavior contradicts the description of the option and confuses a bit.

**To Reproduce**

- Full comand-line: `gcovr --root ${PROJECT_SOURCE_DIR} --object-directory ${PROJECT_BINARY_DIR} --filter ${PROJECT_SOURCE_DIR}/src --exclude ".*\.dasc" --exclude ".*/host/" --print-summary --output ${COVERAGE_HTML_REPORT} --cobertura ${COVERAGE_XML_REPORT} --html --html-title "LuaJIT Code Coverage Report" --html-details --sort-percentage --branches --decisions -j ${CMAKE_BUILD_PARALLEL_LEVEL}`

**Expected behavior**

option's description reflects reality (say that XML reports contains both line and branch coverage, JSON report contains line coverage only) or fix JSON report and description (report always line and branch coverage).

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - GCC version gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
 - GCOVR version 6.0
 - Project directory layout:
   - Roots <project_root>
   - Object directories <project_root>/build
```
        --root ${PROJECT_SOURCE_DIR}
        --object-directory ${PROJECT_BINARY_DIR}
```
**Additional context**

gcovr options are in commit 
https://github.com/tarantool/luajit/commit/8ad3b82eb9f22c17875d21e68483f109b43529d8

JSON report: [luajit_json.txt](https://github.com/gcovr/gcovr/files/12197633/luajit_json.txt)
XML report: [luajit_xml.txt](https://github.com/gcovr/gcovr/files/12197636/luajit_xml.txt)

**Comment by Spacetown** [comment]
You're right. The documentation doesn't fit here. The option `--branches` is used for:

- Change the text output to use branch coverage instead of line coverage.
- Change sort order from lines to branches in CSV, TXT and JSON.

I'll update this for the next release.

**Comment by Spacetown** [comment]
```
For text report: Report the branch coverage instead of the line coverage.
For CSV/JSON report: Sort files by branch coverage instead of line coverage.
```

The `coveralls` format only defines line coverage and the `cobertura` and the internal JSON format always provide both.
