### ISSUE TITLE
Add option to report 0% coverage for all source files in <root> as a baseline, even if they aren't compiled.

### ISSUE THREAD

**Issue by avrahamshukron** [gcovr/gcovr#827]
**Is your feature request related to a problem? Please describe.**
We have a large codebase which we are working slowly to cover with unit tests.
Currently the coverage score is artificially high because `gocv` and `gcovr` only consider compiled object files, but some sources are not even compiled when building the unit tests, thus they are not covered at all but they are not considered as 0%.

More details:
Our code is cross-compiled to some embedded platform.
Building target FW vs. building unit-tests is done with a separate cmake invocations, each with its own unique flags and obviously a different build directory.

Each test program is a cmake target.
Its sources are:
1. The test code
2. The specific code-under-test
3. CUT dependencies (mocks / fakes)

So when we are building the unit-tests, only the source files that are actually tested are getting built.
The rest simply don't exist as far as cmake is concerned (until someone write a new test to cover these files).

**Describe the solution you'd like**
A new command line option to enable actively scanning for all sources under the root directory, and setting 0% coverage for each of them as a baseline. This score can then be overridden by actual execution data from `.gcda` files.

Excludes will still be respected of course, so any source file -compiled or not- which matches an exclusion pattern will be completely removed from the final report.

**Describe alternatives you've considered**
Option 1: A dummy target to compile all code.
I can define a dummy target which will include all the sources that we care about even if they are not tested yet. The problem with this approach is that it would be really hard to establish and maintain: There is a high up-front cost to port and compile all sources to host platform, and new sources added can't be picked-up automatically.

Option 2: Post processing the result from `gcovr` with a custom script to achieve that goal.
Possible, and this is probably what I'll end up doing, but ideally `gcovr` could be a one-stop-shop for coverage.

**Comment by Spacetown** [comment]
I'm not sure if this special case should be handled by gcovr? Can you compile the executable (not the unittest) with all sources and active code coverage? This should produce `gcno` files which are also given to gcov and should produce uncovered lines.

**Comment by avrahamshukron** [comment]
That _could_ work...
Luckily I'm using gcc for both the host and target compiler (although different versions) so maybe I can enable coverage on the target build and I will get `.gcno` files for all the sources that are part of the project.

The troubles might start when invoking host `gcov` on files created with target `gcc`.
Possible solution would be to invoke `gcovr` once with `--gcov-executable` pointing to target `gcov` and `--keep` all `.gcov` files, then invoke it again on the test build directory and pass the target build directory as an additional `--object-directory` and `--use-gcov-files`.

That is a **lot** of moving parts, but I will give it a shot and report back.

But this made me realize that my problem is not unique, rather relevant to almost any cross-compile scenario, since in most of these cases the host build (for tests) will differ from target build which is the source of truth for the files in the project that actually matter.

**Comment by Spacetown** [comment]
It's quite easier. You run gcovr separately for host and target builds and generate a JSON report. Then Bothe JSON reports are given to a third call of gcovr to produce the overall report.

**Comment by avrahamshukron** [comment]
Ah nice!
I will try this approach.
It would require some changes to our build system, mainly enabling building the target FW with coverage flags **and skip linking** because a) it's a waste. b) It might fail due to the enlarged binaries no longer fitting in the designated memory area.

Anyway that is very specific to my project, but I'm detailing it here for the next wandering embedded developer facing similar issue.
With that I think this issue can now be closed.
