### ISSUE TITLE
Using gcovr for simple C1 coverage / interpretation of results

### ISSUE THREAD

**Issue by FlobOb** [gcovr/gcovr#83]
Hi,

for statements like

if (cond_a || cond_b || cond_c)

gcov expands the results to 8 different branches, but I'm just interested in the result of the complete statement, whether it evaluates to true or false. Is there an option for gcov to expand the statements only to 2 branches?

Furthermore, where do I get the information about what branches haven't been reached? If gcovr tells me that branches #3 and #5 in the example above have not been reached, how to interpret the result? The possibilities are

a b c
0 0 0
0 0 1
0 1 0
0 1 1
1 0 0
1 0 1
1 1 0 
1 1 1

What would be branch #3? 0 1 1?

thanks in advance

**Comment by mrx23dot** [comment]
I agree, please add taken branch  indicator in html output.
e.g. in LCOV:
http://i.stack.imgur.com/m9s2M.png

**Comment by latk** [comment]
Gcovr shows lcov-like branch coverage markers in the HTML-details and XML formats.

It is not possible to reduce this to statement-level branch coverage, as branch coverage is based on the actual assembly generated by your compiler. This is common to all of gcovr/gcov/lcov.

The `||` and `&&` operators short-circuit, so should be understood as control flow operators. This matters if parts of the condition are expensive function calls, e.g. `foo() || bar()`. If that's not the case, consider eliminating these extra branches by using bitwise operators:

    if (cond_a | cond_b | cond_c) do_something()

I sometimes find it helpful to build a branch condition outside of the conditional:

    bool is_cond = cond_a;
    if (!is_cond) is_cond = cond_b;
    if (!is_cond) is_cond = cond_c;

    if (is_cond) do_something();

That is much more verbose, but allows you to determine clearly which conditions are covered.
