### ISSUE TITLE
Branch Summary line color based off branches traversed.

### ISSUE THREAD

**Issue by RatMan64** [gcovr/gcovr#838]
I have a small problem with how there is only the percentage and black mono color fractions to visually Identify branch coverage. 

It would be nice to have a color like the yellow or red on the branch line summary to identify the usage of branches.

An alternative could be to change the color of the font for the branch line summary to a different color instead of the line.

**Comment by Spacetown** [comment]
To change the background like it's done for the lines is possible. The problem is that we have three colors here and not only two like for the line coverage:
- completely uncovered
- partial coverd
- full covered

We can use the colors for low, medium and high here. The question is if this should also be done for the background of the lines or only for them.

**Comment by RatMan64** [comment]
Would it be easier to use a argument to trigger this logic like --branch-coverage and so lines that do not have 100% coverage are marked by a single color? could also set what type of color is to be used.

**Comment by Spacetown** [comment]
I think a new option will complicate the logic in the template. It would be easier to use the already defined colors. I'll play a little bit and post a screenshot.

**Comment by Spacetown** [comment]
What about this examples?

Default green theme:
<img width="1266" alt="Bildschirmfoto 2023-10-10 um 23 10 50" src="https://github.com/gcovr/gcovr/assets/40258682/276639fa-b0ad-4296-89f0-ead9a9e268f2">

Default blue theme:
<img width="1146" alt="Bildschirmfoto 2023-10-10 um 23 14 59" src="https://github.com/gcovr/gcovr/assets/40258682/a3a8742f-1dc5-4fd8-a0fa-346b43e34cb9">

Github green:
<img width="1146" alt="Bildschirmfoto 2023-10-10 um 23 15 54" src="https://github.com/gcovr/gcovr/assets/40258682/41251122-0d45-4232-bbf4-dca0a515be68">

Github blue
<img width="1146" alt="Bildschirmfoto 2023-10-10 um 23 13 24" src="https://github.com/gcovr/gcovr/assets/40258682/4fdac673-a672-441c-a015-d3ef62d671bb">

**Comment by RatMan64** [comment]
yeah these would work for my use case.

**Comment by RatMan64** [comment]
pardon my ignorance. Was this achieved through an override of the CSS/html or was this an actual code change to get these results?

**Comment by Spacetown** [comment]
One Line in code to have the three states of coverage and the rest is done by CSS.

**Comment by Spacetown** [comment]
@RatMan64 Please can you check the linked PR branch?
