### ISSUE TITLE
Unhandled merge options

### ISSUE THREAD

**Issue by lodegaard** [gcovr/gcovr#841]
**Describe the bug**
Merge mode options are not passed down to merge functions.

The command I executed:
`$> PYTHONPATH=gcovr-src python3 -m gcovr --json -o /build/folder/path/coverage/coverage.json --gcov-executable=/opt/x86_64-gcc_13.2.0-linux-gnu/bin/x86_64-gcc_13.2.0-linux-gnu-gcov -j -s --root '/path/to/source/' --exclude '/.*/(test|generated|build)/,*' --merge-mode-functions=merge-use-line-0 -- /build/folder/path`

It fails with the following stack trace:
```
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/build/folder/path/gcovr-src/gcovr/__main__.py", line 546, in <module>
    main()
  File "/build/folder/path/gcovr-src/gcovr/__main__.py", line 328, in main
    covdata = collect_coverage_from_gcov(options)
  File "/build/folder/path/gcovr-src/gcovr/__main__.py", line 392, in collect_coverage_from_gcov
    covdata = merge_covdata(covdata, context["covdata"])
  File "/build/folder/path/gcovr-src/gcovr/merging.py", line 190, in merge_covdata
    return _merge_dict(left, right, merge_file, options)
  File "/build/folder/path/gcovr-src/gcovr/merging.py", line 139, in _merge_dict
    _insert_coverage_item(left, key, right_item, merge_item, options)
  File "/build/folder/path/gcovr-src/gcovr/merging.py", line 175, in _insert_coverage_item
    merged_item = merge_item(target_dict[key], new_item, options)
  File "/build/folder/path/gcovr-src/gcovr/merging.py", line 218, in merge_file
    left.functions = _merge_dict(
  File "/build/folder/path/gcovr-src/gcovr/merging.py", line 139, in _merge_dict
    _insert_coverage_item(left, key, right_item, merge_item, options)
  File "/build/folder/path/gcovr-src/gcovr/merging.py", line 175, in _insert_coverage_item
    merged_item = merge_item(target_dict[key], new_item, options)
  File "/build/folder/path/gcovr-src/gcovr/merging.py", line 292, in merge_function
    raise AssertionError(
AssertionError: Got function <Code snippet removed> on multiple lines: 0, 35.
	You can run gcovr with --merge-mode-functions=MERGE_MODE.
	The available values for MERGE_MODE are described in the documentation.
```

If I change the call to `merge_covdata` on `__main__.py:392` to:
```
covdata = merge_covdata(covdata, context["covdata"], get_merge_mode_from_options(options))
```
it works as expected. Is this a bug, or are the merge options omitted for a reason?

**To Reproduce**
I have not been able to reproduce this issue on another codebase

**Expected behavior**
Since the error message suggests adding a command line option to handle the situation, the options should either be included or the error message should be changed

**Desktop (please complete the following information):**
 - OS: Rocky Linux 9
 - GCC version GCC 13.2
 - GCOVR version 6.0

**Comment by Spacetown** [comment]
Hi, as mentioned in https://github.com/gcovr/gcovr/issues/586#issuecomment-1208635579 as first important point this was kept.

@latk I can't remember why this was important. Can you help here?

**Comment by latk** [comment]
I think I was focused in #586/#600 on making merging deterministic, and doing so in a bug-compatible way?

Making the merge-mode user-configurable was introduced in #700. Controlling the function-merging behaviour has only been documented in the context of `-a` combining existing JSON files.

But it sounds entirely sensible to also expose this for normal coverage processing (the gcov path). That we didn't do this sounds like an oversight, and a fix to that effect would be appreciated :)

@lodegaard would you like to create a PR for this?

To prevent similar issues from appearing in the future, we could think about making all the `MergeOptions` arguments in `merging.py` mandatory, removing the default value.

**Comment by Spacetown** [comment]
I also think we oversight this case. Making this a mandatory option would be an incompatible change. I'll vote for the current default or merging the functions by default with line number 0.

**Comment by latk** [comment]
> Making this a mandatory option would be an incompatible change.

We should absolutely keep the default on the CLI level, so that compatibility is maintained.

But within the `merging.py` functions, we can remove the default MergeOptions value so that each callsite within gcovr has to make an explicit decision about which options to use.

**Comment by lodegaard** [comment]
From what I understand, adding `get_merge_mode_from_options(options)` as an argument to `merge_covdata` will keep compatibilty. Since the default value for `options.merge_mode_functions` is `strict`, which yields `DEFAULT_MERGE_OPTIONS`. 

I will try to create a PR with this change

**Comment by Spacetown** [comment]
As latk mentioned we should also remove the default value here:
https://github.com/gcovr/gcovr/blob/88779183abe3ea532671e6fbc8d309e41860f632/gcovr/merging.py#L182-L184

**Comment by Spacetown** [comment]
@lodegaard Will you raise a PR for this?

**Comment by lodegaard** [comment]
@Spacetown Just did, sorry for the delay
