### ISSUE TITLE
Branch Coverage at Function Level

### ISSUE THREAD

**Issue by chaitanyaBhargava** [gcovr/gcovr#842]
**Is your feature request related to a problem? Please describe.**
It would be ideal to get branch coverage at **Per Function Level** in the "List Of Functions" html output. and hence it will be in the json output.
This will help us gate merges at per function level rather than file level.

**Describe the solution you'd like**
The File level Coverage Report shows **Branches Coverage** 
<img width="901" alt="image" src="https://github.com/gcovr/gcovr/assets/5873250/9f4e4be5-c03c-4b13-842a-3ac140d80b5e">

It would be useful to have it at "Per Function Level" as well. So another Column in the "List of Functions" view
<img width="1172" alt="image" src="https://github.com/gcovr/gcovr/assets/5873250/4637e267-a5de-4cb0-a7b5-9749a5f9179d">

**Describe alternatives you've considered**
The other Alternative is to scrape the htmls generate by gcovr, find the start of a function, travel to the end of it, find all instance of text like "5/6 branches covered" and add all those up. If there is a better alternative, willing to try it.

**Additional context**

I was trying to figure out how to add this functionality but couldn't exactly get it. It seem gcovr generates **FileCoverage** where the "type" for each line is present. Then when the html is being generated for each line, is traversed through and if it has branch coverage data that is summed up. 
So the same _could_ be done at the function html generation time but where I got stuck we there is no way to tell the start and end a function (Correction, no way to tell the _end_ of a function. **Start** is present). And annoyingly even GCOV doesn't seem to output the start and end of a function. Not in its text output at least, only in the json out (if --json-format is provided) but then the json output is missing other important info so its not what should be using.

If anyone can provide suggestion on how to do this, I can try adding this.

**Comment by Spacetown** [comment]
As mentioned in #654 this information can't be gathered from the gcov text output since we've no information to which function a branch or line belongs to.
When the gcov JSON format is supported this information would be present (see https://github.com/gcovr/gcovr/issues/282#issuecomment-1505389242).

**Comment by chaitanyaBhargava** [comment]
Interesting, Could like counting the number of `{` and `}` work to figure out function start and end? OR maybe if a `_FunctionLine` is hit, consider start of function till next `_FunctionLine` is hit? Or the combination of these 2?

**Comment by Spacetown** [comment]
As discussed in previous issues/PRs there can be local functions and there it won't work. Sorry.

**Comment by chaitanyaBhargava** [comment]
Got it. Thank you for the info.
