### ISSUE TITLE
--exclude-unreachable-branches removing almost all real branches

### ISSUE THREAD

**Issue by ghost** [gcovr/gcovr#85]
I'm not able to use the --exclude-unreachable-branches because it's incorrectly removing almost all branches as if they were "compiled generated". Is this option broken? I'd like to get real branch information or disable that in the Jenkins report (that I'm also not finding out how to do btw)

**Comment by latk** [comment]
This issue has not seen any progress in a while, so I am closing it for now. If the problem persists, please add further details so it can be re-opened. In particular:

 - whether the problem still occurs with an up-to-date gcovr (`pip install git+https://github.com/gcovr/gcovr.git`)
 - the smallest possible example source file + compiler invocation to reproduce the problem.

If someone else is experiencing a similar issue, please create a new issue.
