### ISSUE TITLE
Hashlib MD5 Fails in FIPS Mode

### ISSUE THREAD

**Issue by MikeFerko** [gcovr/gcovr#851]
**Describe the bug**
In FIPS mode, gcovr fails to use the hashlib MD5 algorithm during the generation of html coverage reports. This should be related to the `usedforsecurity` flag.

```python
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/gcovr/__main__.py", line 546, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/gcovr/__main__.py", line 333, in main
    error_occurred = print_reports(covdata, options)
  File "/usr/local/lib/python3.10/site-packages/gcovr/__main__.py", line 518, in print_reports
    if generator(covdata, output.abspath, options):
  File "/usr/local/lib/python3.10/site-packages/gcovr/writer/html/__init__.py", line [42], in print_html_report
    cdata_sourcefile[f] = _make_short_sourcename(
  File "/usr/local/lib/python3.10/site-packages/gcovr/writer/html/__init__.py", line 8[47], in _make_short_sourcename
    hashlib.md5(filename.encode("utf-8")).hexdigest(),
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
```

**To Reproduce**
1. Run Docker rocky linux 8 gcc10 container with FIPS mode enabled
2. Run `gcovr -a "coverage.json" --html-details --output "coverage.html"` on a GCOVR 6.0 compatible JSON file.

**Expected behavior**
Produce a html and css coverage report.

**Desktop (please complete the following information):**
 - OS: Linux
 - GCC version 10
 - GCOVR version 6.0

**Additional context**
Just some notes:

The National Institute of Standards and Technology (NIST) recommends using cryptographic algorithms that are FIPS-approved. MD5 is not considered secure and is not FIPS-approved, which is why there seems to be an issue when trying to use it in FIPS mode.

For FIPS compliance, it is recommended to use algorithms that are part of the FIPS-approved cryptographic module. [Current guidance](https://csrc.nist.gov/projects/cryptographic-module-validation-program/fips-140-3-ig-announcements) has several options including seven hash algorithms specified in FIPS 180-4: SHA-1, SHA-224, SHA-256, SHA-384 SHA-512, SHA-512/224 and SHA-512/256.

**Comment by latk** [comment]
Thanks for reporting this! This is a duplicate of https://github.com/gcovr/gcovr/issues/848 and already fixed in the development version.

Gcovr does not use MD5 for cryptographic purposes so there shouldn't be an issue with FIPS. But gcovr is really just "best effort" and might not be appropriate in scenarios with stringent compliance/certification needs.

**Comment by MikeFerko** [comment]
> Thanks for reporting this! This is a duplicate of #848 and already fixed in the development version.

Thanks for letting me know @latk!
 
> Gcovr does not use MD5 for cryptographic purposes so there shouldn't be an issue with FIPS. But gcovr is really just "best effort" and might not be appropriate in scenarios with stringent compliance/certification needs.

It should still work for my purpose as long as MD5 is not in use.
