### ISSUE TITLE
Trouble processing file, gcov output is None

### ISSUE THREAD

**Issue by playboy0007** [gcovr/gcovr#855]
![KSb3MuZNpQ](https://github.com/gcovr/gcovr/assets/36851506/fbac0192-4af2-4a67-a0e3-b36a4a97c214)

**Comment by latk** [comment]
Seems like the `gcov` tool might not be installed, or not in your PATH.

* Which compiler are you using?
* How are you invoking gcovr?

**Comment by playboy0007** [comment]
Thanks. I'm OK.
