### ISSUE TITLE
Compile Code and Collect Coverage Data on different machines

### ISSUE THREAD

**Issue by ganwi** [gcovr/gcovr#856]
Hi,
I have a setup where I want to compile source code for coverage (in a docker container) with gcovr. The binaries (and possibly also metadata) are then uploaded to a cloud storage.

In a second step the package is downloaded and tests are executed on a _different_ machine to collect the coverage data. It seems that absolute paths for dependencies are compiled into the binaries which makes me wonder if it is possible to use different machines for compilation and coverage collection?

Thank you.

**Comment by Spacetown** [comment]
That's a issue for cross compiling with gcov and not related to gcovr. See https://github.com/gcovr/gcovr/issues/403#issuecomment-667522168.

**Comment by ganwi** [comment]
Thank you for the hint. It is not clear from the instructions that the variable has to be set at _runtime_ -  not compile time. But after figuring that out it allows me to generate the *.gcda files on the target device.

Since the cross profiling does not provide the *gcno files I thought that I would have to copy the *.gcda files generated on the target device back to the build device and run gcovr from there?

That did not work as expected. I get 0% coverage althought I think the *.gcda files carry the correct information. Is there a step I am missing?

**Comment by Spacetown** [comment]
Can you try to run with option `--verbose` to get information if the files are found and filtered out?

**Comment by Spacetown** [comment]
The gcno files should be generated when compiling the source files. It's correct to copy the gcda files back to the machine where the compilation was done. Can you check with the option `--verbose` if the files are filtered out or why the coverage is 0%?
