### ISSUE TITLE
Large function lists break a browser

### ISSUE THREAD

**Issue by macetw** [gcovr/gcovr#857]
In my case, I use gcov with a large project over  many directories and files. With so many functions to list, I can't even see the function table -- my browser chokes on it. Chrome is trying to render a table with 625142 (+1) lines. The Chrome browser can't handle rendering an HTML table that is so big.

Could a table-break be created after every 1,000 or 10,000 entries? This would give a browser the breathing room to render tables.

(eventually, in my case, Chrome does this ...)
![Screenshot from 2023-12-01 09-30-17](https://github.com/gcovr/gcovr/assets/3484933/517ad0ed-db28-421e-bd2d-a401114670a2)

_Originally posted by @macetw in https://github.com/gcovr/gcovr/issues/840#issuecomment-1836505320_

I am using gcovr 6.0 and Chrome 119.0.6045.159 on Ubuntu Linux 64bit

**Comment by Spacetown** [comment]
Closed because #858 is merged.
