### ISSUE TITLE
gcovr in automated builds windows/mingw no output due to drive letter issue

### ISSUE THREAD

**Issue by kreuzberger** [gcovr/gcovr#86]
Hi!
With older (3.2) and current version of gcovr (3.3-prerelease) i have no output from gcovr, alle _.g_ files are available. After some tries i found out that files are filtered due to a drive letter case issue:

gcovr detect e.g. files in E:\src, the root ist given as e:\src

Unfortunately the root comes from the automated build system, where the root is normaly given via environment variables (e.g. %CD%, %WORKSPACE% )

maybe a "normalization" of the given root is required in the gcovr script.
I try to fix it in my windows script which calls gcovr.

**Comment by mrx23dot** [comment]
I can confirm this!
Use the following everywhere where possible in code:

from os.path import normpath
abs_filename = os.path.abspath(normpath(filename))

**Comment by kreuzberger** [comment]
for me on windows is was also necessary to call normcase. This fixes the drive letter issue alone.
from os.path import normpath
from os.path import normcase
abs_filename = os.path.abspath(normpath(normcase((filename)))

**Comment by latk** [comment]
Thank you for reporting this issue. It has been re-discovered in #230 where a fix is being developed. If you have any insight (e.g. any explanation why this cannot be reproduced on our Appveyor tests), please add your insight there.
