### ISSUE TITLE
An error about lambda was reported when executing gcovr

### ISSUE THREAD

**Issue by shendward** [gcovr/gcovr#860]
**error message:** 
`AssertionError: Got function hal::hal_ipc::IPCManager::pub_send_thread_func()::{lambda()#1}::operator()() const on multiple lines: 238, 245.`

**the 238 line is:** 
`XLOGE("failed to set scheduling policy SCHED_RR for pub thread: %s", strerror(errno));`
it's located is as follows：
`

    struct sched_param sp {};
    sp.sched_priority = 40;  // TODO(shendehua): which priority should be set?
    if (sched_setscheduler(0, SCHED_RR, &sp) < 0) {
        XLOGE("failed to set scheduling policy SCHED_RR for pub thread: %s", strerror(errno));
        return;
    }`

**the 245 line** is a lambda function which is in c++ condition_variable's wait: 
`     
   
     msg_mgr_->cv_.wait(lck, [this]() {
            if (msg_mgr_->queue_.empty()) {
                XLOGD("recv queue is empty");
                return false;
            } else {
                return true;
            }
        });`

I add gcovr's options which "--merge-mode-functions=totally_aggregate" or " --merge-mode-functions=filename_qualifier" or all of them as follows, but it still dosen't work!  

`

    gcovr -r . --config gcovr.cfg \
    --html --html-details -o install/coverage_report/index.html \
    --object-directory build/x64_Debug \
    --merge-mode-functions=totally_aggregate \
    --merge-mode-functions=filename_qualifier`

when i try to modify my log record function form XLOGE to XLOGD it's ok，XLOGE mean log level is error, XLOGD mean log level is debug. so what is the reason? what should i do?

my gcovr's version is 6.0
Programming language is c++
platform ubuntu 20.04.1

**Comment by Spacetown** [comment]
You can try to run `gcovr` with option `-v` to get verbose output. The line number is reported by `gcov` tool. The comment https://github.com/gcovr/gcovr/issues/586#issuecomment-1121869868 pointed out that this can be dependend on the compiler version. To handle such errors we introduced the option [--gcovr-merge-mode-functions](https://gcovr.com/en/stable/manpage.html#cmdoption-gcovr-merge-mode-functions).

**Comment by shendward** [comment]
I replaced the lambda function, and now it's ok!
The modified code is as follows:
`
while (msg_mgr_->queue_.empty()) {
            XLOGD("recv queue is empty");
            msg_mgr_->cv_.wait(lck);
        }
`

**Comment by shendward** [comment]
I have another problem here, Is the problem occurring because the version of gcovr is not matching with the GCC compiler? My gcovr version is 6.0, and the gcc and g++ versions are 10.5.0.
 Looking forward to your reply
It's info as follows: 


[----------] Global test environment tear-down
[==========] 8 tests from 2 test suites ran. (0 ms total)
[  PASSED  ] 8 tests.
/root/workspace/apps
(WARNING) Unrecognized GCOV output for /root/workspace/apps/ipc_service/src/ipc_service.cpp
	  branch  1 taken -1
	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
	NegativeHits: Got negative hit value in gcov line 'branch  1 taken -1' caused by a bug in gcov tool, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080. Use option --gcov-ignore-parse-errors with a value of negative_hits.warn, or negative_hits.warn_one.
(ERROR) Exiting because of parse errors.
	You can run gcovr with --gcov-ignore-parse-errors
	to continue anyway.
(ERROR) Trouble processing '/root/workspace/apps/build/x64_Debug/test/unitest/ipc_service/manager/CMakeFiles/ipc_manager_unitest.dir/__/__/__/__/ipc_service/src/ipc_service.cpp.gcda' with working directory '/root/workspace/apps/build/x64_Debug'.
Stdout of gcov was >>File '/usr/include/c++/10/tuple'
Lines executed:65.62% of 32
No branches
Calls executed:50.00% of 8
Creating 'tuple##b67d7bbf8003e7fd9288f296e6ffae00.gcov'

File '/usr/include/c++/10/bits/refwrap.h'
Lines executed:100.00% of 10
No branches
Calls executed:100.00% of 5
Creating 'refwrap.h##013192db8803a79c650d6748f8bd5b8b.gcov'

File '/usr/include/c++/10/bits/invoke.h'
Lines executed:100.00% of 5
No branches
No calls
Creating 'invoke.h##6fabb01680771b051805f1cbf77ca8bf.gcov'

File '/usr/include/c++/10/bits/move.h'
Lines executed:100.00% of 11
No branches
No calls
Creating 'move.h##a5d3dd30e3d6cc6f571ddd796c63a782.gcov'

File '/usr/include/c++/10/thread'
Lines executed:60.53% of 38
Branches executed:80.00% of 20
Taken at least once:40.00% of 20
Calls executed:53.33% of 15
Creating 'thread##c91a2722520e19f8af899caa0e124987.gcov'

File '/usr/include/c++/10/ext/new_allocator.h'
Lines executed:82.35% of 17
No branches
No calls
Creating 'new_allocator.h##a775ef6c53a715f798b5df3e0465a648.gcov'

File '/usr/include/c++/10/bits/shared_ptr_base.h'
Lines executed:64.22% of 109
Branches executed:42.86% of 14
Taken at least once:21.43% of 14
Calls executed:52.63% of 19
Creating 'shared_ptr_base.h##cc363595220042cdbac998ed150175de.gcov'

File '/usr/include/c++/10/bits/alloc_traits.h'
Lines executed:52.63% of 19
No branches
No calls
Creating 'alloc_traits.h##4f06bc8e96b8877f55ed1daac51de66f.gcov'

File '/usr/include/c++/10/bits/stl_algobase.h'
Lines executed:12.16% of 74
Branches executed:23.08% of 26
Taken at least once:7.69% of 26
Calls executed:14.29% of 28
Creating 'stl_algobase.h##b8a23a7f263d578f050f142c62e6b688.gcov'

File '/usr/include/c++/10/ext/aligned_buffer.h'
Lines executed:100.00% of 4
No branches
No calls
Creating 'aligned_buffer.h##38cc3df8d5e6e292997406e8d0f16153.gcov'

File '/usr/include/c++/10/bits/cpp_type_traits.h'
Lines executed:0.00% of 2
No branches
No calls
Creating 'cpp_type_traits.h##fd4eb49da84a5be3b7b9e9ebb20a22ee.gcov'

File '/usr/include/c++/10/bits/stl_iterator.h'
Lines executed:0.00% of 19
No branches
Calls executed:0.00% of 4
Creating 'stl_iterator.h##e8a0f64242f39c2913ecb011ef173e27.gcov'

File '/usr/include/c++/10/bits/stl_vector.h'
Lines executed:0.00% of 85
Branches executed:0.00% of 12
Taken at least once:0.00% of 12
Calls executed:0.00% of 52
Creating 'stl_vector.h##fc580d35058d21a0a6a07f628c0d70b7.gcov'

File '/usr/include/c++/10/bits/stl_construct.h'
Lines executed:0.00% of 11
No branches
No calls
Creating 'stl_construct.h##2234d5856d490dc691164af4e06c6624.gcov'

File '/usr/include/c++/10/bits/stl_uninitialized.h'
Lines executed:0.00% of 19
Branches executed:0.00% of 2
Taken at least once:0.00% of 2
Calls executed:0.00% of 14
Creating 'stl_uninitialized.h##57a91269ce0714be86eef86ae6e18ff5.gcov'

File '/usr/include/c++/10/bits/ptr_traits.h'
Lines executed:100.00% of 2
No branches
No calls
Creating 'ptr_traits.h##ace4103fe8852f70b4e8449d20da31f9.gcov'

File '/usr/include/c++/10/bits/allocated_ptr.h'
Lines executed:100.00% of 13
No branches
No calls
Creating 'allocated_ptr.h##2754185c606e00ecca0daf06d682969b.gcov'

File '/usr/include/c++/10/bits/stl_deque.h'
Lines executed:3.85% of 156
Branches executed:7.69% of 26
Taken at least once:3.85% of 26
Calls executed:1.18% of 85
Creating 'stl_deque.h##71cb3d98dd95a2e73a67ed774d64b2ce.gcov'

File '/usr/include/c++/10/bits/allocator.h'
Lines executed:100.00% of 5
No branches
No calls
Creating 'allocator.h##5e02915820839beb6c3fe5901afd8713.gcov'

File '/usr/include/c++/10/bits/stl_iterator_base_funcs.h'
Lines executed:0.00% of 5
No branches
No calls
Creating 'stl_iterator_base_funcs.h##73310c1e9ee5a158fe6002311a6967af.gcov'

File '/usr/include/c++/10/bits/stl_iterator_base_types.h'
Lines executed:0.00% of 2
No branches
No calls
Creating 'stl_iterator_base_types.h##e886d1b4e7d690576dac8757d44b3fb6.gcov'

File '/usr/include/c++/10/ext/type_traits.h'
Lines executed:0.00% of 2
No branches
No calls
Creating 'type_traits.h##efb264e3cf163df3b4ba087797000f24.gcov'

File '/usr/include/c++/10/bits/deque.tcc'
Lines executed:0.00% of 65
Branches executed:0.00% of 14
Taken at least once:0.00% of 14
Calls executed:0.00% of 26
Creating 'deque.tcc##1f53a37826ab81cd314dc75ff58f4b63.gcov'

File '/usr/include/c++/10/bits/basic_string.tcc'
Lines executed:0.00% of 13
No branches
No calls
Creating 'basic_string.tcc##289f0906546243d05c20f28d605e0bc8.gcov'

File '/usr/include/c++/10/chrono'
Lines executed:91.67% of 24
Branches executed:100.00% of 2
Taken at least once:50.00% of 2
Calls executed:100.00% of 13
Creating 'chrono##840682e8592ba21b0bad93692b63fa36.gcov'

File '/usr/include/c++/10/bits/predefined_ops.h'
Lines executed:0.00% of 7
No branches
Calls executed:0.00% of 2
Creating 'predefined_ops.h##d73d26d635a35031a8d0d40aa203c632.gcov'

File '/usr/include/c++/10/ext/alloc_traits.h'
Lines executed:0.00% of 4
No branches
Calls executed:0.00% of 1
Creating 'alloc_traits.h##30c9bad6ab674a3111c7f300639aeef8.gcov'

File '/usr/include/c++/10/bits/unique_ptr.h'
Lines executed:0.00% of 17
Branches executed:0.00% of 4
Taken at least once:0.00% of 4
Calls executed:0.00% of 11
Creating 'unique_ptr.h##6f80b1824888301ea8c4ed70c79c8417.gcov'

File '/usr/include/c++/10/bits/basic_string.h'
Lines executed:0.00% of 11
Branches executed:0.00% of 8
Taken at least once:0.00% of 8
Calls executed:0.00% of 7
Creating 'basic_string.h##dae29d0dd5b2a67032dc11bf01012b8b.gcov'

File '/usr/include/c++/10/bits/shared_ptr.h'
Lines executed:88.24% of 17
No branches
Calls executed:60.00% of 5
Creating 'shared_ptr.h##241ab4b6ca92811def360116a08412f5.gcov'

File '/usr/include/c++/10/bits/unique_lock.h'
Lines executed:0.00% of 24
Branches executed:0.00% of 10
Taken at least once:0.00% of 10
Calls executed:0.00% of 8
Creating 'unique_lock.h##df95d8146aa092b7907845401f82ed2a.gcov'

File '/usr/include/c++/10/bits/vector.tcc'
Lines executed:0.00% of 27
Branches executed:0.00% of 2
Taken at least once:0.00% of 2
Calls executed:0.00% of 19
Creating 'vector.tcc##a7508ad933d24b7badc7c5b0742dd3c3.gcov'

File '/usr/include/c++/10/ext/atomicity.h'
Lines executed:0.00% of 11
Branches executed:0.00% of 6
Taken at least once:0.00% of 6
Calls executed:0.00% of 3
Creating 'atomicity.h##3260447a0a9e1a1cf3dd02968e2ee4d5.gcov'

File '/usr/include/c++/10/bits/stl_algo.h'
Lines executed:100.00% of 3
No branches
Calls executed:100.00% of 2
Creating 'stl_algo.h##de9b1a61aa3e2fd9c40ac7bb200bfb5a.gcov'

File '/usr/include/c++/10/bits/stl_queue.h'
Lines executed:11.11% of 18
No branches
Calls executed:11.11% of 9
Creating 'stl_queue.h##85b4abfa2e89e2644d10bda570c54d6c.gcov'

File '/usr/include/c++/10/bits/char_traits.h'
Lines executed:0.00% of 12
Branches executed:0.00% of 4
Taken at least once:0.00% of 4
Calls executed:0.00% of 2
Creating 'char_traits.h##d6726cb6c2b594316536fba5cc251989.gcov'

File '/root/workspace/apps/ipcx_service/service/src/ipcx_service.cpp'
Lines executed:65.15% of 132
Branches executed:59.17% of 240
Taken at least once:35.83% of 240
Calls executed:43.29% of 425
Creating 'ipcx_service.cpp##c54095831d9760c08825639f7f351d88.gcov'

File '/usr/include/c++/10/bits/std_mutex.h'
Lines executed:0.00% of 8
Branches executed:0.00% of 2
Taken at least once:0.00% of 2
Calls executed:0.00% of 3
Creating 'std_mutex.h##2913791588e8b5cbbbf1e1280ee9a27a.gcov'

File '/usr/include/x86_64-linux-gnu/c++/10/bits/gthr-default.h'
Lines executed:0.00% of 10
Branches executed:0.00% of 4
Taken at least once:0.00% of 4
Calls executed:0.00% of 4
Creating 'gthr-default.h##0f3d3b2a916e6aa9c2c4fe2a2c3b93a0.gcov'

File '/usr/include/c++/10/new'
Lines executed:0.00% of 3
No branches
No calls
Creating 'new##e627eee0536ea900e006e331150e8a30.gcov'

File '/usr/include/c++/10/typeinfo'
Lines executed:0.00% of 4
Branches executed:0.00% of 6
Taken at least once:0.00% of 6
No calls
Creating 'typeinfo##5414e9729c54e933e2ea0a1c048b3fec.gcov'

File '/usr/include/c++/10/atomic'
Lines executed:0.00% of 6
No branches
Calls executed:0.00% of 3
Creating 'atomic##ed50ea332c93d810962b5de11cb87d37.gcov'

File '/usr/include/c++/10/bits/atomic_base.h'
Lines executed:0.00% of 7
No branches
Calls executed:0.00% of 3
Creating 'atomic_base.h##71dddbae4e376c7c8d8094f15e731d92.gcov'

<< End of stdout
Stderr of gcov was >><< End of stderr
Current processed gcov file was '/root/workspace/apps/build/x64_Debug/ipcx_service.cpp##c54095831d9760c08825639f7f351d88.gcov'.
Use option --verbose to get extended informations.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 80, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 323, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 564, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 140, in process_gcov_data
    coverage, source_lines = parse_coverage(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 355, in parse_coverage
    _report_lines_with_errors(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 521, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 317, in parse_coverage
    _parse_line(raw_line, ignore_parse_errors, persistent_states),
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 628, in _parse_line
    tag = _parse_tag_line(line, ignore_parse_errors, persistent_states)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 745, in _parse_tag_line
    raise NegativeHits(line)
gcovr.gcov_parser.NegativeHits: Got negative hit value in gcov line 'branch  1 taken -1' caused by a bug in gcov tool, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080. Use option --gcov-ignore-parse-errors with a value of negative_hits.warn, or negative_hits.warn_one.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 80, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 323, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 564, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 140, in process_gcov_data
    coverage, source_lines = parse_coverage(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 355, in parse_coverage
    _report_lines_with_errors(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 521, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 317, in parse_coverage
    _parse_line(raw_line, ignore_parse_errors, persistent_states),
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 628, in _parse_line
    tag = _parse_tag_line(line, ignore_parse_errors, persistent_states)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 745, in _parse_tag_line
    raise NegativeHits(line)
gcovr.gcov_parser.NegativeHits: Got negative hit value in gcov line 'branch  1 taken -1' caused by a bug in gcov tool, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080. Use option --gcov-ignore-parse-errors with a value of negative_hits.warn, or negative_hits.warn_one.
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/gcovr/__main__.py", line 328, in main
    covdata = collect_coverage_from_gcov(options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/__main__.py", line 387, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 173, in __exit__
    self.wait()
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 164, in wait
    raise self.exceptions[0][1]
  File "/usr/local/lib/python3.8/dist-packages/gcovr/__main__.py", line 387, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 164, in wait
    raise self.exceptions[0][1]
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 80, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 323, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 564, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 140, in process_gcov_data
    coverage, source_lines = parse_coverage(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 355, in parse_coverage
    _report_lines_with_errors(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 521, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 317, in parse_coverage
    _parse_line(raw_line, ignore_parse_errors, persistent_states),
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 628, in _parse_line
    tag = _parse_tag_line(line, ignore_parse_errors, persistent_states)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 745, in _parse_tag_line
    raise NegativeHits(line)
gcovr.gcov_parser.NegativeHits: Got negative hit value in gcov line 'branch  1 taken -1' caused by a bug in gcov tool, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080. Use option --gcov-ignore-parse-errors with a value of negative_hits.warn, or negative_hits.warn_one.
root@sh:~/workspace/apps#

**Comment by Spacetown** [comment]
This is a bug in gcov and we can't workaround this. Please see also #583.

**Comment by shendward** [comment]
I'm confused, this problem does not occur every time! Sometims it's ok, even if they are in the exact same environment.

**Comment by Spacetown** [comment]
Please check the link to the gcc bug in the error message. In multi threaded programs there can be race conditions which can result in negative counters in the gcda files. Gover detects this and provides an option to ignore these errors.
