### ISSUE TITLE
Exclude options are confusing

### ISSUE THREAD

**Issue by tsondergaard** [gcovr/gcovr#861]
I get the following error when running `gcovr`:

```
+ gcovr -j 32 --merge-mode-functions=merge-use-line-min --xml --root /home/jenkins/workspace/foo '--exclude=.*/tests/.*' '--exclude=build/.*' '--exclude=.*/examples/.*' '--exclude=third-party/.*' '--exclude=mitest/.*' '--exclude=mcop/.*' '--exclude=ftgl/.*' --exclude-directories=mcopidl -o build/cobertura-coverage.xml /home/jenkins/workspace/foo/build
(ERROR) GCOV produced the following errors processing /home/jenkins/workspace/foo/build/mcop/mcopidl/CMakeFiles/evmcopidl.dir/scanner.cc.gcda:
	Cannot open source file /home/jenkins/workspace/foo/build/scanner.ll
Cannot open source file /home/jenkins/workspace/foo/build/scanner.cc
```

Shouldn't --exclude-directories=mcopidl prevent `gcovr` from running `gcov` on /home/jenkins/workspace/foo/build/mcop/mcopidl/CMakeFiles/evmcopidl.dir/scanner.cc.gcda

I'm using gcovr 6.0.

**Comment by latk** [comment]
Yes, these options are confusing. But changing how they behave would confuse even more people :/

The `--gcov-exclude-directories` option has guide-level documentation here: https://gcovr.com/en/6.0/guide/filters.html#speeding-up-coverage-data-search

You have correctly understood that this option affects what gcda files are detected.

However, this option uses the same filtering system as other filter/exclude options. That is, the value is a regex matched against a *path*. It is not matched just against the directory name.

The regex `mcopidl` would match a path `mcopidl` (in the current directory), but not the path `mcop/mcopidl`: the regex starts matching at the *beginning* of the path (relative to the current working directory).

If you want to exclude any directory `mcopidl`, you would have to use the regex `(.+/)?mcopidl$`. I'm sorry, I know this is awful, but at least it works consistently across filtering options.

If you know the directory's path (relative to your current working directory), you could use the regex `mcop/mcopidl$` instead.

Other remarks on your gcovr invocation:

* The `-j` option has unclear impact on performance. It really depends on the layout of your build directories.
* You can combine the `--xml` and `-o some-path.xml` options to `--xml some-path.xml`
* If you have many exclusion patterns, consider using a config file. Note that the regexes in a config file match paths relative to that file, not relative to gcovr's working directory or root.

**Comment by tsondergaard** [comment]
@latk I really appreciate your help and your work on gcovr. Using `(.+/)?mcopidl$` did the job. Thanks for the additional helpful suggestions!
