### ISSUE TITLE
source file is newer than notes file

### ISSUE THREAD

**Issue by LumanYang** [gcovr/gcovr#863]
i compile project in one pc and run this program in another pc.
i download the source code and check the commitid that is same as when it compiled
i get .gcda and .gcno files, the same name files are in the same directory
but  there is error:
source file is newer than notes file
i cannot find the problem

**Comment by Spacetown** [comment]
This message seems to be from gcov and not from gcovr. If you checkout the commit the files get the current timestamp.

**Comment by Spacetown** [comment]
Have you tried to checkout the source code on machine B before compiling on machine A?

**Comment by Spacetown** [comment]
Close because of no response
