### ISSUE TITLE
Add support to the Atlassian Clover output format

### ISSUE THREAD

**Issue by AJIOB** [gcovr/gcovr#865]
**Atlassian Bamboo test coverage integration needs**
Bamboo's native format is the Atlassian Clover format. It is also an XML, but it differs from the Cobertura one.

On some newer Bamboo UIs I saw an .NET's NCover support, but gcovr doesn't support it too.

**I suggest to natively support Atlassian Clover output**
I want to have an additional `--clover` CLI flag for generating Clover output.

It can be manually rewritten or using some converters.

**Alternatives**
A native Cobertura to clover integration. Looks like [this one](https://github.com/cwacek/cobertura-clover-transform) can be used as a base.

Doing one more call doesn't look nice for me.

**Additional context**
Clover information can be found [here](https://confluence.atlassian.com/clover/clover-documentation-home-71598318.html)

**Comment by Spacetown** [comment]
There was already a request with missing information (#826). Your request gives more context but I miss a schema for the Clover XML format. Do you have more information?

**Comment by AJIOB** [comment]
Hi @Spacetown 

You can use [this transform.xslt](https://github.com/cwacek/cobertura-clover-transform/blob/master/cobertura_clover_transform/transform.xslt) as a base for transforming from the Cobertura XML to the Clover XML one.

[clover.xsd.zip](https://github.com/gcovr/gcovr/files/13815934/clover.xsd.zip) contains *clover.xsd* file from the Clover for Ant 4.1.1. More info can be found [here](https://community.atlassian.com/t5/Bamboo-questions/Clover-XML-Schema/qaq-p/387506).

The similar *clover.xsd* file can be found [in the open-source Atlassian repository](https://bitbucket.org/atlassian/clover/src/master/etc/schema/clover.xsd).

OpenClover 4.5.1 also uses the same schema. It can be found in the root of the *clover-idea-4.5.1.jar* archive.

**Comment by Spacetown** [comment]
I need to check this but have less time this month.

**Comment by AJIOB** [comment]
Hi @Spacetown,

Is this information contains all that you need to add the native Clover support?

**Comment by Spacetown** [comment]
I checked the XSLT but it generates a XML file which doesn't validate. Required attributes (according to the DTD) are missing.

**Comment by Spacetown** [comment]
I saw the XSD but e.g. the documentation of the attribute `clover` on the root level is missing. The transformation also doesn't write this required attribute.

**Comment by AJIOB** [comment]
Let's try to skip this attribute for now.

Conversion tool generates a valid `clover.xml` file for the Bamboo instance that I've already used.

**Comment by Spacetown** [comment]
It's required. If the server accepts it than they don't validate the data. But the XSD describes the expected data someone has to provide.

**Comment by Spacetown** [comment]
I started on this but it's really complicated. All elements are mandatory according to the XSD but it seems that bamboo doesn't know the XSD and tries to read as much as possible.

With the linked XSLT following XML is produced:

```xml
<coverage generated="1234">
  <project timestamp="1234">
    <file name="main.cpp">
      <line type="stmt" num="3" count="0"/>
      <line type="stmt" num="4" count="0"/>
      <line type="stmt" num="7" count="1"/>
      <line type="stmt" num="8" count="1"/>
      <line type="stmt" num="9" count="0"/>
      <line type="stmt" num="11" count="1"/>
      <line type="stmt" num="16" count="1"/>
      <line type="stmt" num="20" count="1"/>
      <line type="stmt" num="21" count="1"/>
      <line type="stmt" num="25" count="0"/>
      <line type="stmt" num="28" count="1"/>
      <line type="stmt" num="29" count="4"/>
      <metrics ncloc="12" coveredelements="8" elements="12"/>
    </file>
    <metrics ncloc="12" coveredelements="8" elements="12"/>
  </project>
</coverage>
```

From schema validation I get following errors:

```text
clover.xml:3: element file: Schemas validity error : Element 'file': This element is not expected. Expected is ( metrics ).
clover.xml:1: element coverage: Schemas validity error : Element 'coverage': Missing child element(s). Expected is ( testproject ).
```

- The mandatory `package` element is missing.
- The `line` elements should be wrapped inside a `lines` element.
- The metrics element must be the first child.
- A `testproject` element is mandatory.

**Comment by Spacetown** [comment]
@AJIOB Please can you check the linked PR? The generated files are valid according to the XSD schema.

**Comment by AJIOB** [comment]
Hi @Spacetown 

I've test your generated coverage file with the Bamboo, but it looks like bad formatted for Bamboo itselves:
![image](https://github.com/gcovr/gcovr/assets/19916290/9933497d-c5d7-4f7c-9c11-5092528f0308)

I've used the `python3.8 -m pip install git+https://github.com/Spacetown/gcovr.git@add_clover_output_format` command for installing the newer version.

`gcovr` was powered by python3.8.9, that was built from sources.

XML file was generated successfully, but it doesn't really work. The current coverage was near 42%, not zero one.

**Comment by AJIOB** [comment]
Maybe we can see the output of https://github.com/openclover/clover-examples/tree/master as a truly Java valid file output (I think it should be also convenient with XSD schema).

**Comment by Spacetown** [comment]
> Maybe we can see the output of https://github.com/openclover/clover-examples/tree/master as a truly Java valid file output (I think it should be also convenient with XSD schema).

There is no example for a report only for configuration.

**Comment by Spacetown** [comment]
@AJIOB Please can you check the updated branch?

**Comment by AJIOB** [comment]
Hi @Spacetown,

Sorry for a long answer.

The new version looks much better:
![image](https://github.com/gcovr/gcovr/assets/19916290/1895b609-e65f-4e42-8353-9705f3f9dd3f)

Thanks
