### ISSUE TITLE
Decisions coverage is not printed in JSON summary

### ISSUE THREAD

**Issue by PiPointX** [gcovr/gcovr#866]
**Describe the bug**
When decisions coverage and JSON summary are activated no decisions coverage will be generated in the json summary.
**To Reproduce**
1. Generate a coverage reproirt with --devicisions and --json-summary
2. Open JSON summary
3. No decisions coverage is shown

**Expected behavior**
I would expect Line-, Funtions-,  Branches-, and Decisions-Coverage in the JSON summary.

**Comment by Spacetown** [comment]
The option only affects the summary report and not the JSON summary report.

**Comment by PiPointX** [comment]
Thats right, but I would expect, that a summary includes also the decision coverage when enabled.

**Comment by Spacetown** [comment]
The decision coverage is fairly new and buggy. It was introduced in the HTML writer, the TXT summary writer and the JSON output (representation of the whole internal data structure).

I'll appreciate any PR for this enhancement.
