### ISSUE TITLE
Update PyPi Frequency

### ISSUE THREAD

**Issue by austride** [gcovr/gcovr#868]
How often does PyPi get updated? 

I see this change was implemented https://github.com/gcovr/gcovr/issues/851 but I wasn't sure how I go about including it when I do a pip3 install gcovr.

Looking at PyPi it says gcovr hasn't been released since March of 2023 (prior to above change/fix)

**Comment by Spacetown** [comment]
It's planed in this month but l can't promiss this. You can install directly from git repository with `git+CloneUrl@Branch OrCommit`.

**Comment by Spacetown** [comment]
Release was done yesterday. Since work is done in our spare time we can't guarantee a release frequency or reaction time at all.
