### ISSUE TITLE
`master` branch docs are out of date

### ISSUE THREAD

**Issue by Pesa** [gcovr/gcovr#870]
The documentation for the `master` branch deployed at https://gcovr.com/en/master/ is stuck at commit 51053d27. Can it be updated please?

**Comment by Spacetown** [comment]
The master was renamed to main last October (see #829). I'll check on this.

**Comment by Spacetown** [comment]
It looks like that the renaming falls together with the requirement to have a configuration file in the repository (https://blog.readthedocs.com/migrate-configuration-v2/).
