### ISSUE TITLE
IOError: [Errno 63] File name too long

### ISSUE THREAD

**Issue by runv** [gcovr/gcovr#88]
gcovr -r fails when processing objective c file with a name, which is longer then 63 letters:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/gcovr", line 1961, in <module>
    process_datafile(file_,covdata,options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/gcovr", line 749, in process_datafile
    process_gcov_data(fname, covdata, options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/gcovr", line 412, in process_gcov_data
    INPUT = open(data_fname,"r")
IOError: [Errno 63] File name too long: u'#var#lib#slave#workspace#com.abcde.app.aaaa#modules#client#abc-abc-abc-abc#src#a#items#process1#subprocess1#subprocess2#ff#ABCEfgHijklMnopQRstuvSomeClassName.m.gcov'

gcovr --version
gcovr 3.2

**Comment by theold190** [comment]
Similar problem when I run my scripts. File names was 123 characters, while full path - 217.

**Comment by whart222** [comment]
Can you add a test to confirm whether #128 resolves this issue?

**Comment by PaulTaykalo** [comment]
The bug is still reproduceable.
It started when switched cocopods to use frameworks instead of static typing.

**Comment by tchernobog** [comment]
This is probably a problem in gcov instead of gcovr. Can you tell gcovr not to remove intermediate files, and paste here the full path on disk to one of the .gcov files triggering the error?

**Comment by PaulTaykalo** [comment]
IOError: [Errno 63] File name too long: u'#Users#jenkins-ci#jenkins-slave#workspace#xxxxxxxxx_IOS_develop-tests_publish#cintegration#output#Build#Intermediates#ArchiveIntermediates#xxxxxxxxxTests#BuildProductsPath#Coverage-iphonesimulator#CedarAsync#CedarAsync.framework#Headers#AsyncActualValue.h.gcov'

**Comment by PaulTaykalo** [comment]
Hm.. and for some reason files like that were actually created inside of the root of the proejct

**Comment by PaulTaykalo** [comment]
This is kind'a fixes it...
```
def process_gcov_data(data_fname, covdata, source_fname, options):
    try:
        INPUT = open(data_fname, "r")
    except Exception as e:
        sys.stdout.write("  Cannot open gcov file %s\n" % e.strerror)
        return
```

**Comment by tchernobog** [comment]
@PaulTaykalo you would however get incomplete or wrong results in the report. I would say this should be fixed in gcov, and gcovr can only abort if such a filename is too long. I am not the maintainer, but my 2¢ would be to close this as WONTFIX, and open a bug against gcov instead.

**Comment by Spacetown** [comment]
Closed as suggested.
