### ISSUE TITLE
UnknownLineType thrown when parsing coverage data from 10K+ line file

### ISSUE THREAD

**Issue by zidel** [gcovr/gcovr#882]
**Describe the bug**
When the source code file is larger than 10K lines the .gcov format appears to drop the space between %%%%%: and the line number. This causes _RE_BLOCK_LINE to not match since it requires the space to be present.

Slightly redacted .gcov extract:
```
    %%%%%: 9998-block  1
call    6 never executed
    #####: 9999:    child_->set_access([...]);
call    0 never executed
branch  1 never executed (fallthrough)
branch  2 never executed (throw)
    #####:10000:    setReadAccess(*child_);
    %%%%%:10000-block  0
call    0 never executed
branch  1 never executed (fallthrough)
branch  2 never executed (throw)
    #####:10001:    child_ = child_->add_child([...]);
    %%%%%:10001-block  0
```

**To Reproduce**
1. Generate coverage data for a file with at least 10000 lines of code
2. gcovr -r . --html-details -o coverage/index.html (or similar)
3. gcovr dumps all -block lines with line number 10000 or higher, then fails with `gcovr.formats.gcov.parser.UnknownLineType:     %%%%%:10000-block  0`

**Expected behavior**
_RE_BLOCK_LINE should matches lines 10000 and later

**Desktop (please complete the following information):**
 - OS: Debian testing
 - GCC version: Debian 13.2.0-13
 - GCOVR version 7.0

**Additional context**
When I deleted the .gcno file for the large .cpp file the report for the other files was generated successfully

**Comment by Spacetown** [comment]
Thanks for reporting this. I try to check on this today.

**Comment by zidel** [comment]
I have a small patch for this at work, but I don't know how long it will take to get approval to upstream it. I'll leave it up to you whether you want to fix it yourself or wait for a PR.

**Comment by Spacetown** [comment]
> I have a small patch for this at work, but I don't know how long it will take to get approval to upstream it. I'll leave it up to you whether you want to fix it yourself or wait for a PR.

I know this. The first contribution to glove I did in my spare time 😆, now you see the result.
