### ISSUE TITLE
Erroneous deprecation warning

### ISSUE THREAD

**Issue by Tsche** [gcovr/gcovr#909]
When executing gcovr with `-u`, `--sort-uncovered`, `-p` or `--sort-percentage` gcovr emits a message like
```
Deprecated, please use '--sort-key uncovered-number' instead. 
```

Running gcovr with `--sort-key uncovered-number` however emits an error
```
gcovr: error: unrecognized arguments: --sort-key uncovered-number
```

The actual argument is called `--sort`, not `--sort-key`. See [`configuration.py` lines 535-549](https://github.com/gcovr/gcovr/blob/91722090733b9da9599139fb58f52349feab2897/gcovr/configuration.py#L535-L549). 

Either the deprecation warnings should be updated or the command line argument `--sort` renamed to match the configuration key. Please let me know which option you prefer, I'm happy to contribute the change myself.

**Comment by Spacetown** [comment]
I prefer to update the deprecation warning because the documentation uses the option `--sort`.
