### ISSUE TITLE
Add support for GCC 14 condition coverage (MC/DC)

### ISSUE THREAD

**Issue by sebhub** [gcovr/gcovr#913]
GCC 14 will support condition coverage:

https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fcondition-coverage

The corresponding GCC commit is:

https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=08a52331803f66a4aaeaedd278436ca8eac57b50

Support was added to the gcov tool to show the condition coverage information:

https://gcc.gnu.org/onlinedocs/gcc/Invoking-Gcov.html

```
gcov --conditions:

        3:   17:void fn (int a, int b, int c, int d) {
        3:   18:    if ((a && (b || c)) && d)
conditions covered 3/8
condition  0 not covered (true false)
condition  1 not covered (true)
condition  2 not covered (true)
condition  3 not covered (true)
        1:   19:        x = 1;
        -:   20:    else
        2:   21:        x = 2;
        3:   22:}

gcov --conditions --json-format:

"conditions": [
    {
        "not_covered_false": [
            0
        ],
        "count": 8,
        "covered": 3,
        "not_covered_true": [
            0,
            1,
            2,
            3
        ]
    }
],
```
It would be nice if gcovr could also present this information.

**Comment by Spacetown** [comment]
We're waiting already for the release of version 14 to finish #766

**Comment by Spacetown** [comment]
@latk How shall we continue with the decision coverage? With gcc 14 this wouldn't be needed anymore.

**Comment by latk** [comment]
> With gcc 14 this wouldn't be needed anymore.

It will be quite some time until GCC 14 is widely used. Gcovr claims support for GCC 5.x (!), and Clang is also a thing.

It would be great to use this new GCC feature whenever available, but to continue supporting a reasonable range of other compilers.

**Comment by whentojump** [comment]
Hi, is there any update on this? Thanks!

**Comment by Spacetown** [comment]
There is still an open bug for the JSON. See #282.

**Comment by Spacetown** [comment]
@sebhub Can we assume that condition 0 is branch 0 and 1, condition 1 is branch 2 and 3, ...?

**Comment by jokva** [comment]
Unfortunately, in general, no. From the gcov manual:

> For each basic block, a line is printed after the last line of the basic block describing the branch or call that ends the basic block. There can be multiple branches and calls listed for a single source line if there are multiple basic blocks that end on that line. In this case, the branches and calls are each given a number. There is no simple way to map these branches and calls back to source constructs. In general, though, the lowest numbered branch or call will correspond to the leftmost construct on the source line. 

https://gcc.gnu.org/onlinedocs/gcc/Invoking-Gcov.html

The condition coverage specifically sorts the conditions in order so the nth condition corresponds to the nth term (assuming short-circuiting semantics).

**Comment by Spacetown** [comment]
Ok. In that case we can only exclude the branch and not the condition in #961 .
