### ISSUE TITLE
Multiple path filtering pitfall

### ISSUE THREAD

**Issue by lwasowicz90** [gcovr/gcovr#92]
Is it possible to pass a few argument as an input for --filter ? I mean a few specific files.
When i invoke command:
gcovr -x -f "path/to/file1/file1.cpp  path/to/file1/file2.cpp" -o out.xml
i get an error,
then invoking:
gcovr -x -f "path/to/file1/file1.cpp"  -f "path/to/file1/file2.cpp" -o out.xml 
it looks as if it was parsing only latter file, not both as i expected.
So, is it possible to invoke gcovr using multiple filtering ?

**Comment by latk** [comment]
It is possible to repeat the filter option multiple times, as in your second example.

In your first case, you were filtering for a directory called “`file1.cpp path`”, i.e. with a space in the directory name.

As the filters are regex patterns, you could also use alternation: `gcovr -f '(path1|path2)'`. However, I strongly recommend using separate filters instead.
