### ISSUE TITLE
gcovr 7.2 package contains gcovr 3.2 binaries

### ISSUE THREAD

**Issue by ruben-fuerst** [gcovr/gcovr#926]
**Describe the bug**
It seems the package gcovr-7.2-1 under kali actually contains gcovr 3.2 binaries.

**To Reproduce**
`sudo apt update && sudo apt upgrade -y && sudo apt install gcovr` under kali-rolling (WSL2). But should be the same for non-WSL kali too. I broke my dual-boot so can only speek for WSL atm.

**Expected behavior**
`gcovr --version` should print "gcovr 7.2"

**Screenshots**
![image](https://github.com/gcovr/gcovr/assets/25719818/309808b5-076a-4833-8e05-61bda573b1be)

**Desktop:**
 - OS: kali-rolling [WSL2 inside Windows 11...]
 - GCC version 14.0.1 (experimental) [Debian 14-20240201-3]
 - GCOVR version 7.2-1

**Comment by Spacetown** [comment]
Duplicate #921.
