### ISSUE TITLE
html-details produces output as print_text_report, not print_html_report

### ISSUE THREAD

**Issue by theold190** [gcovr/gcovr#93]
Right now if you specify --html-details flag the output will be done using print_text_report, and not print_html_report. A fix like this should remove the issue:

```
diff --git a/scripts/gcovr b/scripts/gcovr
index 792aece..fd83523 100755
--- a/scripts/gcovr
+++ b/scripts/gcovr
@@ -2176,7 +2176,7 @@ if options.verbose:
 #
 if options.xml or options.prettyxml:
     print_xml_report(covdata)
-elif options.html:
+elif options.html or options.html_details:
     print_html_report(covdata, options.html_details)
 else:
     print_text_report(covdata)
```

**Comment by daantimmer** [comment]
Another solution that i see being used is using --html --html-details

**Comment by latk** [comment]
Good find! The `--html-details` option should imply `--html`, just like `--xml-pretty` implies `--xml`. I'd welcome a pull request for this :)

**Comment by theold190** [comment]
Nice! Feel free to close the issue if the fix from art-of-dom works as expected.
