### ISSUE TITLE
Read The Docs has deprecated Sphinx context injection

### ISSUE THREAD

**Issue by latk** [gcovr/gcovr#934]
When *Read The Docs* (RTD) builds the gcovr documentation, the Sphinx configuration is adjusted slightly. As explained in this post, that will end on **October 7**: https://about.readthedocs.com/blog/2024/07/addons-by-default/

RTD suggests that the following config snippet should resolve most of the changes:

```python
import os

# Define the canonical URL if you are using a custom domain on Read the Docs
html_baseurl = os.environ.get("READTHEDOCS_CANONICAL_URL", "")

# Tell Jinja2 templates the build is running on Read the Docs
if os.environ.get("READTHEDOCS", "") == "True":
    html_context["READTHEDOCS"] = True
```

The canonical URL is necessary for the docs to properly work on `gcovr.com`.

The `html_context` may be necessary depending on the theme. I'm not sure if the version-selector menu (called "flyout" in the RTD documentation) will work without further changes, or if the theme has to be updated as well. RTD has also created "addons" that may be able to add this menu in a post-processing step, not sure how that works or whether it's actually necessary.

**Comment by Spacetown** [comment]
I read the documentation and the [spynx-build-compatibility extension](https://github.com/readthedocs/sphinx-build-compatibility/blob/main/sphinx_build_compatibility/extension.py). I'm not sure about all the other context variables set by this extension.

**Comment by Spacetown** [comment]
I did already following changes on RTD:
- Activated the add-ons and rebuild the docs for version `7.0`, `7.1` and `7.2`.
- The `main` is replaced by a `latest` to have a banner printed by RTD and a redirect from `/en/main` to `/en/latest` is added.
- The build on PR is activated together with the diff add-on.
