### ISSUE TITLE
Branch coverage exclusion does not work

### ISSUE THREAD

**Issue by swaldhoer** [gcovr/gcovr#937]
**Describe the bug**
Specific branches cannot be excluded from branch coverage calculation.

**To Reproduce**
`main.c`:

```c
enum myEnum {a};

int main() {
    enum myEnum foo = a;

    switch (foo) {
    case a:
        break;
    default:   /* GCOVR_EXCL_LINE */
        break; /* GCOVR_EXCL_LINE */
    }
    return 0;
}
```

Code compilation and report generation:

```bash
gcc --coverage -g -O0 main.c -o"main.exe"
main.exe
py -3.10 -m gcovr --html-details coverage.html
```

**Expected behavior**
Accordingly to <https://gcovr.com/en/7.2/guide/exclusion-markers.html> it should be possible to also exclude branches from coverage calculation.
The code above shall have 100% line **and** branch coverage, when `GCOVR_EXCL_BR` is placed in the `default:`-line.

However, what combinations of `GCOVR_EXCL_BR_*` I used around or in the `default` case I could not remove the `default` branch from coverage calculation.

**Screenshots**
![line-coverage](https://github.com/user-attachments/assets/c8334006-cafd-4b13-97f9-a0eae5cc2e4c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GCC version:
   - gcc x86_64-8.1.0-release-posix-seh-rt_v6-rev0
   - gcc.exe (Rev6, Built by MSYS2 project) 13.2.0
 - GCOVR version: 7.2
 - Project directory layout: not used

**Comment by swaldhoer** [comment]
Okay after trying a few things more, it shows that the only thing that seems to works with `GCOVR_EXCL_BR_*` is
```c
enum myEnum {a};

int main() {
    volatile enum myEnum foo = a;

    switch (foo) { /* GCOVR_EXCL_BR_LINE */
    case a:
        break;
    default:   
        break; 
    }
    return 0;
}
```

![image](https://github.com/user-attachments/assets/1f402b50-7429-48f1-ba54-f172cd80aad5)

but of course this excludes the whole switch case, which is totally undesireable.

I want to mark just certain branches in a conditional statement as uncovered, not the whole statement.

**Comment by Spacetown** [comment]
This behaviour is in the nature of the compiler. The branch instructions are generated in the line of the `switch`. The `case` and the `default` lines are only targets. You can only exclude the lines of the default branch but not the specific branch.

@latk Can we assume that the last branch is the branch for the `default`? In that case we can think about a adding support for a comment like `GCOVR_EXCL_DEFAULT_BR`.

**Comment by swaldhoer** [comment]
Having the option to exclude the `default` branch would be a sufficient good solution for 95% of the typical use cases.
Assuming that the `default` branch is thw last one in a switch case statement is totally reasonable from my point of view.

So for me the proposed solution would be good enough👍

**Comment by latk** [comment]
> Can we assume that the last branch is the branch for the `default`?

On GCC with `-O0` probably yes, because the compiler is not deliberately trying to be antagonistic and emits a fairly literal translation of the source code.

But I'm not sure if this will hold in general, as the order of branches relates to compiler-internal blocks, not necessarily to the order of branching constructs in the source code. I'm also worried how such heuristics might interact if the compiler optimizes the switch to not actually do any branching, or if the switch is translated to a decision tree rather than checking the cases sequentially.

My initial experiments have not revealed such a case, but I don't think GCC developers would be happy to commit to "last branch is always default".

If a feature like switch-exclude-default is developed, it should probably be user-controlled, e.g. by providing a configuration option, or by requiring annotations in the source code.

Things like excluding coverage info via annotations on `case` labels is not possible without re-parsing the C source code. The gcovr "decision coverage" feature tried to do similar things for a "reasonably" formatted subset of C, but that is extremely fragile.

**Comment by Spacetown** [comment]
With the JSON intermediate format we've more information about branches. We know the destination block of a branch and if we put this information into the data model we should be able to process comments on the branch target lint to ignore the branch source. E.g. Following source:
<img width="503" alt="image" src="https://github.com/user-attachments/assets/3859ebe8-427c-4fca-b799-be63ebc04a2b">
in the JSON format:
```json
[
                {
                    "line_number": 5,
                    "function_name": "_Z3fooi",
                    "count": 1,
                    "unexecuted_block": false,
                    "block_ids": [
                        2
                    ],
                    "branches": [
                        {
                            "count": 0,
                            "throw": false,
                            "fallthrough": true,
                            "source_block_id": 2,
                            "destination_block_id": 3
                        },
                        {
                            "count": 1,
                            "throw": false,
                            "fallthrough": false,
                            "source_block_id": 2,
                            "destination_block_id": 4
                        }
                    ],
                    "calls": [],
                    "conditions": []
                },
                {
                    "line_number": 6,
                    "function_name": "_Z3fooi",
                    "count": 0,
                    "unexecuted_block": true,
                    "block_ids": [
                        3
                    ],
                    "branches": [],
                    "calls": [],
                    "conditions": []
                },
                {
                    "line_number": 8,
                    "function_name": "_Z3fooi",
                    "count": 1,
                    "unexecuted_block": false,
                    "block_ids": [
                        4
                    ],
                    "branches": [],
                    "calls": [],
                    "conditions": []
                },
                {
                    "line_number": 10,
                    "function_name": "_Z3fooi",
                    "count": 1,
                    "unexecuted_block": false,
                    "block_ids": [
                        5
                    ],
                    "branches": [
                        {
                            "count": 1,
                            "throw": false,
                            "fallthrough": true,
                            "source_block_id": 5,
                            "destination_block_id": 6
                        },
                        {
                            "count": 0,
                            "throw": false,
                            "fallthrough": false,
                            "source_block_id": 5,
                            "destination_block_id": 7
                        }
                    ],
                    "calls": [],
                    "conditions": []
                },
                {
                    "line_number": 11,
                    "function_name": "_Z3fooi",
                    "count": 1,
                    "unexecuted_block": false,
                    "block_ids": [
                        6
                    ],
                    "branches": [],
                    "calls": [],
                    "conditions": []
                },
                {
                    "line_number": 13,
                    "function_name": "_Z3fooi",
                    "count": 0,
                    "unexecuted_block": true,
                    "block_ids": [
                        7
                    ],
                    "branches": [],
                    "calls": [],
                    "conditions": []
                }
]

**Comment by Spacetown** [comment]
@swaldhoer Can you try the branch of the linked PR?

**Comment by swaldhoer** [comment]
I tested the feature on a work machine, where I only can use GCC 8 on Windows. There I get a failure as soon as I use the comment ``GCOVR_EXCL_BR_SOURCE`` (something like *requires GCC 14 because of json*).

So generally, I would not like to break our test suite just because of the used GCC version because of some comment. I would prefer gcovr to just ignore the comment then and report a lower coverage.

Anyhow, I will have setup a new machine at work with GCC 14 and test our project against the gcovr version in the linked PR. This will however take some days.

**Comment by Spacetown** [comment]
> I tested the feature on a work machine, where I only can use GCC 8 on Windows. There I get a failure as soon as I use the comment `GCOVR_EXCL_BR_SOURCE` (something like _requires GCC 14 because of json_).
> 
> So generally, I would not like to break our test suite just because of the used GCC version because of some comment. I would prefer gcovr to just ignore the comment then and report a lower coverage.

It is only printed as error but the exit code will still be 0. In pipelines this error message can be catched and affect the pipeline status.
Ignoring without a message would not be good. I prefer to have it at least a warning but can also go with an info. What do you think?

**Comment by swaldhoer** [comment]
> It is only printed as error but the exit code will still be 0. In pipelines this error message can be catched and affect the pipeline status. Ignoring without a message would not be good. I prefer to have it at least a warning but can also go with an info. What do you think?

Ah okay, I only had a quick look and didn't check the exit code.
I would prefer a warning/info, as it's not really problem, you jest get lower coverage results.

Anyway, I did not have time to test it until now, I am very sorry. I try to test it on this weekend on my own machine.
