### ISSUE TITLE
Unwanted lines covered

### ISSUE THREAD

**Issue by subhasankarisaravanan** [gcovr/gcovr#939]
I have some 500 lines of my project code.In that for ex i have #ifdef LED and #ifdef SOUND.My project testing scope is only #ifdef LED i have included particular makefiles which is applicable for LED only.But Gcovr is taking SOUND also.So my coverage is less.I am using eclipse IDE to write my code and CPPU test for unittesting.So how to avoid such preprocessor directives while running gcovr

**Comment by Spacetown** [comment]
If the code is marked as untested it was compiled into your tests. GCOV is instrumenting on compiler level and therefore the preprocessor was already executed and the encapsulations and macros are resolved.

**Comment by subhasankarisaravanan** [comment]
Hi sir ,
 Thank you for the mail. I am using cpputest for my unittesting.I am using
the makefile to test my modules.For example if i have led and output
module.And i have one more unit callled light which will present in both
makefiles for different applictions.Is gcovr affect the output of led if
the makefiles has same file light.

**Comment by Spacetown** [comment]
We only show the output for your compiled code we do not add additional files or code. If we show SOUND as uncovered this is because GCOV is showing it as uncovered. If GCOV is showing it as uncovered you've instrumented SOUND in a test but didn't execute it.

Please check your test compilation configuration.

**Comment by subhasankarisaravanan** [comment]
Dear sir,
  thank you for the information.



Regards
SUBHASANKARI S





regards
SUBHASANKARI S

**Comment by subhasankarisaravanan** [comment]
Dear sir ,
 for some codes whatever logics i am writing the coverage is not
happening.Is there any inbuilt tool is available to find how to write code
for particular section




Best regards
SUBHASANKARI

**Comment by Spacetown** [comment]
Sorry, I don‘t get you. Do you want to know how to write tests?

**Comment by subhasankarisaravanan** [comment]
yes sir.I can write tests.I am using cpputest for my unit testing.But i
couldnot write for some lines and i couldnot find where would be the
problem.For example i can cover my test upto 70% beyond that i could not do
for some fuctions.
So kindly help me on this

Regards
SUBHASANKARI


Regards
SUBHASANKARI

**Comment by Spacetown** [comment]
But if you can‘t write tests for some lines that isn‘t related to gcovr. Do you have an example report of such a function?

**Comment by subhasankarisaravanan** [comment]
no sir.I am writing the tests but is not covered by gcovr.Sir kindly tell
me what are the files which gcovr refers for coverage.FOr example
makefiles.Like that is there any another files is it refer while checking
for coverage



Regards
SUBHASANKARI

**Comment by Spacetown** [comment]
We only consider the output of the execution which are generated if your executable is done. Some files are filtered by paths but this is visible in your verbose log which you posted here. We do not consider any build environment.

**Comment by subhasankarisaravanan** [comment]
But sir if change any anything in build it is affecting the output.Thats
why i asked



Regards
SUBHASANKARI

**Comment by subhasankarisaravanan** [comment]
Thank you sir


Regards
SUBHASANKARI S

**Comment by Spacetown** [comment]
Is it working now?

**Comment by subhasankarisaravanan** [comment]
Yes sir.Actually once i make the changes in make file since i am using
cpputest for unittesting i have to do some steps.Now it is working.Thank
you sir for the support.






Regards
SUBHASANKARI S

**Comment by subhasankarisaravanan** [comment]
Hi sir,
   How are you?Hope you are doing well.I am working on with unittest and as
i already told you i am using gcovr for my code coverage.In this i am
facing the new problem.I am testing two different projects and used gcovr
individually .It is working fine and gave coverage of almost 100 % for most
of the modules.But as per my work i have to combine those teo projects and
coverage should support both the projects with a single program.But
coverage is supporting both the projects.For example i have two projects
33,34  if i run make 33(33is my project name).The coverage is not
supporting for 34 and if i run make34 coverage is not supporting 33.Since
the test file is same and the make file is same.So kindly tell me if you
have any idea about the gcovr which supports both the projects?




Thanks and Regards
SUBHASANKARI S

**Comment by Spacetown** [comment]
I don‘t get „coverage is not supporting“. If the gcda and gcno files from the execution are still there they should be taken.

**Comment by subhasankarisaravanan** [comment]
Dear Sir,
    Thanks for the response.Since my makefile has two different projects
with if else i think it is not supporting.And it is supporting either one
project at a time.My question to you is ,Is there any possibilities to
cover both the projects though i have my makefile with two projects
separated with conditional statement.




Best Regards
SUBHASANKARI S

**Comment by Spacetown** [comment]
We are independent from your build. If the report is also generated by your make you can generate a JSON report and merge it afterwards to one overall report.

**Comment by subhasankarisaravanan** [comment]
Dear Sir,
   Thank you for your valuable information.I will try this method and if
will have any doubts i will let you know.



Thanks and Regards
SUBHASANKARI S

**Comment by subhasankarisaravanan** [comment]
Dear sir,
   If i am using json then i have to change my entire test file to support
this.Is there any other way to do that without changing anything in my test
file.







thanks and regards
SUBHASANKARI

**Comment by Spacetown** [comment]
To get it work you need to change something. If your makefile is structured this way that's the only solution if you want to call gcovr inside your make.

**Comment by subhasankarisaravanan** [comment]
Dear Sir,
   I thought the changes would be in my test file.but you told it is in
makefile .Kindly clarify that inorder to get the desired output where shall
i change?


Thanks and regards

**Comment by Spacetown** [comment]
You need to change the command line of gcovr.

**Comment by subhasankarisaravanan** [comment]
Dear Sir,
   Kindly tell me in the command line in the sense for ex i am using gcovr
--exclude some files --html --html-details -o coverage.html .In this how
can i change to support both the projects?




Best regards
SUBHASANKARI

**Comment by Spacetown** [comment]
Instead of creating a HTML you need to create a JSON with `--json`. At the end you call again gcovr with `-a file.x.json` for each file and create here the html report.
This is also described deeper in the documentation https://gcovr.com/en/7.2/guide/merging.html.

**Comment by subhasankarisaravanan** [comment]
Dear Sir,
     I will try and update you definitely.And thank you so much you are
giving immense support to me.



Best Regards
SUBHASANKARI

**Comment by subhasankarisaravanan** [comment]
Dear Sir,
    I have tried the above link.I have generated two json files.But i have
got a error when i tried to merge those two files.I have got a error like
gcovr --json-add-tracefile run-1.json --json-add-tracefile run-2.json
--html-details coverage.html
usage: gcovr [options] [search_paths...]
gcovr: error: unrecognized arguments: --json-add-tracefile
--json-add-tracefile run-2.json
And I am using gcovr=7.2 version
Kindly tell me How can i solve this?


Best Regards
SUBHASANKARI

**Comment by subhasankarisaravanan** [comment]
Hi sir,
   And also after getting two json files for different projects i have
tried this
jq -s 'add' run-1.json run-2.json > combined.json
followed by
gcovr --json-pretty -o combined.json
--merge-mode-functions=merge-use-line-max --gcov-ignore-parse-errors
negative_hits.warn --html-details coverage.html
In this i didnt get any error but both the coverages are not
merged.WHatever i have run latest shown in the coverage.So kindly help on
this




Thanks and regards
SUBHASANKARI

**Comment by subhasankarisaravanan** [comment]
Dear sir,
   how are you?hope you are doing well.I have resolved the previous problem
by making two different json files and merge it.Now i just want my gcovr
outputs are saved inside the folder how to do that ?Kindly tell me




Best regards
SUBHASANKARI S

**Comment by Spacetown** [comment]
Specify the output file with the folder in the command line.

**Comment by subhasankarisaravanan** [comment]
Dear sir,
  I have solved the problem already.Thank you for the mail.






Best regards
SUBHASANKARI S

**Comment by subhasankarisaravanan** [comment]
Dear Sir,
   How are you?.Hope you are doing well.I need a small help from you
regarding gcovr.I am facing the problem that,I have a git branch called
aa.Inside this branch i have some modules to be tested.For example
lcd,led,button and so on.Among these modules  lcd has different config file
and led,button has same config file.But during lcd coverage some lines are
not covered which belongs to led,button config file defines.So how to avoid
it because my lcd unittest only has to test the configuration belongs to
lcd alone.Kindly help me on this.





Thanks and regards
SUBHASANKARI S

**Comment by Spacetown** [comment]
I don't get you. The (un)covered lines depends on your test. Gcovr can reduce the report to a subset of your result, that's all.

**Comment by subhasankarisaravanan** [comment]
dear sir,
  Thank you for the reply.I have solved the issue.


Regards
SUBHASANKARI

**Comment by subhasankarisaravanan** [comment]
Hi sir,
   How are you?Hope you are doing well.I am coming with  a new problem that
i am writing unittest codes by using cpputest and checking coverage by
using gcovr.In my code for loop is there for example
for(i=0;i<aa;i++)
{
some condition
}
But in my code the structure was like this
for(i=0;i<aa;
         i++)
{
some condition
}
while giving gcovr the first line took coverage.But the second line whichis
i++ didnt take coverage and it lie under no of lines uncovered.
So what i did was i have just arranged it like
for(i=0;i<aa;i++)
{
some_condition
}
Then the uncoverage has gone .
Actually gcovr is checking that the test is written for that line or not
correct sir.Then why it is taking the structure.Whatever the structure it
should take the condition correct sir.So kindly tell why it is happening

**Comment by Spacetown** [comment]
New problem --> Please raise a new issue.
Please use verbatim blocks for your code with specifying the language and be more specific on which coverage type is 0.

**Comment by subhasankarisaravanan** [comment]
Dear Sir,
    I have some doubts in gcovr.I tried to send new mail.But i didnt get
any response.SO kindly tell me how to raise a new complaint?.




Thanks and Regards
SUBHASANKARI S

**Comment by Spacetown** [comment]
The same way you opened the first one. Go to the project on GitHub.com and create a new issue. Am 12.12.24 um 06:46 schrieb subhasankarisaravanan
                
            
            
                
                    Von: "subhasankarisaravanan" ***@***.***>Datum: 12. Dezember 2024An: "gcovr/gcovr" ***@***.***>Cc: "Michael Förderer" ***@***.***>,"State change" ***@***.***>Betreff: Re: [gcovr/gcovr] Unwanted lines covered (Issue #939)
                
                
Dear Sir,

    I have some doubts in gcovr.I tried to send new mail.But i didnt get

any response.SO kindly tell me how to raise a new complaint?.









Thanks and Regards

SUBHASANKARI S





On Wed, Nov 27, 2024 at 7:25 PM Michael Förderer ***@***.***>

wrote:

**Comment by subhasankarisaravanan** [comment]
Ok sir Thank you
