### ISSUE TITLE
✨ Upload standalone applications as release artifacts

### ISSUE THREAD

**Issue by s-weigand** [gcovr/gcovr#940]
**Is your feature request related to a problem? Please describe.**
Since `6.0` `gcovr` has a nox session to create a standalone application, however, users still need to build it themselves. It would be nice to simply download the standalone application directly from the release page, which would enable users to easily add them to their own docker images.
The problem with building it locally in the CI is that `bundle_app` nox session also invokes `check_bundled_app` which requires `gcov` and `bash` to be installed in the same environment.
However in a typical docker build environment that isn't always the case since a c++ build image won't necessarily have `python` installed and a `python` build image won't necessarily have `gcov`.
And most Windows docker images won't have `bash` readily available.

**Describe the solution you'd like**
Downloading the `gcovr` standalone applications directly from the release page.

**Describe alternatives you've considered**
Currently, we are building the `gcovr.exe` with a python docker image and just regex remove `session.notify("check_bundled_app")` at the end of the `bundle_app` nox session so it won't fail due to the missing bash executable.

**Additional context**
If the idea of uploading the standalone applications as release artifacts is fine with you I can make a PR to update the workflow.

**Comment by Spacetown** [comment]
The idea is good. I'm not sure how to add a Windows binary in the deploy workflow because it's only running on Linux. One question: Is the executable on Linux the same on each version?
I'm happy to see a PR for this.
