### ISSUE TITLE
CAN I USE GCOVER For the external source file which is part of build but not belongs to the current working directory ? 

### ISSUE THREAD

**Issue by karan999-web** [gcovr/gcovr#943]
CAN I USE GCOVER For the external source file which is part of build but not belongs to the current working directory ?

**Comment by latk** [comment]
Yes you can do this, by adding a `--filter` that matches the path outside of your project. In some cases, it can also make sense to have a project `--root` that differs from the current working directory.

Further reading: https://gcovr.com/en/stable/guide/filters.html

**Comment by karan999-web** [comment]
how to use -filter in command line for example :
gcovr --html --html-details ./Report/UnitTestReport.html --object-directory "./source" 

source is a within a directory but instead of source i want to use SWC which does not belong to current working directory but root directory is same.

1)not able to generate report with a relative/absolute path 
2)i want to generate report For SWC which is not part of Current working directory, but it is part of build 

Help me to generate report for External source file from batch file (which is present in CWD)

**Comment by Spacetown** [comment]
It is working. Be more specific on your structure and where you execute with which options.

**Comment by Spacetown** [comment]
Closed because of no response.
