### ISSUE TITLE
Incomplete coverage report if I remove headers of dependencies?

### ISSUE THREAD

**Issue by mdorier** [gcovr/gcovr#944]
I am using gcovr on a C++ project that has some dependencies, some of which are headers-only (e.g. nlohmann_json). These dependencies are installed in some directory outside of my project. I (obviously) don't care about the coverage of those dependencies. However I noticed that if I delete their headers, gcovr's coverage report is incomplete. It only lists the cpp files in my project that don't include any deleted header. Is that normal? Why am I forced to have these headers available to gcovr even though it doesn't report coverage on them anyway? Is there a solution to have a full coverage report without needing those headers?

**Comment by Spacetown** [comment]
The gcov tool which is called by gcovr needs the source files to generate the output. If a source file isn‘t found the heuristic of gcovr for finding the correct working directory tries the next one. At the end no directory is found and gcovr aborts. 

This error can be ignored by the option `—glob-ignore-error= source_not_found`.

**Comment by mdorier** [comment]
Thanks, it was actually a mistake on my part, I was erasing the project's header files instead of just the headers of its dependencies ("find" command run from one level too high). I'm closing the issue.
