### ISSUE TITLE
ETA of next release?

### ISSUE THREAD

**Issue by hemberger** [gcovr/gcovr#945]
Hi - first of all, thank you for maintaining GCOVR! As an open source maintainer myself, I hate to ask a question like this, but I've got a project suffering from https://github.com/gcovr/gcovr/pull/910 and I am unfortunately limited to using official releases for reasons beyond my control. I was just hoping to get a rough estimate for when you expect the next release for my planning purposes. Thank you!

**Comment by Spacetown** [comment]
I want to merge the opened PR first and update the release process to be fully automated. If everything works I think this or next month.

**Comment by hemberger** [comment]
> I want to merge the opened PR first and update the release process to be fully automated. If everything works I think this or next month.

That sounds great - thank you for the update.
