### ISSUE TITLE
More debug info

### ISSUE THREAD

**Issue by mrx23dot** [gcovr/gcovr#96]
Some addtiitonal debug info would be helpful to setup gcovr in a new project.
Normal run provides no run information, verbose is too much.

something like:

Current root directory (resolved from relative path argument)
Filters will be applied: "dummy._", "._42.c" ...
Using gcov command: "gcov.exe"

GCDA files found: (numof)
GCNO files without GCDA files (numof):
  1, main.gcno

Running gcov for 42 files. (no need to list them)
Numof filtered coverages: 10
Gathered coveraged data for 13 files
Generating html report...
gcovr finished, please see index.html

And there should be a warning if non-existing paths/files are given.

**Comment by Spacetown** [comment]
For now there are a lot of debug infos.
