### ISSUE TITLE
support lcov input files

### ISSUE THREAD

**Issue by oliverlee** [gcovr/gcovr#966]
I currently have a combined coverage report in the LCOV format, which is generated by Bazel. I would like to take this file and generate an HTML report from it using `gcovr` instead of `genhtml`.

From reading https://github.com/gcovr/gcovr/issues/523, specifically, https://github.com/gcovr/gcovr/issues/523#issuecomment-1508204023, it seems like there was some tentative plan to support this as an input format. Is this still the case?

**Comment by Spacetown** [comment]
It should be possible but I haven't worked on this. I'll happy to receive a PR for this.

**Comment by oliverlee** [comment]
I don't write much Python and am not familiar with the LCOV format, but I assume it will essentially be similar to these?
https://github.com/gcovr/gcovr/blob/73edd6ae69fc13ec3957f335d562842e60fbf4d8/gcovr/formats/lcov/write.py#L35
https://github.com/gcovr/gcovr/blob/73edd6ae69fc13ec3957f335d562842e60fbf4d8/gcovr/formats/gcov/read.py#L185

**Comment by Spacetown** [comment]
I need to check first if we've all data in the CLOV file but I can't give you a timeline for this. What tool are you using in Bazel to get the LCOV file?

**Comment by oliverlee** [comment]
> I can't give you a timeline for this.

No problem. I wouldn't expect one.

> What tool are you using in Bazel to get the LCOV file?

It's built into Bazel: https://bazel.build/configure/coverage

The only supported coverage format is LCOV. A combined report is created with [--combined_report](https://bazel.build/reference/command-line-reference#flag--combined_report) and that gets written to an output build directory.

I believe it assumes GCC by default although there's an [option](https://bazel.build/reference/command-line-reference#flag--experimental_generate_llvm_lcov) to convert LLVM profdata files.

**Comment by Spacetown** [comment]
I read a little bit through the docs and sources and it seems that bezel is using the gcd and gcno files as we do. It should be possible to run gcovr with the option [--gcov-use-existing-files](https://gcovr.com/en/stable/manpage.html#cmdoption-gcovr-g) after running your testapplication in bazel?

**Comment by oliverlee** [comment]
I'll need to see if I can generate the gcda? files - maybe they are getting renamed or maybe I need to change some options to generate them. With my current options, it looks like LLVM profdata is converted to LCOV format, and then all the LCOV files are aggregated.

**Comment by oliverlee** [comment]
Okay so I spent some time looking into this and have not been able to emit `.gcda` files for my build, although it may be possible for others using Bazel.

Here are some general notes:

I'm working on macOS and am using a hermetic LLVM toolchain from https://github.com/bazel-contrib/toolchains_llvm.

For macOS, `--copt=-ffile-compilation-dir=.` generally seems necessary to emit coverage files.
https://github.com/bazelbuild/bazel/issues/14970#issuecomment-1894565761

Versions 7.2 and 7.3 of Bazel don't allow override of `COVERAGE_GCOV_PATH`
https://github.com/bazelbuild/bazel/issues/23247

Version 7.1 does, and
```
 --test_env="BAZEL_CC_COVERAGE_TOOL=GCOV"
 --test_env="COVERAGE_GCOV_PATH=external/llvm18_toolchain/bin/llvm-cov"
```
uses `llvm-cov` (which gets symlinked to `gcov`).

However, I'm not able to emit `gcda` files, even after disabling default coverage options and replacing them with:
```
coverage --features=-coverage
coverage --copt="--coverage"
coverage --linkopt="--coverage"
```

I also tested this with LLVM from brew which had the same results.

Unfortunately, my project does not compile with GCC given some (ab)use of defects in the language which seem to be rejected by GCC but are (currently) allowed by Clang.

**Comment by Spacetown** [comment]
I've created a "Hello world" hazel project. I don't get how to activate the coverage.

**Comment by oliverlee** [comment]
Do you have a link you can share?

**Comment by oliverlee** [comment]
Let me also create a minimal example.

**Comment by oliverlee** [comment]
https://github.com/oliverlee/basic-coverage-example

**Comment by Spacetown** [comment]
PR is linked but in draft yet.

**Comment by Spacetown** [comment]
> https://github.com/oliverlee/basic-coverage-example

I need a example without aa specific toolchain because we are testing with several compiler versions.

**Comment by oliverlee** [comment]
I can try and update that later, although the options necessary for coverage will likely depend on the host platform and the toolchain in use.

I added some comments on your PR on how I was able to generate coverage using your example on macOS with LLVM - although Bazel does a transform of profdata ->LCOV in that case.

**Comment by Spacetown** [comment]
I'm experimenting and the gcc-14 is working. Now I try to find the correct options for gcc-5.

**Comment by oliverlee** [comment]
What flags are you using?

> I read a little bit through the docs and sources and it seems that bezel is using the gcd and gcno files as we do. It should be possible to run gcovr with the option [--gcov-use-existing-files](https://gcovr.com/en/stable/manpage.html#cmdoption-gcovr-g) after running your testapplication in bazel?

I've been able to produce gcda files on macOS with LLVM.

When I run `gcovr` specifying options for the GCOV binary, exclude directories, root, and search paths:
```
bazel run //tools:gcovr -- -v --gcov-executable="$(pwd)/external/llvm18_toolchain_llvm/bin/llvm-cov gcov" --gcov-exclude-directories=".*/bin/external/.*" --root=$(pwd) $(bazel info bazel-testlogs)/
```

I get file/directory lookup errors for headers associated with a hermetic toolchain since `gcov` is not run in the sandbox directory:
<details>

```
...

(DEBUG) Running gcov: '/Users/oliver/repos/rigid-geometric-algebra/external/llvm18_toolchain_llvm/bin/llvm-cov gcov /private/var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/testlogs/test/multivector_test/_coverage/bazel-out/darwin_arm64-fastbuild/bin/test/_objs/multivector_test/multivector_test.gcda --branch-counts --branch-probabilities --all-blocks --demangled-names --hash-filenames --object-directory var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/testlogs/test/multivector_test/_coverage/bazel-out/darwin_arm64-fastbuild/bin/test/_objs/multivector_test' in '/private'
(DEBUG) Running gcov: '/Users/oliver/repos/rigid-geometric-algebra/external/llvm18_toolchain_llvm/bin/llvm-cov gcov /private/var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/testlogs/test/multivector_test/_coverage/bazel-out/darwin_arm64-fastbuild/bin/test/_objs/multivector_test/multivector_test.gcda --branch-counts --branch-probabilities --all-blocks --demangled-names --hash-filenames --object-directory private/var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/testlogs/test/multivector_test/_coverage/bazel-out/darwin_arm64-fastbuild/bin/test/_objs/multivector_test' in '/'
(ERROR) GCOV produced the following errors processing /private/var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/testlogs/test/multivector_test/_coverage/bazel-out/darwin_arm64-fastbuild/bin/test/_objs/multivector_test/multivector_test.gcda:
        In directory /Users/oliver/repos/rigid-geometric-algebra:
__bazel_toolchain_llvm_repo__/include/c++/v1/string_view: No such file or directory
__bazel_toolchain_llvm_repo__/include/c++/v1/limits: No such file or directory
__bazel_toolchain_llvm_repo__/include/c++/v1/__ranges/view_interface.h: No such file or directory
__bazel_toolchain_llvm_repo__/include/c++/v1/__ranges/size.h: No such file or directory
__bazel_toolchain_llvm_repo__/include/c++/v1/__ranges/access.h: No such file or directory
__bazel_toolchain_llvm_repo__/include/c++/v1/__ranges/subrange.h: No such file or directory

...

__bazel_toolchain_llvm_repo__/include/c++/v1/initializer_list: No such file or directory
__bazel_toolchain_llvm_repo__/include/c++/v1/__functional/operations.h: No such file or directory
__bazel_toolchain_llvm_repo__/include/c++/v1/__utility/is_pointer_in_range.h: No such file or directory

        In directory /private/var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/testlogs/test/multivector_test/_coverage/bazel-out/darwin_arm64-fastbuild/bin/test/_objs/multivector_test:
Permission denied
Permission denied
Permission denied
Permission denied
Permission denied
Permission denied

...
```

</details>

The output is similar if not using `--gcov-exclude-directories` -- although there are more failures associated with external libraries that are linked against my library.

When I specify `-g` to use existing `gcov` files
```
bazel run //tools:gcovr -- -v -g --root=$(pwd) $(bazel info bazel-testlogs)/
```
I get a parsing error:
<details>

```
...

  File "/private/var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/bin/tools/gcovr.runfiles/pypi_cov_gcovr/site-packages/gcovr/formats/gcov/parser.py", line 774, in _parse_line
    raise UnknownLineType(line)
gcovr.formats.gcov.parser.UnknownLineType: file:test/point_test.cpp

file:test/point_test.cpp
```

</details>

I'm not sure if I can set the necessary options for GCOV specifically.

Bazel uses these:
https://github.com/bazelbuild/bazel/blob/7aa9e7726f4ebf934c9c317c7850e64d901a6141/tools/test/collect_cc_coverage.sh#L165-L181
It seems like it uses `-i`, which isn't listed as an option on the [gcov online docs](https://gcc.gnu.org/onlinedocs/gcc/Invoking-Gcov.html), and then cats all files into one.

When I look at a `.gcov` file it produces, the format doesn't mach any of the samples provided on gcov docs page -- which makes sense given that the parser fails.

**Comment by oliverlee** [comment]
I found some documentation that it is used for [intermediate format](https://gcc.gnu.org/onlinedocs/gcc-5.4.0/gcc/Invoking-Gcov.html).

**Comment by Spacetown** [comment]
Since gcovr can be used with bazel without integrating a LCOV reader I close this issue.

**Comment by oliverlee** [comment]
Thanks for looking into Bazel support!

Is the intended workflow that you run `bazel coverage` to obtain the `gcda` and `gcno` files and then pass all those files directly to `gcovr` or there an alternate approach?

I ran into a bunch of errors when I tested out the former with an existing project that includes external dependencies.

**Comment by Spacetown** [comment]
The intended workflow is to run your executable and then let gcovr search the gcno and gcda files in the build directory.
The problem we have is that we need also the source files and this information can't be determined if the files are copied around.
The main goal of `bazel coverage` command seems to be the generation of the coverage.dat in LCOV format.

**Comment by oliverlee** [comment]
Bazel can output `.gcov` files with intermediate format. Are those usable?

**Comment by Spacetown** [comment]
We can also read existing intermediate files without calling gcov on our own.
Newer gcov versions can produce a JSON intermediate format and if available, this is used. Here we need version 2 and bazel needs version 1.

**Comment by Spacetown** [comment]
@oliverlee Is the integration of gcovr with bazel working for you?

**Comment by phlax** [comment]
iiuc the problem with suggested workflow is if you run in rbe - in that case you dont have the gcno/gcda files to generate coverage from - you literally just get a coverage.dat out at the end

**Comment by Spacetown** [comment]
We've an example where you get the gcda and gcno files out of the bazel build.

**Comment by phlax** [comment]
using rbe?

**Comment by Spacetown** [comment]
This thread is for using gcovr with bazel which out of the box only generates an coverage.dat in LCOV format.

**Comment by phlax** [comment]
nm - i understand the bazel pattern better now - you can override the output generator and pass whatever you like in the .dat files and then in the report generator handle the dats - which allows you to collect whatever you need/like
