### ISSUE TITLE
Gcovr fails to properly process clang-compiled files using

### ISSUE THREAD

**Issue by viksmir** [gcovr/gcovr#970]
# Describe the bug

When processing clang-compiled files, I attempted to generate coverage using the following command:

`gcovr -j 12 --verbose --html --html-details --root ./src --object-directory D:/_projects/MyTool_dev/out/build/Windows-x86_64-debug/myTool_TEST/coverage_metadata --output D:/_projects/MyTool_dev/out/bin/Windows/x86_64/Debug/coverage_report/coverage_report.html  --gcov-executable "llvm-cov gcov"`

Gcovr fails without identifying the issues, other than being unable to find some file. Full log can be found in the file `gcovr_err.txt` provided with this report. No files are generated.

![image](https://github.com/user-attachments/assets/846c0a73-e32e-46b8-8fe3-7d3adb3e6646)

I attempted to call the `llvm-cov gcov` command manually, using the first command invoked by `gcovr` in the error log:

`llvm-cov gcov D:/_projects/MyTool_dev/out/build/Windows-x86_64-debug/myTool_TEST/coverage_metadata/Setup/Node.cpp.gcda --branch-counts --branch-probabilities --all-blocks --object-directory ..\out\build\Windows-x86_64-debug\myTool_TEST\coverage_metadata\Setup`

When called manually,`llvm-cov gcov` was capable of generating gcov files (command output provided in `manual_call.txt`):

![image](https://github.com/user-attachments/assets/a4b45d6d-5978-44f1-807a-85c4cf88c185)

Clearly, `gcovr` not calling the `llvm-cov gcov` command correctly, as invoking it manually works okay.

# To Reproduce

1. Have a setup similar to mine
2. Build using Clang
3. Attempt to generate coverage

# Expected behavior

- Expected `gcovr` to generate report the same way it does for binaries compiled using GCC.
- Expected `gcovr` to identify which files it fails to find for clarity.

# Desktop (please complete the following information)

- OS: Windows 10 64-bit
- Clang version: Msys2 UCRT64 clang version 18.1.8 (Target: x86_64-w64-windows-gnu)
- GCOVR version: 7.2
- Project directory layout:
  - myTool_DLL
  - myTool_EXE
  - myTool_TEST
  - extern
  - src (headers + sources)
  - out
    - bin (all binaries + coverage report get copied here in the end)
      - coverage_report
    - build
      - myTool_DLL
      - myTool_EXE
      - myTool_TEST
        - coverage_metadata (contains all flatly packed gcna + gcda files, I do this for simplicity)
        - CMakeFiles
          - myTool_TEST.dir (CMake-generated gcna + gcda files that follow project folder structure)
          - _
            - src
            - extern
          - ...

# Additional context

It should be noted, that the project setup for coverage generation were already verified for GCC-compiled binaries. The coverage was successfully generated the following command, similar to the one discussed above:

`gcovr -j 12 --verbose --html --html-details --root ./src --object-directory D:/_projects/MyTool_dev/out/build/Windows-x86_64-debug/myTool_TEST/coverage_metadata --output D:/_projects/MyTool_dev/out/bin/Windows/x86_64/Debug/coverage_report/coverage_report.html`

[gcovr_err.txt](https://github.com/user-attachments/files/17104636/gcovr_err.txt)
[manual_call.txt](https://github.com/user-attachments/files/17104638/manual_call.txt)

**Comment by Spacetown** [comment]
We call it exactly as shown in the given directory. The working directory is essential to reproduce the behaviour.
It seems that the input file is removed, can you try without parallel threads?

**Comment by viksmir** [comment]
> We call it exactly as shown in the given directory. The working directory is essential to reproduce the behaviour. It seems that the input file is removed, can you try without parallel threads?

Just to confirm. From my understanding of the documentation, working directory is the directory where all the gcno/gcda files are found. In my case, that would be the `coverage_metadata` folder where I move all the generated gcno/gcda files. Is this not the case?

I do provide the directory with the `--object-directory` argument, so and according to the `gcovr_err.txt` log, it's capable of finding all the gcno/gcda files without issues.

As suggested, I tried specifying `-j 1`, as well as removing the argument altogether. It had no effect, the errors remain.

**Comment by Spacetown** [comment]
Ok. Can you try it without copying the files? We need to execute gcov in the original directory of the build.

**Comment by viksmir** [comment]
> Ok. Can you try it without copying the files? We need to execute gcov in the original directory of the build.

I have tried calling it from the following project directories, all with the same result:
`./`
`./out/build/Windows-x86_64-debug`
`./out/build/Windows-x86_64-debug/myTool_TEST`
**`./out/build/Windows-x86_64-debug/myTool_TEST/CMakeFiles/myTool_TEST.dir`**
**`./out/build/Windows-x86_64-debug/myTool_TEST/CMakeFiles/myTool_TEST.dir/__`**

The latter 2 is where the generated gcno/gcda files are.

**Comment by Spacetown** [comment]
> In my case, that would be the `coverage_metadata` folder where I move all the generated gcno/gcda files. Is this not the case?

Why are you moving the data? They need to be processed in the original directory.

**Comment by viksmir** [comment]
> Why are you moving the data? They need to be processed in the original directory.

I should be clear, I am not "moving" but copying the files. The original files are still in the directory created by CMake. I'm not 100% on the origins of this, but it doesn't affect Gcovr performance when working with GCC-compiled files, something that's clearly not propagated into dealing with Clang-compiled files when using `llvm-cov gcov`.

Additionally, I ran the command in a script from every directory I had, the result is the same and I doubt the directory is to blame here.

**Comment by Spacetown** [comment]
Can you try the latest commit on main branch? The logging on GCOV errors was improved there.

**Comment by viksmir** [comment]
> Can you try the latest commit on main branch? The logging on GCOV errors was improved there.

Hmm, I installed it using `pip install git+https://github.com/gcovr/gcovr.git` but the latest commit I see was 09/19/2024. I'm not sure if that's the one you mean.

In any case, the result file is attached to the message.

[gcovr_err_main09192024.txt](https://github.com/user-attachments/files/17150527/gcovr_err_main09192024.txt)

**Comment by Spacetown** [comment]
That‘s exactly the one I meant. Now we see in the log that chocolate couldn‘t be executed because the executable is not found.

**Comment by viksmir** [comment]
> That‘s exactly the one I meant. Now we see in the log that chocolate couldn‘t be executed because the executable is not found.

But how can it be? The executable's path is in the environmental variables, accessible through console. Running it manually confirms it.

Could the path be formatted in a way not understood by Windows?

**Comment by viksmir** [comment]
> I this log the command `(DEBUG) Running gcov: 'llvm-cov.exe gcov --help' in '.'` is failing but in your command line you define `--gcov-executable "llvm-cov gcov"`. Did you use a different command line here (with the .exe)? If yes, can you try without the `.exe`?
> 
> One thing can be the presence of MSys because in MSys / is needed but Windows uses . I don't know how it is with the MSys patron you are using.

I apologize for the confusion, the `.exe` extension was something I added to see if it would fix the problem.

The executable extension doesn't actually matter in modern Windows, it can figure out what `llvm-cov` is with or without it. I confirm the error is identical with or without `.exe`.

**Comment by Spacetown** [comment]
> The executable extension doesn't actually matter in modern Windows, it can figure out what `llvm-cov` is with or without it. I confirm the error is identical with or without `.exe`.

I know. PATHEXT is used as list of extensions to search for.

Can you try to use another Python than the one which comes with MSys?

**Comment by viksmir** [comment]
Hey, so I think the issue can be closed, as it may be Python-related.

So some background, I am executing Gcovr using a Python script that was calling GCovr using the Subprocess module and the command line arguments passed in a string array format. This worked fine for the standard call for the GCC-compiled code but didn't for Clang-compiled code that required the additional `--gcov-executable "llvm-cov gcov"` argument.

By realizing that the command itself may be the problem, I was able to get it to work by passing the command as a single string, instead of a string array.

My guess is that it's a Python-related bug and how it processes quotation marks when.

**This code breaks**
```
command = ['gcovr',
           '--verbose',
           '--root', './src',
           '--html', '--html-details',
           '--output', f'{args.out_dir}/coverage_report/coverage_report.html',
           '--object-directory', f'{args.bin_dir}/{project_name}/coverage_metadata',
           '--gcov-executable', '"llvm-cov gcov"']
                
coverage_result = subprocess.run(command,
                                 stdout=coverage_output_file,
                                 stderr=coverage_error_file)
```

**This code works**
```
command = ' '.join(['gcovr',
                    '--verbose',
                    '--root', './src',
                    '--html', '--html-details',
                    '--output', f'{args.out_dir}/coverage_report/coverage_report.html',
                    '--object-directory', f'{args.bin_dir}/{project_name}/coverage_metadata',
                    '--gcov-executable', '"llvm-cov gcov"'])
                
coverage_result = subprocess.run(command,
                                 stdout=coverage_output_file,
                                 stderr=coverage_error_file)
```

**Comment by viksmir** [comment]
I guess one thing to note is that even with `llvm-cov gcov` being used for this Clang-compiled code, the bug report still says GCC code coverage. Maybe there could be a way of distinguishing the reports for code compiled by different compilers.

**Comment by Spacetown** [comment]
The first one also works if you remove the double quotes in the arguments.  The subprocess module does the quoting for you and your first example searches for `"llvm-cov gcov.exe"` with a space in the filename.

**Comment by viksmir** [comment]
Would it be possible to change the line at `gcovr/formats/gcov/read.py:771` from:

```
return subprocess.Popen(  # nosec # We know that we execute gcov tool
    cmd,
    env=env,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    encoding="utf-8",
    **kwargs,
)
```

to:

```
return subprocess.Popen(  # nosec # We know that we execute gcov tool
    ' '.join(cmd),
    env=env,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    encoding="utf-8",
    **kwargs,
)
```

This change doesn't bring any functional changes to the user who can currently use their setup, but will make the code more robust and will allow ease of use for people who have a more unconventional setup like mine?

**Comment by Spacetown** [comment]
No. This will be error Perone.
You call it wrong. If you use suprocess with a list you must not quote arguments because subprocess module handles this. With a string we need to handle quotes e.g for arguments with spaces. 

E. g. the user has a space in the build directory he need to add quotes. This quotes are removed by the shell and not part of the argument we receive. If we call a subprocess with this argument in the list the quotes are added again for the next process and there removed again by the shell and so on.
