### ISSUE TITLE
Line with single closing curly brace is falsely reported

### ISSUE THREAD

**Issue by h-2** [gcovr/gcovr#971]
# Describe the bug

![grafik](https://github.com/user-attachments/assets/7d7a7302-188a-4651-a581-3a31d7318626)

---

![grafik](https://github.com/user-attachments/assets/88fdfa58-af20-415b-89df-034ee5eb870c)

---

The two lines are reported as not being covered by gcovr-7.0. They are reported as covered by gcovr-5.0. We want to switch to 7.x, but this is preventing it.

It happens for some functions/blocks, but not for others. I haven't yet found a pattern.

# Steps To Reproduce

I am not sure how to reproduce, as it doesn't happen everywhere and our project structure is not not trivial. If necessary, I will try to make a smaller example.

# Expected behavior

The lines *are* covered / irrelevant. They shouldn't be reported as not being covered.

# Screenshots

See above!

# Desktop (please complete the following information)

- OS: Ubuntu 24.04
- GCC version `llvm-17` / `llvm-cov-17 gcov`
- GCOVR version 7.0
- Project directory layout:

# Additional context

This is the full invocation:
```
/usr/bin/gcovr 
--root /home/hannes/devel/tools/dattel/test/coverage /home/hannes/devel/tools-build/coverage 
--filter '/home/hannes/devel/tools/dattel/include/dattel/.*' 
--filter '/home/hannes/devel/tools/dattel/test/include/dattel/test/.*' 
--exclude-unreachable-branches 
--exclude-throw-branches 
-j 1 
--gcov-executable=llvm-cov-17\ gcov 
--html-theme github.green 
--gcov-delete 
--exclude-lines-by-pattern '(^\s*assert\(.*$)|(^.*GCOVR_EXCL_LINE.*$)|(^\s*DATTEL_UNREACHABLE\s*$)' 
--html-details 
--output /home/hannes/devel/tools-build/coverage/html/index.html
```

Thank you!

**Comment by Spacetown** [comment]
This change is documented in 6.0:
- New `--exclude-noncode-lines` to exclude noncode lines. Noncode lines are not excluded by default anymore. (#704, #705)

**Comment by h-2** [comment]
Thanks for explaining!
