### ISSUE TITLE
Empty Code coverage when mock is used

### ISSUE THREAD

**Issue by flamingvines2** [gcovr/gcovr#972]
Hi, 

I have 2 source (main and driver) that I am generating a coverage report using gcovr. Main doesn't use any mocks while driver use mock. I don't have any issue generating the coverage for main. However, driver has an empty coverage.

Please see attached for details. 
My build log [out.txt](https://github.com/user-attachments/files/17125411/out.txt)
[project.yml.txt](https://github.com/user-attachments/files/17125508/project.yml.txt)
My source files 
[driver.c.txt](https://github.com/user-attachments/files/17125578/driver.c.txt)
[driver.h.txt](https://github.com/user-attachments/files/17125579/driver.h.txt)

My versions are:
Ceedling:: 0.31.1
Unity:: 2.5.4
CMock:: 2.5.4
CException:: 1.3.3
gcovr 4.1

I would appreciate if anyone can point me to what is wrong in my setup or code.

FYI: This is a duplicate of [Link](https://github.com/ThrowTheSwitch/Ceedling/issues/934). Not sure which is the correct place for this since I am triggering gcovr via Ceedling. I will gladly remove one of them if inappropriate. 

Thanks,
Carlo

**Comment by Spacetown** [comment]
You use gcov 4.1 which is more than 6 years old and there where many improvements. Pleas can you try it with the latest version?

**Comment by flamingvines2** [comment]
Hi @Spacetown 
I just used the latest one 7.2.
However I still encounter the same results. main has coverage but driver doesn't have any.

If I trigger via ceedling it does have some warnings because of deprecated parameters. However, it does generate the report still for main but not driver. So I don't think that is the issue. 
This is the build log via ceedling 
[out - via Ceedling.txt](https://github.com/user-attachments/files/17140289/out.-.via.Ceedling.txt)

If I remove the deprecated parameters and do this
gcovr --root "." --exclude "^vendor.*|^build.*|^test.*|^lib.*" --txt-metric branch --html-details --html-medium-threshold 75 --html-high-threshold 90 --html  "build/artifacts/gcov/GcovCoverageResults.html"
driver coverage is still not there. 

Maybe not a gcovr question but a ceedling question if you are familiar, am I supposed to get a output for driver (driver.o)? I don't see any but I have main.o. Not sure if that is because of the internal workings for mock. since Obviously I have mock_driver.o and not mock_main.o

You can see that in the build log.

Thanks,
Carlo

**Comment by Spacetown** [comment]
In this log there is only a call of gcov and this is already complaining about a the missing source file. In that case it‘s not a gcovr issue.

**Comment by flamingvines2** [comment]
@Spacetown 
Ok then. thanks. I will wait for a reply in the linked Ceedling issue.
