### ISSUE TITLE
gcovr with --lcov output does not seem compliant with lcov

### ISSUE THREAD

**Issue by dodolee12** [gcovr/gcovr#973]
# Describe the bug

When creating an lcov output with --lcov, it seems to not be LCOV compliant because `lcov --list coverage.lcov` returns failures.

# To Reproduce

1. Generate an lcov file with --lcov output. `gcovr --lcov coverage.lcov`
2. Try to use lcov to output the file in lcov format `lcov --list coverage.lcov`
3. Step 2 fails

# Expected behavior

LCOV should output fine and correctly parse the file output given by gcovr

# Desktop (please complete the following information)

- OS: [e.g. iOS] Mac
- GCC version [e.g. MinGW 8.1.0]:  13.2
- GCOVR version [e.g. 4.2]: 7.2

# Additional context

The issues seem to be the following:
unexpected file record 'VER:29b9cd73f3659f1b9236a52412291289'
unexpected  file record 'BRDA:1242,None,1,-'

When I run `sed -i '/VER:/d;s/None,/0,/g' coverage.lcov` it seems to work fine.

**Comment by Spacetown** [comment]
The format was implemented according to the [man page of LCOV](https://github.com/linux-test-project/lcov/blame/07a1127c2b4390abf4a516e9763fb28a956a9ce4/man/geninfo.1#L1022). The optional version seems to be introduced with version 2.0 of LCOV.

The error with the block_id `None`: Can you run gcovr with option `--gcov-keep` and check the gcov file? It seems that there is a branch before the block.

**Comment by dodolee12** [comment]
I have a bunch of gcov files. Which one do you want me to look at?

Example branch with None is like

```
FNDA:32,managedStore::RequestStats::toJson[abi:cxx11]() const
FNF:1
FNH:1
BRDA:24,None,0,12
BRDA:24,None,1,16
BRDA:24,None,2,12
BRDA:24,None,3,16
```

**Comment by dodolee12** [comment]
Here is the start of one of the gcov files (test_include_request_stats_test.cpp.gcda.request_stats.hpp##0d1c21ca3750eb1f7d3e86f9c319afde.gcov)

```
        -:    0:Source:../include/request_stats.hpp
        -:    0:Graph:request_stats_test.p/test_include_request_stats_test.cpp.gcno
        -:    0:Data:request_stats_test.p/test_include_request_stats_test.cpp.gcda
        -:    0:Runs:2
        -:    1:#pragma once
        -:    2:
        -:    3:#include "managed_store_clock.hpp"
        -:    4:
        -:    5:#include <boost/beast/http/verb.hpp>
        -:    6:#include <boost/url/url_view.hpp>
        -:    7:#include <nlohmann/json.hpp>
        -:    8:
        -:    9:#include <map>
        -:   10:#include <string>
        -:   11:#include <string_view>
        -:   12:#include <vector>
        -:   13:
        -:   14:// TODO:: probably need a new namespace? even though there is no good reason for
        -:   15:// it
        -:   16:// TODO:: probably will just rename to bmcweb
        -:   17:namespace managedStore
        -:   18:{
        -:   19:
        -:   20:struct RdeRequestStats
        -:   21:{
        -:   22:    RdeRequestStats() :
        -:   23:        totalReqs(0), totalDbusErrors(0), totalSkips(0),
        -:   24:        totalRateLimitToggles(0), rdeDbusErrorCount(0), rdeRequestSkips(0)
        -:   25:    {}
        -:   26:
        -:   27:    nlohmann::json toJson() const
        -:   28:    {
        -:   29:        nlohmann::json obj;
        -:   30:        obj["totalReqs"] = this->totalReqs;
        -:   31:        obj["totalDbusErrors"] = this->totalDbusErrors;
        -:   32:        obj["totalSkips"] = this->totalSkips;
        -:   33:        obj["totalRateLimitToggles"] = this->totalRateLimitToggles;
        -:   34:        obj["CurrentRdeDbusErrorCount"] = this->rdeDbusErrorCount;
        -:   35:        obj["CurrentRdeRequestSkips"] = this->rdeRequestSkips;
        -:   36:        return obj;
        -:   37:    }
        -:   38:
        -:   39:    void clear()
        -:   40:    {
        -:   41:        this->totalReqs = 0;
        -:   42:        this->totalDbusErrors = 0;
        -:   43:        this->totalSkips = 0;
        -:   44:        this->totalRateLimitToggles = 0;
        -:   45:    }
        -:   46:
        -:   47:    /** Total number of Rde Requests */
        -:   48:    int totalReqs;
        -:   49:    /** Total number if dbus error in Rde Requests */
        -:   50:    int totalDbusErrors;
        -:   51:    /** Total number Rde Requests skipped because of Rate Limit */
        -:   52:    int totalSkips;
        -:   53:    /** Total number times Rde Requests Rate Limiter enabled */
        -:   54:    int totalRateLimitToggles;
        -:   55:
        -:   56:    // This is used to enable the rate limit the number of requests that can
        -:   57:    // be sent to the RDEd.
        -:   58:    /** Current Dbus error count*/
        -:   59:    int rdeDbusErrorCount;
        -:   60:
        -:   61:    // This keeps track number of skipped RDEd requests before turning off
        -:   62:    // rate limiting
        -:   63:    /** Current RDE Requests skip count*/
        -:   64:    int rdeRequestSkips;
        -:   65:};
        -:   66:
        -:   67:/** stats context captured by each request handler in the bmcweb */
        -:   68:class RequestStatsContext
        -:   69:{
        -:   70:  public:
        -:   71:    RequestStatsContext(const std::string& queryURLKey,
        -:   72:                        const std::chrono::steady_clock::time_point& now =
        4:   73:                            managedStore::clockNow());
        2:   73-block  0
call    0 returned 2
branch  1 taken 2 (fallthrough)
branch  2 taken 0 (throw)
```

Seems to be missing a branch at the top?

**Comment by Spacetown** [comment]
Here you see in line 73 the preceding block information but it seems that there is another compilation unit where the Bloch id is 1 for the same line. 
```
BRDA:73,0,1,2
BRDA:73,e0,2,-
BRDA:73,1,4,2
BRDA:73,e1,5,-
```

What about line 103 where we print the None? You can search for `branch  1 taken 0 (throw)`.
There must also be additional gcov files with the branch for line 24.

**Comment by dodolee12** [comment]
Here are all the gcov files for request_stats.hpp.

Also I cannot find anything with `branch  1 taken 0 (throw)`in request_stats.hpp related gcov files

[gcov_files_for_request_stats_hpp.zip](https://github.com/user-attachments/files/17194396/gcov_files_for_request_stats_hpp.zip)

**Comment by Spacetown** [comment]
In `src_request_stats.cpp.gcda.request_stats.hpp##0d1c21ca3750eb1f7d3e86f9c319afde.gcov` we see following content:
```
       48:   22:    RdeRequestStats() :
       76:   23:        totalReqs(0), totalDbusErrors(0), totalSkips(0),
       56:   24:        totalRateLimitToggles(0), rdeDbusErrorCount(0), rdeRequestSkips(0)
branch  0 taken 12 (fallthrough)
branch  1 taken 16
branch  2 taken 12 (fallthrough)
branch  3 taken 16
        -:   25:    {}
```

Here we have no block information. 

@latk What do you think? Can we assume block 0 in this case?

**Comment by Spacetown** [comment]
@latk That is really strange why one function has a block and one doesn't. Since this occurs in gcov files and we need to replace the `None` with something I would use `0` and if a project will have problems we can check deeper.

**Comment by Spacetown** [comment]
@dodolee12 Please can you check the linked PR if the branch solves your issue. We also had `None` in our reference data.

**Comment by dodolee12** [comment]
Do you have commands anywhere to build the gcov binary locally?

I dont believe I saw it in gcovr documentation or README. Maybe I missed it?

**Comment by Spacetown** [comment]
It is described in the chapter [Installation](https://gcovr.com/en/latest/installation.html)
