### ISSUE TITLE
KeyError: 'function_name'

### ISSUE THREAD

**Issue by Keith-Cancel** [gcovr/gcovr#978]
So I downloaded the latest branch to try a new feature out. However, I immediately ran into an error. This does affect a release version.  I did look at the code and commenting out line 237 makes everything run again. It seems like not every element will always have a `function_name` when this iterates over it. https://github.com/gcovr/gcovr/blob/67478e84dc5847cc169764608e8b35296cdcde57/gcovr/formats/gcov/read.py#L231-L241

I don't run into this issue in the current stable/release version.  Looking at the code for that version it looks like these lines are a recent addition since they are not there.
```python
function_name=line["function_name"],
block_ids=line["block_ids"],
```

# To Reproduce

1. All I did was invoke `gcovr ./test_bin/config/parser.gcda --html-details test.html  --html-single-page`

# Expected behavior

Run without generating a python KeyError and generate a report. 

# Screenshots
Here is the screen shot of the error.
![Screenshot_2024-10-02_22-17-35](https://github.com/user-attachments/assets/ad5a4d6b-7cfe-45d7-af63-a05f203a09c3)

# Desktop

- OS: Arch Linux
- GCC version: gcc (GCC) 14.2.1 20240910
- GCOVR version: gcovr 7.2+main
- Project directory layout:
 -- The compiled object that generates the `gcda` and `gcno` files was located at `./test_bin/config/parser.o`
 -- The source file for that object located at `./src/config/parser.c`
 -- I was mainly trying out  `--html-single-page` so was only using a single source file that was pretty independent and compiled it with the flags `-fprofile-arcs -ftest-cov` so not exactly a large project structure.

**Comment by Spacetown** [comment]
I checked the documentation of the gcov JSON format and indeed, this field is optional:

> function_name: a name of a function this line belongs to (for a line with an inlined statements can be not set)

I need to setup a test case with a missing line number and will fix this.

**Comment by Spacetown** [comment]
@Keith-Cancel Please can you check with the branch of the linked PR? In the added test I had also the KeyError exception and with the change it's fixed.

**Comment by Keith-Cancel** [comment]
Yes that change does prevent the exception. I don't notice any other issues so far. I will say looking at the PR if it is the fact inline functions may not have a function_name. That file I was using does have a lot of `static inline` functions so that makes sense as to why it caused an exception/error.
