### ISSUE TITLE
Generating json for files which have no coverage

### ISSUE THREAD

**Issue by dlegaultbbry** [gcovr/gcovr#986]
I'm not sure this would qualify as an idea or not, but here's what I'd like to do even if it means writing separate tool(s).

Assuming I can generate the list of source files which have no coverage (because no tests defined for them), how would I go to generate a gcovr output file using the current version of gcovr's json format such that later I can simple use `--json-add-tracefile` with 'empty' coverage stats combined with the actual json files which have real coverage from tests in them to get a combined report showing 0 for all the missing files.

**Comment by Spacetown** [comment]
If a source is compiled with coverage information (gcno is generated) but isn't covered (no gcda generated) we use the gcno file to show exact what you want.

**Comment by dlegaultbbry** [comment]
The way our stuff is setup the file is not wired to be compiled so we don't have the gcno file. I need an alternate method to report all these source files as 0% on every metric and merged with the ones that are covered so I get a full field view of the source tree coverage for a repository.

**Comment by Spacetown** [comment]
The easiest way is to compile them, linking isn't needed. If you want to generate a JSON you need to add all data which is available in the JSON and set the values to 0. In this case you would be hardly tied to our data model and all the changes we do in the future.

**Comment by dlegaultbbry** [comment]
Unfortunately, changing things to have them compiled is going to be a bit difficult in the short term given this is a custom system.

I was planning to just import gcovr's data model of the currently installed version and generate json entries for each file showing 0 for everything. Then dumping it so it can be merged with other coverage files at a later stage.

In any case, thanks for the hints on how I could go around doing this.

**Comment by Spacetown** [comment]
@latk What do you think about a new "input format" which gets a list of input files which are only added to the data model with empty coverage?

**Comment by Spacetown** [comment]
@dlegaultbbry Can you install git+https://github.com/Spacetown/gcovr@add_empty_file_coverage and try the option `--include`? The value is a filter expression for the files in the search paths of gcovr.
