### ISSUE TITLE
Excessive "No block number defined, assuming 0" messages

### ISSUE THREAD

**Issue by Syeberman** [gcovr/gcovr#989]
# Describe the bug

In gcovr 8.0, the following string is being printed thousands of times:

```
(INFO) No block number defined, assuming 0
```

This print was added in https://github.com/gcovr/gcovr/pull/976.

# To Reproduce

```
.venv/bin/gcovr --lcov coverage.codecov/munit_test.lcov --use-gcov-files coverage.codecov/munit_test.gcov/ --gcov-ignore-parse-errors
```

I am unsure what causes the block number to be undefined in `.gcov` files. I will check my project ([nohtyP](https://github.com/Syeberman/nohtyP)) to see if there's a gcov option I'm missing.

# Expected behavior

I would recommend removing this print, or printing once rather than at every applicable line.

# Screenshots

From my build https://ci.appveyor.com/project/Syeberman/nohtyp/builds/50783482?fullLog=true:

![image](https://github.com/user-attachments/assets/ec08a898-b4f8-4b1e-a4a7-aab5d7651621)

Relevant files:

- `.gcov` archive: [munit_test.gcov.tar.gz](https://github.com/user-attachments/files/17350307/munit_test.gcov.tar.gz)
- `.lcov`: [munit_test.lcov.txt](https://github.com/user-attachments/files/17350338/munit_test.lcov.txt)

# Desktop (please complete the following information)

- OS: Ubuntu 22.04
- GCC version: GCC 11, 13
- GCOVR version: 8.0
- Project directory layout:
  - Project: [nohtyP](https://github.com/Syeberman/nohtyP)
  - `./Build/make coverage` creates a `Build/native/coverage/munit_test.gcov.tar.gz` file containing the `.gcov` files

**Comment by Spacetown** [comment]
This behaviour was discussed in #973 because gvoc is missing this info for some functions. It seems that the "some" is many for you.
I'll change it to be printed only once.
