### ISSUE TITLE
Crash when trying to fix case of non existent path

### ISSUE THREAD

**Issue by LordAro** [gcovr/gcovr#994]
# Describe the bug

gcovr crashes if it attempts to fix the path case sensitivity of a path that does not exist.

```
Traceback (most recent call last):
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/workers.py", line 81, in worker
    work(*args, **kwargs)
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 1009, in process_existing_gcov_file
    process_gcov_data(filename, None, covdata, options)
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 329, in process_gcov_data
    fname = guess_source_file_name(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 406, in guess_source_file_name
    fname = fix_case_of_path(fname)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/utils.py", line 83, in fix_case_of_path
    matchedFileName = [f for f in os.listdir(rest) if f.lower() == curL]
                                  ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/builds/Kii9hbKm/0/foo/bar/libs/libfoo_clang-8d2d4406/include/clang/AST'
```

# To Reproduce

1. Generate some source code
2. Build & run it with coverage
3. Delete generated files
4. Run gcovr
5. Crash.

# Expected behavior

Not to crash :)

# Screenshots

N/A

# Desktop (please complete the following information)

- OS: Windows / MSYS2
- GCC version: 12.3.0
- GCOVR version: 8.0

# Additional context

**Comment by Spacetown** [comment]
That's expected. The source file information is needed for the internal data model and for some output formats. I saw that the sources are generated in a temporary directory but the source files should be placed in the output to also be able to debug the code.

**Comment by LordAro** [comment]
I don't much mind if it doesn't work, but crashing with an exception isn't great

**Comment by LordAro** [comment]
Oh, and just for clarity, this works fine on Linux, it's only the path conversion stuff that causes it to fall over on Windows

**Comment by Spacetown** [comment]
I can try to check this but can't guaranty because I haven't a Windows computer. 
The function is only executed if a case insensitive file system is detected.
